### PR TITLE
Remove spurious whitespace in the launcher script (1.8.x)

### PR DESCRIPTION
**Pull request by julienrf**
Backport of #7134

### CODE REVIEW

**Review by mkurz — APPROVED** [review]
Thanks for fixing my mistake!

**Review by eed3si9n — APPROVED** [review]
Thanks!

**Comment by SethTisue** [comment]
someone on Discord was bitten by this today. it took us hours to figure out what was going on. it might be worth rolling 1.8.3 over? not sure

**Comment by eed3si9n** [comment]
Yea. I've been busy with ScalaMatsuri prep, but after this weekend, I can get out 1.8.x or see if 1.9.x can be ready for RC soon.

**Pull request merged**
