### PR TITLE
Add sbt-mima. Fixes #2037.

### LINKED ISSUE #2037: Consider using sbt-mima to mechanically verifying we're not breaking bincompat.
I had a look and didn't see this mentioned in any issue, pull request or mailing list thread.

Thoughts?

### PR DESCRIPTION
**Pull request by dwijnand**

### CODE REVIEW

**Comment by typesafe-tools** [comment]
Can one of the admins verify this patch?

**Comment by eed3si9n** [comment]
This is good, but since sbt 1.0 will be an aggregate of modules, we should MIMA check the publicly exposed types at the module level.

**Comment by dwijnand** [comment]
Do you mean here somehow, or do you mean add mima to the modules? Either way, I agree.

**Comment by eed3si9n** [comment]
We need to catch API breakage at the PR validation of the modules.

**Comment by dwijnand** [comment]
Ok. I'll create a meta-ticket for the various modules.

**Pull request merged**
