### PR TITLE
Mark pickled existential test as passing.

### PR DESCRIPTION
**Pull request by gkossakowski**
The problem with pickled existential flag has been fixed upstream
in Scala 2.10 (the one sbt is using right now) so let's mark this
test as passing.

Note, that the fix went into Scala 2.9.3 so it's passing with that
version of Scala as well.

### CODE REVIEW

**Comment by harrah** [comment]
What is the relation to #616 and #623?  Does it fix them?

**Comment by gkossakowski** [comment]
Sorry, I totally forgot that those tickets was a motivation for me to touch that test in the first place. I'll amend a commit message.

**Comment by gkossakowski** [comment]
@harrah: done

**Comment by harrah** [comment]
Ok, thanks for the clarifications.

**Pull request merged**
