### PR TITLE
Fix for JUnitXmlTestsListener that is removing part of test name when it contains dot

### LINKED ISSUE #5114: sbt.JUnitXmlTestsListener removes part of test name if test name contains dot
## steps
sbt version: `1.3.0`, `1.3.1`, `1.3.2` (probably earlier)

## problem
After spending *hours* figuring out why upgrade from `1.1.6` mangled our tests (https://github.com/scalatest/scalatest/issues/1427 - really there should be migration info when `JUnitXmlReportPlugin` was added) I stared to test should run sbt's reporter or ScalaTest's.

- When running with `1.1.6` our CI reported that we have **1318** tests, it combined both reports with `TEST-` and without and removed duplicates.
- When disabled sbt's writer test count dropped to **1235** (which is correct).
- When running only `sbt.JUnitXmlTestsListener` test count dropped to **1233**.

Problem is is that test names having dot in them are splitted and only last part is written to XML, and couple of test names ended in domain name and only `net` was written to file. (and again CI removes duplicates).

There is quite many test classes containing dot and caused previously extra 83 tests reported as names where different. 

## expectation
Test names in `JUnitXmlTestsListener` not to be truncated.

## notes
https://github.com/sbt/sbt/blob/develop/testing/src/main/scala/sbt/JUnitXmlTestsListener.scala#L117

### PR DESCRIPTION
**Pull request by margussipria**
Attempt to fix https://github.com/sbt/sbt/issues/5114 (and https://github.com/sbt/sbt/issues/2949)

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @margussipria,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by eed3si9n** [comment]
@margussipria Thanks for the contribution.
It seems like there are some [scripted](https://www.scala-sbt.org/1.x/docs/Testing-sbt-plugins.html) tests here that might be of your interest - https://github.com/sbt/sbt/blob/develop/sbt/src/sbt-test/tests/junit-xml-report/build.sbt

**Comment by eed3si9n** [comment]
```
[error] 1 files must be formatted
[error] (testingProj / Compile / scalafmtCheck) 1 files must be formatted
```

**Comment by margussipria** [comment]
I formatted the code, also Fixed MyNestedSuites test where `MyInnerSuite` isn't part of name.

Also added new coverage and new test checking names of testcases covering name with dot in it.

**Comment by eed3si9n** [comment]
@margussipria Thanks for the update. Also have you signed the CLA?
http://www.lightbend.com/contribute/cla

**Comment by margussipria** [comment]
I did sign it now, but that check didn't change?

**Comment by margussipria** [comment]
Added some function return types so CLA test would be run again, those would be needed in distant future when migrating to and past Scala 2.13 so not totally worthless commit.

**Review by eed3si9n — APPROVED** [review]
LGTM

**Comment by margussipria** [comment]
is it possible to get this also to 1.3.x branch?

**Comment by eed3si9n** [comment]
Sure.

**Comment by HeartSaVioR** [comment]
Do you have any update on this, given it was merged in Oct last year? Are there any releases containing this?

**Comment by margussipria** [comment]
@eed3si9n about backporting this, who should do it? (expected that not me, "but who then")

**Comment by eed3si9n** [comment]
Normally I do the backports. Looks like this slipped through the cracks.

**Comment by HeartSaVioR** [comment]
Hopefully sbt has been releasing bugfix versions monthly - unless there's a long pause, wouldn't be a big deal.

**Pull request merged**
