### PR TITLE
Fix #2411

### LINKED ISSUE #2411: [0.13.10] unexpected java.lang.NoSuchFieldError when use nested case class
`project/build.properties`

```
sbt.version=0.13.10-RC1
```

`A.scala`

``` scala
package example

class A {
  case class B(x: Int)

  def c = B
}

object A {
  def main(args: Array[String]): Unit = {
    (new A).c
  }
}
```

result

```
[error] (run-main-15) java.lang.NoSuchFieldError: B$module
java.lang.NoSuchFieldError: B$module
        at example.A.B(A.scala:4)
        at example.A.c(A.scala:6)
        at example.A$.main(A.scala:11)
        at example.A.main(A.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
[trace] Stack trace suppressed: run last compile:run for the full output.
java.lang.RuntimeException: Nonzero exit code: 1
        at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last compile:run for the full output.
[error] (compile:run) Nonzero exit code: 1
```

There is same problem in playframework, scalikejdbc, skinny-framework, cats.
- https://travis-ci.org/xuwei-k/Play20/jobs/104261656#L497
- https://travis-ci.org/xuwei-k/scalikejdbc/jobs/104293183#L1193
- https://travis-ci.org/seratch/skinny-framework/jobs/104275385#L2107
- https://travis-ci.org/xuwei-k/cats/jobs/104294044#L2702

### PR DESCRIPTION
**Pull request by Duhemm**
This PR fixes the breakage introduced in #2261.

The fix comes from @adriaanm who suggested to use `transformedType` rather `exitingPostErasure` to inspect types after erasure in https://github.com/scala/scala/commit/6dd149505d6782d35655cfd76e573e7fbeaecb77.

I can confirm that with this PR applied, these builds now pass:

https://travis-ci.org/xuwei-k/Play20/jobs/104261656#L497
https://travis-ci.org/seratch/skinny-framework/jobs/104275385#L2107
https://travis-ci.org/xuwei-k/cats/jobs/104294044#L2702

Fixes #2411

### CODE REVIEW

**Comment by typesafe-tools** [comment]
Can one of the admins verify this patch?

**Comment by eed3si9n** [comment]
Fix should target 0.13.10 branch. In this case we should be able to automatically merge, but 0.13 can move ahead.

**Comment by eed3si9n** [comment]
Should this be forward ported?

**Comment by eed3si9n** [comment]
I guess this is superseded by https://github.com/sbt/zinc/pull/95

**Pull request merged**
