### PR TITLE
Start handling default types when serialising query setting values

### PR DESCRIPTION
**Pull request by dwijnand**
Refs #3024

Looks like this:

    { "type": "SettingQuery", "setting": "t/scalaVersion" }
    {"type":"SettingQueryResponse","value":"2.12.1"}
    
    { "type": "SettingQuery", "setting": "t/baseDirectory" }
    {"type":"SettingQueryResponse","value":"file:/s/t/"}
    
    { "type": "SettingQuery", "setting": "t/sourcesInBase" }
    {"type":"SettingQueryResponse","value":true}
    
    { "type": "SettingQuery", "setting": "t/sourceDirectories" }
    {"type":"SettingQueryResponse","value":["file:/s/t/src/main/scala-2.12","file:/s/t/src/main/scala","file:/s/t/src/main/java","file:/s/t/target/scala-2.12/src_managed/main"]}
    
    { "type": "SettingQuery", "setting": "t/scalaArtifacts" }
    {"type":"SettingQueryResponse","value":["scala-library","scala-compiler","scala-reflect","scala-actors","scalap"]}
    
    { "type": "SettingQuery", "setting": "t/startYear" }
    {"type":"SettingQueryResponse","value":null}
    
    { "type": "SettingQuery", "setting": "t/pollInterval" }
    {"type":"SettingQueryResponse","value":500}
    
    { "type": "SettingQuery", "setting": "t/maxErrors" }
    {"type":"SettingQueryResponse","value":100}

Still TODO: Supporting LM types and util types, such as ModuleID.

### CODE REVIEW

**Comment by eed3si9n** [comment]
Is it possible to capture the type of the response as FastTypeTag or String representation of it?

```json
{ "type": "SettingQuery", "setting": "t/sourcesInBase" }
{"type":"SettingQueryResponse","contentType":"Boolean","value":true}
```

**Comment by dwijnand** [comment]
Sure, we have the full Manifest of it:

```scala
scala> manifest[List[Option[Int]]]
res1: Manifest[List[Option[Int]]] = scala.collection.immutable.List[scala.Option[Int]]
```

**Comment by dwijnand** [comment]
@eed3si9n the question is how do we respond with failure? E.g when you requested a nonsense setting.

**Comment by eed3si9n** [comment]
The same way sbt or a database would respond on bad query.

```
zinc Root> show fooo
[error] Not a valid key: fooo (similar: fork)
[error] show fooo
[error]          ^
```

**Comment by dwijnand** [comment]
I mean in terms of the payload shipped over the socket. Or if you prefer, in terms of the contraband data type definition. Currently I have it defined as:

```
type SettingQueryResponse implements EventMessage {
  value: String!
}
```

How should it communicate "Not a valid key: fooo (similar: fork)"?

**Comment by eed3si9n** [comment]
We could send another event type for errors:

```json
{ "type": "SettingQuery", "setting": "t/fooo", "queryId": "0000-1111" }
{ "type":"SettingQueryError", "message": "Not a valid key: fooo (similar: fork)", "queryId": "0000-1111"}
```

**Comment by dwijnand** [comment]
blocked on the modules upgrade - #3031

**Comment by dwijnand** [comment]
and depends on sbt/util#73 being accepted, merged and released.

**Comment by dwijnand** [comment]
Here's what it looks like, before switching how to obtain the JsonWriter:

```json
{ "type": "SettingQuery", "setting": "t/scalaVersion" }
{"type":"SettingQuerySuccess","value":"2.12.1","contentType":"java.lang.String"}

{ "type": "SettingQuery", "setting": "t/baseDirectory" }
{"type":"SettingQuerySuccess","value":"file:/s/t/","contentType":"java.io.File"}

{ "type": "SettingQuery", "setting": "t/sourcesInBase" }
{"type":"SettingQuerySuccess","value":true,"contentType":"Boolean"}

{ "type": "SettingQuery", "setting": "t/sourceDirectories" }
{"type":"SettingQuerySuccess","value":["file:/s/t/src/main/scala-2.12","file:/s/t/src/main/scala","file:/s/t/src/main/java","file:/s/t/target/scala-2.12/src_managed/main"],"contentType":"scala.collection.Seq[java.io.File]"}

{ "type": "SettingQuery", "setting": "t/scalaArtifacts" }
{"type":"SettingQuerySuccess","value":["scala-library","scala-compiler","scala-reflect","scala-actors","scalap"],"contentType":"scala.collection.Seq[java.lang.String]"}

{ "type": "SettingQuery", "setting": "t/startYear" }
{"type":"SettingQuerySuccess","value":null,"contentType":"scala.Option[Int]"}

{ "type": "SettingQuery", "setting": "t/pollInterval" }
{"type":"SettingQuerySuccess","value":500,"contentType":"Int"}

{ "type": "SettingQuery", "setting": "t/fooo" }
{"type":"SettingQueryFailure","message":"Expected ':' (if selecting a configuration)\nNot a valid key: fooo (similar: fork)\nt/fooo\n      ^"}

{ "type": "SettingQuery", "setting": "scalaVersion" }
{"type":"SettingQueryFailure","message":"Not a valid project ID: scalaVersion\nscalaVersion\n            ^"}

{ "type": "SettingQuery", "setting": "t/scalacOptions" }
{"type":"SettingQueryFailure","message":"Key {file:/s/t/}t/compile:scalacOptions is a task, can only query settings"}
```

**Review by eed3si9n — APPROVED** [review]

**Pull request merged**
