### PR TITLE
Add a pending test case for private var declared in a trait.

### PR DESCRIPTION
**Pull request by gkossakowski**
Added a test-case for an edge case where an introduction of private member
(var in this case) should trigger recompilation of all classes that
inherit from a trait where the member is declared.

The reason is that current encoding of traits make it impossible for them
to declare fields directly so fields are being introduced in classes
inheriting from those traits. Check the test case for details.

### CODE REVIEW

**Comment by harrah** [comment]
merged, thanks!

**Comment by gkossakowski** [comment]
@harrah: thanks for merging. Is there any reason why do you perform rebase/cherry-pick in cases like that? I ask because my commits end up having different sha1s and pruning local branches is slightly more work.

**Comment by harrah** [comment]
I use `git am` on the patch set (`https://github.com/sbt/sbt/pull/#.patch`) because I find it to be a faster and easier workflow.  I can do a proper merge on your pull requests if you prefer.

**Comment by gkossakowski** [comment]
Oh I see. If you can perform proper merges so sha1s are preserved I'd be grateful.

**Pull request closed without merging**
