### PR TITLE
Interned serialization format for Analysis objects.

### PR DESCRIPTION
**Pull request by benjyw**

### CODE REVIEW

**Comment by harrah** [comment]
Merged, thanks!

**Comment by benjyw** [comment]
And that's everything in SBT!

Thanks so much for your help and your prompt responses to the pull
requests.

When can we get a release with these changes in? I want to make the last
remaining zinc change needed, so I need an SBT version to go with it.

Thanks again!

**Comment by harrah** [comment]
Great, thanks for this performance improvement.  Hopefully we'll get some external reports of speedups as well from it.  There will be a 0.13.1-RC1 probably in the next week.  I have one more enhancement to implement before it.  If that is too long to wait, I can do a 0.13.1-M1 milestone.

**Comment by benjyw** [comment]
An 0.13.1-M1 milestone would be awesome, if it's not too much trouble.

**Comment by harrah** [comment]
There is an error when using the interned formats with `Sync` (https://github.com/sbt/sbt/blob/0.13/main/actions/src/main/scala/sbt/Sync.scala#L74).  The error is:

```
[info] java.lang.RuntimeException: Intern pool not available for java.io.File
[info]  at sbt.inc.InternPoolFormats.sbt$inc$InternPoolFormats$$toIdx(InternPool.scala:74)
[info]  at sbt.inc.InternPoolFormats$$anonfun$itemFormat$1.apply(InternPool.scala:57)
[info]  at sbt.inc.InternPoolFormats$$anonfun$itemFormat$1.apply(InternPool.scala:57)
[info]  at sbinary.Generic$$anon$5.writes(generic.scala:72)
[info]  at sbinary.Operations$.write(operations.scala:10)
[info]  at sbinary.BasicTypes$$anon$4.writes(standardtypes.scala:34)
[info]  at sbinary.BasicTypes$$anon$4.writes(standardtypes.scala:24)
[info]  at sbinary.Operations$.write(operations.scala:10)
[info]  at sbinary.Generic$$anon$2$$anonfun$writes$3.apply(generic.scala:47)
[info]  at sbinary.Generic$$anon$2$$anonfun$writes$3.apply(generic.scala:47)
[info]  at scala.collection.immutable.Map$Map1.foreach(Map.scala:109)
[info]  at sbinary.Generic$$anon$2.writes(generic.scala:47)
[info]  at sbinary.Generic$$anon$2.writes(generic.scala:46)
[info]  at sbinary.Operations$.write(operations.scala:10)
[info]  at sbinary.Generic$$anon$9.writes(generic.scala:128)
[info]  at sbinary.Operations$.write(operations.scala:10)
[info]  at sbinary.BasicTypes$$anon$4.writes(standardtypes.scala:34)
[info]  at sbinary.BasicTypes$$anon$4.writes(standardtypes.scala:24)
[info]  at sbinary.Operations$.write(operations.scala:10)
[info]  at sbt.Sync$$anonfun$writeInfo$1.apply(Sync.scala:79)
[info]  at sbt.Sync$$anonfun$writeInfo$1.apply(Sync.scala:78)
[info]  at sbt.Using.apply(Using.scala:25)
[info]  at sbt.IO$$anonfun$gzipFileOut$1$$anonfun$apply$6.apply(IO.scala:775)
[info]  at sbt.IO$$anonfun$gzipFileOut$1$$anonfun$apply$6.apply(IO.scala:774)
[info]  at sbt.Using.apply(Using.scala:25)
[info]  at sbt.IO$$anonfun$gzipFileOut$1.apply(IO.scala:774)
[info]  at sbt.IO$$anonfun$gzipFileOut$1.apply(IO.scala:773)
[info]  at sbt.Using.apply(Using.scala:25)
[info]  at sbt.IO$.gzipFileOut(IO.scala:773)
[info]  at sbt.Sync$.writeInfo(Sync.scala:78)
[info]  at sbt.Sync$$anonfun$apply$1.apply(Sync.scala:46)
[info]  at sbt.Sync$$anonfun$apply$1.apply(Sync.scala:23)
```

This is when running `scripted project/settings` (an integration test, so it is not minimal, unfortunately).

**Comment by benjyw** [comment]
I'll take a look.

**Comment by benjyw** [comment]
Looks like I replaced the old format with the new one overzealously. If I
understand correctly "cacheFile" here has nothing to do with Analysis?

**Comment by harrah** [comment]
Correct.  I figured you did it to apply the optimization to the files here as well, but I guess not ;).

**Pull request merged**
