### PR TITLE
Fix serialization in Sync.

### PR DESCRIPTION
**Pull request by benjyw**
The serialized structures there aren't part of an Analysis,
so they aren't interned.

TODO: Refactor InternedAnalysisFormats so that this is more
straightforward and less error-prone.  This commit is
a first-pass fix of the broken test.

### CODE REVIEW

**Comment by gkossakowski** [comment]
LGTM.

**Comment by harrah** [comment]
Thanks @benjyw, LGTM as well.

**Comment by harrah** [comment]
Merged, thanks!  Jars for 0.13.1-M1 are published, also.

**Comment by benjyw** [comment]
Thanks!

I still can't see 0.13.1-M1 on maven central though.

**Comment by jsuereth** [comment]
@benjyw Are you using the com.typesafe.sbt artifacts we publish to maven central?  If so, I can do that shortly here.

**Comment by benjyw** [comment]
I believe so, yes.

**Comment by jsuereth** [comment]
Cool.  It's pushed to OSSRH.  Should be on central after the next synch.

**Pull request closed without merging**
