### PR TITLE
acknowledge the deprecatio of set/unset in scala.concurrent.SyncVar

### PR DESCRIPTION
**Pull request by huitseeker**
This is part one of two of the steps needed to make SBT 2.11 compatible.
The second step is porting the use of MurmurHash.scala in xsbt.HashApi to MurmurHash3.scala.

This PR is here to ensure the trivial parts (i.e. this) are not forgotten in the upcoming sbt release.

### CODE REVIEW

**Comment by retronym** [comment]
Here's where I temporarily undeprecated things: https://github.com/scala/scala/pull/2552.

@huitseeker As discussed, I would appreciate if you could sweep over SBT for other used of deprecation APIs.

**Comment by jsuereth** [comment]
I'll let @harrah take care of this when he's back, but it LGTM.

**Comment by harrah** [comment]
DNLGTM. The first replacement is ok, later ones are not.  SyncVar claims "to provide safe concurrent access to a mutable cell", not to be a [single element synchronous queue](http://docs.oracle.com/javase/6/docs/api/java/util/concurrent/SynchronousQueue.html).  So, it is not possible to simply replace `set` calls with `put`.  I guess the proper solution has to be to have an sbt SyncVar implementation now.

**Comment by harrah** [comment]
Superseded by fa591364f710df12883e031a6533371f9c19b8e5.  At some point, the `set`s might be replaced by a try/finally with `put`s, but the `unset`s shouldn't block.

**Pull request closed without merging**
