### PR TITLE
Add a mode where missing source files are not considered deleted.

### PR DESCRIPTION
**Pull request by benjyw**
Deleted source files must be explicitly provided.

This makes it practical to build only the needed parts of a large
single-tree codebase, without SBT requiring knowledge of the whole
world of sources.

### CODE REVIEW

**Comment by gkossakowski** [comment]
Hi. Thanks for pull request. I think this functionality needs more elaboration. What do you try to achieve? Is it that you want to recompile parts of your source tree without losing Analysis information about the rest?

**Comment by benjyw** [comment]
Hi, thanks for the quick reply. I had elaborated in an email to Mark and Peter, but forgot to add that detail here. So here it is: 

We have a large Scala codebase, where all source files live under a single com/foursquare/... tree. We use a custom build tool called Pants, originally from Twitter and now developed jointly by Twitter and Foursquare. Pants is modeled after Google's Blaze. Like that system, it explicitly models the code as a DAG of targets and dependencies. 

When Pants attempts to build some target it computes that target's transitive dependencies and then figures out which of those need building/rebuilding. It then figures out the source files belonging to those targets and presents only those sources to the compiler. 

This means that you can build some part of the codebase without knowing anything about the rest of it, which is crucial when working in a large shared code tree.

However this scheme runs into a problem when using zinc, because it assumes that the source files presented to it on the command line are the entire universe of source files. So it'll nuke class files and analysis information from previously compiled sources that it now thinks have been deleted.

We've worked around this so far by doing atrocious things like copying classfiles around, and splitting and merging analysis files to conserve their data. But the performance implications of all this filesystem work have been huge. 

The change introduces a new flag, -explicit-deletes, which causes the following behavior: 

Source files that are mentioned in the analysis file but not listed on the command line are no longer considered deleted. Their .class files and analysis entries are preserved unchanged. When this flag is on, to tell Zinc about files that really have been deleted you just specify them as a source files; Zinc checks the filesystem for the presence of each file (the normal behavior is to crash if a nonexistent source file is specified on the command line).

This behavior is what allows us to present Zinc with just the parts of the codebase that we care about in a given build, instead of Zinc requiring a full view of the entire world at all times.

The results have been tremendous: our builds have gotten much, much faster. So you can see why we're excited about this change.

**Comment by gkossakowski** [comment]
Thanks for providing some context.

If I understand you correctly, you have one big Analysis object which represents the whole source tree but you want to compile a subset of source files and you would like to update Analysis entries only related to files you want to compile, right?

In other words your analysis is `A+M` where `M` is part of analysis that corresponds to source files you want to recompile. What you want to achieve is recompile source files mentioned in M and get `M1` Analysis as a result and then have `A+M1` as a final result where A part hasn't been touched.

If that's the case then I think you should solve this problem by preprocessing (splitting into to two parts) analysis object before you pass it to incremental compiler. Is this what you tried before and you were not satisfied with the results? You mentioned that you needed to copy class files around. Why that was needed?

In general, I'd like to understand if there's a way to achieve what's needed by Pants without touching incremental compiler logic. Also, I see your changes are targetting 0.12.x branch but I think a change like this should target 0.13 or 0.14 branch. I believe 0.12.x is mostly in maintenance mode but I'll let @harrah comment on that specific point.

**Comment by benjyw** [comment]
On Fri, Aug 16, 2013 at 11:49 AM, Grzegorz Kossakowski <
notifications@github.com> wrote:

> Thanks for providing some context.
> 
> If I understand you correctly, you have one big Analysis object which
> represents the whole source tree but you want to compile a subset of source
> files and you would like to update Analysis entries only related to files
> you want to compile, right?

Sort of. We have one big output classes dir, and one big associated
analysis object, that represent "the subset of the source tree that I've
built since the last clean". For example, I work on target A for a bit,
then I switch to target B for a while, then back to A and so on. The global
classes+analysis represent A, B and all of their transitive dependencies,
but not the entire source tree.

**Comment by gkossakowski** [comment]
FYI: I'm busy traveling. I'll come back to this in upcoming days.

**Comment by gkossakowski** [comment]
> The bigger problem is not the analysis modifications, which we could possibly work around as you describe, but the fact that SBT nukes the classfiles corresponding to source files it thinks have been deleted.

This is the part I don't understand. Sbt will nuke only the class files it knows about from the Analysis object. If you pass limited Analysis object to it then it should leave other class files (not mentioned anywhere in Analysis object) intact, right?

> Peter suggested getting a 0.12.5 release with just this change, since 0.13 is still a way off apparently?

As you probably saw, sbt 0.13.0 final was released. Zinc release will follow soon. I strongly suggest upgrading to sbt 0.13.0 as it receives a lot of fixes to incremental compiler that won't be back ported to sbt 0.12.x.

**Comment by benjyw** [comment]
On Thu, Aug 29, 2013 at 11:14 AM, Grzegorz Kossakowski <
notifications@github.com> wrote:

> The bigger problem is not the analysis modifications, which we could
> possibly work around as you describe, but the fact that SBT nukes the
> classfiles corresponding to source files it thinks have been deleted.
> 
> This is the part I don't understand. Sbt will nuke only the class files it
> knows about from the Analysis object. If you pass limited Analysis object
> to it then it should leave other class files (not mentioned anywhere in
> Analysis object) intact, right?
> 
> Hmm, I guess you're right? I had been under the impression that it would
> nuke everything under the output directory, but then my hack wouldn't work
> either... I will try this out.
> 
>  Peter suggested getting a 0.12.5 release with just this change, since
> 0.13 is still a way off apparently?
> 
> As you probably saw, sbt 0.13.0 final was released. Zinc release will
> follow soon. I strongly suggest upgrading to sbt 0.13.0 as it receives a
> lot of fixes to incremental compiler that won't be back ported to sbt
> 0.12.x.

Sounds good, I will look into upgrading us. When does the zinc release
happen?

**Comment by gkossakowski** [comment]
> Hmm, I guess you're right? I had been under the impression that it would nuke everything under the output directory, but then my hack wouldn't work either... I will try this out.

Excellent! Let me know about the results.

> Sounds good, I will look into upgrading us. When does the zinc release happen?

Most likely tomorrow.

**Comment by pvlugter** [comment]
Zinc 0.3.0 is published.

Will be synced to maven central soon, or available now in https://oss.sonatype.org/content/repositories/releases

**Comment by benjyw** [comment]
Will give it a try.

**Comment by benjyw** [comment]
So I've noticed the following problem (with both my hack and with your new
suggestion of restricting the analysis externally first):

I'm not clear on when things get registered in the analysis as a "source
dependency" and when as a "binary dependency", but changes to source
dependencies don't seem to invalidate the dependent.

That is, if A.scala depends on B.scala and I change A.scala and compile it,
and then compile B.scala separately (with an appropriately split analysis
that does contain the relevant source dep), zinc doesn't invalidate and
recompile B.scala.

This problem doesn't occur if the dependency is a binary dependency, i.e.,
B.scala -> A.class. But again, I have no idea what the distinction is
between those two types of dependency, and why Zinc chooses to express a
dep as one vs. the other.

Any idea what might be going on?

Thanks!
Benjy

PS Happy to follow up by direct email if you prefer, I'm my first name at
foursquare dot com.

**Comment by gkossakowski** [comment]
> I'm not clear on when things get registered in the analysis as a "source dependency" and when as a "binary dependency", but changes to source dependencies don't seem to invalidate the dependent.
> 
> That is, if A.scala depends on B.scala and I change A.scala and compile it, and then compile B.scala separately (with an appropriately split analysis that does contain the relevant source dep), zinc doesn't invalidate and recompile B.scala.
> 
> This problem doesn't occur if the dependency is a binary dependency, i.e., B.scala -> A.class. But again, I have no idea what the distinction is between those two types of dependency, and why Zinc chooses to express a dep as one vs. the other.
> 
> Any idea what might be going on?

The relevant code is in [Compile.scala](https://github.com/sbt/sbt/blob/0.13/compile/inc/src/main/scala/sbt/inc/Compile.scala#L111). I believe what's happening is that you make B.scala depend on A.scala _internally_ which means that sbt assumes that Analysis is already consistent and no invalidation needs to happen.

What you need to do is to make B.scala depend on A.scala externally (as they were in separate projects). What you want in relations is to have "external source dependency". Note that external source dependencies carry their copies of API representation that allows sbt to detect the change to A.scala when it consider invalidating B.scala.

**Comment by benjyw** [comment]
Note that I _do_ see B.scala -> A.scala under "source dependencies" in the
relations. Doesn't that make it an "external source dependency"? If not,
how do I make it so?

**Comment by gkossakowski** [comment]
> Note that I _do_ see B.scala -> A.scala under "source dependencies" in the relations. Doesn't that make it an "external source dependency"? If not, how do I make it so?

I'm pretty sure you see it as internal dependency. To add an external dependency (assuming you are still looking at 0.12.x), use: https://github.com/sbt/sbt/blob/0.12.4/compile/inc/Relations.scala#L36

Note, that you pass name of a class and not source file as argument. If you just have source file, then you'll need to add classes that are products of given source file, see: https://github.com/sbt/sbt/blob/0.12.4/compile/inc/Relations.scala#L47

**Comment by benjyw** [comment]
I'm not creating any of these analyses programatically. Zinc creates them
when compiling, and we subsequently split/merge them, again using zinc.
This gets created by:

1) Compiling A.scala into a classes directory, yielding analysis_A.
2) Compiling B.scala into the same classes directory, yielding analysis_B.
3) Merging analysis_A and analysis_B into a global analysis file.

**Comment by gkossakowski** [comment]
How the last step is achieved? I didn't know zinc has capability of merging analysis files. So far, I worked more on sbt side of things.

**Comment by benjyw** [comment]
Ah, zinc has commands for splitting, merging and rebasing analysis files
(we asked for them, I think Peter Vlugter implemented them).

But regardless, even if we ignore that merging, analysis_B doesn't seem to
contain the right information to invalidate B.scala when A.scala changes.

**Comment by gkossakowski** [comment]
My bet would be that either splitting or merging is faulty. I'm pretty sure analysis_B has enough information that, once propagated to the merged Analysis object, would be sufficient to invalidate B.scala.

It would be great if you could create an automated test case (scripted test case) for this issue. Unfortunately, I won't be able to look into that until some time next week.

**Comment by pvlugter** [comment]
Benjy, not good to hear that it hasn't been working all this time.

History in zinc for the analysis utils can be found here:
https://github.com/typesafehub/zinc/commits/master/src/main/scala/com/typesafe/zinc/SbtAnalysis.scala

The merging and splitting in zinc just uses the `++` and `--` methods on Analysis:
https://github.com/sbt/sbt/blob/0.13/compile/inc/src/main/scala/sbt/inc/Analysis.scala#L20-L21

So this could be improved within sbt itself, or within zinc.

Moving dependencies between source and binary dependencies on split and merge, based on the listed products, certainly seems like it would fix this, and be consistent with the analyses that would usually be produced when compiling separately or together. I don't see anything doing this already.

**Comment by benjyw** [comment]
On Fri, Sep 6, 2013 at 3:20 AM, Peter Vlugter notifications@github.comwrote:

> Benjy, not good to hear that it hasn't been working all this time.
> 
> History in zinc for the analysis utils can be found here:
> 
> https://github.com/typesafehub/zinc/commits/master/src/main/scala/com/typesafe/zinc/SbtAnalysis.scala
> 
> The merging and splitting in zinc just uses the ++ and -- methods on
> Analysis:
> 
> https://github.com/sbt/sbt/blob/0.13/compile/inc/src/main/scala/sbt/inc/Analysis.scala#L20-L21
> 
> So this could be improved within sbt itself, or within zinc.
> 
> Moving dependencies between source and binary dependencies on split and
> merge, based on the listed products, certainly seems like it would fix
> this, and be consistent with the analyses that would usually be produced
> when compiling separately or together. I don't see anything doing this
> already.
> 
> So basically convert each source dependency B.scala -> A.scala into the
> following binary dependencies:

B.scala -> A.class
B.scala -> A$.class
...

For each product of A.scala?  Where should this happen?

I'm still really confused about all the different types of relation, and
when zinc creates each type...

Also note that when debugging I'm looking at the .relations file, which is
text, because I have no convenient way to examine the binary analysis file,
and my understanding is that the .relations file contains only part of the
information in the analysis.

**Comment by pvlugter** [comment]
So taking the source dependency `B.scala -> A.scala` and the product `A.scala -> A.class` to translate it into the binary dependency `B.scala -> A.class`. And vice versa for merging. Making sure that the merged or split analyses are the same as what would normally be generated in a combined or separate compile.. For looking into the analysis objects, `console-project` in sbt is useful. Pants is the only build tool making use of these analysis utilities, so please contribute any changes to zinc as needed.

I remember there was a suggested contribution of an alternative analysis format to sbinary that was both readable and easily editable outside of java/scala. That could be the best place to start, and remove the analysis utils from zinc, as discussed earlier. Or if this 'no deletes' approach is used instead.

I'm short on time right now, but happy to help where possible.

**Comment by benjyw** [comment]
On Fri, Sep 6, 2013 at 4:56 PM, Peter Vlugter notifications@github.comwrote:

> So taking the source dependency B.scala -> A.scala and the product A.scala
> -> A.class to translate it into the binary dependency B.scala -> A.class.
> And vice versa for merging. Making sure that the merged or split analyses
> are the same as what would normally be generated in a combined or separate
> compile.. For looking into the analysis objects, console-project in sbt
> is useful. Pants is the only build tool making use of these analysis
> utilities, so please contribute any changes to zinc as needed.
> 
> So on split, make all source dependencies into binary dependencies, and on
> merge make all binary dependencies into source dependencies? Sounds not too
> hard, I will look at it.

It's not clear to me what "the same as what would normally be generated in
a combined or separate compile" is...  When does a compile make something a
binary dep and when does it make something a source dep?

**Comment by pvlugter** [comment]
I think just looking at the simple relations output can be a good starting point for a top-level view. For example:

```
% cat A.scala
class A

% cat B.scala
class B extends A
```

```
% zinc -d a/classes A.scala
% zinc -cp a/classes -d b/classes -output-relations b/relations B.scala
```

```
% cat b/relations
products:
   B.scala -> b/classes/B.class
binary dependencies:
   B.scala -> .../scala-library.jar
source dependencies:

external dependencies:
   B.scala -> A
class names:
   B.scala -> B
```

```
% zinc -d ab/classes -output-relations ab/relations A.scala B.scala
```

```
% cat ab/relations
products:
   A.scala -> ab/classes/A.class
   B.scala -> ab/classes/B.class
binary dependencies:
   A.scala -> .../classes.jar
   A.scala -> .../scala-library.jar
   B.scala -> .../scala-library.jar
source dependencies:
   B.scala -> A.scala
external dependencies:

class names:
   A.scala -> A
   B.scala -> B
```

**Comment by gkossakowski** [comment]
Note that changes to binary dependencies are not analyzed in any way so they essentially disable incremental compiler algorithm. That's the main difference between external and binary dependencies.

**Comment by benjyw** [comment]
Closing this, since I've re-implemented another way.

**Pull request closed without merging**
