### PR TITLE
Override scala organization and version transitively at the Ivy level

### PR DESCRIPTION
**Pull request by milessabin**
This is a forward port of the parts of #2634 which aren't included in https://github.com/sbt/librarymanagement/pull/44. Please note that the scripted test `dependency-management/scala-organization` will fail until the latter is merged.

### CODE REVIEW

**Comment by milessabin** [comment]
I think Travis should go green now that sbt/librarymanagement#44 has been merged ... could you rerun the build?

**Comment by eed3si9n** [comment]
I published librarymanagement 0.1.0-M12 to Sonatype (https://oss.sonatype.org/content/repositories/public/org/scala-sbt/librarymanagement_2.11/0.1.0-M12/). When it syncs to Maven Central, could you bump the dependencies?

**Comment by milessabin** [comment]
Done.

**Comment by milessabin** [comment]
I don't think the remaining test failure is my doing ... thoughts?

**Comment by eed3si9n** [comment]
Probably not.. I'm going to rerun the Travis job for the failing one.

**Pull request merged**
