### PR TITLE
sbt.cmd -> sbt.bat and --sbt-script update

### PR DESCRIPTION
**Pull request by eed3si9n**
Ref https://github.com/sbt/sbt/issues/5870

### CODE REVIEW

**Comment by eatkins** [comment]
This will break sbtn on my windows vm. I think possibly a better fix would be to scan the PATH environment variable for sbt.bat or sbt.cmd.

**Comment by eed3si9n** [comment]
As proposed in https://github.com/sbt/sbt/issues/5872, ideally I'd like `sbtn` to look for `sbt` (or `sbt.bat`, `sbt.cmd` I guess) within the same directory first. Is there an equivalent of `$0`?

**Comment by eatkins** [comment]
Aah, that's an interesting idea. I don't know that there is an easy equivalent of $0. What I would propose is that we do something similar to what I did to fix the missing powershell executable issue in the directories project: https://github.com/dirs-dev/directories-jvm/pull/40/files
We first scan the path to see if the executables we are looking for exist. If we fail to find it on the path, we fall back to looking in the system wide default locations. For example, on mac we'd look for /usr/local/bin/sbt as the fallback. On windows, it would probably be a few `C:\Program Files\...\` like directories. It's not the most elegant solution but would probably meet like 99% of use cases.

**Comment by eed3si9n** [comment]
Also where did `.bat` vs `.cmd` change come from? Should we switch the official distribution to use `.cmd`?

**Comment by eatkins** [comment]
Good question. I have no idea why I have an sbt.bat on my vm. I have both choco and scoop on my vm and I'm not sure which one is being used.

**Comment by eatkins** [comment]
I have `C:\Program Files (x86)\sbt\bin` on my path and it contains sbt.bat. It was updated in june, so either choco or scoop is installing an sbt.bat.

**Comment by eed3si9n** [comment]
`sbt.bat` is what the official installer installs. But NetworkClient.scala is looking for `sbt.cmd`?

**Comment by eatkins** [comment]
Oh, shoot, you're right. sbt.bat does work on my vm.

**Review by eatkins — APPROVED** [review]
LGTM

**Pull request merged**
