### PR TITLE
Add weaver-cats as a default test framework

### PR DESCRIPTION
**Pull request by kubukoz**
Inspired by #7053, let me know if I need to change anything else please :)

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @kubukoz,

Thank you for your contribution! We really value the time you've taken to put this together.

We see that you have signed the Lightbend Contributors License Agreement before, however, the CLA has changed since you last signed it.
Please review the new CLA and sign it before we proceed with reviewing this pull request:

[https://www.lightbend.com/contribute/cla](https://www.lightbend.com/contribute/cla)

**Review by eed3si9n — APPROVED** [review]
Thanks @kubukoz!

**Comment by kubukoz** [comment]
image

This seems unrelated, perhaps worth bumping the heap size?

**Comment by eed3si9n** [comment]
Yea. If it keeps failing, I'll disable the test for now.

**Comment by mzuehlke** [comment]
The PR you link as a reference (#7053) adds the `TestFramework` instance to the `testFrameworks` key in `Defaults.scala`. I would have guessed that you need to do this, too. 
No idea why the test works anyways.

**Comment by kubukoz** [comment]
OH. yeah. I suppose the test "works" by not running any tests. Perhaps it'd be better to make the scripted tests base off a test failure instead?

**Comment by kubukoz** [comment]
@eed3si9n would you mind approving CI once more? I expect this one to fail because the `test` task would succeed. I have a commit ready to go that adds the framework to the actual `testFrameworks` list, but would like to see this failure first

**Comment by kubukoz** [comment]
Confirmed locally, the test now fails. I'll push the update now.

**Pull request merged**
