### PR TITLE
Add a link to sbt-sonatype plugin in Using-Sonatype page

### PR DESCRIPTION
**Pull request by xerial**
Please add a pointer to sbt-sonatype plugin.

### CODE REVIEW

**Comment by xerial** [comment]
FYI, sbt-sonatype plugin has started to be used in some projects.  
https://github.com/search?q=sbt-sonatype&source=c&type=Code

**Comment by jsuereth** [comment]
Awesome!  Thanks for the patch.

**Comment by jsuereth** [comment]
Cherry-pick successful. Thanks again for the sbt-sonatype plugin! it's great.

**Comment by xerial** [comment]
Wow, thanks!

**Pull request merged**
