### PR TITLE
Changed default version setting to 0.1.0-SNAPSHOT

### LINKED ISSUE #3467: Use a semantic version as defaut version : 0.0.1-SNAPSHOT

### PR DESCRIPTION
**Pull request by laughedelic**
Fixes #3467

Changed default version setting to make it compatible with semantic versioning.

### CODE REVIEW

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild/?sbt=pull/3577/head&deploy_to_bintray=false&run_sbt_community=false">this link.</A>

**Comment by typesafe-tools** [comment]
A validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt-validator/198/console">is in progress...</a>

**Review by dwijnand — APPROVED** [review]

**Comment by dwijnand** [comment]
Thanks, @laughedelic!

**Comment by laughedelic** [comment]
I just noticed that issue and thought that it's a 5 seconds fix 😄 

I'm a bit confused about this CI build thing: am I supposed to push the Build button or the maintainers here? And should it really build all modules?

**Comment by dwijnand** [comment]
The validator isn't required. We use it when we want to check impact. For instance if there's some enthusiastic refactoring in sbt/zinc we validate that it doesn't break any of sbt/sbt's scripted tests. For this I'm happy to just see Travis CI go green, and meanwhile give @eed3si9n a chance to weigh in.

**Comment by laughedelic** [comment]
OK. Thanks for explaining.

**Comment by typesafe-tools** [comment]
[//]: # (Refs: pull/3577/head-1.x-1.x-1.x-1.x-1.x)
The validator <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/198/">has checked</A> the following projects against Scala 2.12,
tested using dbuild, projects built on top of each other.

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | <A HREF="https://github.com/sbt/sbt/pull/3577">pull/3577/head      </A> | sbt/sbt@632b14cf7875c53572f3503edb2d91036f979e3e
  zinc              | <A HREF="https://github.com/sbt/zinc/tree/1.x">1.x                 </A> | sbt/zinc@b63e9c6808ebd7eb5b511b9b9b7c0cf3a27cd896
  io                | <A HREF="https://github.com/sbt/io/tree/1.x">1.x                 </A> | sbt/io@62004b28dfcdc33273ebb07a563e78178f6eb21d
  librarymanagement | <A HREF="https://github.com/sbt/librarymanagement/tree/1.x">1.x                 </A> | sbt/librarymanagement@293666f653d2686e3049dce37fb80ccb58845b99
  util              | <A HREF="https://github.com/sbt/util/tree/1.x">1.x                 </A> | sbt/util@be73dc0a331a3b64994baa6267fdb2efea0fa925
  website           | <A HREF="https://github.com/sbt/website/tree/1.x">1.x                 </A> | 

:x: The result is: ***FAILED***
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild?sbt=pull/3577/head&zinc=1.x&io=1.x&librarymanagement=1.x&util=1.x&website=1.x&deploy_to_bintray=false&run_sbt_community=false">(restart)</A>

**Review by eed3si9n — CHANGES_REQUESTED** [review]
overall LGTM

Could you add a release note under 1.1.0 in the style of https://github.com/sbt/sbt/blob/1.x/notes/1.0.2/sample.md, plz

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild/?sbt=pull/3577/head&deploy_to_bintray=false&run_sbt_community=false">this link.</A>

**Comment by laughedelic** [comment]
@eed3si9n sure. Done in e99aa6d.

Why do you keep now release notes in nested folders and separate files? Do you use some new cool tool for aggregating them and publishing?

**Review by eed3si9n — CHANGES_REQUESTED** [review]
The Travis failure is legitimate. Please update https://github.com/sbt/sbt/blob/9d8a041a06238d3db855ee88018d3aeceb5ff75f/sbt/src/sbt-test/actions/package-delete-target/test

**Comment by eed3si9n** [comment]
> Why do you keep now release notes in nested folders and separate files? Do you use some new cool tool for aggregating them and publishing?

This is to avoid merge conflict when we have multiple PRs pending. The release note is hand-crafted, and I think it makes our release notes pretty good.

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild/?sbt=pull/3577/head&deploy_to_bintray=false&run_sbt_community=false">this link.</A>

**Comment by laughedelic** [comment]
> The Travis failure is legitimate. Please update /sbt/src/sbt-test/actions/package-delete-target/test@9d8a041

Done: 402b9ef

> This is to avoid merge conflict when we have multiple PRs pending. 

Makes sense. 

> The release note is hand-crafted, and I think it makes our release notes pretty good.

They are good indeed 👍

**Review by eed3si9n — APPROVED** [review]
LGTM
Thanks for the contribution.

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild/?sbt=pull/3577/head&deploy_to_bintray=false&run_sbt_community=false">this link.</A>

**Pull request merged**
