### PR TITLE
Fix unstable existential type names bug.

### LINKED ISSUE #823: Private def with existential type causes spurious recompilation due to name instability
Consider the following code structure:

``` scala
// Box.scala
class Box[T]

// Foo.scala
class Foo {
    def foo: Box[_] = null
}

// Bar.scala
class Bar {
    def f: Foo = null //we introduce dependency on Foo
}
```

Let's assume it's been compiled.

Now, let's introduce a _private_ method to `Foo` so it looks like this:

``` scala
class Foo {
    private def abc: Box[_] = null
    def foo: Box[_] = null
}
```

If we recompile we would expect one iteration of compilation (just to recompile `Foo.scala`) because the newly introduced method is private. At the moment, incremental compiler will decide to recompile `Bar.scala` as well because it sees changed signature of `foo` method. The reason its seen as changed is name instability for existential types introduced with widlcard syntax. What happens is that Scala compiler has a global counter for ids per compilation unit and uses that counter for naming existential types. Therefore even private definition can affect a signature a public definition thus causing spurious recompilation.

### PR DESCRIPTION
**Pull request by gkossakowski**
Fix the problem with unstable names synthesized for existential
types (declared with underscore syntax) by renaming type variables
to a scheme that is guaranteed to be stable no matter where given
the existential type appears.

The sheme we use are De Bruijn-like indices that capture both position
of type variable declarion within single existential type and nesting
level of nested existential type. This way we properly support nested
existential types by avoiding name clashes.

In general, we can perform renamings like that because type variables
declared in existential types are scoped to those types so the renaming
operation is local.

There's a specs2 unit test covering instability of existential types.
The test is included in compiler-interface project and the build
definition has been modified to enable building and executing tests
in compiler-interface project. Some dependencies has been modified:
- compiler-interface project depends on api project for testing
  (test makes us of SameAPI)
- dependency on junit has been introduced because it's needed
  for `@RunWith` annotation which declares that specs2 unit
  test should be ran with JUnitRunner

SameAPI has been modified to expose a method that allows us to
compare two definitions.

Also, a integration test has been added which tests scenario
mentioned in #823.

This commit fixes #823.

Proper fix for unstable existential names.

### CODE REVIEW

**Comment by gkossakowski** [comment]
@harrah: this implements the De Brujin-like scheme we discussed during Scala Summit and addresses your feedback from #839 on nested existential types.

**Comment by gkossakowski** [comment]
@retronym: your feedback is addressed in 47f1a8b and 63f1e0f.

@harrah: your feedback is addressed in a few commits I just pushed.

**Comment by harrah** [comment]
LGTM.  Do you want to rebase before I merge it?

**Comment by gkossakowski** [comment]
I don't have strong opinion. I decided to append new commits instead of amending old ones because that's easier for reviewer to see if his feedback is addressed. That's the lesson I learnt from working in scala/scala where there's arguably a lot more traffic than in sbt/sbt so maybe practices from there shouldn't be brought here. It's up to you to decide.

Do you want me to just rebase or also squash commits?

**Comment by harrah** [comment]
Oh, I agree that was the right thing to do for the reason you give.  A clean history would be nice to merge though- whatever you think is appropriate works for me.

**Comment by gkossakowski** [comment]
@harrah: ok, I'll squash some of the commits.

**Comment by gkossakowski** [comment]
@harrah: squashed to the degree I find optimal for this PR :)

**Comment by gkossakowski** [comment]
Actually, I was too fast. If reorder some of the commits I can squash even more.

**Comment by gkossakowski** [comment]
@harrah: ok, that's final list of commits ready to be merged.

**Pull request merged**
