### PR TITLE
Fixes #1973. Renames distinct to distinctName

### LINKED ISSUE #1973: PathFinder.distinct is based on file name, not path
If I have the following files:
- `a/b/foo.txt`
- `a/c/foo.txt`

And I do:

``` scala
file("a").***.distinct
```

I end up with only one file, even though there are two distinct paths, because the implementation of `distinct` matches on file name, not file path.

See https://github.com/playframework/playframework/issues/4208 for an example of issues this can cause.

### PR DESCRIPTION
**Pull request by eed3si9n**
Fixes #1973

/review @dwijnand, @jroper

### CODE REVIEW

**Comment by dwijnand** [comment]
The change LGTM, but it doesn't really "fix" #1973.

Perhaps we should add a `.distinctPath`, which would solve #1973 (imo).

Also I agree with @jroper about the intuitive intent of `.distinct` and would argue that the deprecated message should point to `.distinctPath` (or maybe just indicate both).

**Comment by dwijnand** [comment]
For reference, how @jroper worked around current `.distinct`: https://github.com/playframework/playframework/pull/4236

**Comment by eed3si9n** [comment]
What's the return type of `distinctPath`? `PathFinder`, `Seq[String`, or `Seq[File]`?

**Comment by dwijnand** [comment]
`PathFinder` I would've thought.

**Comment by eed3si9n** [comment]
Added it.

``` scala
scala> import sbt._
import sbt._

scala> (file("src") ***).distinctPath
res0: sbt.PathFinder = 

   src/main
   src/main/conscript/sbt
   src/main/conscript/screpl/launchconfig
   src/main/conscript/screpl
   src
   src/main/conscript/scalas/launchconfig
   src/main/conscript/sbt/launchconfig
   src/main/conscript
   src/main/conscript/scalas
```

**Comment by dwijnand** [comment]
Sweet. LGTM.

**Pull request merged**
