### PR TITLE
Make `baseScalacOptions` Scala version dependent.

### PR DESCRIPTION
**Pull request by gkossakowski**
The 92d7520f7 added Scala 2.10 specific compiler options that break
IDE build for Scala 2.9.

This commit makes the new options version specific and
enables them for Scala 2.10 and Scala 2.11 only.

### CODE REVIEW

**Comment by gkossakowski** [comment]
See the problem here: https://jenkins.scala-ide.org:8496/jenkins/view/Sbt%20vs%20Trunk/job/Stock%20SBT%20(0.13)/204/console

I hope soon we can move building Sbt artifacts for IDE into Sbt build so this can be discovered much more easily.

Review by @Blaisorblade.

**Comment by Blaisorblade** [comment]
The code looks good to me and it's still working as expected on 2.10.

Sorry for the breakage! But if this needs to build with Scala 2.9, could you meanwhile document that, say in `CONTRIBUTING.md`? Otherwise other breakage might soon come.
Or maybe it would be easy to add an option for building with 2.9? I was thinking of enabling cross-building, but maybe it's just better to document the command line you use for your build.

Once you at least document the situation, LGTM. And thanks for involving me.

**Comment by gkossakowski** [comment]
@Blaisorblae: Yes. I'm planning to add some docs but I first need to clarify the whole building situation myself. I haven't been involved in IDE builds of sbt until yesterday.

**Comment by Blaisorblade** [comment]
Well then, in the interest of speeding things up, I'll say LGTM anyway.
Please make sure to open a ticket if you don't get this fixed fast. Maybe, while merging this, Mark could quickly add a note to `CONTRIBUTING.md` pointing here.

**Comment by harrah** [comment]
Non-Typesafe contributors don't need to worry about 2.9 or the IDE.  That is our responsibility and mine in particular since I merged it.

**Pull request closed without merging**
