### PR TITLE
Update bridge retrieval in `consoleProject`

### PR DESCRIPTION
**Pull request by Duhemm**
Fixes sbt/sbt#2428

### CODE REVIEW

**Comment by typesafe-tools** [comment]
Can one of the admins verify this patch?

**Comment by dwijnand** [comment]
I'm guessing there's no way to write a test for this?

**Comment by dwijnand** [comment]
maybe a scripted test with `initialCommands` set to `sys exit 0` or something?

**Comment by Duhemm** [comment]
Actually there already are tests for `consoleProject`: https://github.com/sbt/sbt/tree/0.13/sbt/src/sbt-test/project/console

I don't know how they passed...

**Comment by dwijnand** [comment]
huh "This can't actually fail, unfortunately.  The repl traps the exception and continues normally." :)

**Comment by Duhemm** [comment]
Hmmm I think this comment applies only to line 8 of the test. The exception thrown by the failed assertion  will be caught by the Scala REPL which will then continue normally. sbt will probably not even notice the exception.

However, a failure in the previous commands should be caught by sbt...

**Comment by dwijnand** [comment]
This isn't a blocker to this being merged of course. I've just been thinking more about making my pull requests include tests to avoid my addition/change regressing. If you can find a way that we can catch this, that would be great. But even otherwise LGTM.

**Pull request merged**
