### PR TITLE
Fix/1431 wildcard exclusions

### PR DESCRIPTION
**Pull request by jtgrabowski**
Support wildcard exclusions in maven resolver
Like

```
    <dependency>
      <groupId>dom4j</groupId>
      <artifactId>dom4j</artifactId>
      <version>1.6.1</version>
      <scope>compile</scope>
      <exclusions>
        <exclusion>
          <artifactId>*</artifactId>
          <groupId>*</groupId>
        </exclusion>
      </exclusions>
    </dependency>
```

The idea here is that if a dependency contains exclude with wildcards
than it is inTransitive.

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @jtgrabowski,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by jtgrabowski** [comment]
Hi @eed3si9n I was looking why travis tests failed and noticed that there are two similar runs:
- SBT_CMD="scripted dependency-management/*1of2" (this fails)
- SBT_CMD="mavenResolverPluginTest:scripted dependency-management/*1of2 project/transitive-plugins" (this passes)

Why are there two?

**Comment by dwijnand** [comment]
Because one uses regular ivy resolving, the other has the maven resolver
plugin enabled and therefore uses that.

**Comment by jtgrabowski** [comment]
That explains it, thanks. I need to investigate ivy resolving than.

**Comment by jtgrabowski** [comment]
Here is a complementary PR to sbt.ivy:
https://github.com/sbt/ivy/pull/22

**Comment by dwijnand** [comment]
Bumped Ivy and tweaked release notes in https://github.com/sbt/sbt/pull/2731.

**Pull request closed without merging**
