### PR TITLE
add csrReconciliations  setting and set to use Relaxed by default

### LINKED ISSUE #4720: [1.3.0-RC1] coursier fails when with "Conflicting dependencies"
- [x] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md) guidelines

## steps
Add `"com.github.gpgekko" % "sbt-autoprefixer" % "1.2.0"` to a project

## problem
```
[error] lmcoursier.internal.shaded.coursier.error.ResolutionError$Several: Error downloading org.webjars.npm:browserslist:[2.5.1,3)
[error]   Not found
[error]   not found: https://repo1.maven.org/maven2/org/webjars/npm/browserslist/2.11.3/browserslist-2.11.3.pom
[error]   not found: C:\Users\katri\.ivy2\local\org.webjars.npm\browserslist
[error]   not found: https://repo.triplequote.com/artifactory/sbt-plugins-release/org.webjars.npm/browserslist/
[error]   not found: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.webjars.npm/browserslist/
[error]   not found: http://repo.typesafe.com/typesafe/releases/org/webjars/npm/browserslist/maven-metadata.xml
[error] Conflicting dependencies:
[error] org.webjars.npm:is-number:2.1.0:default(compile)
[error] org.webjars.npm:is-number:4.0.0:default(compile)
[error] org.webjars.npm:kind-of:3.2.2:default(compile)
[error] org.webjars.npm:kind-of:6.0.2:default(compile)
[error] org.webjars.npm:string-width:1.0.2:default(compile)
[error] org.webjars.npm:string-width:2.1.1:default(compile)
[error] org.webjars.npm:strip-ansi:3.0.1:default(compile)
[error] org.webjars.npm:strip-ansi:4.0.0:default(compile)
[error]         at lmcoursier.internal.shaded.coursier.error.ResolutionError$.from(ResolutionError.scala:70)
[error]         at lmcoursier.internal.shaded.coursier.Resolve.validate0$1(Resolve.scala:141)
[error]         at lmcoursier.internal.shaded.coursier.Resolve.$anonfun$ioWithConflicts0$4(Resolve.scala:183)
[error]         at lmcoursier.internal.shaded.coursier.util.Task$.$anonfun$flatMap$2(Task.scala:11)
[error]         at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
[error]         at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
[error]         at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] (update) lmcoursier.internal.shaded.coursier.error.ResolutionError$Several: Error downloading org.webjars.npm:browserslist:[2.5.1,3)
[error]   Not found
[error]   not found: https://repo1.maven.org/maven2/org/webjars/npm/browserslist/2.11.3/browserslist-2.11.3.pom
[error]   not found: C:\Users\katri\.ivy2\local\org.webjars.npm\browserslist
[error]   not found: https://repo.triplequote.com/artifactory/sbt-plugins-release/org.webjars.npm/browserslist/
[error]   not found: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.webjars.npm/browserslist/
[error]   not found: http://repo.typesafe.com/typesafe/releases/org/webjars/npm/browserslist/maven-metadata.xml
[error] Conflicting dependencies:
[error] org.webjars.npm:is-number:2.1.0:default(compile)
[error] org.webjars.npm:is-number:4.0.0:default(compile)
[error] org.webjars.npm:kind-of:3.2.2:default(compile)
[error] org.webjars.npm:kind-of:6.0.2:default(compile)
[error] org.webjars.npm:string-width:1.0.2:default(compile)
[error] org.webjars.npm:string-width:2.1.1:default(compile)
[error] org.webjars.npm:strip-ansi:3.0.1:default(compile)
[error] org.webjars.npm:strip-ansi:4.0.0:default(compile)
```

## expectation
Now, the POM truly is missing for some reason, but it worked just fine with 1.2.8

sbt version: 1.3.0-RC1

### PR DESCRIPTION
**Pull request by eed3si9n**
This is a resend of #4925
Fixes #4720
Ref coursier/coursier#1293

Coursier by default uses conflict resolution logic that uses latest-wins for specific versions (for example `commons-io:commons-io:1.1` vs `commons-io:commons-io:2.6`) similar to Ivy, but strict for version ranges (for example `org.webjars.npm:entities:[1.0,1.1)` vs `org.webjars.npm:entities:[1.1.1,2)`), _unlike_ Ivy. This creates seemingly arbitrary conflicts that were discovered in #4720, https://github.com/lagom/lagom-samples/pull/82, and https://github.com/playframework/play-samples/pull/43.

Note that this has nothing to do with Semantic Versioning as seen in the examples above, 2.6 would evict 1.1 if it were a specific version; and `[1.1.1,2)` won't evict `[1.0,1.1)`.

For sbt 1.3.0 we will default to "Relaxed" reconciliation to preserve Ivy-like latest-wins semantics on specific versions as well as version ranges.

### CODE REVIEW

**Comment by eed3si9n** [comment]
My reply was:

The purpose of this change is more for keeping semantic compatibility with Ivy's resolution. Even though version ranges (intervals) are used more often in the context of webjars, I think it's worse to have an ah-hoc rules for a subset of artifacts.

I started digging deep into this area when I ran Lagom sample applications using sbt 1.3.0-RC3 (https://github.com/lagom/lagom-samples/pull/82) and found the following:

```
[error] lmcoursier.internal.shaded.coursier.error.ResolutionError$ConflictingDependencies: Conflicting dependencies:
[error] io.grpc:grpc-core:1.16.1:default(compile)
[error] io.grpc:grpc-core:1.20.0:default(compile)
[error] io.grpc:grpc-core:[1.16.1]:default(compile)
[error] io.grpc:grpc-core:[1.20.0]:default(compile)
[error] 	at lmcoursier.internal.shaded.coursier.Resolve$.validate(Resolve.scala:394)
[error] 	at lmcoursier.internal.shaded.coursier.Resolve.validate0$1(Resolve.scala:140)
[error] 	at lmcoursier.internal.shaded.coursier.Resolve.$anonfun$ioWithConflicts0$4(Resolve.scala:184)
[error] 	at lmcoursier.internal.shaded.coursier.util.Task$.$anonfun$flatMap$2(Task.scala:14)
[error] 	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
[error] 	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
[error] 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (hello-impl / update) lmcoursier.internal.shaded.coursier.error.ResolutionError$ConflictingDependencies: Conflicting dependencies:
[error] io.grpc:grpc-core:1.16.1:default(compile)
[error] io.grpc:grpc-core:1.20.0:default(compile)
[error] io.grpc:grpc-core:[1.16.1]:default(compile)
[error] io.grpc:grpc-core:[1.20.0]:default(compile)
```

Since we have lots of Play and Lagom users, smooth transition of is a must have. Note that this isn't a webjar conflict. I think it would be better to migrate all users first into Couriser-based sbt, and then provide them with various options to make their graph more correct, using eviction report and/or strict mode.

Also part of the issue might be that the error reporting has regressed compared to lm-ivy that reports error with tree-view (https://github.com/sbt/sbt/pull/1447):

```
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: foundrylogic.vpp#vpp;2.2.1: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn]  Note: Unresolved dependencies path:
[warn]      foundrylogic.vpp:vpp:2.2.1
[warn]        +- org.apache.cayenne:cayenne-tools:3.0.2
[warn]        +- org.apache.cayenne.plugins:maven-cayenne-plugin:3.0.2
[warn]        +- d:d_2.10:0.1-SNAPSHOT
```

Reporting errors or conflicts this way might allow the build users to reduce some (probably not all) of the unnecessary transitive conflicts.

**Comment by eed3si9n** [comment]
```
Running watch/alias
[info] #
[info] # A fatal error has been detected by the Java Runtime Environment:
[info] #
[info] #  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00000000649701c1, pid=2424, tid=0x00000000000009a0
[info] #
[info] # JRE version: Java(TM) SE Runtime Environment (8.0_162-b12) (build 1.8.0_162-b12)
[info] # Java VM: Java HotSpot(TM) 64-Bit Server VM (25.162-b12 mixed mode windows-amd64 compressed oops)
[info] # Problematic frame:
[info] # V  [jvm.dll+0x1401c1]
[info] #
[info] # Core dump written. Default location: C:\Users\appveyor\AppData\Local\Temp\1\sbt_6a87ad0a\hs_err_pid2424.mdmp
[info] #
[info] # An error report file with more information is saved as:
[info] # C:\Users\appveyor\AppData\Local\Temp\1\sbt_6a87ad0a\hs_err_pid2424.log
[info] #
[info] # If you would like to submit a bug report, please visit:
[info] #   http://bugreport.java.com/bugreport/crash.jsp
[info] #
[error] x watch/alias 
[error]  Cause of test exception: {line 1}  Command failed
```

@eatkins I am kind of confused why this is coming back in this PR.

**Comment by eed3si9n** [comment]
Maybe my branch is out of date. Plz hold.

**Comment by eed3si9n** [comment]
35bc79063ccdc78dbcf5e1c45ad4bed343a97b1a is still having EXCEPTION_ACCESS_VIOLATION

```
Running watch/alias
[info] #
[info] # A fatal error has been detected by the Java Runtime Environment:
[info] #
[info] #  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x0000000050bc01c1, pid=2824, tid=0x0000000000000290
[info] #
[info] # JRE version: Java(TM) SE Runtime Environment (8.0_162-b12) (build 1.8.0_162-b12)
[info] # Java VM: Java HotSpot(TM) 64-Bit Server VM (25.162-b12 mixed mode windows-amd64 compressed oops)
[info] # Problematic frame:
[info] # V  [jvm.dll+0x1401c1]
[info] #
[info] # Core dump written. Default location: C:\Users\appveyor\AppData\Local\Temp\1\sbt_f9c472e4\hs_err_pid2824.mdmp
[info] #
[info] # An error report file with more information is saved as:
[info] # C:\Users\appveyor\AppData\Local\Temp\1\sbt_f9c472e4\hs_err_pid2824.log
[info] #
[info] # If you would like to submit a bug report, please visit:
[info] #   http://bugreport.java.com/bugreport/crash.jsp
[info] #
[error] x watch/alias 
[error]  Cause of test exception: {line 1}  Command failed
```

**Comment by eatkins** [comment]
This is almost certainly due to https://github.com/coursier/sbt-coursier/pull/120. I was able to reproduce on my vm and generate a call stack at the crash:
```
Stack: [0x000000002ac00000,0x000000002ad00000],  sp=0x000000002acfe5b0,  free space=1017k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
V  [jvm.dll+0x11a621]
C  [jansi-64-6166856592215972021.dll+0x2280]
C  0x00000000030c89a7

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  org.fusesource.jansi.internal.Kernel32$INPUT_RECORD.init()V+0
j  org.fusesource.jansi.internal.Kernel32$INPUT_RECORD.<clinit>()V+6
v  ~StubRoutines::call_stub
j  org.fusesource.jansi.internal.Kernel32.readConsoleInputHelper(JIZ)[Lorg/fusesource/jansi/internal/Kernel32$INPUT_RECORD;+8
j  org.fusesource.jansi.internal.Kernel32.readConsoleKeyInput(JIZ)[Lorg/fusesource/jansi/internal/Kernel32$INPUT_RECORD;+3
j  org.fusesource.jansi.internal.WindowsSupport.readConsoleInput(I)[Lorg/fusesource/jansi/internal/Kernel32$INPUT_RECORD;+21
j  jline.WindowsTerminal.readConsoleInput()[B+3
j  jline.WindowsTerminal.access$000(Ljline/WindowsTerminal;)[B+1
j  jline.WindowsTerminal$1.read()I+24
j  sbt.internal.Continuous$$anon$1$$anon$2.run()V+27
v  ~StubRoutines::call_stub

```

**Comment by eatkins** [comment]
https://github.com/sbt/sbt/pull/4953

**Comment by eed3si9n** [comment]
I'm a bit confused since https://github.com/coursier/sbt-coursier/pull/118 is merged, so I thought that's now sorted out.

**Comment by eatkins** [comment]
Yeah, I don't know, but above the full report from the hs_errXXX.log file was:
```
                                                                                                                                                                                                                        
Register to memory mapping:                                                                                                                                                                                             
                                                                                                                                                                                                                        
RAX=0x0000000000000000 is an unknown value                                                                                                                                                                              
RBX=0x0000000018c82800 is a thread                                                                                                                                                                                      
RCX=0x0000000018c82800 is a thread                                                                                                                                                                                      
RDX=0x00000000f480abc8 is an oop                                                                                                                                                                                                                                                           
java.lang.NoSuchFieldError                                                              
 - klass: 'java/lang/NoSuchFieldError'                                                                                                                                                                                               
RSP=0x000000002acfe5b0 is pointing into the stack for thread: 0x0000000018c82800                            
RBP=0x0000000000000002 is an unknown value                                                              
RSI=0x0000000000000002 is an unknown value                                                 
RDI=0x0000000000000000 is an unknown value                                                                                                                                                                                                                                                
R8 =0x0000000000000000 is an unknown value                                                                              
R9 =0x0000000000000002 is an unknown value                                     
R10=0x0000000000000000 is an unknown value                                     
R11=0x000000002acfe5f0 is pointing into the stack for thread: 0x0000000018c82800                                      
R12=0x0000000000000000 is an unknown value                                                                            
R13=0x00000000239c6cc8 is pointing into metadata                                                                      
R14=0x000000002acfe6d0 is pointing into the stack for thread: 0x0000000018c82800                                                                                                                                                                                                           R15=0x0000000018c82800 is a thread       
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Stack: [0x000000002ac00000,0x000000002ad00000],  sp=0x000000002acfe5b0,  free space=1017k                                                                                                                                                                                                  Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)                                                                                                                                                                                                            V  [jvm.dll+0x11a621]                                                                                                                                                                                                                                                                      C  [jansi-64-6166856592215972021.dll+0x2280]                                    
C  0x00000000030c89a7                                                                               
                                                                                        
Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)                         
j  org.fusesource.jansi.internal.Kernel32$INPUT_RECORD.init()V+0                                         
j  org.fusesource.jansi.internal.Kernel32$INPUT_RECORD.<clinit>()V+6                                                                                                                                                                                                                       v  ~StubRoutines::call_stub                                                                                                                                                                                                                                                                j  org.fusesource.jansi.internal.Kernel32.readConsoleInputHelper(JIZ)[Lorg/fusesource/jansi/internal/Kernel32$INPUT_RECORD;+8
j  org.fusesource.jansi.internal.Kernel32.readConsoleKeyInput(JIZ)[Lorg/fusesource/jansi/internal/Kernel32$INPUT_RECORD;+3
j  org.fusesource.jansi.internal.WindowsSupport.readConsoleInput(I)[Lorg/fusesource/jansi/internal/Kernel32$INPUT_RECORD;+21
j  jline.WindowsTerminal.readConsoleInput()[B+3                                      
j  jline.WindowsTerminal.access$000(Ljline/WindowsTerminal;)[B+1                  
j  jline.WindowsTerminal$1.read()I+24                                                                                                                                      
j  sbt.internal.Continuous$$anon$1$$anon$2.run()V+27                                      
v  ~StubRoutines::call_stub     
```                                                                        
 
which sure looks like a binary compatibility issue.

**Comment by eatkins** [comment]
Pretty sure this will be fixed once the branch is updated to develop.

**Review by eatkins — APPROVED** [review]
LGTM.

**Pull request merged**
