### PR TITLE
Improve performance for DefaultParsers.validID(String)

### PR DESCRIPTION
**Pull request by pauldraper**
`DefaultParsers.validID` is called _a lot_. (I think mostly from KeyIndex).

When loading the following project, it is called about 300k times .

**project/build.sbt**

``` scala
addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.3.8")

resolvers += Resolver.typesafeRepo("releases")
```

**build.sbt**

``` scala
lazy val a = project.enablePlugins(PlayScala)

lazy val b = project.enablePlugins(PlayScala)

lazy val c = project.enablePlugins(PlayScala)

lazy val d = project.enablePlugins(PlayScala)

lazy val e = project.enablePlugins(PlayScala)

lazy val f = project.enablePlugins(PlayScala)

lazy val g = project.enablePlugins(PlayScala)

lazy val h = project.enablePlugins(PlayScala)

lazy val i = project.enablePlugins(PlayScala)

lazy val j = project.enablePlugins(PlayScala)

lazy val k = project.enablePlugins(PlayScala)

lazy val l = project.enablePlugins(PlayScala)

lazy val m = project.enablePlugins(PlayScala)

lazy val n = project.enablePlugins(PlayScala)

lazy val o = project.enablePlugins(PlayScala)

lazy val p = project.enablePlugins(PlayScala)

lazy val q = project.enablePlugins(PlayScala)

lazy val r = project.enablePlugins(PlayScala)

lazy val s = project.enablePlugins(PlayScala)

lazy val t = project.enablePlugins(PlayScala)

lazy val u = project.enablePlugins(PlayScala)

lazy val v = project.enablePlugins(PlayScala)

lazy val w = project.enablePlugins(PlayScala)

lazy val x = project.enablePlugins(PlayScala)

lazy val y = project.enablePlugins(PlayScala)

lazy val z = project.enablePlugins(PlayScala)

lazy val all = project.aggregate(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z)

lazy val consonants = project.aggregate(b, c, d, f, g, h, j, k, l, m, p, q, r, s, t, v, w, x, y, z)

lazy val noel = project.aggregate(a, b, c, d, e, f, g, h, i, j, k, m, n, o, p, q, r, s, t, u, v, w, x, y, z)

lazy val improvementOfEnglish = project.aggregate(a, b, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, z)

lazy val periodicTable = project.aggregate(a, b, c, d, e, f, g, h, i, k, l, m, n, o, p, q, r, s, t, u, v, w, z)
```

After this change, the load time after compilation is about 10% faster for me (down from 8-9s to 7-8s).

### CODE REVIEW

**Comment by eed3si9n** [comment]
LGTM
Could you rebase on top of the latest?

**Comment by pauldraper** [comment]
Rebased.

**Comment by pauldraper** [comment]
So, it fails the "quality" check, which is fair, but in this case intentional.

**Comment by pauldraper** [comment]
Ping.

**Review by dwijnand — APPROVED** [review]

**Pull request merged**
