### PR TITLE
Jansi init

### PR DESCRIPTION
**Pull request by szeiger**
[Jansi](http://jansi.fusesource.org/) can be used to get colorized output from sbt on Windows. This patch for the sbt launcher initializes Jansi and enables ANSI output for sbt if Jansi is found on the classpath, thus removing the need for a separate launcher class for bootstrapping.

Here's the sbt.bat I'm using with this launcher:

```
@set SCRIPT_DIR=%~dp0\
@java -version:1.6.0 -server -XX:ReservedCodeCacheSize=128m -XX:+UseCompressedOops -XX:+UseParallelGC -XX:+DoEscapeAnalysis -Xmx3076M -XX:MaxPermSize=1024M -Xss2M -cp "%SCRIPT_DIR%jansi-1.7.jar;%SCRIPT_DIR%sbt-launch-0.11.2-ansi.jar" xsbt.boot.Boot %*
```

And for MSYS:

```
UDIR=`dirname $0`
WDIR=`cmd //c echo $UDIR`
java -version:1.6.0 -server -XX:ReservedCodeCacheSize=128m -XX:+UseCompressedOops -XX:+UseParallelGC -XX:+DoEscapeAnalysis -Xmx3076M -XX:MaxPermSize=1024M -Xss2M -cp "$WDIR/jansi-1.7.jar;$WDIR/sbt-launch-0.11.2-ansi.jar" xsbt.boot.Boot $@
```

This could be done in more elegant ways (e,g, having the main sbt JAR depend on Jansi and initializing it there, so that the launcher wouldn't need the separate Jansi JAR. OTOH, doing it in the launcher makes it work retroactively for all sbt versions.

### CODE REVIEW

**Comment by harrah** [comment]
Sorry, I didn't notice that this was on the wrong branch.  It should go on 0.11.

**Comment by indrajitr** [comment]
And what about 0.12, shouldn't it go there as well?

**Comment by indrajitr** [comment]
cherry-picked on 0.12 branch

**Comment by harrah** [comment]
Thanks!

**Comment by jsuereth** [comment]
Just a note:

After having battled the JANSI battle again,  I feel this fix may need to get reverted for an alternative.   In ideal-o-land, sbt will correctly call `systemInstall` on a classloader that contains JANSI in such a way that does not break either the scala REPL or sbt itself after a `reboot` command.   The mechanisms represented in this PR falls short of those two requirements.  I'd like to open a new ticket/enhancement request where we can focus on this solution, and I'd also like to remove this workaround in the meantime, as it's causing issues with JLine functionality across scala REPL versions.

**Pull request merged**
