### PR TITLE
Expand the DSL abilities with Project manipulations

### LINKED ISSUE #1213: Circumventing the common declaration of addPlugins
Given the proposed AutoPlugin mechanism where plugins are required to be added, it'd be nice to have a short cut to the following common expressions in build.sbt:

``` scala
import com.typesafe.sbt.web.SbtWeb

lazy val root = project.in(file(".")).addPlugins(SbtWeb)
```

For example, if the project is a single module then may be sbt's processing of build.sbt can be magical and automatically perform the above. Why else would you call `addSbtPlugin` from `plugins.sbt` if your single module project wasn't going to use it?

Further to the above, and orthogonal, perhaps a short cut to the expression could be provided e.g.:

``` scala
lazy val root = project.current.addPlugins(SbtWeb)
```

My major concern though is that all build.sbt files will have at least 3 extra lines over what they used to have. It isn't a massive concern, but if we are able to address it then I think it'll make a good UX.

### PR DESCRIPTION
**Pull request by jsuereth**
This does the following:
- Split loading of configuration into two pieces: Discovery and Resolution
- Discovery is when we find all projects defined in a config file _and_ load all Setting/Manipulation/Definitions
- Resolution is when we take _all_ the .sbt + .scala files associated with a project, do the AutoPlugin resolution and finalize the `Project` instance
- Migrates the DSL of `.sbt` files to use `sbt.internals.DslEntry`.
- Adds `ProjectManipulation` as a DSL option instead of just `Seq[Setting[_]]`
- Applies project manipulation functions before finalizing projects
- Add `enablePlugin` and `disablePlugin` to the DSL.
- Update tests.

Note: @benburton informs me we should upgrade to using Fiber instead of a DSL.

Fixes #1213 and #1299

Also, I expect this one may take some time for review, but we should still be prompt.   Review by @eed3si9n cc> @cunei

### CODE REVIEW

**Comment by jsuereth** [comment]
Oh, also still waiting on full test suite.  DO NOT MERGE until we have two verified computers with success.  This one is a too big not to be cautious if Travis fails.

**Comment by jsuereth** [comment]
Note on failures:

```
[trace] Stack trace suppressed: run last root/*:scripted for the full output.
[error] (root/*:scripted) Failed tests:
[error]     project / derived
[error] Total time: 5342 s, completed May 6, 2014 6:27:19 PM
```

I'll have to investigate.  Maybe @dansanduleac has ideas on why we're failing now.

**Comment by jsuereth** [comment]
Ok, ignore the derived setting test failures, they're failing against _MASTER_ for me, so I think this PR is good to go. I'm going to investigate why we lost "success" for the derived settings tests.  Looks like a commit is missing or something.

**Comment by eed3si9n** [comment]
A scripted test combined with auto plugin would be interesting.

In `a.sbt`:

``` scala
enablePlugins(FooPlugin) // Suppose FooPlugin requires BarPlugin, and bring in setting for foo

check := {
  println(foo.value) // foo.value fails here?
}
```

In `b.sbt`:

``` scala
disablePlugins(BarPlugin) 
```

**Comment by eed3si9n** [comment]
Also what's the ordering if there is `c.sbt`?

``` scala
val root = (project in file(".")).enablePlugins(BarPlugin)
```

Add docs for this behavior?

**Comment by jsuereth** [comment]
@eed3si9n BarPlugin is enabled first if you define a root project there, an oddity of the implementation.

Basically, here's your order:
1. `Project` instances are loaded first
2. .sbt file manipulations in alphabentical order (or whatever SettingSets defines them to be)

Not a ton we can do about that at this point, without some MAJOR refactorings to the DSL.

**Comment by eed3si9n** [comment]
Is there a document that describes this DSL shuffling? To be clear, `enablePlugins(FooPlugin)` in `a.sbt` is applied to the same instance defined in `c.sbt` as `root` correct?

**Comment by jsuereth** [comment]
It's the same shuffling that occurs with regular-old settings in build.sbt, so by "document" I think the way we already describe build.sbt and multi-modules has documentation on this.  If not, then we're lacking in general around load and _now_ (with more clearly commented code) we could improve those docs if needed

**Comment by jsuereth** [comment]
Oh, and the answer to the question is yes.

**Comment by jsuereth** [comment]
@eed3si9n Check out  f579e90 for the test showcasing what you asked for.

**Comment by jsuereth** [comment]
So it looks like besides derived setting failures, travisCI is passing.  Giving it one more go with better memory settings this time.

**Comment by jsuereth** [comment]
Ok, so enough tests passed you should be able to review/merge now.

**Comment by jsuereth** [comment]
COOL!  Travis passes everything but `project/derived` which is failing in 0.13 branch anyway.

**Pull request merged**
