### PR TITLE
Add `print` command that mimics `show`, but to standard output, not the logger

### LINKED ISSUE #4184: Plain print project settings
## problem
As a build master, I want to print the project settings in plain text for consumption by other scripts. For example, setting ENV vars, or setting properties in Jenkins pipeline scripts.

``` bash
export SBT_PROJECT_VERSION=$(sbt 'show version')
```

## expectation
When I run "show", I would like an output like:

>$ sbt 'show version'
0.1-SNAPSHOT

I dont want any log output. If there's an error, just print an empty string.

## notes
If changing the behaviour of `show` is not possible, then a new task like `$sbt 'print version'` would suffice.

I was steered here from a discussion on #840

### PR DESCRIPTION
**Pull request by Falmarri**
Fixes  #4184

- [ x ] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/1.x/CONTRIBUTING.md) guidelines

### CODE REVIEW

**Comment by muuki88** [comment]
Thanks for your pull request :hugs: 

The usage described in the issue still wouldn't work as there are always initial logging outputs, right?
```bash
export SBT_PROJECT_VERSION=$(sbt 'show version')
```
or does it?

**Comment by eed3si9n** [comment]
This would be a change in the behavior, so it might end up breaking other people's build.
Maybe we should either make a new similarly named command or implement JVM flag that we can pass in from the bash/bat script (similar to `-no-colors`)?

**Comment by Falmarri** [comment]
@muuki88 If you run with `-error` it will suppress logging outputs. I hadn't considered having it override all logging on its own

@eed3si9n open to suggestions/requirements =]

**Comment by muuki88** [comment]
@Falmarri since when version does `-error` work? I tried with `1.1.0` and I still see a lot of logging output.

**Comment by muuki88** [comment]
@eed3si9n I like the jvm flag suggestion. Actually I search for a `--quiet` flag that silences everything aside from the `show` command. WDYT @Falmarri ?

**Comment by eed3si9n** [comment]
@muuki88 `--error` works well for sbt 1.2.3:

Try the following on sbt/sbt:

```
$ sbt --error "eval println(\"hello\")"
hello
```

**Comment by Falmarri** [comment]
@muuki88 the -error was fixed somewhere in the 1.1.x releases. Not sure where exactly, but it definitely works on 1.2.x

**Comment by Falmarri** [comment]
@eed3si9n I pushed a change that adds this new version as the `print` command, rather than `show`. Thoughts?

**Review by eed3si9n — APPROVED** [review]
LGTM

**Review by muuki88 — APPROVED** [review]

**Comment by dwijnand** [comment]
1. This isn't documented anywhere
2. It doesn't work as soon as your build contains more than one project (and you follow the custom of having the root project aggregate all modules).  Even using `ThisBuild` won't work, due to #5349...

**Pull request merged**
