### PR TITLE
fix scaladoc cache bug. when use -doc-root-content

### PR DESCRIPTION
**Pull request by xuwei-k**
### steps

Define build.sbt that uses scaladoc `-doc-root-content` option.

``` scala
scalacOptions in (Compile, doc) := Seq("-doc-root-content", "root.txt")
```
1. Run `doc` task from the shell.
2. Change the content of root.txt.
3. Run `doc` task again.
### problem

The `doc` does not reflect the change in root.txt.
### what this pull request changes

The cache is updated if the file specified by `-doc-root-content` changes.

### CODE REVIEW

**Comment by harrah** [comment]
Thanks for the pull request.  This one needs some discussion and feedback is appreciated from the wider audience.

Parsing general options is not something sbt has historically handled.  On one hand, the user changes the doc-root-content file and scaladoc is not rerun, which is incorrect behavior to the user.  On the other hand, parsing options is a slippery slope and difficult to maintain, especially across Scala versions.

Thoughts?

**Comment by eed3si9n** [comment]
When sbt started caching docs, it put itself on top of the slippery slope. I'd say +1 for @xuwei-k's fix.

**Comment by eed3si9n** [comment]
I updated the description to provide better context for further discussion.

**Comment by jsuereth** [comment]
+1 to what @eed3si9n said.   We're already on the hill with a millstone on our necks.  Might as well embrace it.  (I'd argue we're probably half-way down the slippery slope already.   We should invest in some mud boots).

**Comment by harrah** [comment]
The feedback is appreciated.  

There are several clear boundaries that make this slippier than what already exists.  There are the core aspects of compilation with options that are not going to change or aren't changing anytime soon.  That is what is supported now.  Then, there are options that are more likely to change, such as -doc-root-content.   Finally, there are things like compiler plugins and options to them.  There is probably always going to be something missed by caching as long as there isn't a solution that catches everything without needing to know about all options that take a file.

I'll merge this if no one changes their mind in the next day ;).

**Comment by jsuereth** [comment]
@harrah Perhaps we just need a way to add things to the cache detection in a more principled fashion.  When you have slippery slopes, having the "out of control truck ramps" is better than nothing i.e. if we have a workaround for our own builds, that's better than nothing.

**Comment by harrah** [comment]
If there is a more principled fashion, I'm open to it.  This pull request duplicates an option name and how options are parsed, but I don't see a better way to do it.

**Comment by eed3si9n** [comment]
If you want to future proof the implementation, how about making a new key that tracks options like `fileInputOptions: SettingKey[Seq[String]]`? That way, you can set it to:

``` scala
fileInputOptions in doc := Seq("doc-root-content", "diagrams-dot-path")
```

In case the options changed in a future `scalaVersion`, build users have a way out.
Note Kenji's implementation is passively reading what's passed to `scalacOptions in (Compile, doc)`, so even when the option renames to "doc-foo-content" it should just revert back to the current behavior.

ps: `"diagrams-dot-path"` also takes file input?

**Comment by harrah** [comment]
Yeah, a reasonable idea.  I don't think enough people would actually change it to be worth it, though.  I doubt that many people would notice and then figure out what to change.  I'd like to see a more general caching mechanism anyway.

@xuwei-k Whatever @eed3si9n decides, go with and he can merge.  Either just add `diagrams-dot-path` to your hard coded set or do the `fileInputOptions` approach.

**Comment by harrah** [comment]
@eed3si9n if I wasn't clear, this is yours to review further and/or merge if you want it.

**Comment by eed3si9n** [comment]
@harrah Yea, I got that part. I was hoping @xuwei-k would commit more code. Otherwise, I can work on it is that cool?

**Comment by harrah** [comment]
Yes, certainly feel free to work on it further.  @xuwei-k may have been waiting for which direction you wanted to go with it, since I indicated that was up to you.

**Comment by eed3si9n** [comment]
We've had a few exchanges on Twitter. Unless it's difficult, I'm leaning towards `fileInputOptions: SettingKey[Seq[String]]`.

**Comment by eed3si9n** [comment]
Added a new key `fileInputOptions`:

```
doc-file-options> inspect tree doc::fileInputOptions
[info] compile:doc::fileInputOptions = List(-doc-root-content, -diagrams-dot-path)
```

Tested it using the example that came with the original commit, and it seems to work.

**Comment by eed3si9n** [comment]
rebased, squashed, and merged.

**Comment by xuwei-k** [comment]
@eed3si9n thanks a lot!

**Pull request merged**
