### PR TITLE
Stop run tasks from being too verbose

### PR DESCRIPTION
**Pull request by indrajitr**
Having `"Running " + mainClass` ...  at `info` level generates too many messages when run task is used (for example, to generate resources). Setting this at debug level would suffice.

### CODE REVIEW

**Comment by harrah** [comment]
Not sure about this.  I agree that in custom cases it might not be desirable, but it is in the standard cases.  Perhaps the message should be moved somewhere more appropriate?

**Comment by indrajitr** [comment]
I see your point. Any recommendation where this can be relocated?

FWIW, there is an inconsistency here in the fact that `Run.run()` spews _lots_ on messages where as `ForkRun.run()` stays totally silent. So having `fork in mytask := true` goes totally silent but `fork in mytask := false` is noisy. We should straighten that anyway.

**Comment by harrah** [comment]
Perhaps it could go in the run task directly instead of the runner.  The run task creation method might need a `quiet` parameter with default=true and the built-in sbt tasks changing this to be false.  I haven't actually looked to see if this is reasonable.

I don't see how Run.run() produces a lot of messages.  It has more information at the debug level, but I only see one message at the info level.

**Comment by indrajitr** [comment]
I should have been clearer, `Run.run()` produces a lot of messages when it's invoked lot of times (say, when using script multiple times to generate source files).

That said, this is purely cosmetic and doesn't lead to loss of functionality or anything like that. So let's defer this till there is a good alternative.

**Pull request merged**
