### PR TITLE
Updates to Coursier 2.0.7

### PR DESCRIPTION
**Pull request by jtjeferreira**
https://github.com/coursier/sbt-coursier/releases/tag/v2.0.4 which includes https://github.com/coursier/coursier/releases/tag/v2.0.7

> Memo-ize classes that can be created at a high rate
coursier.core.{Dependency, Module, Publication} are now memo-ized (using weak references). This can lower the amount of duplicate instances of these objects, and lower GC pressure.

### CODE REVIEW

**Comment by jtjeferreira** [comment]
I cant reproduce the failure of `repoOverrideTest:scripted dependency-management/*` locally. I will keep digging.

@alexarchambault there is a problem with windows paths in https://ci.appveyor.com/project/sbt/sbt/builds/36400186?fullLog=true
```
[info] [error] (update) java.nio.file.InvalidPathException: Illegal character [:] in path at index 4: ///C:/Users/appveyor/.ivy2//local/
```
maybe a problem from https://github.com/coursier/sbt-coursier/commit/6b597b3f799b27dd1022d2b0a4365a7e7cfafa47

**Comment by jtjeferreira** [comment]
The failure of `failure of repoOverrideTest:scripted dependency-management/*` seems gone... However one check seems stuck. Going to close and reopen...

**Comment by eed3si9n** [comment]
```
[error] 	project/sbt-file-projects
[error] 	project/src-scala-binary-version
```

These scripted failures are likely unrelated to this PR - https://github.com/sbt/sbt/issues/6123

**Comment by jtjeferreira** [comment]
> ```
> [error] 	project/sbt-file-projects
> [error] 	project/src-scala-binary-version
> ```
> 
> These scripted failures are likely unrelated to this PR - #6123

so the only problem is with windows path handling. @alexarchambault I will wait for your feedback. Meanwhile I will try to make some performance measurements locally...

**Comment by jtjeferreira** [comment]
From the stacktrace 
```
[info] [error] java.nio.file.InvalidPathException: Illegal character [:] in path at index 4: ///C:/Users/appveyor/.ivy2//local/
[info] [error] 	at sun.nio.fs.WindowsPathParser.nextSlash(WindowsPathParser.java:212)
[info] [error] 	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:111)
[info] [error] 	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
[info] [error] 	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
[info] [error] 	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
[info] [error] 	at java.nio.file.Paths.get(Paths.java:84)
[info] [error] 	at lmcoursier.internal.Resolvers$.pathToUriString(Resolvers.scala:61)
[info] [error] 	at lmcoursier.internal.Resolvers$.repository(Resolvers.scala:88)
[info] [error] 	at lmcoursier.CoursierDependencyResolution.$anonfun$update$17(CoursierDependencyResolution.scala:106)
[info] [error] 	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:292)
[info] [error] 	at scala.collection.Iterator.foreach(Iterator.scala:943)
```

and looking at the code of `WindowsPathParser.java` (http://hg.openjdk.java.net/jdk8/jdk8/jdk/file/687fd7c7986d/src/windows/classes/sun/nio/fs/WindowsPathParser.java). It looks like the initial slashes are making that path to be interpreted as an UNC path, which then fails in the `:`.

@alexarchambault any hint here? also could you explain what you were trying to fix in [`6b597b3` (#294)](https://github.com/coursier/sbt-coursier/pull/294/commits/6b597b3f799b27dd1022d2b0a4365a7e7cfafa47)? Please also note that if possible we should avoid `Path.toUri` as it can make a system call as I discovered recently in https://github.com/eed3si9n/sjson-new/pull/117

**Comment by alexarchambault** [comment]
I changed things [in coursier itself in a first time](https://github.com/coursier/coursier/pull/1916), to fix https://github.com/coursier/coursier/issues/1581 / https://github.com/sbt/sbt/issues/5868 / https://github.com/sbt/sbt/issues/5433. In order to accomodate escaped characters in `file://` URLs.

I would expect things to be fix-able here, as we already run some `publishLocal` tests from Windows in the CI of sbt-coursier, like [this one](https://github.com/coursier/sbt-coursier/tree/master/modules/sbt-coursier/src/sbt-test/shared-2/tests-classifier).

**Comment by jtjeferreira** [comment]
Looks like I fixed it

**Comment by jtjeferreira** [comment]
Hi @eed3si9n WDYT about backporting this to 1.4.x? 

Comparing sbt `1.4.3` and `1.5.0-bin-20201128T081330` in my work project I see reduction of retained heap for `lmcoursier.internal.SbtCoursierCache` from 327M to 139M...

image

image

In the left side of each image, in the attributes tab you can see the HashMap has the same number of elements...

**Comment by eed3si9n** [comment]
I'd be +1 on backporting this for the bug fix that affects Windows users (whitespace in path) - https://github.com/coursier/coursier/pull/1916.

**Pull request merged**
