### PR TITLE
Resolved bugs reported in Issue 947.

### PR DESCRIPTION
**Pull request by awhitford**
name and version had some duplication in the source that didn't seem to appear anywhere -- looked safe to remove.
For version, I think the initial advice should be to use a SNAPSHOT version (as a non-SNAPSHOT version should be limited to "cutting a release.")
For organization, it looks like the initial advice was being hidden because of a missing double colon, and then the later advice for organizationName was incorrectly stating organization in its example.
The organizationHomepage and license urls needed to be url values -- not strings.

### CODE REVIEW

**Comment by harrah** [comment]
The "duplication" is used by the index with examples: http://www.scala-sbt.org/release/docs/Howto/Howto.html#project-metadata.  @jsuereth might have an opinion about using `-SNAPSHOT`.  Looks good otherwise.

**Comment by jsuereth** [comment]
yeah, given that we use ivy AND all the issues around -SNAPSHOT in generally, it's best to avoid that convention.  I have a talk about it in effective sbt, and I know a lot of those of us who work with maven/ivy dependency management agree on this.  I can go into more detail, but I highly recommend not using -SNAPSHOT (see the sbt-git plugin's option here for sha-versioned releases).  I'd prefer not to encourage this in our HowTo, because people will copy-paste those example and then wonder why resolutoins continues to get slower every time they add dependencies, and why changes aren't showing up when they compile.... (or too many changes).

Also -SNAPSHOT completely ruins tools like `git bisect`, which are bread and butter for support/bug analysis tasks...

**Comment by jsuereth** [comment]
Oh, other than -SNAPSHOT bits, this looks great!!!! Thanks for taking time to improve our docs.  If you're using -SNAPSHOT with sbt (and not because you integrate with existing maven builds), then I'd encourage you to look at the alternatives to this.

**Comment by harrah** [comment]
@awhitford Can you update the pull request according to the feedback?

**Comment by awhitford** [comment]
Hope this helps.

**Comment by harrah** [comment]
Merged in e7d5cd1bd25aa24abb6a1ead3a2701bc451ff724, thanks!

**Pull request closed without merging**
