### PR TITLE
merge 1.1.x

### PR DESCRIPTION
**Pull request by eed3si9n**
- [x] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/1.x/CONTRIBUTING.md) guidelines

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @som-snytt,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Review by dwijnand — APPROVED** [review]

**Comment by lightbend-cla-validator** [comment]
Hi @som-snytt,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by som-snytt** [comment]
The only time Cla talks to me is when she wants something or to complain about me.

**Comment by eed3si9n** [comment]
Backporting the last few commits to 1.1.x first - https://github.com/sbt/sbt/pull/4144

**Pull request merged**
