### PR TITLE
Publish to WinGet

### LINKED ISSUE #6980: Publish releases to Windows Package Manager (WinGet)
With every new release of SBT, use a GitHub workflow to update manifests at https://github.com/microsoft/winget-pkgs repository.

I can create a pull request if you would like. It would help in keeping manifests up-to-date at WinGet with every new release automatically.

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
This action automatically generates manifests for WinGet Community Repository ([microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs)) and submits them.

Before merging this:
1. Please add a GitHub token with `public_repo` scope as a repository secret and rename the secret name in the workflow.
2. Fork [microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs) under @sbt.

* Resolves https://github.com/sbt/sbt/issues/6980

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @vedantmgoyal2009,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[https://www.lightbend.com/contribute/cla](https://www.lightbend.com/contribute/cla)

**Comment by vedantmgoyal9** [comment]
Screenshot_20220724-103611_Gmail

**Comment by lightbend-cla-validator** [comment]
Hi @vedantmgoyal2009,

Thank you for your contribution! We really value the time you've taken to put this together.

We see that you have signed the Lightbend Contributors License Agreement before, however, the CLA has changed since you last signed it.
Please review the new CLA and sign it before we proceed with reviewing this pull request:

[https://www.lightbend.com/contribute/cla](https://www.lightbend.com/contribute/cla)

**Comment by eed3si9n** [comment]
I'm in the process of creating a dedicated GitHub account for this, since I don't think putting my own token is a good idea.
The GitHub account that I created got immediately flagged as suspicious, so I am contacting GitHub support to reactivate it.

**Pull request merged**
