### PR TITLE
Enable Javadoc generation in `doc` task

### PR DESCRIPTION
**Pull request by indrajitr**
- `docSetting` is now updated to do `Javadoc` in addition to `Scaladoc`. In hybrid project, the outputs are rebased to `scala` or `java` sub-directory but for pure scala or pure java projects, the subdirectory isn't added. This helps retain compatibility as much as possible. I would have liked to tuck them behind some sort of `Doc.apply(...)(...)` but kept it as-is to avoid breaking change (at least at this level).
- Taking cue from `compileInputsTask`, the maxErrors is currently set to 100 to avert the 9 argument cap. Going forward, I wonder if we can re-use `compileInputs` instead - similar to the way it was in (now deprecated)
  docTask. We can then simplify `docSetting` by reusing `compileInputs in (Compile, doc)`
- Related to that, what would be your recommendation to deal with the 9 argument cap? Bringing in intermediate keys might be against the overall intention of reusing existing keys in right scope as much as possible. For consistency, I wanted to find and apply the approach from another `Setting` or `Task` where this was needed – but couldn't find one by casual 'eyeballing'.
- Is it necessary to have `fullClasspath <<= dependencyClasspath`? Can't we just use `dependencyClasspath` instead?
- Also maxErrors isn't used currently for javadoc since it is along the lines of javac (which doesn't use `xsbti.Reporter` either. I have kept is there just in case it's put to use later on.
- Doc.scala has some duplicated currently. This is mostly to preserve the signature of `Scaladoc`. At some later major version (maybe 0.12) this can be restructred a bit. Unless, of course, if you have other
  thing in mind.

This is a draft version to start the conversation. As usual, looking forward to suggestions and feedback (and modifying the patch accordingly).

NB: You get to see three commits for this pull request. I suspect, you'll have to apply #248 and #249 to remove the other commits from showing up here.

### CODE REVIEW

**Comment by harrah** [comment]
This looks good overall and is close to being included.  Comments:
- `val mixed = !srcs.isEmpty && !jsrcs.isEmpty` means that even pure Java projects will use out / "java".  Is that intended?
- It is probably more direct to do `srcs.filterNot(_.getName.endsWith(".scala))` or similar.
- I guess using dependencyClasspath directly is more consistent with the way 'compile' works.
- As you say, it is good to preserve the signature of Scaladoc, but you can still write a new interface, wrap it in the old interface, deprecate the old interface.
- I don't think there is a problem with intermediate tasks/settings as long as they are constructed in the most specific scope.  Alternatively, see the `local` methods on TaskKey and SettingKey, which are currently `private[sbt]` and are still new: https://github.com/harrah/xsbt/blob/0.11/main/Defaults.scala#L1085

**Comment by indrajitr** [comment]
Updates:
- `val mixed ...` logic was incorrect, fixed
- Other adjustments based on your previous comment
- Now using reusing `compileInputs` for doc generation. Would take care of `compileInputsTask` in a separate commit so that `maxErrors` is honored.
- Refactored `Doc.scala` to reduce duplicates. The current arrangement doesn't require deprecating any type or method. An intermediate type externalizes the doc generation function.

**Comment by indrajitr** [comment]
BTW, `local` method on `TaskKey` and `SettingsKey` is cool! That's the one I'll prefer.

**Comment by harrah** [comment]
I think this is ready to go after squashing down to one commit.

It would be good to have a scripted test for this.  See http://harrah.github.com/xsbt/Developing.pdf if you aren't already familiar with this.

**Comment by indrajitr** [comment]
Rebased and squashed. Also enhanced scripted test `actions/doc` to handle the new arrangement.

**Pull request merged**
