### PR TITLE
Add inherit IO option to JProcessBuilder on Java 7

### PR DESCRIPTION
**Pull request by vigdorchik**

### CODE REVIEW

**Comment by harrah** [comment]
1. The inherit IO should be enabled for Java 7 and later.  The version number shouldn't be used to enable the behavior.  Check for the presence of the method on JProcessBuilder and cache Optino[Method] in a lazy val or something.
2. The equivalent pre-Java 7 code does not just hook up standard in and out to the process.  That is, it isn't equivalent to inheritIO.  It is used to implement piping between processes or files and URLs.  So, the input isn't necessarily standard input.  ProcessIO probably needs to be changed to support redirection.

**Comment by harrah** [comment]
The check for Redirect and the redirect methods should go in a companion object, since it only needs to be done once (the Java standard library isn't going to change).

toSink/toSource are just for the URL/File wrappers that pretend to be processes.  It isn't the right way to detect whether stdin/stdout should be redirected.  standard in is never redirected automatically.  The user has to request it.  For standard  out, if you `a #| b`, the output of a is supposed to be sent to b, not standard output.

**Comment by harrah** [comment]
I really think ProcessIO is where this needs to go.  Redirecting input should be done where ProcessIO.writeInput is called.  So, ProcessIO should have the redirectStdin: Boolean member and not Process.

**Comment by vigdorchik** [comment]
Can't make it work reliably on Windows. Possibly jline issue?

**Comment by harrah** [comment]
Did you commit your latest code somewhere?

**Comment by vigdorchik** [comment]
@harrah I still have the dirty local working copy. Need to think over what should be committed.

**Pull request closed without merging**
