### PR TITLE
Evict cleaned files from the AggressiveCompile cache

### PR DESCRIPTION
**Pull request by jorgeortiz85**
AggressiveCompile keeps a cache of AnalysisStores for files that have already been compiled.

This cache is kept with SoftReferences, which means the garbage collector is guaranteed to clear them before throwing an OutOfMemoryError. However, they need not be cleared if there is still memory available. In long-running sbt sessions, I've noticed that the heap keeps growing and growing with objects from this cache. This will trigger GCs, which make progress (garbage collect a small number of objects) and so don't feel pressured to collect SoftReferences. Because so little memory is reclaimed on each GC, eventually GCs are happening very frequently, and SoftReferences don't ever get collected. These very frequent collections hurt the performance of the entire VM (including compiles, etc).

In general, using SoftReferences as a caching mechanism is a bad idea, but until there's a better caching mechanism, this patch (admittedly an ugly hack) will clear entries from the cache when their file is cleaned. The evicted values can then be marked as unreachable by the garbage collector and collected even if the VM is not about to OOM.

### CODE REVIEW

**Comment by ijuma** [comment]
You may also consider http://code.google.com/p/concurrentlinkedhashmap/

**Comment by ijuma** [comment]
Mark, given that SBT 0.11.0 RC0 went out today, what is your position on this?

**Comment by harrah** [comment]
I will look at this after 0.11.0 final, when I also look at #117.

**Comment by ijuma** [comment]
OK, thanks.

**Comment by jsuereth** [comment]
Is there any chance I can have you look at this before 0.11 goes final?

**Comment by jhartman** [comment]
Concurrent Linked Hashmap is great. As an interim solution, you could switch from SoftReference to WeakReference which would solve the problem but clear data from the cache more frequently.

**Comment by harrah** [comment]
Full API is no longer stored, so cache size should be much smaller.

**Comment by jorgeortiz85** [comment]
Just tried this out. HUGE improvement. Thanks Mark!

**Pull request closed without merging**
