### PR TITLE
New Testing Framework API

### PR DESCRIPTION
**Pull request by cheeseng**
Changes to make use of new testing framework API.

### CODE REVIEW

**Comment by cheeseng** [comment]
It uses the new test-interface in:-

https://github.com/scalatest/test-interface/tree/new-framework-api

and ScalaTest master contains the implementation of the above new framework API:-

https://github.com/scalatest/scalatest/blob/master/src/main/scala/org/scalatest/tools/Framework.scala

you can get the latest ScalaTest 2.0 snapshot by using the following in sbt:-

libraryDependencies += "org.scalatest" % "scalatest_2.10" % "2.0.M6-SNAP16" % "test"

**Comment by jsuereth** [comment]
Just wanted to chime in from the peanut gallery:  GREAT WORK!  I can't wait to see this fully integrated and in sbt.

**Comment by harrah** [comment]
Didn't see any objections, so it is now merged.  Next steps that I see:
- [ ] Feedback and implementations from test framework authors
- [ ] Take advantage of new features in `testOnly` and `testQuick`
- [ ] Update change summary and testing documentation.

To help with the first one, there will be a milestone, hopefully by the end of the week.  Anything else I'm forgetting?

**Comment by cheeseng** [comment]
Hi Mark & Josh,

Thanks a lot for merging it in!

Cheers,
Chee Seng

**Pull request merged**
