### PR TITLE
Fixes Maven Central getting included even with repo override

### LINKED ISSUE #2519: sbt 0.13.11 hits Maven Central even with repository overrides
## steps

Add repository override.

```
$ cat repo.config
[repositories]
  local
  typesafe-ivy-releases: https://repo.typesafe.com/typesafe/ivy-releases/, [organization]/[module]/[revision]/[type]s/[artifact](-[classifier]).[ext]
```
## problem

It tries to hit Maven Central for the compiler bridge.

```
$ sbt -Dsbt.override.build.repos=true -Dsbt.repository.config=$HOME/work/foo/repo.config
....
root> show externalResolvers
[info] ArrayBuffer(FileRepository(local,FileConfiguration(true,None),Patterns(ivyPatterns=List(${ivy.home}/local/[organisation]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]), artifactPatterns=List(${ivy.home}/local/[organisation]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]), isMavenCompatible=false, descriptorOptional=false, skipConsistencyCheck=false)), public: https://repo1.maven.org/maven2/, URLRepository(typesafe-ivy-releases,Patterns(ivyPatterns=List(https://repo.typesafe.com/typesafe/ivy-releases/[organization]/[module]/[revision]/[type]s/[artifact](-[classifier]).[ext]), artifactPatterns=List(https://repo.typesafe.com/typesafe/ivy-releases/[organization]/[module]/[revision]/[type]s/[artifact](-[classifier]).[ext]), isMavenCompatible=false, descriptorOptional=false, skipConsistencyCheck=false)))
```
## expectation

Don't do it.

### PR DESCRIPTION
**Pull request by eed3si9n**
Fix #2519 
Fixes Maven Central getting included even with repo override.

/review @Duhemm, @dwijnand

### CODE REVIEW

**Comment by Duhemm** [comment]
Oh, I understand better the logic behind `reorganizeAppResolvers` now. 

How about rewriting `reorganizeAppResolvers` as something along the lines of:

``` scala
/**
 * Reorganize the built-in resolvers that is configured for this application by the sbt launcher.
 * If `jcenter` is true, add the JCenter.
 * If `mavenCentral` is true, add the Maven Central repository.
 */
private[sbt] def reorganizeAppResolvers(appResolvers: Seq[Resolver], jcenter: Boolean, mavenCentral: Boolean): Seq[Resolver] = {
  appResolvers.partition(_ == Resolver.defaultLocal) match {
    case (locals, xs) =>
      // Remove Maven Central and JCenter, we will add them again if `jcenter` or `mavenCentral` are set.
      val excluded = Set(JCenterRepository, DefaultMavenRepository)
      val retained = xs filterNot excluded
      locals ++ retained ++ single(JCenterRepository, jcenter) ++ single(DefaultMavenRepository, mavenCentral)
  }
```

I find it clearer.

By the way, does the order of the repositories matter at this point?

The fix LGTM.

**Comment by eed3si9n** [comment]
I think the ordering does matter. That's why I'm reorganizing it so Maven Central comes first.

**Comment by dwijnand** [comment]
I too instantly thought why don't we fix it in the method rather than outside.

Also, is this untestable?

**Comment by eed3si9n** [comment]
Probably testable at least partially.
The bug I think is that I had `true` hardcoded, not the implementation of `Resolver.reorganizeAppResolvers(...)`.

**Comment by dwijnand** [comment]
I see. Then LGTM, pending Travis and possibly hopefully some testing.

**Comment by eed3si9n** [comment]
@dwijnand I added another config for scritped to test repo override specifically.

**Comment by dwijnand** [comment]
Looks good. Thanks

**Pull request merged**
