### PR TITLE
dependsOn can now be used inside a .sbt file for a subproject

### PR DESCRIPTION
**Pull request by anatolydwnld**
### Improvements
- Add the ability to call dependsOn for the current project inside a build sbt file. By [@anatolydwnld][@anatolydwnld]

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @anatolydwnld,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by eed3si9n** [comment]
LGTM pending CLA

**Comment by anatolydwnld** [comment]
@eed3si9n I've confirmed signing the CLA. Please, let me know if there is something else I need to do.

**Comment by nafg** [comment]
Is documentation updated somewhere?

**Pull request merged**
