### PR TITLE
Update ForkError.getMessage() to include exception's original name.

### PR DESCRIPTION
**Pull request by kamilkloch**
See #2028

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @kamilkloch,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.typesafe.com/contribute/cla](http://www.typesafe.com/contribute/cla)

**Comment by typesafe-tools** [comment]
Can one of the admins verify this patch?

**Comment by jsuereth** [comment]
LGTM, not sure on the patch failure.

Would you mind adding a `notes/` file as per the contributing doc?

**Comment by lightbend-cla-validator** [comment]
Hi @kamilkloch,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.typesafe.com/contribute/cla](http://www.typesafe.com/contribute/cla)

**Comment by kamilkloch** [comment]
@jsuereth: I added the notes.

**Comment by dwijnand** [comment]
You want the notes to be as a separate file under `notes/0.13.9/`, as this change will become a part of the upcoming 0.13.9 release.

Also you're targeting the wrong branch here, we want to merge this into `0.13` not `0.13.8`.

Do you mind fixing the notes and opening a new pull request to target 0.13 please?

**Comment by kamilkloch** [comment]
@dwijnand: done.

**Pull request closed without merging**
