### PR TITLE
Apply google java formatting to sbt java source files

### PR DESCRIPTION
**Pull request by eatkins**
This adds https://github.com/swoval/sbt-source-format to the sbt build so that java source files are automatically formatted like we do with scala source files.

### CODE REVIEW

**Comment by He-Pin** [comment]
How about the lightbend one？

**Comment by eatkins** [comment]
I was unaware of the existence of the lightbend formatter. I prefer the caching model used in the swoval formatter (perhaps unsurprising since I wrote it). They have effectively the same api so it's trivial to switch plugins by just changing the value in `project/plugins.sbt`.

**Comment by eatkins** [comment]
The swoval plugin is actually also a real world use case of some of the caching apis that I added for sbt 1.3.0, so it's nice to get more coverage of that code. The lightbend formatter is very similar to the official scalafmt plugin so it does not exercise the new apis.

**Review by eed3si9n — APPROVED** [review]
If the backends are using the same format, I am fine with either implementation.

**Comment by eatkins** [comment]
> If the backends are using the same format, I am fine with either implementation.

Yep. I swapped the implementation and ran `clean; javafmt` and formatting ran but no diffs were generated.

**Pull request merged**
