### PR TITLE
Append doc-title and doc-version to scaladocOptions by default

### PR DESCRIPTION
**Pull request by indrajitr**
Appending doc-title and doc-version to `scaladocOptions` by default would be nice. The generated scaladoc pages would have proper title OOTB.

### CODE REVIEW

**Comment by harrah** [comment]
I hesitate when it comes to default options to scalac/scaladoc.  We really need a solid way to know if options are valid before adding them by default.  This kind of thing was problematic in the switch to 2.8, where some options that were added by default were removed.  It does look like these options exist in 2.8.0 through 2.10-SNAPSHOT.

**Comment by indrajitr** [comment]
First thing first. The patch was originally motivated by the fact that `scalacOptions` would not be honored despite `scaladocOptions in doc` not being set anywhere.

Thus, I originally intended to have this fix:

``` diff
--- a/main/Defaults.scala
+++ b/main/Defaults.scala
@@ -201,7 +201,7 @@ object Defaults extends BuildCommon
                run <<= runTask(fullClasspath, mainClass in run, runner in run),
                runMain <<= runMainTask(fullClasspath, runner in run),
                scaladocOptions in GlobalScope :== Nil,
-               scaladocOptions in doc <<= scaladocOptions in doc or scalacOptions.identity,
+               scaladocOptions in doc <<= scalacOptions in doc,
                copyResources <<= copyResourcesTask
        )
```

This way, the user could either ignore the default `:=`, append to the default `++=` or anything in between. Since, almost all the `scalacOptions` hold true for `scaladocOptions` this would be a nice default.

While at this, I thought it would be a good idea to add `-doc-title` and `-doc-version` be default. In fact, going forward, I also intended to add `Seq("-encoding", "UTF-8")` by default to `scalacOptions` and `javacOptions` (it's a nice default when teams have different system encoding across different OS). Hence the patch ended up being something different from what I set out to fix :)

But I totally understand your point of view (yes, I remember the extra work you had to do in 0.7.x to accomodate the transition to 2.8). However, I hope that scalac/scaladoc is reaching a steady state and canonical options won't change drastically in near future unless it's a _must_. Far too many tools would get affected.

Unless, you have already planned to do validation of options by some kind of dynamic inspection, there are couple of things you an consider in immediate term:
- Always keep the options Seq empty by default like it is now (I'll post a separate patch to fix `scaladocOptions` specific issue mentioned above)
- Keep the options Seq empty in Global scope and set the minimal canonical defaults (`-encoding` for scalac, title, version for scaladoc) and no more. This has the risk as you mentioned by unlikely to happen till at least 2.10 (I am not aware of any motivation to change/remove `-encoding` for example)

`-doc-title`, `-doc-version` has negligible impact, so I can live without them being default. `-encoding` is more significant in heterogeneous environment, so that would be good to have (but we'll survive if that's not default as well). Let me know what you think :)

**Comment by harrah** [comment]
How about a third option, where we have methods that provide reasonable defaults:

``` scala
object DefaultOptions {
  val encoding: Seq[String] = Seq("-encoding", "UTF-8")
  val scalac: Seq[String] = encoding ++ ...
  val scaladoc: Seq[String] = ...
}
```

Using the defaults is opt-in:

``` scala
scalacOptions := DefaultOptions.scalac

scaladocOptions <++= DefaultOptions.scaladoc
```

(or some variation.)

The original patch makes sense.  Alternatively, remove the line:

``` scala
scaladocOptions in GlobalScope :== Nil
```

(Also, I wonder if it would have been better to do `scalacOptions in doc` instead of a new key.)

**Comment by indrajitr** [comment]
Having `DefaultOptions` is a great idea!

I kept the line `scaladocOptions in GlobalScope :== Nil` for consistency with other `xxxOptions` which exist (as `Nil`) in `GlobalScope`.

`scalacOptions in doc` is quite what I was wondering about as well! But then assumed you must have had something in mind else you could have done that during recent doc scoping exercise. (assumption is a dangerous thing).

So I am going to update the patch with `scaladocOptions` deprecated in favor of `scalacOptions in doc`. `DefaultOptions` thing can be taken up separately.

**Comment by harrah** [comment]
I don't think `scaladocOptions in GlobalScope` serves a purpose anymore if you do `scaladocOptions <<= scalacOptions`.

**Comment by indrajitr** [comment]
Except, `scaladocOptions ++= Seq("-encoding", "UTF-8")` would fall through the crack :)

``` console
[error]   test-proj/*:scaladoc-options from test-proj/*:scaladoc-options
[error]      Did you mean test-proj/compile:scaladoc-options ?
```

You'll have to do `scaladocOptions := Seq("-encoding", "UTF-8")` instead.

**Comment by harrah** [comment]
That's technically true, but there is no point in defining scaladocOptions in the global configuration like that because it won't get used.

The new definition :

``` scala
scaladocOptions in Compile <<= scalacOptions in Compile
```

does not reference scaladocOptions in the global configuration.

**Comment by indrajitr** [comment]
I agree in principle that `scaladocOptions` isn't really a good global config candidate. But kept it "as is" because of this _potential_ trouble.

But now that we are going with `scalacOptions in doc`, this analysis won't be relevant. Patch coming up.

**Comment by indrajitr** [comment]
Patch for `scaladocOptions` deprecation is part of #181

**Comment by indrajitr** [comment]
Mark, ref [your comment above](#issuecomment-2071661). Are you still interested in this? If yes, I would send out a fresh patch for this one.

Have been away from this. And GitHub apparently auto-closed the ticket as a result of another pull request.

**Comment by indrajitr** [comment]
In any case, a passive helper like so would be limited.

``` scala
object DefaultOptions {
  val encoding: Seq[String] = Seq("-encoding", "UTF-8")
  val scalac: Seq[String] = encoding ++ ...
  val scaladoc: Seq[String] = ...
}
```

For defaults to be more useful, we would need to bring in other `SettingKey` at the least. For example,

``` scala
scalacOptions ++= encoding
scalacOptions in doc <++= (name in doc, version in doc) map(Seq("-doc-title", _, "-doc-version", _))
```

**Comment by harrah** [comment]
Yes, I can't reopen this either, so open a new pull request.

**Pull request merged**
