### PR TITLE
Add javaSourceManaged as a SettingKey.

### PR DESCRIPTION
**Pull request by paddymahoney**
Set it by default to target/java/src-managed
Update the documentation to include info on the javaSourceManaged key.

Issue #753

### CODE REVIEW

**Comment by harrah** [comment]
This assumes that the Java sources don't depend on any Scala code, since it doesn't use the cross-versioned target directory.  That might be ok, but perhaps it should be mentioned in the documentation?

**Comment by paddymahoney** [comment]
If it goes in the cross-versioned target directory, will that make it a subdir of scala-<version>? For ex /target/scala-2.10/java/src-managed ? Do you think it would be preferable to have it under the cross-versioned target directory? I don't have a deep grasp of the consequences, as I don't have any java sources that depend on scala code.

**Comment by harrah** [comment]
Yes, the cross-versioned target directory goes under scala-<version>.  I'm not sure it is worth having a `javaSourceManaged` if it goes under the cross-versioned target directory, since it wouldn't really be any different from `sourceManaged`.

The reason directories are cross-versioned is to avoid unnecessary rebuilds when cross-building.  For example, if you build against 2.9, you might generate different Java/Scala sources to be source compatible with 2.9.  Say you were to then generate sources with slightly different content but in the same location for 2.10.  Each cross-build would recompile the sources because the class files would be for another Scala version.

**Comment by paddymahoney** [comment]
"Yes, the cross-versioned target directory goes under scala-. I'm not sure it is worth having a javaSourceManaged if it goes under the cross-versioned target directory, since it wouldn't really be any different from sourceManaged."

Yeah, I'm sort of of the same mind. Perhaps a convenience key that makes javaSourceManaged a subdir of crossTarget.value/java_src_managed. 
I updated the pull request to add this convenience key. If you don't think it is a desirable change, feel free to close the pull request. Sorry this didn't bear more fruit.

**Comment by harrah** [comment]
I was ok with the original way if the documentation gets updated to indicate it isn't cross-versioned.  What is the gain for it to be cross-versioned though?

I wouldn't consider this a waste at all- the discussion is useful.

**Comment by harrah** [comment]
I'll take it that your preferred outcome is dropping this pull request.  If not, just comment and I'll reopen.

**Pull request closed without merging**
