### PR TITLE
Assorted incremental compiler bug fixes.

### PR DESCRIPTION
**Pull request by eed3si9n**
Cherry picked adriaanm/sbt#1 on top of 0.13 to prepare for 0.13.10.

/cc @adriaanm

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @romanowski,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.typesafe.com/contribute/cla](http://www.typesafe.com/contribute/cla)

**Comment by dwijnand** [comment]
I know that this is WIP, but just wanted to mention, it would be great to have lots of notes about these assorted changes for the release.

**Comment by eed3si9n** [comment]
```
[error] (sbtRoot/*:scripted) Failed tests:
[error]     source-dependencies / value-class
```

**Comment by lightbend-cla-validator** [comment]
Hi @romanowski,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.typesafe.com/contribute/cla](http://www.typesafe.com/contribute/cla)

**Comment by adriaanm** [comment]
Hey, @eed3si9n, thanks for turning this into a PR! When looking at the release notes, I noticed I hadn't cleaned up 0f61629's commit message yet. It probably wasn't clear what it's doing, and so it's not included in the notes, although we may want to.

We should probably also mention the changes to logging (are they ok for you?). For example, you can now limit nesting (`-Dsbt.inc.apidiff.depth=N`, where N defaults to `2`), and number of declarations shown for a class/structural type (via `sbt.inc.apidiff.decls`, which defaults to `0` -- no limit).

I'm happy to do the rewording.

/cc @gkossakowski for some double checking of my changes & fixes.

**Comment by eed3si9n** [comment]
@adriaanm I summarized it to "Fixes the tracking of self types in the incremental compiler." I'd be happy to take better wording on a one-liner summary of this change.

As per logging, I was a bit sad to see beautiful `Show` typeclass-based logging go, but I figured you had good reasons to turn it into the current imple. Especially towards sbt 1.0 modularization, I don't want to promise any internal behaviors of the incremental compiler (beyond that it compiles stuff), so I intentionally didn't mention anything about that one. These logs are more or less for sbt/zinc devs only, correct?

**Comment by adriaanm** [comment]
Correct, the logs are meant to simplify reporting bugs. Honestly, I'm stumped that someone like the implicit approach to logging -- it took me a long time to wrap my head around it :dizzy_face: 

Regarding 0f61629, this fixed a performance problem with the old traversal, which would visit the same AST multiple times (first with `traverseTrees` at https://github.com/sbt/sbt/commit/0f616294c4e713dc415f5dc3ae7aef257decb228#diff-29aef71183363f225a8d6946a80cf619L149, then again using `super.traverse` a few lines later), causing blowups on big code bases. It also improves the precision by visiting a couple of AST nodes that were missed before.

**Comment by dwijnand** [comment]
Out of curiosity are these changes coming from use of sbt inside the scala repo, or something else?

**Comment by adriaanm** [comment]
No, we're battle testing it on a customer's MLoC code base ;-)

**Comment by lightbend-cla-validator** [comment]
Hi @romanowski,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.typesafe.com/contribute/cla](http://www.typesafe.com/contribute/cla)

**Comment by gkossakowski** [comment]
I wish @adriaanm had a chance to clean up commits before merging. Notes for future archeologists:
- the  5152405 fixed symptom (OOME due to gigantic list of collected symbols) but not the real bug that was fixed in 0f616294c4e713dc415f5dc3ae7aef257decb228
- the 0f616294c4e713dc415f5dc3ae7aef257decb228 fixes exponential walk on trees which caused exponential number of symbols collected from trees and an OOME as a result. It fixes other things mentioned in the commit message
- the 0f616294c4e713dc415f5dc3ae7aef257decb228 claims that self types are considered as inheritance dependencies but the diff of DependencySpecification shows that they are treated as member ref. This is correct treatment because a changes to a self type do not affect type checking of classes that inherit from a given class, they only affect classes that want to instantiate the class and they refer to it by a member reference

In aggregate, changes to the source code look good to me.

**Comment by eed3si9n** [comment]
Due to sbt's omission, we weren't running the unit tests on the compiler bridge, which @gkossakowski caught in #2357. On my machine the test that was changed now fails:

```
[info] x Extracted source dependencies from public members
[error]  Set('E, 'A, 'G, 'B, 'D) is not equal to Set('E, 'A, 'G, 'B, 'C, 'D) (DependencySpecification.scala:29)
[error] Expected: ...'B, '[C, ']D)
[error] Actual:   ...'B, '[]D)
```

This is consistent with earlier comment:

> the 0f61629 claims that self types are considered as inheritance dependencies but the diff of DependencySpecification shows that they are treated as member ref.

**Comment by adriaanm** [comment]
Yeah, that was one of the mistakes that @gkossakowski pointed out in my original code during an over-the-shoulder review. I should have been quicker with fixing the commit messages and test...

**Comment by eed3si9n** [comment]
I'd be happy to roll the commit history back before this got merged if you're up for fixing the commits etc.

**Comment by adriaanm** [comment]
I had planned to improve my branch before submitting the PR anyway, so, yes, I'm happy to make the fixes next week. I'll leave it up to you whether you want to `push --force` to a public branch -- at `scala/scala`, we would revert the commit instead.

**Comment by gkossakowski** [comment]
Unfortunately, I have rebased my development branch on top of 0.13 already.
I'd like to suggest we fix the test (PR coming) and move on keeping in mind a good lesson for future submissions.

**Comment by adriaanm** [comment]
+1, thanks @gkossakowski

**Comment by gkossakowski** [comment]
I submitted a fix in #2358. I'll wait for Travis to validate the change.

**Pull request merged**
