### PR TITLE
[sbt 0.13] Port sbt-cross-building's ^ and ^^ commands

### PR DESCRIPTION
**Pull request by eed3si9n**
@jrudolph's [sbt-cross-building](https://github.com/jrudolph/sbt-cross-building) is a plugin author's plugin. It adds cross command `^` and sbtVersion switch command `^^`, similar to `+` and `++`,
but for switching between multiple sbt versions across major versions. This PR merges these commands into sbt because the feature they provide is really useful as we migrate plugins to sbt 1.0.

### sbtVersion switching

To switch the `sbtVersion in pluginCrossBuild` from the shell use:

```
^^ 1.0.0-M5
[info] Setting `sbtVersion in pluginCrossBuild` to 1.0.0-M5
[info] Set current project to sbt-buildinfo (in build file:/xxx/sbt-buildinfo/)
```

Your plugin will now build with sbt 1.0.0-M5 (and its Scala version 2.12.2).

### sbt specific source directories

If you need to make changes specific to a sbt version, you can now include them into `src/main/scala-sbt-0.13`,
and `src/main/scala-sbt-1.0.0-M5`, where the binary sbt version number is used as postfix.

### plugin cross command

To run a command across multiple sbt versions, set:

```scala
crossSbtVersions := Vector("0.13.15", "1.0.0-M5")
```

Then, run:

```
> ^compile
[info] Setting `sbtVersion in pluginCrossBuild` to 0.13.15
[info] Set current project to sbt-buildinfo (in build file:/xxx/sbt-buildinfo/)
[info] Updating {file:/xxx/sbt-buildinfo/}root...
[info] Resolving org.scala-sbt#sbt-launch;0.13.15 ...
[info] Done updating.
[info] Compiling 11 Scala sources to /xxx/sbt-buildinfo/target/scala-2.10/sbt-0.13/classes...
[success] Total time: 5 s, completed Apr 22, 2017 3:31:44 AM
[info] Setting `sbtVersion in pluginCrossBuild` to 1.0.0-M5
[info] Set current project to sbt-buildinfo (in build file:/xxx/sbt-buildinfo/)
[info] Updating {file:/xxx/sbt-buildinfo/}root...
[info] Resolving org.scala-sbt#launcher;1.0.0 ...
[info] Done updating.
[info] Compiling 11 Scala sources to /xxx/sbt-buildinfo/target/scala-2.12/sbt-1.0.0-M5/classes...
[success] Total time: 9 s, completed Apr 22, 2017 3:31:53 AM
[info] Setting `sbtVersion in pluginCrossBuild` to 0.13.15-SNAPSHOT
[info] Set current project to sbt-buildinfo (in build file:/xxx/sbt-buildinfo/)
```

### notes

The idea of merging this in to sbt was first brought up in 2013 https://github.com/jrudolph/sbt-cross-building/issues/17, and last year https://github.com/sbt/sbt/issues/2619.

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @n8han,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by eed3si9n** [comment]
I though I should include the original history from sbt-cross-building in here, but I guess it gets confusing since the GitHub issue links are now all mess up.

**Review by dwijnand — APPROVED** [review]

**Comment by jrudolph** [comment]
Nice ;) Did you check that the scripted plugin still works?

**Comment by eed3si9n** [comment]
I did check scripted manually using sbt-buildinfo, and at least running one from sbt 1.0 worked without changing much:

```
> ^^1.0.0-M5
[info] Setting `sbtVersion in pluginCrossBuild` to 1.0.0-M5
[info] Set current project to sbt-buildinfo (in build file:/xxx/sbt-buildinfo/)
> scripted sbt-buildinfo/simple
[info] :: delivering :: com.eed3si9n#sbt-buildinfo;0.7.0-SNAPSHOT :: 0.7.0-SNAPSHOT :: integration :: Mon Apr 24 10:34:41 EDT 2017
[info] 	delivering ivy file to /xxx/sbt-buildinfo/target/scala-2.12/sbt-1.0.0-M5/ivy-0.7.0-SNAPSHOT.xml
....
/private/var/folders/7g/l96y5q310h90xsz109qqjpmc0000gn/T/sbt_70b902ac/simple/project/build.properties setting sbt.version to: 1.0.0-M5
[info] [info] Loading settings from plugins.sbt ...
[info] [info] Loading project definition from /private/var/folders/7g/l96y5q310h90xsz109qqjpmc0000gn/T/sbt_70b902ac/simple/project
[info] [info] Updating {file:/private/var/folders/7g/l96y5q310h90xsz109qqjpmc0000gn/T/sbt_70b902ac/simple/project/}simple-build...
[info] [warn] Choosing local for com.eed3si9n#sbt-buildinfo;0.7.0-SNAPSHOT
[info] [info] Done updating.
[info] [info] Loading settings from build.sbt ...
[info] [info] Set current project to helloworld (in build file:/private/var/folders/7g/l96y5q310h90xsz109qqjpmc0000gn/T/sbt_70b902ac/simple/)
[info] [info] Updating {file:/private/var/folders/7g/l96y5q310h90xsz109qqjpmc0000gn/T/sbt_70b902ac/simple/}root...
[info] [info] Done updating.
[info] [info] Compiling 1 Scala source to /private/var/folders/7g/l96y5q310h90xsz109qqjpmc0000gn/T/sbt_70b902ac/simple/target/scala-2.11/classes ...
[info] [info] Done compiling.
[info] [info] Total time: 4 s, completed Apr 24, 2017 10:35:04 AM
[info] [info] Total time: 0 s, completed Apr 24, 2017 10:35:04 AM
[info] + sbt-buildinfo / simple
[success] Total time: 25 s, completed Apr 24, 2017 10:35:06 AM
```

**Pull request merged**
