### PR TITLE
"Use HTTPS for downloading artifacts from Maven Central" + disable flag

### PR DESCRIPTION
**Pull request by eed3si9n**
This is an amendment to #1494. HTTPS will be enabled by default, but can be turned off using the following flag:

```
-Dsbt.repository.secure=false
```

### CODE REVIEW

**Comment by jsuereth** [comment]
LGTM

**Comment by rtyley** [comment]
:+1:

**Comment by eed3si9n** [comment]
Travis is failing legitimately with `scripted dependency-management/make-pom` and `pom-advanced`. Please do not merge until these are fixed.

**Comment by eed3si9n** [comment]
@rtyley Thanks for taking care of the problem.

**Comment by jsuereth** [comment]
travis looks green, just need to fix merge conflict.

**Pull request merged**
