### PR TITLE
HTTPS: Fetch typesafe artifacts using https

### PR DESCRIPTION
**Pull request by benmccann**
See http://blog.ontoillogical.com/blog/2014/07/28/how-to-take-over-any-java-developer/

Seems some people are having problems with typesafe's ssl cert, so may want to fix that before comitting this. Sounds like [the solution](http://stackoverflow.com/questions/18746565/godaddy-ssl-cert-not-working-with-java/21117993#21117993) for Java not supporting GoDaddy G2 certs is for typesafe to rekey it's SSL cert using SHA-1
http://support.godaddy.com/help/article/4976/re-keying-an-ssl-certificate

Hopefully that's not too much trouble. If it ends up being tricky, could also just buy an SSL cert from someplace else. They start at $4.99/yr from ssls.com

### CODE REVIEW

**Comment by typesafe-tools** [comment]
Can one of the admins verify this patch?

**Comment by edwardcallahan** [comment]
We can rekey.

**Comment by edwardcallahan** [comment]
SHA-1 cert for repo.typesafe.com has been installed. Cheers to Alex @ JFrog for the quick turnaround on the install of the updated cert.

**Comment by benmccann** [comment]
Awesome. Thanks @edwardcallahan !

**Pull request merged**
