### PR TITLE
Adds bundledLauncherProj to allProj

### PR DESCRIPTION
**Pull request by eed3si9n**
This matters when someone tries to locally build sbt from source.

/review @dwijnand, @jsuereth

### CODE REVIEW

**Comment by dwijnand** [comment]
:+1:

Everything's used by `sbtRoot` now:
- before: before
- after: after

**Comment by eed3si9n** [comment]
@jsuereth There's a legit failure introduced by #1938 (wrapped launcher).
`launch` directory contains tests, but because `autoScalaLibrary` is set to `false`, it's unable to compile the tests.

**Comment by jsuereth** [comment]
Hmm, so we should remove the tests?

Your PR looks good to me

**Comment by eed3si9n** [comment]
Yea. I'll try to split out the test into another subproject.

**Pull request merged**
