### PR TITLE
Fix inconsistent naming.

### PR DESCRIPTION
**Pull request by Atry**
See the patch below.

### CODE REVIEW

**Comment by Atry** [comment]
I thought these functions are just used internally, only meaningful for one who wants to see the internal mechanism.

**Comment by harrah** [comment]
Yes, deprecations are needed here.  Defaults is a public API.

**Comment by jsuereth** [comment]
Wow, I'd love to see this make it in though (with the deprecations so we can remove in 0.12).

**Comment by harrah** [comment]
I don't plan on another 0.11.x release, so it won't be removed until 0.13.

**Comment by harrah** [comment]
No response, closing.

**Pull request closed without merging**
