### PR TITLE
Add a warning if the build scala version is evicted for another.

### PR DESCRIPTION
**Pull request by jsuereth**
- Add new ConflictReport helper to build to display only conflict information
- Add hook to issue warnings if the scalaVersion isn't the one resolved
- Update documentation to reflect these changes.

Review by @eed3si9n

### CODE REVIEW

**Comment by eed3si9n** [comment]
So this implements the first US from https://github.com/sbt/sbt/wiki/User-Stories:-Conflict-Warning#user-story-warn-if-scalaversion-is-no-longer-effective, or not fully wired up yet?

**Comment by jsuereth** [comment]
implements the whole thing (first user story) (with a slightly altered error message).

**Comment by eed3si9n** [comment]
I set up a project as described on the user story, but did not see the warning:

```
> scalaVersion
[info] 2.10.0
> libraryDependencies
[info] List(org.scala-lang:scala-library:2.10.0, commons-io:commons-io:2.4, com.typesafe.akka:akka-actor:2.3.2)
> clean
[success] Total time: 0 s, completed Apr 26, 2014 6:29:26 PM
> update
[info] Updating {file:/Users/eugene/work/slow-ivy-project/}app...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[success] Total time: 0 s, completed Apr 26, 2014 6:29:28 PM
> show fullClasspath
[info] List(Attributed(/Users/eugene/work/slow-ivy-project/app/target/scala-2.10/classes), Attributed(/Users/eugene/work/slow-ivy-project/util/target/scala-2.10/classes), Attributed(/Users/eugene/.sbt/0.13.5-SNAPSHOT/boot/scala-2.10.4/lib/scala-library.jar), Attributed(/Users/eugene/.ivy2/cache/commons-io/commons-io/jars/commons-io-2.4.jar), Attributed(/Users/eugene/.ivy2/cache/com.typesafe.akka/akka-actor_2.10/jars/akka-actor_2.10-2.3.2.jar), Attributed(/Users/eugene/.ivy2/cache/com.typesafe/config/bundles/config-1.2.0.jar))
[success] Total time: 0 s, completed Apr 26, 2014 6:29:53 PM
```

As you can see, `scalaVersion` is "2.10.0", but `fullClasspath` shows `.sbt/0.13.5-SNAPSHOT/boot/scala-2.10.4/lib/scala-library.jar`.

**Comment by jsuereth** [comment]
Does updateConflictReport show up for you?

Also this missed the feature freeze deadline anyway.

**Comment by jsuereth** [comment]
Ok, so I'm closing this. I'll reopen against 0.13.6 and we can rediscuss.

**Pull request closed without merging**
