### PR TITLE
Bump expected 2.11 module versions so we can compile with 2.11

### PR DESCRIPTION
**Pull request by jsuereth**
Review by @retronym or @gkossakowski 

(Note our tests should always be green on 0.13 branch now, so please wait for travis before merging)

### CODE REVIEW

**Comment by retronym** [comment]
LGTM

**Comment by retronym** [comment]
I notice the `.travis.yml` file isn't touched. At some point you might want CI with Scala 2.11.x.

**Comment by jsuereth** [comment]
Good point. Will fix up before merge (that and travis failed)

**Comment by jsuereth** [comment]
Ok, fixed all the tests to be compatible with 2.11 now.  We can officially build/test against 2.11.  Once this is merged, we can merge 0.13 into 1.0

**Pull request merged**
