### PR TITLE
[sbt 1.0] Improve `show` when key returns a `Seq`

### PR DESCRIPTION
**Pull request by eed3si9n**
This changes the output to:

```
> show externalDependencyClasspath
[info] Updating {file:/xxx/hello/}root...
[info] Resolving jline#jline;2.12.1 ...
[info] Done updating.
[info] * Attributed(/Users/xxx/.sbt/boot/scala-2.11.8/lib/scala-library.jar)
[info] * Attributed(/Users/xxx/.ivy2/cache/commons-io/commons-io/jars/commons-io-
2.4.jar)
```

/review @dwijnand, @Duhemm

### CODE REVIEW

**Review by dwijnand — APPROVED** [review]
Amazingly beautiful and amazingly simple.

**Comment by dwijnand** [comment]
Can we backport this too?

**Comment by eed3si9n** [comment]
> Can we backport this too?

I'm not sure if we count this as semantic change. If we do we might have to guard it with an opt-out flag.

**Comment by dwijnand** [comment]
I'm happy with an opt-out.

**Pull request merged**
