### PR TITLE
Tail-end fixes for #1750.

### PR DESCRIPTION
**Pull request by dwijnand**

### CODE REVIEW

**Comment by typesafe-tools** [comment]
Can one of the admins verify this patch?

**Comment by dwijnand** [comment]
See https://github.com/sbt/sbt/pull/2163#issuecomment-135448249 there were a few changes left to finish.

Opened for feedback on notes and how and where to enable the flag. If all's well I'll publish the Ivy hash to Bintray.

**Comment by eed3si9n** [comment]
LGTM

**Comment by dwijnand** [comment]
Cool, then published Ivy hash to Bintray and restarting Travis.

**Comment by dwijnand** [comment]
Linked to https://github.com/sbt/ivy/pull/18, and both Travis passed on both.

**Comment by jsuereth** [comment]
Nice!

**Comment by dwijnand** [comment]
Wo hoo! Thanks.

It's been a long 3 months since I [first tried to reproduce the problem](https://github.com/sbt/sbt/issues/1750#issuecomment-109768232).

**Pull request merged**
