### PR TITLE
Add a pending test for a modified member of a trait

### PR DESCRIPTION
**Pull request by gkossakowski**
The test shows that name hashing optimization is broken for members
defined in traits. The problem is that modification of a member of a trait
triggers change of a hash of trait's name.

The behavior covered by this test regressed in
40ebc825317ed29a2ab87be07246fcdcfc6d1e3d
The bug is tracked in #2436.

### CODE REVIEW

**Comment by gkossakowski** [comment]
Review by @Duhemm

**Comment by typesafe-tools** [comment]
Can one of the admins verify this patch?

**Comment by Duhemm** [comment]
Shouldn't this test be located in `source-dependencies` rather than `compiler-project`?

Apart from that, LGTM

**Comment by gkossakowski** [comment]
I put it into `compiler-project` to emphasize that this test doesn't check if dependencies are tracked correctly but whether invalidation is done correctly. However, many tests in source-dependencies test for invalidation too so probably makes sense to put everything in one place. I'll move it.

**Comment by Duhemm** [comment]
@gkossakowski Could you please update your branch? It looks like GitHub forces you to have an up-to-date branch when using required status check: https://github.com/blog/2051-protected-branches-and-required-status-checks

**Comment by gkossakowski** [comment]
Do you mean you cannot merge my PR? I see the merge button here (I still have merge rights to sbt).

**Comment by Duhemm** [comment]
That's strange. Maybe it's because Travis has not finished running the build... I have a grayed out merge button.

screen shot 2016-02-03 at 16 52 01

**Comment by dwijnand** [comment]
@gkossakowski as an owner you can override the status check requirement.

**Comment by gkossakowski** [comment]
Ok, in that case I'll just merge it.

**Pull request merged**
