### PR TITLE
Run pending tests in scripted, consider their successes as failures

### PR DESCRIPTION
**Pull request by Duhemm**
This will allow to detect more easily when some scripted tests are fixed and will force us to re-enable them, thus helping to find future regressions.

The following tests have had their status changed:
- dependency-management/gh-1484-npe **pending -> test**  
  It was considered as flaky in #1958, but it seems to run fine now.
- dependency-management/publish-local **pending -> disabled**  
  It was considered as flaky in #1958.
- project/session-save **pending -> disabled**  
  Unreliable on Travis.
- source-dependencies/implicit-search-companion-scope **pending -> test**  
  I can't really say why it was pending, but it looks like it runs just fine. Maybe it's redundant with other tests?
- source-dependencies/trait-super **pending -> test**  
  It appears to have been fixed by #2160 
- tests/arguments-new **pending -> test**  
  Marked as pending since #813, but runs fine now.

### CODE REVIEW

**Comment by typesafe-tools** [comment]
Can one of the admins verify this patch?

**Comment by dwijnand** [comment]
`dependency-management / mvn-local` is also another one that is very flaky on Travis (re-running `mavenResolverPluginTest:scripted dependency-management/*2of2` for this PR in an attempt to have it go green).

**Comment by Duhemm** [comment]
Thanks @dwijnand! I've disabled it.

**Comment by jsuereth** [comment]
Why is session-save disabled?

**Comment by Duhemm** [comment]
I have seen spurious failures on Travis. It has been marked as pending by @eed3si9n in #1958, but I don't have much more information.

**Comment by jsuereth** [comment]
k. It's our only test of .sbt refactoring code, but we can merge as is for now.

**Pull request merged**
