### PR TITLE
Add Remove instances for Set and Map

### PR DESCRIPTION
**Pull request by DavidGregory084**
Adds `Remove` instances for `Set` and `Map`. I have tried to follow the same pattern that's used for the `Append` instances, with the exception that for `Map` we only remove the keys, like in the stdlib methods.

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @DavidGregory084,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[https://www.lightbend.com/contribute/cla](https://www.lightbend.com/contribute/cla)

**Review by eed3si9n — APPROVED** [review]
Thanks!

**Comment by DavidGregory084** [comment]
@eed3si9n just waiting for our legal folks to get back to me about the CLA 👀

**Comment by DavidGregory084** [comment]
Sorry for the long delay on this one @eed3si9n, my request to review the CLA got lost in somebody's inbox for a while 😆

**Comment by eed3si9n** [comment]
ok. It's all green, so I am going to merge it.

**Pull request merged**
