### PR TITLE
Interim fix for #3583, for 1.0.3

### PR DESCRIPTION
**Pull request by cunei**
In 0.13.x, zinc would discover only top-level objects and classes
containing tests to the test framework. In 1.x, however, zinc can
discover also nested objects and classes; that causes the "name"
of a ClassLike to no longer be usable for reflection.

This change filters out nested objects/classes from the list,
restoring compatibility with 0.13. A zinc extension of ClassLike
will probably be introduced in 1.1 or 1.2, in order to provide
the test framework with enough information to deal with nested
classes.

This patch unblocks https://github.com/sbt/sbt-standalone-build/issues/15

### CODE REVIEW

**Comment by eed3si9n** [comment]
It might be good to add scripted test for repro.

**Review by eed3si9n — CHANGES_REQUESTED** [review]
Release notes, and repro tests plz.

**Comment by cunei** [comment]
retest this please

**Review by eed3si9n — APPROVED** [review]

**Comment by eed3si9n** [comment]
Closed and re-opened to wake up Travis - https://travis-ci.org/sbt/sbt/builds/293329548

**Pull request merged**
