### PR TITLE
Use latest sbtn

### PR DESCRIPTION
**Pull request by mkurz**
Waiting for this release: https://github.com/sbt/sbtn-dist/releases/tag/v1.8.1

### CODE REVIEW

**Comment by mkurz** [comment]
@eed3si9n Can me merged now, release is done: https://github.com/sbt/sbtn-dist/releases/tag/v1.8.1
Thanks a lot!

**Comment by eed3si9n** [comment]
afk now but I'll probably need to do the post release tar step.

**Review by eed3si9n — APPROVED** [review]

**Comment by mkurz** [comment]
@eed3si9n Out of interest: How to you let sdkman know that a new sbt release is available? I read that you have to use an api to post to https://vendors.sdkman.io/, however I do not see that in the GitHub actions workflows somewhere, so do you do that by hand?

**Comment by eed3si9n** [comment]
> How to you let sdkman know that a new sbt release is available?

I run curl script by hand once the installers are uploaded to sbt/sbt releases.

**Pull request merged**
