### PR TITLE
Separate dependency phase

### PR DESCRIPTION
**Pull request by gkossakowski**
Move dependency extraction to separate compiler phase called `Dependency` that can be run independently from class file extraction that is performed by `Analyzer` phase.

This pull request serves as foundation for more deep changes were we switch to dependency extraction performed by incremental compiler.

This is pure refactoring that does not change behavior. One would wonder if moving logic that traverses contents of `CompilationUnit.depends` to earlier phase could affect behavior because `CompilationUnit.depends` might be populated by later phases. I verified this manually by grepping compiler code and checking where that field gets modified. It turns out that there are two places where `depends` is mutated:
- in typer (and dependency phase runs after typer)
- in mixin where it add dependency on symbols corresponding to `$class`

Since we are running before mixing we won't see those Symbols but that does not matter because sbt's tracking is not fine-grained enough to run into problem of tracking trait symbol but not tracking implementation class symbol.

### CODE REVIEW

**Comment by harrah** [comment]
1.  Do you intend to move the location of the extraction phase or will it always be right after the api phase?  If it will always be after the api phase, there isn't a need to make it a separate phase and deal with the ordering problems, right?
2. There are now two `startSource` and `endSource` calls per source file.  I'm pretty sure they aren't used internally anymore though, so they should probably just be removed.  Alternatively (or additionally), there isn't a problem with dependency lookup being done with class file extraction; it is just the call to `unit.depends` that needs to be moved, right?

**Comment by gkossakowski** [comment]
1. Yes, I was planning to collapse dependency phase along with api phase but I wanted to keep them separate for now for debugging purposes (Scala compiler has nice capabilities to do per-phase logging). I'd collapse them once everything stabilizes and I was planning to do that in a few weeks so you can treat this as a transition setup.
2. Yes I was wondering about `startSource` and `endSource`. The API callback doesn't do anything special with them so it wasn't really clear to me what's their purpose. I can deprecate them on the interface and remove calls to it. How does it sound?
   When it comes to dependency extraction you are right. We need to determine the set of Symbols (as with call to `unit.depends`) early on but we don't need to map them in earlier phase. However, alternatively we would have to capture that set for each compilation unit, store somewhere (probably in `Map[CompulationUnit, Set[Symbol]]`) and then in Analyzer phase map to class files. Do you see any advantage of derring mapping symbols to class files?

**Comment by gkossakowski** [comment]
@harrah: also, to see how this will evolve you can look at: https://github.com/gkossakowski/xsbt/commit/f3dc338f21a423a10aaa132de79bbc5d0fc97750 where I don't use `unit.depends` anymore.

**Comment by harrah** [comment]
1. If it is temporary, perhaps just have a rightAfter dependency on API and say "to be merged with API"?
2. If anyone implements `startSource/endSource` (and I doubt anyone does), there isn't much point in deprecating them if they aren't going to be called anymore.  Their code might compile but it wouldn't work right.  Better to have a compile error, so let's just drop them.
3. I see no advantage except perhaps keeping the callback code together.  I suggested it mainly in case you didn't want to drop `startSource/endSouce`.  If you kept it in the old place, you wouldn't need two calls to them.  If you drop `startSource/endSource`, I don't think it matters either way.  The class file lookup shouldn't change.

**Comment by gkossakowski** [comment]
I'm closing it as I'll be rebasing my patches and submitting them once 0.13 is out.

@harrah: thanks for the feedback, I'll remove `startSource/endSource` methods when rebasing.

**Comment by gkossakowski** [comment]
Weird. It seems like github has some bug related to displayed the list of commits I want to merge after reopening the PR. It shows too many commits. I'll open a fresh PR because this view is very confusing.

**Pull request closed without merging**
