### PR TITLE
Move API extraction logic to a separate class.

### PR DESCRIPTION
**Pull request by gkossakowski**
This way we have a little bit more clear separation
between compiler phase logic and the core logic responsible for
processing each compilation unit and extracting an api for it.

As added benefit, we have a little bit less of mutable state
(e.g. sourceFile doesn't need to be a var anymore).

The API extraction logic contains some internal caches that are
required for correctness. It wasn't very clear if they have to
be maintained during entire phase run or just during single compilation
unit processing. It looks like they have to be maintained during
single compilation unit processing and refactored code both
documents that contracts and implements it in the API phase.

### CODE REVIEW

**Comment by gkossakowski** [comment]
@harrah: As far as I can see this is purely refactoring without any changes to behavior.

**Comment by harrah** [comment]
There is probably a non-trivial benefit to sharing the type cache across units, though.  The rest looks ok.

**Comment by gkossakowski** [comment]
@harrah: true but the old logic didn't do that either. I'm trying to minimize a risk of accidental breakage when submitting PRs to 0.13 branch.

**Comment by harrah** [comment]
Yeah, you're right.  I missed that the old code didn't do it.

**Pull request merged**
