### PR TITLE
Do not always use Level.Debug while creating a backgroundLog

### LINKED ISSUE #3655: [debug] messages ouput bloat the console during every runs.
## steps
Run a main class

## problem
Console is bloated with debug messages
```
[info] Done packaging.
[info] Running test.Test 
[debug] Waiting for threads to exit or System.exit to be called.
[debug]   Classpath:
[debug] 	/var/folders/7k/k9clqrk14bz5051664nhnrbc0000gn/T/sbt_e726a6e5/job-2/target/a2ed466f/kafka-slick-offsetstorage_2.12-a4f3ad0ff7e28ccbd186b3a5e9bcaf5fad0b742b-SNAPSHOT.jar
[debug] 	/var/folders/7k/k9clqrk14bz5051664nhnrbc0000gn/T/sbt_e726a6e5/target/dd235d04/scala-library-2.12.1.jar
[debug] 	/var/folders/7k/k9clqrk14bz5051664nhnrbc0000gn/T/sbt_e726a6e5/target/b85f56c3/slick_2.12-3.2.0.jar
[debug] 	/var/folders/7k/k9clqrk14bz5051664nhnrbc0000gn/T/sbt_e726a6e5/target/14b8c877/reactive-streams-1.0.0.jar
[debug] 	/var/folders/7k/k9clqrk14bz5051664nhnrbc0000gn/T/sbt_e726a6e5/target/f65b7c28/slick-hikaricp_2.12-3.2.0.jar
[debug] 	/var/folders/7k/k9clqrk14bz5051664nhnrbc0000gn/T/sbt_e726a6e5/target/b896b711/HikariCP-2.5.1.jar
[debug] 	/var/folders/7k/k9clqrk14bz5051664nhnrbc0000gn/T/sbt_e726a6e5/target/a87bb474/log4j-over-slf4j-1.7.25.jar
[debug] 	/var/folders/7k/k9clqrk14bz5051664nhnrbc0000gn/T/sbt_e726a6e5/target/da76ca59/slf4j-api-1.7.25.jar
[debug] 	/var/folders/7k/k9clqrk14bz5051664nhnrbc0000gn/T/sbt_e726a6e5/target/8ac759c6/postgresql-42.0.0.jre7.jar
[debug] 	/var/folders/7k/k9clqrk14bz5051664nhnrbc0000gn/T/sbt_e726a6e5/target/08eebdbb/zookeeper-3.4.10.jar
[debug] 	/var/folders/7k/k9clqrk14bz5051664nhnrbc0000gn/T/sbt_e726a6e5/target/99a18e9a/jline-0.9.94.jar
[debug] 	/var/folders/7k/k9clqrk14bz5051664nhnrbc0000gn/T/sbt_e726a6e5/target/9ca7d55d/netty-3.10.5.Final.jar
[debug] 	/var/folders/7k/k9clqrk14bz5051664nhnrbc0000gn/T/sbt_e726a6e5/target/68d8107d/akka-stream-kafka_2.12-0.15.jar
[debug] 	/var/folders/7k/k9clqrk14bz5051664nhnrbc0000gn/T/sbt_e726a6e5/target/46331543/akka-stream_2.12-2.4.17.jar
[debug] 	/var/folders/7k/k9clqrk14bz5051664nhnrbc0000gn/T/sbt_e726a6e5/target/ba05c9b5/akka-actor_2.12-2.4.17.jar
[debug] 	/var/folders/7k/k9clqrk14bz5051664nhnrbc0000gn/T/sbt_e726a6e5/target/f533aa6e/config-1.3.0.jar
[debug] 	/var/folders/7k/k9clqrk14bz5051664nhnrbc0000gn/T/sbt_e726a6e5/target/1e6f1e74/scala-java8-compat_2.12-0.8.0.jar
[debug] 	/var/folders/7k/k9clqrk14bz5051664nhnrbc0000gn/T/sbt_e726a6e5/target/7497c001/ssl-config-core_2.12-0.2.1.jar
[debug] 	/var/folders/7k/k9clqrk14bz5051664nhnrbc0000gn/T/sbt_e726a6e5/target/7c5f25a2/scala-parser-combinators_2.12-1.0.4.jar
[debug] 	/var/folders/7k/k9clqrk14bz5051664nhnrbc0000gn/T/sbt_e726a6e5/target/c20571ff/kafka-clients-0.10.2.0.jar
[debug] 	/var/folders/7k/k9clqrk14bz5051664nhnrbc0000gn/T/sbt_e726a6e5/target/c708bb25/lz4-1.3.0.jar
[debug] 	/var/folders/7k/k9clqrk14bz5051664nhnrbc0000gn/T/sbt_e726a6e5/target/48d92871/snappy-java-1.1.2.6.jar
[debug] 	/var/folders/7k/k9clqrk14bz5051664nhnrbc0000gn/T/sbt_e726a6e5/target/7c4f3c47/logback-classic-1.2.3.jar
[debug] 	/var/folders/7k/k9clqrk14bz5051664nhnrbc0000gn/T/sbt_e726a6e5/target/86434440/logback-core-1.2.3.jar
[debug] Waiting for thread run-main-1 to terminate.
Hello world
[debug] 	Thread run-main-1 exited.
[debug] Interrupting remaining threads (should be all daemons).
[debug] Sandboxed run complete..
[debug] Exited with code 0
```
## expectation
Unbloated output :)

## notes
sbt version: 1.0.1, 1.0.2

Not present in sbt 0.13.x and sbt 1.0.0

### PR DESCRIPTION
**Pull request by cunei**
The creation of a backgroundLog was always using Debug as the
logging level for console and backing. This commit sets the
levels to those used by the caller. Fixes #3655

### CODE REVIEW

**Comment by dwijnand** [comment]
@cunei Could you rebase this branch on 1.0.x so we can merge it there? That way we can ship this in 1.0.4.

**Review by dwijnand — CHANGES_REQUESTED** [review]
Looks reasonable to me, but we need to rebase this to merge it for 1.0.4.

**Comment by cunei** [comment]
Rebased on 1.0.x

**Review by dwijnand — APPROVED** [review]

**Review by eed3si9n — APPROVED** [review]

**Comment by eed3si9n** [comment]
Looks good.

**Pull request merged**
