### PR TITLE
Off-the-grid installation of sbt

### PR DESCRIPTION
**Pull request by Duhemm**
This PR adds a new main object `sbt.Main` that implements a launcher that can start sbt without ivy or internet access.

The new command `install` creates the fat JAR that can then be launched.

Ref #2518

### CODE REVIEW

**Comment by eed3si9n** [comment]
Notes please.
Also forward port.

**Comment by k0001** [comment]
If I understand correctly, among other things this change allows me to call, for example, `sbt compile` within a SBT project (or a similar command that avoids `sbt-launcher` perhaps), and provided all the `jar`s that both `sbt` and the project itself depends on are already in place, the project will start compiling without downloading anything. Is this correct?

If this is the case: How do I tell `sbt` where to find all those `jar`s? Otherwise: Can I accomplish the example mentioned above somehow?

Sorry if this isn't the right place to ask this question!

**Comment by k0001** [comment]
FYI: I'm working on improving the packaging of SBT applications in the Nix package manager (https://nixos.org/nix). Basically, I want to be able to call `sbt compile` (or any other command that would achieve the same thing), without having SBT hit the internet. One valid approach seems to be to create a local ivy cache, but that's really cumbersome to do as you have to recreate the ivy repository structure and have the `ivy.xml` files. Instead, I would like to be able to somehow list where to find all of the `jar`s both SBT and the project itself needs by hand, in a `CLASSPATH`-like fashion, and it looks like this pull request tries to solve some of that. Am I right? Thanks!

**Comment by eed3si9n** [comment]
This was an experimental feature, and it hasn't been given enough attention.
I wrote https://github.com/sbt/sbt-export-repo, which lets you create a preloaded local repository correctly, by driving Ivy.

**Pull request merged**
