### PR TITLE
Upgrade the build to use sbt 1.0.0-M5

### PR DESCRIPTION
**Pull request by dwijnand**
Some plugins remain commented out, for now.

The motivation for this PR is to start using and exercising sbt 1 ourselves.

### CODE REVIEW

**Comment by eed3si9n** [comment]
Nice!

**Review by eed3si9n — APPROVED** [review]
Looking fwd to this.

**Comment by jvican** [comment]
Me too! I've been meaning to do this in Zinc too. Waiting for all the plugins to be out there :smile:.

**Comment by dwijnand** [comment]
1 test is failing: tests/fork-test-group-parallel.

<details>
  <summary>Here's its output:</summary>

```
Running tests / fork-test-group-parallel
[error] Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256M; support was removed in 8.0
[info] Getting org.scala-sbt sbt 1.0.0-SNAPSHOT ...
[info] :: retrieving :: org.scala-sbt#boot-app
[info] 	confs: [default]
[info] 	51 artifacts copied, 0 already retrieved (15089kB/62ms)
[info] Getting Scala 2.12.2 (for sbt)...
[info] :: retrieving :: org.scala-sbt#boot-scala
[info] 	confs: [default]
[info] 	5 artifacts copied, 0 already retrieved (18841kB/28ms)
[info] Updated file /tmp/sbt_b5adcf60/fork-test-group-parallel/project/build.properties setting sbt.version to: 1.0.0-SNAPSHOT
[info] [info] Loading project definition from /tmp/sbt_b5adcf60/fork-test-group-parallel/project
[info] [info] Updating {file:/tmp/sbt_b5adcf60/fork-test-group-parallel/project/}fork-test-group-parallel-build...
[info] [warn] Choosing local for org.scala-sbt#sbt;1.0.0-SNAPSHOT
[info] [warn] Choosing local for org.scala-sbt#main_2.12;1.0.0-SNAPSHOT
[info] [warn] Choosing local for org.scala-sbt#actions_2.12;1.0.0-SNAPSHOT
[info] [warn] Choosing local for org.scala-sbt#run_2.12;1.0.0-SNAPSHOT
[info] [warn] Choosing local for org.scala-sbt#task-system_2.12;1.0.0-SNAPSHOT
[info] [warn] Choosing local for org.scala-sbt#tasks_2.12;1.0.0-SNAPSHOT
[info] [warn] Choosing local for org.scala-sbt#testing_2.12;1.0.0-SNAPSHOT
[info] [warn] Choosing local for org.scala-sbt#test-agent;1.0.0-SNAPSHOT
[info] [warn] Choosing local for org.scala-sbt#main-settings_2.12;1.0.0-SNAPSHOT
[info] [warn] Choosing local for org.scala-sbt#command_2.12;1.0.0-SNAPSHOT
[info] [warn] Choosing local for org.scala-sbt#protocol_2.12;1.0.0-SNAPSHOT
[info] [info] :: loading settings :: url = jar:file:/tmp/sbt_b5adcf60/fork-test-group-parallel/global/boot/scala-2.12.2/org.scala-sbt/sbt/1.0.0-SNAPSHOT/ivy-2.3.0-sbt-48dd0744422128446aee9ac31aa356ee203cc9f4.jar!/org/apache/ivy/core/settings/ivysettings.xml
[info] [info] :: loading settings :: url = jar:file:/tmp/sbt_b5adcf60/fork-test-group-parallel/global/boot/scala-2.12.2/org.scala-sbt/sbt/1.0.0-SNAPSHOT/ivy-2.3.0-sbt-48dd0744422128446aee9ac31aa356ee203cc9f4.jar!/org/apache/ivy/core/settings/ivysettings.xml
[info] [info] :: loading settings :: url = jar:file:/tmp/sbt_b5adcf60/fork-test-group-parallel/global/boot/scala-2.12.2/org.scala-sbt/sbt/1.0.0-SNAPSHOT/ivy-2.3.0-sbt-48dd0744422128446aee9ac31aa356ee203cc9f4.jar!/org/apache/ivy/core/settings/ivysettings.xml
[info] 0m[info] :: loading settings :: url = jar:file:/tmp/sbt_b5adcf60/fork-test-group-parallel/global/boot/scala-2.12.2/org.scala-sbt/sbt/1.0.0-SNAPSHOT/ivy-2.3.0-sbt-48dd0744422128446aee9ac31aa356ee203cc9f4.jar!/org/apache/ivy/core/settings/ivysettings.xml
[info] [info] :: loading settings :: url = jar:file:/tmp/sbt_b5adcf60/fork-test-group-parallel/global/boot/scala-2.12.2/org.scala-sbt/sbt/1.0.0-SNAPSHOT/ivy-2.3.0-sbt-48dd0744422128446aee9ac31aa356ee203cc9f4.jar!/org/apache/ivy/core/settings/ivysettings.xml
[info] [info] :: loading settings :: url = jar:file:/tmp/sbt_b5adcf60/fork-test-group-parallel/global/boot/scala-2.12.2/org.scala-sbt/sbt/1.0.0-SNAPSHOT/ivy-2.3.0-sbt-48dd0744422128446aee9ac31aa356ee203cc9f4.jar!/org/apache/ivy/core/settings/ivysettings.xml
[info] [info] :: loading settings :: url = jar:file:/tmp/sbt_b5adcf60/fork-test-group-parallel/global/boot/scala-2.12.2/org.scala-sbt/sbt/1.0.0-SNAPSHOT/ivy-2.3.0-sbt-48dd0744422128446aee9ac31aa356ee203cc9f4.jar!/org/apache/ivy/core/settings/ivysettings.xml
[info] [info] :: loading settings :: url = jar:file:/tmp/sbt_b5adcf60/fork-test-group-parallel/global/boot/scala-2.12.2/org.scala-sbt/sbt/1.0.0-SNAPSHOT/ivy-2.3.0-sbt-48dd0744422128446aee9ac31aa356ee203cc9f4.jar!/org/apache/ivy/core/settings/ivysettings.xml
[info] [info] :: loading settings :: url = jar:file:/tmp/sbt_b5adcf60/fork-test-group-parallel/global/boot/scala-2.12.2/org.scala-sbt/sbt/1.0.0-SNAPSHOT/ivy-2.3.0-sbt-48dd0744422128446aee9ac31aa356ee203cc9f4.jar!/org/apache/ivy/core/settings/ivysettings.xml
[info] [info] :: loading settings :: url = jar:file:/tmp/sbt_b5adcf60/fork-test-group-parallel/global/boot/scala-2.12.2/org.scala-sbt/sbt/1.0.0-SNAPSHOT/ivy-2.3.0-sbt-48dd0744422128446aee9ac31aa356ee203cc9f4.jar!/org/apache/ivy/core/settings/ivysettings.xml
[info] [info] :: loading settings :: url = jar:file:/tmp/sbt_b5adcf60/fork-test-group-parallel/global/boot/scala-2.12.2/org.scala-sbt/sbt/1.0.0-SNAPSHOT/ivy-2.3.0-sbt-48dd0744422128446aee9ac31aa356ee203cc9f4.jar!/org/apache/ivy/core/settings/ivysettings.xml
[info] [info] :: loading settings :: url = jar:file:/tmp/sbt_b5adcf60/fork-test-group-parallel/global/boot/scala-2.12.2/org.scala-sbt/sbt/1.0.0-SNAPSHOT/ivy-2.3.0-sbt-48dd0744422128446aee9ac31aa356ee203cc9f4.jar!/org/apache/ivy/core/settings/ivysettings.xml
[info] [info] :: loading settings :: url = jar:file:/tmp/sbt_b5adcf60/fork-test-group-parallel/global/boot/scala-2.12.2/org.scala-sbt/sbt/1.0.0-SNAPSHOT/ivy-2.3.0-sbt-48dd0744422128446aee9ac31aa356ee203cc9f4.jar!/org/apache/ivy/core/settings/ivysettings.xml
[info] [info] :: loading settings :: url = jar:file:/tmp/sbt_b5adcf60/fork-test-group-parallel/global/boot/scala-2.12.2/org.scala-sbt/sbt/1.0.0-SNAPSHOT/ivy-2.3.0-sbt-48dd0744422128446aee9ac31aa356ee203cc9f4.jar!/org/apache/ivy/core/settings/ivysettings.xml
[info] [info0m] :: loading settings :: url = jar:file:/tmp/sbt_b5adcf60/fork-test-group-parallel/global/boot/scala-2.12.2/org.scala-sbt/sbt/1.0.0-SNAPSHOT/ivy-2.3.0-sbt-48dd0744422128446aee9ac31aa356ee203cc9f4.jar!/org/apache/ivy/core/settings/ivysettings.xml
[info] [info] :: loading settings :: url = jar:file:/tmp/sbt_b5adcf60/fork-test-group-parallel/global/boot/scala-2.12.2/org.scala-sbt/sbt/1.0.0-SNAPSHOT/ivy-2.3.0-sbt-48dd0744422128446aee9ac31aa356ee203cc9f4.jar!/org/apache/ivy/core/settings/ivysettings.xml
[info] [info] :: loading settings :: url = jar:file:/tmp/sbt_b5adcf60/fork-test-group-parallel/global/boot/scala-2.12.2/org.scala-sbt/sbt/1.0.0-SNAPSHOT/ivy-2.3.0-sbt-48dd0744422128446aee9ac31aa356ee203cc9f4.jar!/org/apache/ivy/core/settings/ivysettings.xml
[info] [info] :: loading settings :: url = jar:file:/tmp/sbt_b5adcf60/fork-test-group-parallel/global/boot/scala-2.12.2/org.scala-sbt/sbt/1.0.0-SNAPSHOT/ivy-2.3.0-sbt-48dd0744422128446aee9ac31aa356ee203cc9f4.jar!/org/apache/ivy/core/settings/ivysettings.xml
[info] [info] :: loading settings :: url = jar:file:/tmp/sbt_b5adcf60/fork-test-group-parallel/global/boot/scala-2.12.2/org.scala-sbt/sbt/1.0.0-SNAPSHOT/ivy-2.3.0-sbt-48dd0744422128446aee9ac31aa356ee203cc9f4.jar!/org/apache/ivy/core/settings/ivysettings.xml
[info] [info] :: loading settings :: url = jar:file:/tmp/sbt_b5adcf60/fork-test-group-parallel/global/boot/scala-2.12.2/org.scala-sbt/sbt/1.0.0-SNAPSHOT/ivy-2.3.0-sbt-48dd0744422128446aee9ac31aa356ee203cc9f4.jar!/org/apache/ivy/core/settings/ivysettings.xml
[info] [info] :: loading settings :: url = jar:file:/tmp/sbt_b5adcf60/fork-test-group-parallel/global/boot/scala-2.12.2/org.scala-sbt/sbt/1.0.0-SNAPSHOT/ivy-2.3.0-sbt-48dd0744422128446aee9ac31aa356ee203cc9f4.jar!/org/apache/ivy/core/settings/ivysettings.xml
[info] [info] :: loading settings :: url = jar:file:/tmp/sbt_b5adcf60/fork-test-group-parallel/global/boot/scala-2.12.2/org.scala-sbt/sbt/1.0.0-SNAPSHOT/ivy-2.3.0-sbt-48dd0744422128446aee9ac31aa356ee203cc9f4.jar!/org/apache/ivy/core/settings/ivysettings.xml
[info] [info] :: loading settings :: url = jar:file:/tmp/sbt_b5adcf60/fork-test-group-parallel/global/boot/scala-2.12.2/org.scala-sbt/sbt/1.0.0-SNAPSHOT/ivy-2.3.0-sbt-48dd0744422128446aee9ac31aa356ee203cc9f4.jar!/org/apache/ivy/core/settings/ivysettings.xml
[info] [info] :: loading settings :: url = jar:file:/tmp/sbt_b5adcf60/fork-test-group-parallel/global/boot/scala-2.12.2/org.scala-sbt/sbt/1.0.0-SNAPSHOT/ivy-2.3.0-sbt-48dd0744422128446aee9ac31aa356ee203cc9f4.jar!/org/apache/ivy/core/settings/ivysettings.xml
[info] [info] :: loading settings :: url = jar:file:/tmp/sbt_b5adcf60/fork-test-group-parallel/global/boot/scala-2.12.2/org.scala-sbt/sbt/1.0.0-SNAPSHOT/ivy-2.3.0-sbt-48dd0744422128446aee9ac31aa356ee203cc9f4.jar!/org/apache/ivy/core/settings/ivysettings.xml
[info] [info] :: loading settings :: url = jar:file:/tmp/sbt_b5adcf60/fork-test-group-parallel/global/boot/scala-2.12.2/org.scala-sbt/sbt/1.0.0-SNAPSHOT/ivy-2.3.0-sbt-48dd0744422128446aee9ac31aa356ee203cc9f4.jar!/org/apache/ivy/core/settings/ivysettings.xml
[info] [info] :: loading settings :: url = jar:file:/tmp/sbt_b5adcf60/fork-test-group-parallel/global/boot/scala-2.12.2/org.scala-sbt/sbt/1.0.0-SNAPSHOT/ivy-2.3.0-sbt-48dd0744422128446aee9ac31aa356ee203cc9f4.jar!/org/apache/ivy/core/settings/ivysettings.xml
[info] [info] :: loading settings :: url = jar:file:/tmp/sbt_b5adcf60/fork-test-group-parallel/global/boot/scala-2.12.2/org.scala-sbt/sbt/1.0.0-SNAPSHOT/ivy-2.3.0-sbt-48dd0744422128446aee9ac31aa356ee203cc9f4.jar!/org/apache/ivy/core/settings/ivysettings.xml
[info] [info] :: loading settings :: url = jar:file:/tmp/sbt_b5adcf60/fork-test-group-parallel/global/boot/scala-2.12.2/org.scala-sbt/sbt/1.0.0-SNAPSHOT/ivy-2.3.0-sbt-48dd0744422128446aee9ac31aa356ee203cc9f4.jar!/org/apache/ivy/core/settings/ivysettings.xml
[info] [info] :: loading settings :: url = jar:file:/tmp/sbt_b5adcf60/fork-test-group-parallel/global/boot/scala-2.12.2/org.scala-sbt/sbt/1.0.0-SNAPSHOT/ivy-2.3.0-sbt-48dd0744422128446aee9ac31aa356ee203cc9f4.jar!/org/apache/ivy/core/settings/ivysettings.xml
[info] [info] :: loading settings :: url = jar:file:/tmp/sbt_b5adcf60/fork-test-group-parallel/global/boot/scala-2.12.2/org.scala-sbt/sbt/1.0.0-SNAPSHOT/ivy-2.3.0-sbt-48dd0744422128446aee9ac31aa356ee203cc9f4.jar!/org/apache/ivy/core/settings/ivysettings.xml
[info] [info] :: loading settings :: url = jar:file:/tmp/sbt_b5adcf60/fork-test-group-parallel/global/boot/scala-2.12.2/org.scala-sbt/sbt/1.0.0-SNAPSHOT/ivy-2.3.0-sbt-48dd0744422128446aee9ac31aa356ee203cc9f4.jar!/org/apache/ivy/core/settings/ivysettings.xml
[info] [info] Done updating.
[info] [info] Loading settings from build.sbt ...
[info] [info] Set current project to fork-test-group-parallel (in build file:/tmp/sbt_b5adcf60/fork-test-group-parallel/)
[info] [info] Updating {file:/tmp/sbt_b5adcf60/fork-test-group-parallel/}fork-test-group-parallel...
[info] [info] Done updating.
[info] [info] Compiling 1 Scala source to /tmp/sbt_b5adcf60/fork-test-group-parallel/target/scala-2.11/test-classes ...
[info] [info] Done compiling.
[info] [info] TestInitEvent()
[info] [info] TestInitEvent()
[info] [info] TestInitEvent()
[info] [info] TestInitEvent()
[error] x tests / fork-test-group-parallel
[error]    {line 1}  Command failed
```

</details>

I'll come back to this tomorrow.

**Pull request merged**
