### PR TITLE
sbinary formats for generated API classes.

### PR DESCRIPTION
**Pull request by benjyw**
Currently these are hand-coded. We might want to replace these with
generated ones in the future, although that might not be easy/worth it.

### CODE REVIEW

**Comment by harrah** [comment]
Now that we're to the bigger changes, can we have all of the commits needed to see a performance improvement in one pull request along with a description of the expected improvement?

**Comment by benjyw** [comment]
Sure, was trying to keep the commits small for your benefit, but I can create a big one.

**Comment by harrah** [comment]
Small commits are good- just put the relevant commits on a single branch and a single pull request.

**Comment by benjyw** [comment]
Closed as the performance benefits aren't significant yet. May revisit in the future.

**Pull request closed without merging**
