### PR TITLE
Default set of opt-ins for convenience

### PR DESCRIPTION
**Pull request by indrajitr**
This is a followup of the proposal [here](https://github.com/harrah/xsbt/pull/179#issuecomment-2071661)

Default set of _well-known_ opt-ins to be used together other deduced Task or Setting values.

Example usages:

``` scala
javacOptions  ++= DefaultOptions.encoding
scalacOptions ++= DefaultOptions.encoding :+ DefaultOptions.deprecation
scalacOptions in doc <++= (name in doc, version in doc) map DefaultOptions.scaladoc
credentials    += DefaultOptions.credentials
```

### CODE REVIEW

**Comment by indrajitr** [comment]
A quick note on an alternative:

For better grouping, we could also have

``` scala
object DefaultOptions {
  object scalac {
    val deprecation = "-deprecation"
    val encoding = Seq("-encoding", "UTF-8")
    val explaintypes = "-explaintypes"
  }
  object javac {
    val deprecation = "-deprecation"
    val encoding = Seq("-encoding", "UTF-8")
    // ...
  }
```

Thoughts on this?

**Comment by harrah** [comment]
Perhaps it would be better to nest in Defaults instead of a separate DefaultOptions in that case.  What about the default scalac/scaladoc options list?  What would they be called/where would they go?

**Comment by indrajitr** [comment]
The above code was a more casually done to express the nesting idea. In more concrete terms, it would look something like this:

``` scala
object DefaultOptions {
  object CompileOptions {
    val deprecation = "-deprecation"
    def encoding(enc: String = "UTF-8") = Seq("-encoding", enc)
    // val encoding = Seq("-encoding", "UTF-8") // So that we don't need encoding() with empty arglist
    val explaintypes = "-explaintypes"
    // ...
    // ...
  }
  object DocOptions {
    def title(t: String) = Seq("-doc-title", t)
    def version(v: String) = Seq(, "-doc-version", v)
  }
}
def scalac: Seq[String] = CompileOptions.encoding
def scaladoc(name: String, version: String): Seq[String] = DocOptions.title(name) ++ DocOptions.version(version)
```

Few things here:
- Most of the frequently used `javac` options are `scalac` options as well, the common (and often used) ones can all go in `CompileOptions`
- The return types of the options vary (`String`, `Seq[String]`). We can leave them this way for simplicity or if consistency is important always wrap them to `Seq[String]` or even have a separate type like the way it was in 0.7. Opinion?
- Related to above, `encoding` now requires an empty `()` which is unwanted. We can either bring in an `implicit` or just keep `val encoding = Seq("-encoding", "UTF-8")` which would be the most common case anyway.
- The default options list is available as `DefaultOptions.scalac`, `DefaultOpions.scaladoc(name, version)` as mentioned in the example usage above.

I'll update the pull request once I have your thoughts.

**Comment by harrah** [comment]
Seems verbose to say:

``` scala
scalacOptions += DefaultOptions.CompileOptions.deprecation
```

Maybe rename DefaultOptions to Opts, CompileOptions to compile, and DocOptions to doc?

For encoding, I'd drop the default and make it required.  Saying encoding("UTF-8") isn't that bad and might be clearer.

**Comment by indrajitr** [comment]
Yeah, verbosity is a worry. Smaller name is welcome, would take Opts.

The patterns `{Task}Options` were reluctant choice to disambiguate from the TaskKeys with same name. That would have accommodated wildcard import of `DefaultOptions._`. Under new convention one has to do `Opts.compile` explicitly. Let me think about it.

Very good point on encoding, agreed.

**Comment by indrajitr** [comment]
Okay, I am sold. `Opts.compile`, `Opts.doc` etc. are shorter and considerably clearer. Updated patch coming.

**Comment by harrah** [comment]
Ok, sounds good.  I think Opts should go in its own source file.

**Comment by indrajitr** [comment]
In it's own source file now.

Typical usages:

``` scala
// just use the provided default
scalacOptions ++= DefaultOptions.scalac
scalacOptions in doc <++= (name in doc, version in doc) map DefaultOptions.scaladoc
credentials += DefaultOptions.credentials

// use provided default and append additional options
scalacOptions ++= DefaultOptions.scalac :+ Opts.compile.deprecation

// make your own options
scalacOptions ++= Opts.compile.encoding("UTF-8") :+ Opts.compile.deprecation :+ Opts.compile.optimize
```

**Comment by harrah** [comment]
Looks good.  Thanks!

**Comment by mslinn** [comment]
I tried this in build.sbt:

```
docOptions ++= Seq("-doc-source-url https://github.com/mslinn/hanuman")
```

but got

```
docOptions ++= Seq("-doc-source-url https://github.com/mslinn/hanuman")
^
build.sbt:20: error: reassignment to val
```

Same for this:

```
docOptions += "-doc-source-url https://github.com/mslinn/hanuman"
^
build.sbt:20: error: reassignment to val
```

**Pull request merged**
