### PR TITLE
Honor <exclusions/> in <dependency/> when available

### PR DESCRIPTION
**Pull request by indrajitr**
When we add exclusions via `ivyXML` setting, the generated pom should also honor the exclusions in the `<dependency/>` block.

Thus, the following ivyXML block would generate the right `<exclusion/>` under dependency.

``` xml
<dependency org="net.databinder" name="..." rev="...">
  <exclude org="commons-logging" module="commons-logging" />
</dependency>
```

Further, it's worth noting that although Ivy allows you to skip `org="..."` in `<exclude/>` element (legacy stuff), Maven enforces **both** `<artifactId/>` and `<groupId/>` to avoid resolution ambiguities (which is a good thing).

I think, in SBT we should also actively persuade users to provide both the atributes for completeness and better interoperability.

In the current implementation, I have blindly assumed that both `org` and `module` are provided. There is no good default if they aren't, and the `<exclusion/>` block in pom ends up being a defective one. We can take two position here: 
- Keep the current implementation (your `<exclusion/>` is _broken_ because of incomplete info)
- Modify the implementation _not to_ add exclusion element unless both `org` and `module` are available (your `<exclusion/>` is _unavailable_ because of incomplete info).

Thoughts?

### CODE REVIEW

**Comment by ijuma** [comment]
I think fail-fast is good, personally.

**Comment by harrah** [comment]
A conversion from Ivy metadata to a pom.xml is likely to be lossy.  So, the standard approach should probably be to warn when information is lost when the user is likely to care.  I think this is such a case, so I would go with the second choice: only add an exclusion element if both exist and warn otherwise.

Obviously Ivy allows finer grained exclusions per configuration, which is why you have to get all exclude rules for all configurations.  I think there it is more reasonable to do as you do and not warn about the mismatch.

**Comment by indrajitr** [comment]
Okay, I'll update the patch to add exclusion _iff_ both exist.

But to warn otherwise, the logger has to be pushed from `def makePom` to deeper methods. It would mean lot of signature changes, wouldn't it?

**Comment by harrah** [comment]
Yes it would.  I haven't looked to verify this, but I think that would be ok.

**Comment by indrajitr** [comment]
Okay, working on a patch.

**Comment by indrajitr** [comment]
Patch updated. Have added `Logger` as member of `MakePom` so that it is available for other methods as well. I guess, that's okay because all the meaningful methods (excluding the small helpers) are side-effecting anyway.

**Comment by harrah** [comment]
If you prefer, you can certainly return the NodeSeq and a list of warnings and log the warnings higher up.  Code comments:
1. What is the point of this line:
   
   ``` scala
   val (g, a) = (m.getOrganisation, m.getName)
   ```
2. Why `s.equals("*")` instead of using `==` ?
3. Why not `excl.flatMap(makeExclusion)` instead of `map/filterNot`?

**Comment by indrajitr** [comment]
Okay, here is a modified approach using `Either[String,NodeSeq]` bubbled up one level. One approach could be to have all the intermediate methods return `Either[String,NodeSeq]` instead of `NodeSeq` and do the logging finally in `toPom`.

Other points:
1. They are for convenience (to avoid calling `m.getOrganisation`, `m.getName` repeatedly)
2. Java hangover :-)
3. No excuse, sorry

**Comment by harrah** [comment]
The earlier code didn't use g/a more than once, which was why I asked.  It makes more sense now, although you realize that the type ascriptions change the null-semantics from the previous unascripted version, right?  Is it true that organization and name won't be null?

I don't see the point in using `Either.cond` here, since it introduces two closures and negates the conditional for marginal gain over if/else+Left/Right.

**Comment by indrajitr** [comment]
Type ascription is redundant, and can go away. In any case, `organization` and `name` are unlikely to be null because they would come either via ivyXML block (xml attribute where passing `null` is difficult) or via the upcoming inline `ExclusionRule`. In case of `ExclusionRule`, I think the situation is comparable to a build config author specifying `null` version in library-dependency.

You seem to be on the other side of `Either.cond` camp :) I agree to your point, and have modified. So long as things are consistent within SBT, we are good.

**Comment by indrajitr** [comment]
On related note, should we consider having `StringUtilities.nonEmpty(...)` handle `null` as well?

**Comment by harrah** [comment]
I pointed it out because type ascription treats null differently.  It will throw a `MatchError` on null, whereas a variable pattern will not.  Although the exclude might come from `ivyXML` or inline, it might also come from an `ivy.xml` (unlikely that an `ivy.xml` user would generate a pom, but it still needs to be handled).  So, I was wondering if the `ExcludeRule` documentation said that they would never be null.  (Unfortunately, Ivy sometimes returns null for things.)  It would be best to check for null unless the docs say it won't happen.

As for `StringUtilities.nonEmpty`, I don't think so.  In general, I think that Java-interfacing code should test for and convert a null directly as soon as possible.

**Comment by harrah** [comment]
(That is, a type ascription pattern, not type ascription in general)

**Comment by indrajitr** [comment]
Aha! I interpreted you point on ascription incorrectly.

Fair point, I'll handle `organization` null check explicitly. No such need for `name` I think because Ivy explicitly mentions that `name` must not be `null`. See `ModuleId.newInstance`.

**Comment by indrajitr** [comment]
Updated to handle null `organization`.

**Pull request merged**
