### PR TITLE
Classloader::getResource() should never return null

### PR DESCRIPTION
**Pull request by jerrinot**
fixing #1368

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @jerrinot,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.typesafe.com/contribute/cla](http://www.typesafe.com/contribute/cla)

**Comment by typesafe-tools** [comment]
Can one of the admins verify this patch?

**Comment by jerrinot** [comment]
I just signed the individual CLA

**Comment by hcoles** [comment]
This doesn't compile as it uses the java 7 only Collections.emptyEnumeration.

There are also some other areas of the code where null might be returned e.g in NullLoader. I am unclear if this fix would also catch these.

I'm unable to try this out locally due to this problem -> http://stackoverflow.com/questions/28431934/publish-precompiled-x-binaries-locally-for-sbt

I'd be happy to produce a clean tested PR if some-one can help me through the issue above.

**Comment by hcoles** [comment]
@jerrinot I've put together an alternate PR that is confirmed to work and does not rely on java 7. It might be worth closing this one to avoid confusion.

**Comment by jerrinot** [comment]
@hcoles: great, thanks for info!
I'm closing to PR in favour for #1853

**Pull request closed without merging**
