### PR TITLE
Corrections for xml handling and session save

### PR DESCRIPTION
**Pull request by ajozwik**
See comment https://github.com/sbt/sbt/commit/e8218faa7fb777ab99e7615fa0fecd1e6580264b#commitcomment-7954217

Still can be problem with white spaces in tests.
I received:

```
Caused by: java.lang.RuntimeException: Test script error: File contents are different:
k1 := {error("k1")}

k2 <<= k1 map identity
And:
k1 := {error("k1")}

k2 <<= k1 map identity

    at scala.sys.package$.error(package.scala:27)
```

But I have no idea - what is wrong? End of line?

### CODE REVIEW

**Comment by typesafe-tools** [comment]
Can one of the admins verify this patch?

**Comment by jsuereth** [comment]
Would you mind rebasing this on the current wip/no-blankies?

**Comment by ajozwik** [comment]
Yes, but I'm not sure what I should do? Merge wip/no-blankies to WarsawScala/sbt and create pull request?

**Comment by jsuereth** [comment]
Closing in favor of other PR.

**Pull request closed without merging**
