### PR TITLE
add tests around scope delegation

### PR DESCRIPTION
**Pull request by eed3si9n**
Ref https://github.com/sbt/sbt/pull/3979

### CODE REVIEW

**Comment by dwijnand** [comment]
could you describe what you've looked and achieved in this PR? it's a little hard to reverse engineer from the diff.

**Comment by eed3si9n** [comment]
> could you describe what you've looked and achieved in this PR? it's a little hard to reverse engineer from the diff.

1. Changes in main/src/test/scala/sbt/internal/TestBuild.scala is mostly around hard-coding the datatype to Vector instead of Seq.
2. The change in main/src/test/scala/Delegates.scala is adding two property-based testing. This the code that tests `Scope.delegates(...)`. Given a scoped key, it can return the list of delegations.
  - "Project axis delegates to BuildRef then Zero" tests that if you have `foo/Compile/x` it delegates to `ThisBuild/Compile/x` etc..
  - "Config axis delegates to parent configuration" tests that if you have `foo/Test/x` it delegates to `foo/Runtime/x` etc..

**Comment by eed3si9n** [comment]
Can I merge this one?

**Comment by dwijnand** [comment]
do you think it fully tests the behaviour and invariants of `Scope.delegates`?

I've never spent time understanding the state of the implementation and testing of scope delegation.

**Comment by eed3si9n** [comment]
I don't think it does fully yet, but it covers some aspects.

**Comment by dwijnand** [comment]
ok then I'll pick up from where you left off.

**Review by dwijnand — APPROVED** [review]
these tests are great!

this pr should not (I should not) blockade its merging just because test coverage could further be improved!

**Pull request merged**
