### PR TITLE
add flyway-sbt plugin to community plugins

### PR DESCRIPTION
**Pull request by cdedie**

### CODE REVIEW

**Comment by jsuereth** [comment]
Thanks for the contribution AND for the plugin!

**Comment by jsuereth** [comment]
@harrah is this good to merge, or do we need to target "master" for sbt's doc build?

**Comment by harrah** [comment]
Good to merge to 0.13.1 and CI will update the site.

**Comment by harrah** [comment]
Merged in 38f44ec8abc74f548274bd69b5557642e252f06d.

**Pull request closed without merging**
