### PR TITLE
Add support for loading Ivy settings from a URL

### PR DESCRIPTION
**Pull request by mallman**
This is just a re-commit and re-submit of https://github.com/harrah/xsbt/pull/416 because I bone-headedly made some commits with the wrong user.email. The patch is identical as of the time of 416's close.

### CODE REVIEW

**Comment by harrah** [comment]
No problem about the new pull request.  I have merged it, thanks!  I have a couple of comments for a follow-up:
1. I typically avoid URL and use URI instead because URL's hashCode/equals access the network and it can be non-obvious when this happens.  (Obviously a URI is a superset of a URL and we only want a URL, but I think the downside to the network access for URL is high enough to warrant using URI instead of URL.)
2. The code that selects the hash to use based on the protocol should be broken out into its own method.

**Comment by harrah** [comment]
Also, for documentation, you can add a line to the [0.12 Changes](https://github.com/harrah/xsbt/wiki/ChangeSummary_0.12.0) page under the first section and then the Ivy settings section of the [Library Management](https://github.com/harrah/xsbt/wiki/Library-Management) page.  There should be an Edit Page button when you are signed into your github account. The pages are in Markdown.

**Comment by mallman** [comment]
Hi Mark,

I'm also aware of the drawbacks you mention of the URL class vis-a-vis URI, but decided that URL was more appropriate because it better conveys the intent of this use-case. I dunno. I see drawbacks either way.

As regards extracting the hashing code into a separate method, I will do that on or before this weekend and submit another pull request. Same goes for the documentation edits.

I do have a question about updating the wiki page. My understanding is that the wiki documentation applies to 0.11.2. Should I mention that this feature will be upcoming in 0.12.0, and do you have standard language/markup for that?

Cheers.

**Comment by ijuma** [comment]
I agree with Mark. The URL class should be avoided whenever possible.

**Comment by harrah** [comment]
I had to add support for multi-projects when using an ivysettings.xml so I made the changes while I was at it.

Yes, the wiki documentation is for 0.11.2 and yes, just put a note in bold at the top of your new section that says something "Note: this feature is only present in 0.12.0 and later".  Nothing standard beyond that.

**Comment by harrah** [comment]
Also, I had to call `IvySettings.load(File)` when it a file is specified because otherwise I hit [Ivy-1114](https://issues.apache.org/jira/browse/IVY-1114).

**Comment by mallman** [comment]
Added dox as requested. Thanks for accepting this change! :)

**Pull request merged**
