### PR TITLE
Bump the 2.12 version to 2.12.8 in 1.2.x

### PR DESCRIPTION
**Pull request by cunei**

### CODE REVIEW

**Comment by typesafe-tools** [comment]
A validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt-validator/1332/console">is in progress...</a>

**Comment by typesafe-tools** [comment]
[//]: # (Refs: pull/4516/head-1.2.x-1.2.x-1.2.x-1.2.x)
The validator <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/1332/">has checked</A> the following projects, tested using dbuild, projects built on top of each other.

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | <A HREF="https://github.com/sbt/sbt/pull/4516">pull/4516/head      </A> | sbt/sbt@0b103c57015d06e1cd3432d157741db881407de8
  zinc              | <A HREF="https://github.com/sbt/zinc/tree/1.2.x">1.2.x               </A> | sbt/zinc@c46643f3e68d7d4f270bf318e3f150f5a59c0aab
  io                | <A HREF="https://github.com/sbt/io/tree/1.2.x">1.2.x               </A> | sbt/io@628d8738070bb65356349630e56cac5c83707c70
  librarymanagement | <A HREF="https://github.com/sbt/librarymanagement/tree/1.2.x">1.2.x               </A> | sbt/librarymanagement@c236d111b833ca6d048cdadfb669317eeee17b34
  util              | <A HREF="https://github.com/sbt/util/tree/1.2.x">1.2.x               </A> | sbt/util@016858ddd8601f9d55224d2b6ec9b046cf8e29d9

:x: The result is: ***FAILED***
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild?sbt=pull/4516/head&zinc=1.2.x&io=1.2.x&librarymanagement=1.2.x&util=1.2.x&deploy_to_bintray=false&run_sbt_community=false">(restart)</A>

**Comment by typesafe-tools** [comment]
A validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt-validator/1334/console">is in progress...</a>

**Comment by typesafe-tools** [comment]
[//]: # (Refs: pull/4516/head-1.2.x-1.2.x-1.2.x-1.2.x)
The validator <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/1334/">has checked</A> the following projects, tested using dbuild, projects built on top of each other.

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | <A HREF="https://github.com/sbt/sbt/pull/4516">pull/4516/head      </A> | sbt/sbt@6b3ec4e1d0e21c2f3ea49979b0c9f20d416fa92a
  zinc              | <A HREF="https://github.com/sbt/zinc/tree/1.2.x">1.2.x               </A> | sbt/zinc@c46643f3e68d7d4f270bf318e3f150f5a59c0aab
  io                | <A HREF="https://github.com/sbt/io/tree/1.2.x">1.2.x               </A> | sbt/io@628d8738070bb65356349630e56cac5c83707c70
  librarymanagement | <A HREF="https://github.com/sbt/librarymanagement/tree/1.2.x">1.2.x               </A> | sbt/librarymanagement@c236d111b833ca6d048cdadfb669317eeee17b34
  util              | <A HREF="https://github.com/sbt/util/tree/1.2.x">1.2.x               </A> | sbt/util@016858ddd8601f9d55224d2b6ec9b046cf8e29d9

:white_check_mark: The result is: ***SUCCESS***
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild?sbt=pull/4516/head&zinc=1.2.x&io=1.2.x&librarymanagement=1.2.x&util=1.2.x&deploy_to_bintray=false&run_sbt_community=false">(restart)</A>

**Review by eed3si9n — APPROVED** [review]

**Pull request merged**
