### PR TITLE
Fix the run logic so the mainClass setting is actually used when set.

### PR DESCRIPTION
**Pull request by jsuereth**
This is one of those super hard to test scenarios where the "main class" being run is a from a different JAR (i.e. we'll never discover one).    More importantly, the run task wasn't using the configured main class due to, what appears to be, a refactoring mixup we didn't catch during code review of the new select-main-class warning.

Review by @eed3si9n cc @fommil

### CODE REVIEW

**Comment by eed3si9n** [comment]
#1669
This should be reviewed by @kretes

**Comment by kretes** [comment]
This will not change what was introduced in #1669 .
Pity there are no test for those behaviours. Could you point to some test that for given sbt project verifies what the actual value of some sbt setting is? I guess it's needed here to avoid regression in the future

**Comment by jsuereth** [comment]
I was actually used a custom publishe dproject for the test.  I'll see if I can expand the regression test suite with such a test, albeit I'm hesitant to do so, as anythign which requries publishing to a local artifactory is cause of flakiness in travis (it seems).

**Comment by jsuereth** [comment]
Ok guys, I added an automated test.

**Comment by kretes** [comment]
Yes, that works. However this scripted test scenario is not really easy to follow.
I would imagine an assertion like 'ensure mainClass is "Test"' instead of specifying an sbt job to run.
I should dig into scripted plugin more to understand how to use it better

**Comment by jsuereth** [comment]
@jaceklaskowski The inter-project resolver is how we fake ivy into understanding internal project dependencies within an sbt build.  What sbt does for "dependsOn" is two-fold.
1. We set up a dependency in IVY so any generated poms/ivy files are correct in specifying the dependencies
2. We use inter-project resolver and sbt-task dependencies to figure out what the classpath should be and ensure the sub-project is compiled before the dependent project.

So inter-project comes from sbt-itself.

**Pull request merged**
