### PR TITLE
Dependency graph with colors (based on the organization)

### PR DESCRIPTION
**Pull request by sideeffffect**
# With this PR
image

image

image

# Before
image

image

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @sideeffffect,

Thank you for your contribution! We really value the time you've taken to put this together.

We see that you have signed the Lightbend Contributors License Agreement before, however, the CLA has changed since you last signed it.
Please review the new CLA and sign it before we proceed with reviewing this pull request:

[https://www.lightbend.com/contribute/cla](https://www.lightbend.com/contribute/cla)

**Comment by eed3si9n** [comment]
@sideeffffect Thanks for the contribution. In the description of the PR could you add a few lines describing the motivation for this change?

Also I wonder if you could implement a global setting that can turn the color on or off? I am fine with this being on-by-default, but also some users might prefer monochromatic graph from the dependency graph for various reasons.

**Comment by sideeffffect** [comment]
@eed3si9n done and done :+1:

**Comment by sideeffffect** [comment]
@eed3si9n ready to be reviewed/merged

**Review by eed3si9n — APPROVED** [review]
LGTM

**Comment by sideeffffect** [comment]
Just for my curiosity, has a version with this improvement been already published?

**Comment by eed3si9n** [comment]
This went into develop branch, so I am guessing it's stuck there. I might be good to backport it to 1.9.x?

**Pull request merged**
