### PR TITLE
Add forceUpdatePeriod

### PR DESCRIPTION
**Pull request by ajsquared**
Adds `forceUpdatePeriod` key, that takes values of `Option[FiniteDuration]`.  If set, a full `update` will occur after that amount of time without needing to explicitly run the `update` task.

The use case is to simplify the workflow a fit for projects with SNAPSHOT/`changing()` dependencies.  By setting `forceUpdatePeriod` you can ensure you will get new SNAPSHOT versions periodically even without explicitly running `update`.

### CODE REVIEW

**Comment by typesafe-tools** [comment]
Can one of the admins verify this patch?

**Comment by ajsquared** [comment]
The `dependency-management/mvn-local` test seems to be flaky for me locally.  Its failing intermittently both with and without the changes in this PR.

`source-dependencies/macro-arg-dep-2-11` and `source-dependencies/macro-arg-dep-nested-2-11` are both working consistently for me locally with these changes.

**Comment by dwijnand** [comment]
Why not use `scala.concurrent.duration.Duration`/`FiniteDuration` instead of a Long?

**Comment by ajsquared** [comment]
@dwijnand Good call, I'll make that change

**Comment by ajsquared** [comment]
`source-dependencies/macro-arg-dep-2-11` and `source-dependencies/macro-arg-dep-nested-2-11` are still passing for me locally.

The `reporter/*` failure looks spurious as well.

**Comment by jsuereth** [comment]
LGTM

**Pull request merged**
