### PR TITLE
Added JavacLogger, for #68

### PR DESCRIPTION
**Pull request by duboisf**
Had commited to 0.10 branch, created a new topic branch for the pull request.

Like I said previously, if I don't use `var exitCode = -1` how can I pass it into `javacLogger.flush`? As in:

``` scala
try { Process... } finally { javacLogger.flush(???) }
```

So I used this instead:

``` scala
allCatch opt { Process... } match { 
  case exitCode => {
    javacLogger.flush(exitCode)
    exitCode getOrElse (-1)
  }
}
```

### CODE REVIEW

**Comment by harrah** [comment]
I'm sorry about that.  I missed you saying that the first time and didn't catch it myself either time (obviously).  Your original code with the var was good, so let's go with that one.  I don't think you need to re-fork, just create a new branch.  You can delete the branch after I merge it if you want.  Finally, please confirm new BSD license is ok.

**Comment by duboisf** [comment]
No worries.

Yeah I reforked because for some reason I couldn't delete the 0.10 branch in my fork and I wanted to rebase it. From now on I'll always do topic branches first :)

BSD license is ok. Just out of curiosity, what was it before?

One final note, I forgot to change logging from Debug to Info in the print function:

``` scala
case (Info, msg) => log.debug(msg)
```

so I changed it to

``` scala
case (Info, msg) => log.info(msg)
```

**Comment by harrah** [comment]
The name of the license is "new BSD".  The license is same as before.  Thanks again for the patch!

**Comment by duboisf** [comment]
I rebased my modifications in my issue_68 branch into a single commit and deleted and repushed the issue_68 branch. 

Github didn't pick up that it has changed (well it says that it was 2 days ago) but if you look at the commit above (`2f4be49`) it's the one I just updated.

Sorry, new to github's pull requests, if I'm not doing it right, do tell :)

**Comment by duboisf** [comment]
My pleasure!

**Comment by harrah** [comment]
Yeah, it's merged now, thanks!

**Pull request merged**
