### PR TITLE
Bump sbt dogfood version

### PR DESCRIPTION
**Pull request by eatkins**

### CODE REVIEW

**Review by eed3si9n — CHANGES_REQUESTED** [review]
Duplicate of https://github.com/sbt/sbt/pull/5029

**Comment by eatkins** [comment]
Do you want to merge #5029 back into develop after #5027? If so, I think we should bump the version to 1.4.0-SNAPSHOT, but otherwise that makes sense.

**Comment by eed3si9n** [comment]
Yea. I think we can get develop square with 1.3.x, and then bump the version.

**Comment by eatkins** [comment]
Ok. I consolidated those changes into #5027.

**Pull request closed without merging**
