### PR TITLE
set status according to the isSnapshot setting

### PR DESCRIPTION
**Pull request by earldouglas**
sbt is currently publishing all artifacts as status `"release"`, which is undesirable for `-SNAPSHOT` artifacts.

I changed a line in `Defaults.scala` to look at the state of `isSnapshot` and set the status accordingly.

### CODE REVIEW

**Comment by harrah** [comment]
I assume this is so you can use `latest.integration`?

**Comment by earldouglas** [comment]
Not exactly; this is so that when publishing a project where any of:
1. Version ends in `-SNAPSHOT`
2. `isSnapshot := true`

then the published `ivy.xml` file should indicate that this is an integration version.  Then when _other_ projects use this one as a dependency (by `latest.integration`, or by naming the `-SNAPSHOT` version, etc.), they will know not to rely on a cached version when a known repository might have a newer integration version (unless they are using sbt and have `offline := true`).

I had hoped that this would also solve [issue 335](https://github.com/harrah/xsbt/issues/335), but no such luck. :]

**Comment by harrah** [comment]
Ah, no.  status doesn't affect that.  If a 'clean' fixes your problems, the actual issue is probably a result of 0.10 trying to have `update` be automatically run (among other things).  The problem is that if dependency configuration doesn't change, sbt doesn't think 'update' needs to do any work (and this is independent of Ivy).  I will look into making an explicit call to 'update' from the command line force update to do work.

**Comment by indrajitr** [comment]
Picking nit :) This has gone in 0.11.2 branch which was used to spin 0.11.2 only. I am guessing this won't be necessary in 0.12.0 (since @harrah worked on force update), but if that's not the case this needs to be cherry-picked to 0.12 branch.

**Comment by harrah** [comment]
Thanks, I didn't notice that.  Put this one and #330 on 0.12 or I'll get to it later.

**Comment by indrajitr** [comment]
cherry-picked on 0.12 branch

**Pull request merged**
