### PR TITLE
Fix for sbt#1180 - discovered classes are now sorted

### PR DESCRIPTION
**Pull request by kretes**

### CODE REVIEW

**Comment by kretes** [comment]
Travis is out of mind (i.e. out of disk space) - see https://travis-ci.org/sbt/sbt/jobs/39009541. I guess it all started here: https://travis-ci.org/sbt/sbt/builds/38965956

**Comment by typesafe-tools** [comment]
Can one of the admins verify this patch?

**Comment by jsuereth** [comment]
Sorry, this is a little late for 0.13.7 unless it's a regression.  Would you mind targeting the 0.13 branch?

**Comment by kretes** [comment]
will retarget to 0.13

**Pull request closed without merging**
