### PR TITLE
Use the new Zinc main class detection

### PR DESCRIPTION
**Pull request by smarter**
See https://github.com/sbt/zinc/pull/287 for details.

### CODE REVIEW

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild/?sbt=pull/3312/head&deploy_to_bintray=false">this link.</A>

**Comment by typesafe-tools** [comment]
A dbuild validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/81/console">is in progress...</a>

**Comment by typesafe-tools** [comment]
[//]: # (Refs: pull/3312/head-1.0-1.0-1.0-1.0-1.0.x)
dbuild <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/81/">has checked</A> the following projects against Scala 2.12:

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | pull/3312/head       | sbt/sbt@be187d61b1c337df89fa0576baf5257d7dfb8e6f
  zinc              | 1.0                  | sbt/zinc@1e6893685583f1ecd33d0bd862545ff6552de78a
  io                | 1.0                  | sbt/io@16c2e3100ade4c4e6dfec83bcf8d5bce6506a773
  librarymanagement | 1.0                  | sbt/librarymanagement@f8d3718d283cacdc11c6d4a9f101c675f687dc49
  util              | 1.0                  | sbt/util@88395e18a4acbb194b9476f3f717153c43bbd04c
  website           | 1.0.x                | sbt/website@7e644bc8fc623589152e98bee75afd44893690e3

:x: The result is: ***FAILED***
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild?sbt=pull/3312/head&zinc=1.0&io=1.0&librarymanagement=1.0&util=1.0&website=1.0.x&deploy_to_bintray=false">(restart)</A>

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild/?sbt=pull/3312/head&deploy_to_bintray=false">this link.</A>

**Review by eed3si9n — APPROVED** [review]
LGTM

Dbuild failure is due to lm change not being propagated to downstream.

**Comment by typesafe-tools** [comment]
A dbuild validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/82/console">is in progress...</a>

**Comment by typesafe-tools** [comment]
[//]: # (Refs: pull/3312/head-1.0-1.0-pull/122/head-1.0-1.0.x)
dbuild <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/82/">has checked</A> the following projects against Scala 2.12:

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | pull/3312/head       | sbt/sbt@cfc8a85fdf72253291001a2291cc9adc37365b22
  zinc              | 1.0                  | sbt/zinc@aabdd7a7e4c58cc4173b52c1f55e58a11a545cb4
  io                | 1.0                  | sbt/io@16c2e3100ade4c4e6dfec83bcf8d5bce6506a773
  librarymanagement | pull/122/head        | sbt/librarymanagement@e3891c8732dc248bd3ff3be9d5c796454d66bc3a
  util              | 1.0                  | sbt/util@88395e18a4acbb194b9476f3f717153c43bbd04c
  website           | 1.0.x                | sbt/website@7e644bc8fc623589152e98bee75afd44893690e3

:x: The result is: ***FAILED***
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild?sbt=pull/3312/head&zinc=1.0&io=1.0&librarymanagement=pull/122/head&util=1.0&website=1.0.x&deploy_to_bintray=false">(restart)</A>

**Comment by eed3si9n** [comment]
```
[error] java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Metaspace
[error] Use 'last' for the full log.
```

**Comment by typesafe-tools** [comment]
A dbuild validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/83/console">is in progress...</a>

**Comment by typesafe-tools** [comment]
[//]: # (Refs: pull/3312/head-1.0-1.0-pull/122/head-1.0-1.0.x)
dbuild <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/83/">has checked</A> the following projects against Scala 2.12:

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | pull/3312/head       | sbt/sbt@cfc8a85fdf72253291001a2291cc9adc37365b22
  zinc              | 1.0                  | sbt/zinc@aabdd7a7e4c58cc4173b52c1f55e58a11a545cb4
  io                | 1.0                  | sbt/io@16c2e3100ade4c4e6dfec83bcf8d5bce6506a773
  librarymanagement | pull/122/head        | sbt/librarymanagement@e3891c8732dc248bd3ff3be9d5c796454d66bc3a
  util              | 1.0                  | sbt/util@88395e18a4acbb194b9476f3f717153c43bbd04c
  website           | 1.0.x                | sbt/website@7e644bc8fc623589152e98bee75afd44893690e3

:x: The result is: ***FAILED***
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild?sbt=pull/3312/head&zinc=1.0&io=1.0&librarymanagement=pull/122/head&util=1.0&website=1.0.x&deploy_to_bintray=false">(restart)</A>

**Comment by typesafe-tools** [comment]
A dbuild validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/84/console">is in progress...</a>

**Comment by typesafe-tools** [comment]
A dbuild validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/85/console">is in progress...</a>

**Comment by typesafe-tools** [comment]
[//]: # (Refs: pull/3312/head-1.0-1.0-pull/122/head-1.0-1.0.x)
dbuild <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/85/">has checked</A> the following projects against Scala 2.12:

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | pull/3312/head       | sbt/sbt@cfc8a85fdf72253291001a2291cc9adc37365b22
  zinc              | 1.0                  | sbt/zinc@aabdd7a7e4c58cc4173b52c1f55e58a11a545cb4
  io                | 1.0                  | sbt/io@16c2e3100ade4c4e6dfec83bcf8d5bce6506a773
  librarymanagement | pull/122/head        | sbt/librarymanagement@e3891c8732dc248bd3ff3be9d5c796454d66bc3a
  util              | 1.0                  | sbt/util@88395e18a4acbb194b9476f3f717153c43bbd04c
  website           | 1.0.x                | sbt/website@7e644bc8fc623589152e98bee75afd44893690e3

:x: The result is: ***FAILED***
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild?sbt=pull/3312/head&zinc=1.0&io=1.0&librarymanagement=pull/122/head&util=1.0&website=1.0.x&deploy_to_bintray=false">(restart)</A>

**Comment by typesafe-tools** [comment]
A dbuild validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/86/console">is in progress...</a>

**Comment by typesafe-tools** [comment]
A dbuild validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/87/console">is in progress...</a>

**Comment by typesafe-tools** [comment]
[//]: # (Refs: pull/3312/head-1.0-1.0-pull/122/head-1.0-1.0.x)
dbuild <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/87/">has checked</A> the following projects against Scala 2.12:

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | <A HREF="https://github.com/sbt/sbt/pull/pull/3312">pull/3312/head      </A> | sbt/sbt@cfc8a85fdf72253291001a2291cc9adc37365b22
  zinc              | <A HREF="https://github.com/sbt/zinc/tree/1.0">1.0                 </A> | sbt/zinc@aabdd7a7e4c58cc4173b52c1f55e58a11a545cb4
  io                | <A HREF="https://github.com/sbt/io/tree/1.0">1.0                 </A> | sbt/io@16c2e3100ade4c4e6dfec83bcf8d5bce6506a773
  librarymanagement | <A HREF="https://github.com/sbt/librarymanagement/pull/pull/122">pull/122/head       </A> | sbt/librarymanagement@e3891c8732dc248bd3ff3be9d5c796454d66bc3a
  util              | <A HREF="https://github.com/sbt/util/tree/1.0">1.0                 </A> | sbt/util@88395e18a4acbb194b9476f3f717153c43bbd04c
  website           | <A HREF="https://github.com/sbt/website/tree/1.0.x">1.0.x               </A> | sbt/website@7e644bc8fc623589152e98bee75afd44893690e3

:x: The result is: ***FAILED***
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild?sbt=pull/3312/head&zinc=1.0&io=1.0&librarymanagement=pull/122/head&util=1.0&website=1.0.x&deploy_to_bintray=false">(restart)</A>

**Comment by typesafe-tools** [comment]
A dbuild validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/88/console">is in progress...</a>

**Comment by typesafe-tools** [comment]
[//]: # (Refs: pull/3312/head-1.0-1.0-pull/122/head-1.0-1.0.x)
dbuild <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/88/">has checked</A> the following projects against Scala 2.12:

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | <A HREF="https://github.com/sbt/sbt/pull/3312">pull/3312/head      </A> | sbt/sbt@cfc8a85fdf72253291001a2291cc9adc37365b22
  zinc              | <A HREF="https://github.com/sbt/zinc/tree/1.0">1.0                 </A> | sbt/zinc@aabdd7a7e4c58cc4173b52c1f55e58a11a545cb4
  io                | <A HREF="https://github.com/sbt/io/tree/1.0">1.0                 </A> | sbt/io@16c2e3100ade4c4e6dfec83bcf8d5bce6506a773
  librarymanagement | <A HREF="https://github.com/sbt/librarymanagement/pull/122">pull/122/head       </A> | sbt/librarymanagement@e3891c8732dc248bd3ff3be9d5c796454d66bc3a
  util              | <A HREF="https://github.com/sbt/util/tree/1.0">1.0                 </A> | sbt/util@88395e18a4acbb194b9476f3f717153c43bbd04c
  website           | <A HREF="https://github.com/sbt/website/tree/1.0.x">1.0.x               </A> | sbt/website@7e644bc8fc623589152e98bee75afd44893690e3

:x: The result is: ***FAILED***
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild?sbt=pull/3312/head&zinc=1.0&io=1.0&librarymanagement=pull/122/head&util=1.0&website=1.0.x&deploy_to_bintray=false">(restart)</A>

**Pull request merged**
