### PR TITLE
Change "Not a simple type" warning to log message

### PR DESCRIPTION
**Pull request by puffnfresh**
Workaround for -Xfatal-warnings being triggered because of #830.

### CODE REVIEW

**Comment by puffnfresh** [comment]
Looks like other pull requests are having the same problem with Travis and `sbt.std.TaskSerial`.

**Comment by nuttycom** [comment]
:+1:

**Comment by jsuereth** [comment]
Yeah, I think TaskSerial has parallelization issues.

Otherwise I need @gkossakowski to review this, in case he knows why a non-simple type is getting exposed in the simpleType method.

**Comment by typesafe-tools** [comment]
Can one of the admins verify this patch?

**Comment by gkossakowski** [comment]
LGTM.

@jsuereth, the underlying problem can be fixed only in next major release of sbt due to binary compatibility constraints. Check the discussion in #830 for details.

**Comment by eed3si9n** [comment]
I just pushed 0.13.6-M1 with this in it. Could you test if it works?

**Comment by puffnfresh** [comment]
@eed3si9n thanks for publishing that.

Sadly, I get the following stacktrace when running `update`:

```
java.lang.NullPointerException
    at sbinary.JavaUTF$StringFormat$.writes(javaprotocol.scala:156)
    at sbinary.JavaUTF$StringFormat$.writes(javaprotocol.scala:100)
    at sbinary.Operations$.write(operations.scala:10)
    at sbinary.BasicTypes$$anon$3.writes(standardtypes.scala:15)
    at sbinary.BasicTypes$$anon$3.writes(standardtypes.scala:8)
    at sbinary.Operations$.write(operations.scala:10)
    at sbinary.BasicTypes$$anon$20.writes(standardtypes.scala:738)
    at sbinary.BasicTypes$$anon$20.writes(standardtypes.scala:704)
    at sbinary.Operations$.write(operations.scala:10)
    at sbinary.Generic$$anon$5.writes(generic.scala:72)
    at sbinary.Operations$.write(operations.scala:10)
    at sbinary.Generic$CollectionFormat$$anonfun$writes$1.apply(generic.scala:24)
    at sbinary.Generic$CollectionFormat$$anonfun$writes$1.apply(generic.scala:24)
    at scala.collection.immutable.List.foreach(List.scala:318)
    at sbinary.Generic$LengthEncoded.foreach(generic.scala:32)
    at sbinary.Generic$LengthEncoded.foreach(generic.scala:30)
    at sbinary.Generic$CollectionFormat.writes(generic.scala:24)
    at sbinary.Operations$.write(operations.scala:10)
    at sbinary.Generic$$anon$5.writes(generic.scala:72)
    at sbinary.Operations$.write(operations.scala:10)
    at sbinary.BasicTypes$$anon$5.writes(standardtypes.scala:57)
    at sbinary.BasicTypes$$anon$5.writes(standardtypes.scala:44)
    at sbinary.Operations$.write(operations.scala:10)
    at sbinary.Generic$$anon$5.writes(generic.scala:72)
    at sbinary.Operations$.write(operations.scala:10)
    at sbinary.Generic$CollectionFormat$$anonfun$writes$1.apply(generic.scala:24)
    at sbinary.Generic$CollectionFormat$$anonfun$writes$1.apply(generic.scala:24)
    at scala.collection.immutable.List.foreach(List.scala:318)
    at sbinary.Generic$LengthEncoded.foreach(generic.scala:32)
    at sbinary.Generic$LengthEncoded.foreach(generic.scala:30)
    at sbinary.Generic$CollectionFormat.writes(generic.scala:24)
    at sbinary.Operations$.write(operations.scala:10)
    at sbinary.Generic$$anon$5.writes(generic.scala:72)
    at sbinary.Operations$.write(operations.scala:10)
    at sbinary.BasicTypes$$anon$6.writes(standardtypes.scala:81)
    at sbinary.BasicTypes$$anon$6.writes(standardtypes.scala:67)
    at sbinary.Operations$.write(operations.scala:10)
    at sbinary.Generic$$anon$5.writes(generic.scala:72)
    at sbinary.Operations$.write(operations.scala:10)
    at sbinary.Generic$CollectionFormat$$anonfun$writes$1.apply(generic.scala:24)
    at sbinary.Generic$CollectionFormat$$anonfun$writes$1.apply(generic.scala:24)
    at scala.collection.immutable.List.foreach(List.scala:318)
    at sbinary.Generic$LengthEncoded.foreach(generic.scala:32)
    at sbinary.Generic$LengthEncoded.foreach(generic.scala:30)
    at sbinary.Generic$CollectionFormat.writes(generic.scala:24)
    at sbinary.Operations$.write(operations.scala:10)
    at sbinary.Generic$$anon$5.writes(generic.scala:72)
    at sbinary.Operations$.write(operations.scala:10)
    at sbinary.BasicTypes$$anon$6.writes(standardtypes.scala:80)
    at sbinary.BasicTypes$$anon$6.writes(standardtypes.scala:67)
    at sbinary.Operations$.write(operations.scala:10)
    at sbinary.Generic$$anon$5.writes(generic.scala:72)
    at sbinary.Generic$$anon$7.writes(generic.scala:98)
    at sbinary.Operations$.toByteArray(operations.scala:18)
    at sbinary.Operations$.toFile(operations.scala:34)
    at sbt.CacheIO$.toFile(CacheIO.scala:33)
    at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:36)
    at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1289)
    at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1284)
    at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:45)
    at sbt.Classpaths$.cachedUpdate(Defaults.scala:1292)
    at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1256)
    at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1234)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
    at sbt.std.Transform$$anon$4.work(System.scala:63)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
    at sbt.Execute.work(Execute.scala:235)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:744)
```

**Comment by eed3si9n** [comment]
```
    at sbt.CacheIO$.toFile(CacheIO.scala:33)
    at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:36)
    at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1289)
```

@puffnfresh That looks like I messed up something while implementing #1467. Could you open another case on this preferably with the list of library dependencies you have?

**Comment by puffnfresh** [comment]
@eed3si9n https://github.com/sbt/sbt/issues/1484

**Comment by puffnfresh** [comment]
@eed3si9n looks like M1 fixes our original problem! :+1:

Sadly I just remembered https://issues.scala-lang.org/browse/SI-8410 which is causing me pains now.

Thank you.

**Pull request merged**
