### PR TITLE
WIP Glob

### PR DESCRIPTION
**Pull request by eatkins**
- [ ] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md) guidelines

### CODE REVIEW

**Comment by eatkins** [comment]
This pr is dependent on a new io milestone release. I manually build io for travis builds, but not appveyor builds. Once we publish the io milestone, I'll remove 
https://github.com/sbt/sbt/pull/4495/commits/ee5289a6f6e6f68a8a87129e96571bd6a6582a86 and change the io version string in 
https://github.com/sbt/sbt/pull/4495/commits/ec10ba44deae30b8a9c1af33f75f9a82de900b61

**Comment by typesafe-tools** [comment]
A validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt-validator/1274/console">is in progress...</a>

**Comment by eed3si9n** [comment]
> I manually build io for travis builds, but not appveyor builds.

You can trigger Dbuild, and it'll do the same thing for you across multiple PRs.

**Comment by typesafe-tools** [comment]
[//]: # (Refs: pull/4495/head-develop-pull/216/head-develop-develop)
The validator <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/1274/">has checked</A> the following projects, tested using dbuild, projects built on top of each other.

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | <A HREF="https://github.com/sbt/sbt/pull/4495">pull/4495/head      </A> | sbt/sbt@144f216b7d049158507a6083c83fa135e12b6f12
  zinc              | <A HREF="https://github.com/sbt/zinc/tree/develop">develop             </A> | sbt/zinc@9bef954753a1ae033722d5bc9e89b945a9f2da3e
  io                | <A HREF="https://github.com/sbt/io/pull/216">pull/216/head       </A> | sbt/io@cc239c599c879dad4eb36564ea3560fcff9d5ce5
  librarymanagement | <A HREF="https://github.com/sbt/librarymanagement/tree/develop">develop             </A> | sbt/librarymanagement@91071253d98e66331a7821278444ebf41544da20
  util              | <A HREF="https://github.com/sbt/util/tree/develop">develop             </A> | sbt/util@2e0d2d920a9f11c1910f0a5d48a2ff6f2c57c44d

:white_check_mark: The result is: ***SUCCESS***
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild?sbt=pull/4495/head&zinc=develop&io=pull/216/head&librarymanagement=develop&util=develop&deploy_to_bintray=false&run_sbt_community=false">(restart)</A>

**Pull request closed without merging**
