### PR TITLE
0.13 branch: sbt 0.13.18, Scala 2.10.7

### PR DESCRIPTION
**Pull request by SethTisue**
this fixes the extraction error on JDK 11 seen at e.g.
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-jdk11-integrate-community-build/318/

### CODE REVIEW

**Review by eed3si9n — APPROVED** [review]

**Comment by SethTisue** [comment]
not sure what to make of the one CI failure:

```
[error] x tests / fork-parallel
[error]    {line 2}  Command succeeded but failure was expected
```

**Comment by eed3si9n** [comment]
I restarted the job. Let's see if it's a flaky test.

**Comment by eed3si9n** [comment]
`tests / fork-parallel` is failing, but I think that test has always been weird.
Given the state of 0.13, let's delete https://github.com/sbt/sbt/blob/0.13/sbt/src/sbt-test/tests/fork-parallel/.

**Comment by eed3si9n** [comment]
Thanks!

**Pull request merged**
