### PR TITLE
In-source the modules of sbt/util required in sbt/sbt

### PR DESCRIPTION
**Pull request by dwijnand**
Super-sedes #3290

The subset of sbt/util was prepared like this:

1) Move sbt.internal.util.HListFormats from util-cache to util-collection to break the dependency from cache to collection, so util-collection be moved here.
2) Break out sbt.util.ShowLines from util-collection to its own dependency, to break the dependency from util-logging to util-collection, and allow util-collection can be moved here.
3) Break out sbt.internal.util.Position from util-collection to its own dependency, to break the dependency of lm on util-collection, allowing util-collection to be moved here.

4) In a separate clone of sbt/util run git filter-branch:

```
git filter-branch -f --index-filter 'git rm --cached -qr -- . && git reset -q $GIT_COMMIT -- util/collection util/complete util/logic internal/util-collection internal/util-complete internal/util-logic' --prune-empty
git reset --hard && git gc --aggressive && git prune
```

5) Add that clone of sbt/util as a remote to your clone of sbt
6) Find the first proper commit in sbt/util, the one that says "move modules around" by eed3si9n
7) Label it with a temporary 'before-split' branch
8) Run git rebase --onto:

```
git rebase -p --onto consume-util before-split detangle
```

9) Configure the build

### CODE REVIEW

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild/?sbt=pull/3302/head&deploy_to_bintray=false">this link.</A>

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild/?sbt=pull/3302/head&deploy_to_bintray=false">this link.</A>

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild/?sbt=pull/3302/head&deploy_to_bintray=false">this link.</A>

**Comment by Duhemm** [comment]
What's the situation with sbt/util now?

**Comment by Duhemm** [comment]
@jvican told me it's dead.

How about the PRs that are open in sbt/util?

**Comment by dwijnand** [comment]
It's not dead. See https://github.com/sbt/util/issues/58#issuecomment-312242348.

**Pull request merged**
