### PR TITLE
Disable scripted tests that fail in CI

### LINKED ISSUE #3452: HEAD is broken on 1.x branch?
## steps

1. Will sent in PR for a typo change - https://github.com/sbt/sbt/pull/3450

## problem

The build fails - https://travis-ci.org/sbt/sbt/builds/264907233

- project / scripted13
- source-dependencies / repeated-parameters
- tests / fork-test-group-parallel

## expectation

HEAD passes

### PR DESCRIPTION
**Pull request by dwijnand**
Fixes #3452

### CODE REVIEW

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild/?sbt=pull/3456/head&deploy_to_bintray=false">this link.</A>

**Review by eed3si9n — APPROVED** [review]

**Comment by eed3si9n** [comment]
Once this merges, we should branch 1.0.x

**Comment by eed3si9n** [comment]
Tests are still failing.

```
[error] java.lang.RuntimeException: Failed tests:
[error] 	tests / t543
[error] 	tests / test-quick
```

I wonder if this has more to do with logging and other concurrency error, rather than tests per se.

**Comment by eed3si9n** [comment]
Let me rerun https://travis-ci.org/sbt/sbt/jobs/265143222.

**Comment by eed3si9n** [comment]
```
[error] java.lang.RuntimeException: Failed tests:
[error] 	tests / t543
```

That one failing again, but I can't reproduce it locally.

**Pull request merged**
