### PR TITLE
Watch improvements

### PR DESCRIPTION
**Pull request by eatkins**
(See the guidelines for contributing, linked above)

### CODE REVIEW

**Review by dwijnand — DISMISSED** [review]

**Comment by eatkins** [comment]
This PR was broken upstream. I'll have a fix up by tomorrow (along with a related io bugfix).

**Comment by eed3si9n** [comment]
I combined this PR with https://github.com/sbt/sbt/pull/4145 and added d8fe09f00776ad45d404fe0319df237bef8cc00f that tracks the rename upstream.

**Comment by eed3si9n** [comment]
@eatkins 

> (along with a related io bugfix).

Is that a show stopper? Should I hold off sbt 1.1.5?

**Comment by eatkins** [comment]
Yeah. Let me make a PR now. Won't be long.

**Comment by eatkins** [comment]
The bug I was referring to is arguably not show stopping, but it can make the ux annoying. It can cause the user to have to hit enter twice to exit a watched build see https://github.com/sbt/io/pull/149. Sorry I didn't make the PR earlier since fixing will require publishing another io version.

**Comment by eed3si9n** [comment]
ok. Thanks for following up.

**Pull request merged**
