### PR TITLE
bump sjson-new to latest

### PR DESCRIPTION
**Pull request by eed3si9n**
This is a ripple PR for https://github.com/sbt/util/pull/85

### CODE REVIEW

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild/?sbt=pull/3294/head&deploy_to_bintray=false">THIS LINK.</A>

**Comment by typesafe-tools** [comment]
A dbuild validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/39/console">is in progress...</a>

**Comment by typesafe-tools** [comment]
dbuild <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/39/">has checked</A> the following projects against Scala 2.12:

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | pull/3294/head       | sbt/sbt@6ae4cfb37a7e6a750b59b106aa6e4a116265be21
  zinc              | 1.0                  | sbt/zinc@866d9fdc89eaa3f412ea4f83052384e4f0f60a7d
  io                | 1.0                  | sbt/io@880de81bcc9bd4308885d2515d0a1b746026b946
  librarymanagement | pull/119/head        | sbt/librarymanagement@536077962e17b21927547f8c7afa83637a17d3ed
  util              | pull/85/head         | sbt/util@32d6bf38cf78e08316442159900d6135b8f417db
  website           | 1.0.x                | sbt/website@5c32a0afcf64dc600ff154f5456026e2a74dc668

:x: The result is: ***FAILED***

**Comment by typesafe-tools** [comment]
A dbuild validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/40/console">is in progress...</a>

**Comment by typesafe-tools** [comment]
dbuild <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/40/">has checked</A> the following projects against Scala 2.12:

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | pull/3294/head       | sbt/sbt@6ae4cfb37a7e6a750b59b106aa6e4a116265be21
  zinc              | pull/323/head        | sbt/zinc@6a6965b12b14c779bb8a6e0e3d6edd31610c259e
  io                | 1.0                  | sbt/io@880de81bcc9bd4308885d2515d0a1b746026b946
  librarymanagement | pull/119/head        | sbt/librarymanagement@536077962e17b21927547f8c7afa83637a17d3ed
  util              | pull/85/head         | sbt/util@32d6bf38cf78e08316442159900d6135b8f417db
  website           | 1.0.x                | sbt/website@5c32a0afcf64dc600ff154f5456026e2a74dc668

:x: The result is: ***FAILED***

**Comment by typesafe-tools** [comment]
A dbuild validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/41/console">is in progress...</a>

**Comment by typesafe-tools** [comment]
dbuild <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/41/">has checked</A> the following projects against Scala 2.12:

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | pull/3294/head       | sbt/sbt@6ae4cfb37a7e6a750b59b106aa6e4a116265be21
  zinc              | pull/323/head        | sbt/zinc@6a6965b12b14c779bb8a6e0e3d6edd31610c259e
  io                | 1.0                  | sbt/io@880de81bcc9bd4308885d2515d0a1b746026b946
  librarymanagement | pull/119/head        | sbt/librarymanagement@536077962e17b21927547f8c7afa83637a17d3ed
  util              | pull/85/head         | sbt/util@32d6bf38cf78e08316442159900d6135b8f417db
  website           | 1.0.x                | sbt/website@

:x: The result is: ***FAILED***

**Comment by typesafe-tools** [comment]
A dbuild validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/46/console">is in progress...</a>

**Comment by typesafe-tools** [comment]
[//]: # (Refs: pull/3294/head-pull/323/head-1.0-pull/85/head-pull/119/head-1.0.x)
dbuild <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/46/">has checked</A> the following projects against Scala 2.12:

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | pull/3294/head       | 
  zinc              | pull/323/head        | 
  io                | 1.0                  | 
  librarymanagement | pull/85/head         | 
  util              | pull/119/head        | 
  website           | 1.0.x                | 

:x: The result is: ***FAILED***

**Comment by typesafe-tools** [comment]
A dbuild validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/47/console">is in progress...</a>

**Comment by typesafe-tools** [comment]
[//]: # (Refs: pull/3294/head-pull/323/head-1.0-pull/119/head-pull/85/head-1.0.x)
dbuild <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/47/">has checked</A> the following projects against Scala 2.12:

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | pull/3294/head       | 
  zinc              | pull/323/head        | 
  io                | 1.0                  | 
  librarymanagement | pull/119/head        | 
  util              | pull/85/head         | 
  website           | 1.0.x                | 

:x: The result is: ***FAILED***
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/47/parambuild?sbt=pull/3294/head&zinc=pull/323/head&io=1.0&librarymanagement=pull/119/head&util=pull/85/head&website=1.0.x">(restart)</A>

**Comment by typesafe-tools** [comment]
A dbuild validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/48/console">is in progress...</a>

**Comment by typesafe-tools** [comment]
[//]: # (Refs: pull/3294/head-pull/323/head-1.0-pull/119/head-pull/85/head-1.0.x)
dbuild <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/48/">has checked</A> the following projects against Scala 2.12:

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | pull/3294/head       | 
  zinc              | pull/323/head        | 
  io                | 1.0                  | 
  librarymanagement | pull/119/head        | 
  util              | pull/85/head         | 
  website           | 1.0.x                | 

:x: The result is: ***FAILED***
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild?sbt=pull/3294/head&zinc=pull/323/head&io=1.0&librarymanagement=pull/119/head&util=pull/85/head&website=1.0.x&deploy_to_bintray=false">(restart)</A>

**Comment by typesafe-tools** [comment]
A dbuild validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/49/console">is in progress...</a>

**Comment by typesafe-tools** [comment]
A dbuild validation involving this pull request<a href="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/50/console">is in progress...</a>

**Comment by typesafe-tools** [comment]
[//]: # (Refs: pull/3294/head-pull/323/head-1.0-pull/119/head-pull/85/head-1.0.x)
dbuild <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/50/">has checked</A> the following projects against Scala 2.12:

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | pull/3294/head       | 
  zinc              | pull/323/head        | 
  io                | 1.0                  | 
  librarymanagement | pull/119/head        | 
  util              | pull/85/head         | 
  website           | 1.0.x                | 

:white_check_mark: The result is: ***SUCCESS***
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild?sbt=pull/3294/head&zinc=pull/323/head&io=1.0&librarymanagement=pull/119/head&util=pull/85/head&website=1.0.x&deploy_to_bintray=false">(restart)</A>

**Comment by typesafe-tools** [comment]
A dbuild validation involving this pull request<a href="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/51/console">is in progress...</a>

**Comment by typesafe-tools** [comment]
[//]: # (Refs: pull/3294/head-pull/323/head-1.0-pull/119/head-pull/85/head-1.0.x)
dbuild <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/51/">has checked</A> the following projects against Scala 2.12:

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | pull/3294/head       | 
  zinc              | pull/323/head        | 
  io                | 1.0                  | 
  librarymanagement | pull/119/head        | 
  util              | pull/85/head         | 
  website           | 1.0.x                | 

:x: The result is: ***FAILED***
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild?sbt=pull/3294/head&zinc=pull/323/head&io=1.0&librarymanagement=pull/119/head&util=pull/85/head&website=1.0.x&deploy_to_bintray=false">(restart)</A>

**Comment by typesafe-tools** [comment]
A dbuild validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/52/console">is in progress...</a>

**Comment by typesafe-tools** [comment]
[//]: # (Refs: pull/3294/head-pull/323/head-1.0-pull/119/head-pull/85/head-1.0.x)
dbuild <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/52/">has checked</A> the following projects against Scala 2.12:

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | pull/3294/head       | 
  zinc              | pull/323/head        | 
  io                | 1.0                  | 
  librarymanagement | pull/119/head        | 
  util              | pull/85/head         | 
  website           | 1.0.x                | 

:x: The result is: ***FAILED***
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild?sbt=pull/3294/head&zinc=pull/323/head&io=1.0&librarymanagement=pull/119/head&util=pull/85/head&website=1.0.x&deploy_to_bintray=false">(restart)</A>

**Comment by typesafe-tools** [comment]
A dbuild validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/53/console">is in progress...</a>

**Comment by typesafe-tools** [comment]
[//]: # (Refs: pull/3294/head-pull/323/head-1.0-pull/119/head-pull/85/head-1.0.x)
dbuild <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/53/">has checked</A> the following projects against Scala 2.12:

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | pull/3294/head       | 
  zinc              | pull/323/head        | 
  io                | 1.0                  | 
  librarymanagement | pull/119/head        | 
  util              | pull/85/head         | 
  website           | 1.0.x                | 

:x: The result is: ***FAILED***
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild?sbt=pull/3294/head&zinc=pull/323/head&io=1.0&librarymanagement=pull/119/head&util=pull/85/head&website=1.0.x&deploy_to_bintray=false">(restart)</A>

**Comment by typesafe-tools** [comment]
A dbuild validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/54/console">is in progress...</a>

**Comment by typesafe-tools** [comment]
[//]: # (Refs: pull/3294/head-pull/323/head-1.0-pull/119/head-pull/85/head-1.0.x)
dbuild <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/54/">has checked</A> the following projects against Scala 2.12:

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | pull/3294/head       | 
  zinc              | pull/323/head        | 
  io                | 1.0                  | 
  librarymanagement | pull/119/head        | 
  util              | pull/85/head         | 
  website           | 1.0.x                | 

:x: The result is: ***FAILED***
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild?sbt=pull/3294/head&zinc=pull/323/head&io=1.0&librarymanagement=pull/119/head&util=pull/85/head&website=1.0.x&deploy_to_bintray=false">(restart)</A>

**Comment by typesafe-tools** [comment]
A dbuild validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/55/console">is in progress...</a>

**Comment by typesafe-tools** [comment]
[//]: # (Refs: pull/3294/head-pull/323/head-1.0-pull/119/head-pull/85/head-1.0.x)
dbuild <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/55/">has checked</A> the following projects against Scala 2.12:

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | pull/3294/head       | 
  zinc              | pull/323/head        | 
  io                | 1.0                  | 
  librarymanagement | pull/119/head        | 
  util              | pull/85/head         | 
  website           | 1.0.x                | 

:x: The result is: ***FAILED***
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild?sbt=pull/3294/head&zinc=pull/323/head&io=1.0&librarymanagement=pull/119/head&util=pull/85/head&website=1.0.x&deploy_to_bintray=false">(restart)</A>

**Comment by typesafe-tools** [comment]
A dbuild validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/56/console">is in progress...</a>

**Comment by typesafe-tools** [comment]
[//]: # (Refs: pull/3294/head-pull/323/head-1.0-pull/119/head-pull/85/head-1.0.x)
dbuild <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/56/">has checked</A> the following projects against Scala 2.12:

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | pull/3294/head       | 
  zinc              | pull/323/head        | 
  io                | 1.0                  | 
  librarymanagement | pull/119/head        | 
  util              | pull/85/head         | 
  website           | 1.0.x                | 

:x: The result is: ***FAILED***
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild?sbt=pull/3294/head&zinc=pull/323/head&io=1.0&librarymanagement=pull/119/head&util=pull/85/head&website=1.0.x&deploy_to_bintray=false">(restart)</A>

**Comment by typesafe-tools** [comment]
A dbuild validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/57/console">is in progress...</a>

**Comment by typesafe-tools** [comment]
[//]: # (Refs: pull/3294/head-pull/323/head-1.0-pull/119/head-pull/85/head-1.0.x)
dbuild <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/57/">has checked</A> the following projects against Scala 2.12:

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | pull/3294/head       | 
  zinc              | pull/323/head        | 
  io                | 1.0                  | 
  librarymanagement | pull/119/head        | 
  util              | pull/85/head         | 
  website           | 1.0.x                | 

:x: The result is: ***FAILED***
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild?sbt=pull/3294/head&zinc=pull/323/head&io=1.0&librarymanagement=pull/119/head&util=pull/85/head&website=1.0.x&deploy_to_bintray=false">(restart)</A>

**Comment by typesafe-tools** [comment]
A dbuild validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/58/console">is in progress...</a>

**Comment by typesafe-tools** [comment]
[//]: # (Refs: pull/3294/head-pull/323/head-1.0-pull/119/head-pull/85/head-1.0.x)
dbuild <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/58/">has checked</A> the following projects against Scala 2.12:

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | pull/3294/head       | 
  zinc              | pull/323/head        | 
  io                | 1.0                  | 
  librarymanagement | pull/119/head        | 
  util              | pull/85/head         | 
  website           | 1.0.x                | 

:x: The result is: ***FAILED***
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild?sbt=pull/3294/head&zinc=pull/323/head&io=1.0&librarymanagement=pull/119/head&util=pull/85/head&website=1.0.x&deploy_to_bintray=false">(restart)</A>

**Comment by typesafe-tools** [comment]
A dbuild validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/59/console">is in progress...</a>

**Comment by typesafe-tools** [comment]
[//]: # (Refs: pull/3294/head-pull/323/head-1.0-pull/119/head-pull/85/head-1.0.x)
dbuild <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/59/">has checked</A> the following projects against Scala 2.12:

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | pull/3294/head       | sbt/sbt@6ae4cfb37a7e6a750b59b106aa6e4a116265be21
  zinc              | pull/323/head        | sbt/zinc@6a6965b12b14c779bb8a6e0e3d6edd31610c259e
  io                | 1.0                  | sbt/io@880de81bcc9bd4308885d2515d0a1b746026b946
  librarymanagement | pull/119/head        | sbt/librarymanagement@536077962e17b21927547f8c7afa83637a17d3ed
  util              | pull/85/head         | sbt/util@32d6bf38cf78e08316442159900d6135b8f417db
  website           | 1.0.x                | sbt/website@5c32a0afcf64dc600ff154f5456026e2a74dc668

:x: The result is: ***FAILED***
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild?sbt=pull/3294/head&zinc=pull/323/head&io=1.0&librarymanagement=pull/119/head&util=pull/85/head&website=1.0.x&deploy_to_bintray=false">(restart)</A>

**Comment by typesafe-tools** [comment]
A dbuild validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/62/console">is in progress...</a>

**Comment by typesafe-tools** [comment]
[//]: # (Refs: pull/3294/head-pull/323/head-1.0-pull/119/head-pull/85/head-1.0.x)
dbuild <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/62/">has checked</A> the following projects against Scala 2.12:

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | pull/3294/head       | sbt/sbt@6ae4cfb37a7e6a750b59b106aa6e4a116265be21
  zinc              | pull/323/head        | sbt/zinc@6a6965b12b14c779bb8a6e0e3d6edd31610c259e
  io                | 1.0                  | sbt/io@880de81bcc9bd4308885d2515d0a1b746026b946
  librarymanagement | pull/119/head        | sbt/librarymanagement@536077962e17b21927547f8c7afa83637a17d3ed
  util              | pull/85/head         | sbt/util@32d6bf38cf78e08316442159900d6135b8f417db
  website           | 1.0.x                | sbt/website@5c32a0afcf64dc600ff154f5456026e2a74dc668

:x: The result is: ***FAILED***
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild?sbt=pull/3294/head&zinc=pull/323/head&io=1.0&librarymanagement=pull/119/head&util=pull/85/head&website=1.0.x&deploy_to_bintray=false">(restart)</A>

**Comment by typesafe-tools** [comment]
A dbuild validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/63/console">is in progress...</a>

**Comment by typesafe-tools** [comment]
A dbuild validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/64/console">is in progress...</a>

**Comment by typesafe-tools** [comment]
[//]: # (Refs: pull/3294/head-pull/323/head-1.0-pull/119/head-pull/85/head-1.0.x)
dbuild <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/64/">has checked</A> the following projects against Scala 2.12:

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | pull/3294/head       | sbt/sbt@6ae4cfb37a7e6a750b59b106aa6e4a116265be21
  zinc              | pull/323/head        | sbt/zinc@6a6965b12b14c779bb8a6e0e3d6edd31610c259e
  io                | 1.0                  | sbt/io@880de81bcc9bd4308885d2515d0a1b746026b946
  librarymanagement | pull/119/head        | sbt/librarymanagement@536077962e17b21927547f8c7afa83637a17d3ed
  util              | pull/85/head         | sbt/util@32d6bf38cf78e08316442159900d6135b8f417db
  website           | 1.0.x                | sbt/website@5c32a0afcf64dc600ff154f5456026e2a74dc668

:white_check_mark: The result is: ***SUCCESS***
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild?sbt=pull/3294/head&zinc=pull/323/head&io=1.0&librarymanagement=pull/119/head&util=pull/85/head&website=1.0.x&deploy_to_bintray=false">(restart)</A>

**Comment by dwijnand** [comment]
Superseded by #3303 (found out the hard way: I was trying to rebase and fix this..)

**Pull request closed without merging**
