### PR TITLE
Don't include current ref in inter project dependencies

### LINKED ISSUE #4995: doc task fails with java.lang.NoClassDefFoundError: scala/xml/NodeSeq
_Originally posted by @xuwei-k in https://github.com/scala/scala-xml/pull/348#issuecomment-525703962_

## steps

In scala/scala-xml using sbt 1.3.0-RC4

`sbt ++2.12.9 doc`

## problems

https://travis-ci.org/scala/scala-xml/jobs/577682776#L485

```
model contains 132 documentable templates
[error] java.lang.NoClassDefFoundError: scala/xml/NodeSeq
[error] 	at scala.tools.nsc.doc.html.HtmlFactory.writeTemplates(HtmlFactory.scala:168)
[error] 	at scala.tools.nsc.doc.html.HtmlFactory.generate(HtmlFactory.scala:156)
[error] 	at scala.tools.nsc.doc.html.Doclet.generateImpl(Doclet.scala:30)
[error] 	at scala.tools.nsc.doc.doclet.Generator.generate(Generator.scala:35)
[error] 	at scala.tools.nsc.doc.DocFactory.generate$1(DocFactory.scala:135)
[error] 	at scala.tools.nsc.doc.DocFactory.document(DocFactory.scala:138)
[error] 	at xsbt.Runner.run(ScaladocInterface.scala:34)
[error] 	at xsbt.ScaladocInterface.run(ScaladocInterface.scala:19)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:498)
[error] 	at sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:248)
[error] 	at sbt.internal.inc.AnalyzingCompiler.doc(AnalyzingCompiler.scala:177)
[error] 	at sbt.internal.inc.AnalyzingCompiler.doc(AnalyzingCompiler.scala:158)
[error] 	at sbt.Doc$.$anonfun$scaladoc$1(Doc.scala:39)
[error] 	at sbt.Doc$.$anonfun$scaladoc$1$adapted(Doc.scala:39)
[error] 	at sbt.RawCompileLike$.$anonfun$prepare$1(RawCompileLike.scala:83)
[error] 	at sbt.RawCompileLike$.$anonfun$prepare$1$adapted(RawCompileLike.scala:76)
[error] 	at sbt.RawCompileLike$.$anonfun$cached$3(RawCompileLike.scala:67)
[error] 	at sbt.RawCompileLike$.$anonfun$cached$3$adapted(RawCompileLike.scala:65)
[error] 	at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:150)
[error] 	at sbt.RawCompileLike$.$anonfun$cached$1(RawCompileLike.scala:72)
[error] 	at sbt.RawCompileLike$.$anonfun$cached$1$adapted(RawCompileLike.scala:55)
[error] 	at sbt.Defaults$.$anonfun$docTaskSettings$3(Defaults.scala:1588)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:280)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.Execute.work(Execute.scala:289)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:280)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] Caused by: java.lang.ClassNotFoundException: scala.xml.NodeSeq
[error] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[error] 	at scala.tools.nsc.doc.html.HtmlFactory.writeTemplates(HtmlFactory.scala:168)
[error] 	at scala.tools.nsc.doc.html.HtmlFactory.generate(HtmlFactory.scala:156)
[error] 	at scala.tools.nsc.doc.html.Doclet.generateImpl(Doclet.scala:30)
[error] 	at scala.tools.nsc.doc.doclet.Generator.generate(Generator.scala:35)
[error] 	at scala.tools.nsc.doc.DocFactory.generate$1(DocFactory.scala:135)
[error] 	at scala.tools.nsc.doc.DocFactory.document(DocFactory.scala:138)
[error] 	at xsbt.Runner.run(ScaladocInterface.scala:34)
[error] 	at xsbt.ScaladocInterface.run(ScaladocInterface.scala:19)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:498)
[error] 	at sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:248)
[error] 	at sbt.internal.inc.AnalyzingCompiler.doc(AnalyzingCompiler.scala:177)
[error] 	at sbt.internal.inc.AnalyzingCompiler.doc(AnalyzingCompiler.scala:158)
[error] 	at sbt.Doc$.$anonfun$scaladoc$1(Doc.scala:39)
[error] 	at sbt.Doc$.$anonfun$scaladoc$1$adapted(Doc.scala:39)
[error] 	at sbt.RawCompileLike$.$anonfun$prepare$1(RawCompileLike.scala:83)
[error] 	at sbt.RawCompileLike$.$anonfun$prepare$1$adapted(RawCompileLike.scala:76)
[error] 	at sbt.RawCompileLike$.$anonfun$cached$3(RawCompileLike.scala:67)
[error] 	at sbt.RawCompileLike$.$anonfun$cached$3$adapted(RawCompileLike.scala:65)
[error] 	at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:150)
[error] 	at sbt.RawCompileLike$.$anonfun$cached$1(RawCompileLike.scala:72)
[error] 	at sbt.RawCompileLike$.$anonfun$cached$1$adapted(RawCompileLike.scala:55)
[error] 	at sbt.Defaults$.$anonfun$docTaskSettings$3(Defaults.scala:1588)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:280)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.Execute.work(Execute.scala:289)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:280)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (xml / Compile / doc) java.lang.NoClassDefFoundError: scala/xml/NodeSeq
```

`sbt ++2.12.9 doc` fail with sbt 1.3.0-RC4. (success with sbt 1.3.0-RC3)

## expectation

It should work.

## notes by eed3si9n

Also reported as https://github.com/coursier/coursier/issues/1340 to upstream

### PR DESCRIPTION
**Pull request by eatkins**
Fixes https://github.com/sbt/sbt/issues/4995. I tracked the doc failures
to 777cc39fcf49a4b8d19214207451d1d02f153ab3. I'm not sure why
projectRef was added to the scope filter in that commit, but removing it
fixes the doc issue.

### CODE REVIEW

**Review by eed3si9n — COMMENTED** [review]
> I'm not sure why projectRef was added to the scope filter in that commit

That's what I said in https://github.com/coursier/sbt-coursier/pull/101/files#r312687891 too.
It might be good to validate https://github.com/coursier/coursier/issues/1181 if that's not already in scripted.

**Comment by eatkins** [comment]
I think this might be bad. Some of the dependency management scripted tests fail.

**Comment by eatkins** [comment]
So if we don't include projectRef, doc works but a bunch of scripted tests fail. If we do include it, then doc breaks and the scripted tests pass.

**Comment by eatkins** [comment]
Closing this since it looks like it's going to need some Coursier work to fix.

**Pull request closed without merging**
