### PR TITLE
Fix Zinc component compiler to respect -Dsbt.ivy.home

### PR DESCRIPTION
**Pull request by eed3si9n**
This is currently blocking the new nightly process.

### CODE REVIEW

**Comment by typesafe-tools** [comment]
A validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt-validator/1898/console">is in progress...</a>

**Comment by typesafe-tools** [comment]
[//]: # (Refs: pull/5345/head-develop-develop-develop-develop)
The validator <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/1898/">has checked</A> the following projects, tested using sources.sh.

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | <A HREF="https://github.com/sbt/sbt/pull/5345">pull/5345/head      </A> | sbt/sbt@ef7c3cabb68deacf21ca46f31c6661287d42d640
  zinc              | <A HREF="https://github.com/sbt/zinc/tree/develop">develop             </A> | sbt/zinc@a9fd8fcb3c28ca06f46009a7f15f68e7a19ed929
  io                | <A HREF="https://github.com/sbt/io/tree/develop">develop             </A> | sbt/io@d3297b56297a524baf5982661170edfdb8a6823e
  librarymanagement | <A HREF="https://github.com/sbt/librarymanagement/tree/develop">develop             </A> | sbt/librarymanagement@f8a83710572394cffdb5fa0af7fd5fbd85e8af16
  util              | <A HREF="https://github.com/sbt/util/tree/develop">develop             </A> | sbt/util@098796cdff7305a4aaadea9fdbba7fb6c23ff3ed

:x: The result is: ***FAILED***
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild?sbt=pull/5345/head&zinc=develop&io=develop&librarymanagement=develop&util=develop&deploy_to_bintray=false&run_sbt_community=false">(restart)</A>

**Comment by typesafe-tools** [comment]
A validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt-validator/1899/console">is in progress...</a>

**Comment by typesafe-tools** [comment]
[//]: # (Refs: pull/5345/head-develop-develop-develop-develop)
The validator <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/1899/">has checked</A> the following projects, tested using sources.sh.

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | <A HREF="https://github.com/sbt/sbt/pull/5345">pull/5345/head      </A> | sbt/sbt@f5090cf70f97fa5d761976d2e7968967b8e624bb
  zinc              | <A HREF="https://github.com/sbt/zinc/tree/develop">develop             </A> | sbt/zinc@a9fd8fcb3c28ca06f46009a7f15f68e7a19ed929
  io                | <A HREF="https://github.com/sbt/io/tree/develop">develop             </A> | sbt/io@d3297b56297a524baf5982661170edfdb8a6823e
  librarymanagement | <A HREF="https://github.com/sbt/librarymanagement/tree/develop">develop             </A> | sbt/librarymanagement@f8a83710572394cffdb5fa0af7fd5fbd85e8af16
  util              | <A HREF="https://github.com/sbt/util/tree/develop">develop             </A> | sbt/util@098796cdff7305a4aaadea9fdbba7fb6c23ff3ed

:x: The result is: ***FAILED***
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild?sbt=pull/5345/head&zinc=develop&io=develop&librarymanagement=develop&util=develop&deploy_to_bintray=false&run_sbt_community=false">(restart)</A>

**Comment by eed3si9n** [comment]
Looks like component compiler got fixed, but there's a similar bug for server test.

**Comment by eed3si9n** [comment]
```
[warn] 
[warn] 	Note: Unresolved dependencies path:
[error] sbt.librarymanagement.ResolveException: Error downloading org.scala-sbt:sbt:1.4.0-SNAPSHOT
[error]   Not found
[error]   Not found
[error]   not found: /home/jenkinssbt/.ivy2/local/org.scala-sbt/sbt/1.4.0-SNAPSHOT/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/org/scala-sbt/sbt/1.4.0-SNAPSHOT/sbt-1.4.0-SNAPSHOT.pom
[error]   not found: https://repo.scala-sbt.org/scalasbt/maven-snapshots/org/scala-sbt/sbt/1.4.0-SNAPSHOT/sbt-1.4.0-SNAPSHOT.pom
[error]   not found: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.scala-sbt/sbt/1.4.0-SNAPSHOT/ivys/ivy.xml
[error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt/1.4.0-SNAPSHOT/ivys/ivy.xml
[error] 	at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:245)
[error] 	at lmcoursier.CoursierDependencyResolution.$anonfun$update$34(CoursierDependencyResolution.scala:214)
[error] 	at scala.util.Either$LeftProjection.map(Either.scala:573)
[error] 	at lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:214)
[error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:60)
[error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:52)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:102)
[error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:73)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:115)
[error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:228)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:115)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:96)
[error] 	at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:154)
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:129)
[error] 	at sbt.Classpaths$.$anonfun$updateTask0$5(Defaults.scala:2966)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:184)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (update) sbt.librarymanagement.ResolveException: Error downloading org.scala-sbt:sbt:1.4.0-SNAPSHOT
```

**Comment by typesafe-tools** [comment]
A validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt-validator/1900/console">is in progress...</a>

**Comment by eed3si9n** [comment]
```
[error] (update) sbt.librarymanagement.ResolveException: Error downloading org.scala-sbt:sbt:1.4.0-SNAPSHOT
[error]   Not found
[error]   Not found
[error]   not found: /home/jenkinssbt/.ivy2/local/org.scala-sbt/sbt/1.4.0-SNAPSHOT/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/org/scala-sbt/sbt/1.4.0-SNAPSHOT/sbt-1.4.0-SNAPSHOT.pom
[error]   not found: https://repo.scala-sbt.org/scalasbt/maven-snapshots/org/scala-sbt/sbt/1.4.0-SNAPSHOT/sbt-1.4.0-SNAPSHOT.pom
[error]   not found: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.scala-sbt/sbt/1.4.0-SNAPSHOT/ivys/ivy.xml
[error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt/1.4.0-SNAPSHOT/ivys/ivy.xml
```

That didn't seem to work.

**Comment by typesafe-tools** [comment]
A validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt-validator/1901/console">is in progress...</a>

**Comment by typesafe-tools** [comment]
[//]: # (Refs: pull/5345/head-develop-develop-develop-develop)
The validator <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/1901/">has checked</A> the following projects, tested using sources.sh.

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | <A HREF="https://github.com/sbt/sbt/pull/5345">pull/5345/head      </A> | sbt/sbt@4d8c8b8e34efa054ea7ede765201cf4ef52a7ebf
  zinc              | <A HREF="https://github.com/sbt/zinc/tree/develop">develop             </A> | sbt/zinc@a9fd8fcb3c28ca06f46009a7f15f68e7a19ed929
  io                | <A HREF="https://github.com/sbt/io/tree/develop">develop             </A> | sbt/io@d3297b56297a524baf5982661170edfdb8a6823e
  librarymanagement | <A HREF="https://github.com/sbt/librarymanagement/tree/develop">develop             </A> | sbt/librarymanagement@f8a83710572394cffdb5fa0af7fd5fbd85e8af16
  util              | <A HREF="https://github.com/sbt/util/tree/develop">develop             </A> | sbt/util@098796cdff7305a4aaadea9fdbba7fb6c23ff3ed

:x: The result is: ***FAILED***
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild?sbt=pull/5345/head&zinc=develop&io=develop&librarymanagement=develop&util=develop&deploy_to_bintray=false&run_sbt_community=false">(restart)</A>

**Pull request merged**
