### PR TITLE
Overwrite previous setting if possible.

### PR DESCRIPTION
**Pull request by vigdorchik**
I'd love to provide tests for this functionality if I'm given guidelines.

### CODE REVIEW

**Comment by harrah** [comment]
1. This only overwrites the last applicable setting (by design).  I'm not sure whether this is the best default, but at least it seems reasonable to me.  It looks easy enough to switch this behavior with a flag on writeSettings/saveSomeSettings, though.  It doesn't need to be accessible through the command line, but it will be useful for programmatic clients.
2. Shadowing in appended settings is correctly resolved.  This is good.
3. It correctly handles settings that depend on the previous value.  Good.
4. Doesn't handle multi-line settings correctly.  This is why we need the end position in SourcePos.

For testing, start with integration tests.  There are ScalaCheck generators in `main/src/test/scala/` used to test the scope key parser combinators that could possibly be used for testing this.

**Comment by vigdorchik** [comment]
I would change SessionSetting to keep the list of lines rather than the text. @harrah What do you think?

**Comment by harrah** [comment]
What is the advantage of doing so?

**Comment by vigdorchik** [comment]
On Tue, Feb 21, 2012 at 2:48 AM, Mark Harrah
reply@reply.github.com
wrote:

**Comment by harrah** [comment]
Can you clarify why the range positions aren't sufficient?

**Comment by vigdorchik** [comment]
@harrah It is sufficient. The code that is in works (I'm going to add tests, but otherwise feel free to review). It could be just made cleaner if I didn't have to split the new text into lines twice: first time to get the actual lines to write, second to calculate the positions. I understand this is an implementation detail, so not a big deal.

**Comment by vigdorchik** [comment]
@harrah I spent some time trying to understand the generators in main/src/test and see if I can use them to test correctly saving session settings. I must admit I'm not fully comfortable with the generators, and it looks I will need way more time to get into it than the actual benefit we could gain from having integration tests. So having tested the functionality manually, I think that might be enough to merge this pull request.

**Comment by harrah** [comment]
Ok, how about scripted tests at least?

**Comment by vigdorchik** [comment]
@harrah Yes, I can provide scripted test, but it will only test that setting produced with a session is actually written, but it can't validate it overwrites the previous value, since scripted framework can't diff files. I doubt such tests are useful. Maybe add a scripted command that checks for contents of 2 files being identical?

**Comment by harrah** [comment]
Right, I know you can't verify it was overwritten using the current scripted commands.  There are other properties we want to test, like ensuring that the generated settings file is valid, other settings aren't messed up (like in the multi-line case), and the new value is indeed written.  I think adding a file comparison command and using that for testing 'set' would be useful.

**Pull request merged**
