### PR TITLE
Introduce incremental compiler options.

### PR DESCRIPTION
**Pull request by gkossakowski**
Introduce a way to configure incremental compiler itself instead
of underlying Java/Scala compiler.

Check 9cfbeb5 for details.

NOTE: This is API breaking change that is likely to affect both zinc and Eclipse IDE so CCing @dragos and @pvlugter. The fix should be very easy as I provide the right defaults. See `sbt.inc.IncOptions.Default`.

### CODE REVIEW

**Comment by gkossakowski** [comment]
@harrah: this is cleaned up version of what I presented some time ago. It doesn't introduce any changes to behavior so it should be safe to merge. I'd like to get feedback on this relatively quickly if possible because all other pull requests I have in a queue depends on this.

**Comment by gkossakowski** [comment]
@harrah: sorry for long overdue. I had lots of distractions recently. I squashed two commits and removed string duplication as requested. Let me know what you think now.

**Comment by harrah** [comment]
`recompileAllFraction` and `transitiveStep` from the new options data structure should replace the existing constants, right?

**Comment by gkossakowski** [comment]
@harrah: I was planning to submit bigger refactorings (that use `apiDebug` option) later on but for those two are easy enough that I can submit in this PR. Commit attached.

**Comment by harrah** [comment]
Merged in f3d2df0f9cd0acd6edeed9fed35c6c05195f23f6.

**Pull request closed without merging**
