### PR TITLE
Make analysis file portable.

### PR DESCRIPTION
**Pull request by benjyw**
Serializes CompileSetup as text instead of base64-encoded
binary-serialized object.

This is necessary so that file paths in the CompileSetup can be
rebased when porting analysis files between systems.

### CODE REVIEW

**Comment by gkossakowski** [comment]
LGTM.

Thanks!

**Comment by jsuereth** [comment]
Is there something issing from here?  I'm getting this now when compiling:

```
[error] /home/jsuereth/projects/sbt/sbt/compile/persist/src/main/scala/sbt/inc/TextAnalysisFormat.scala:360: overriding method outputGroups in trait MultipleOutput of type ()Array[xsbti.compile.MultipleOutput.OutputGroup];
[error]  value outputGroups has incompatible type
[error]                         val outputGroups = outputAsMap.toArray.map {
[error]                             ^
```

**Comment by benjyw** [comment]
taking a look

**Comment by jsuereth** [comment]
If you add the type annotation on that line, it succeeds.   Seems like an odd "inferred something more specific" issue where Scala's bytecode would use Object because the type is a crazy `AnyRef with XYZ with { random methods}`.   I've started noticing this issue in Scala 2.10.3 but haven't been able to isolate it.    (@retronym does this sound familiar?  I'm not in tune with the ticket DB).

**Comment by benjyw** [comment]
Can you fix directly, so it doesn't have to go through a pull request from
me? Or would you rather have the pull request?

**Comment by jsuereth** [comment]
Doesn't matter. I think I'll issue a quick fix to unblock everyone.

**Comment by jsuereth** [comment]
done.

**Pull request merged**
