### PR TITLE
Add support for common project information (description, homepage, licenses)

### PR DESCRIPTION
**Pull request by indrajitr**
This patch adds support for basic project info related properties, viz., description, homepage and licenses.

Adding these properties would enhance the generated Ivy and Maven descriptors out of the box. Most projects (including Scala library) would want to use these anyway. From SBT's point of view these are merely cosmetic and doesn't affect regular operation in anyway.

So, if the overall intention of SBT is to keep the <info/> minimal by default, this isn't necessary. A project can conveniently, add these either by using a custom ivyXML or pomExtra.

But if this is something of interest, we can use these stuff in other places as well (e.g., MANIFEST.MF).

### CODE REVIEW

**Comment by ijuma** [comment]
Seems useful. What about other things that Maven has support for like source repository location and such?

**Comment by harrah** [comment]
There is no fundamental reason for these not existing and I would be happy to have a pull request for using this information in the manifest.

Two things.  First, the keys should go in the global scope.  This way, a user can override them at the build level and have them apply to all projects.  Second, I think I'd prefer seeing this information, which is non-essential for resolution, be passed directly in InlineConfiguration and EmptyConfiguration as a ModuleInfo type instead of with ModuleID.  It is a bit more work, but I think the right way.  Thoughts?

**Comment by indrajitr** [comment]
Ismael,
My initial intention was to have the 'common denominator' in place, that is:
- More detailed <info/> block as available in [Ivy config](http://ant.apache.org/ivy/history/latest-milestone/ivyfile/info.html) so that basic stuff are available for free
- More detailed MANIFEST.MF (for example to include organization full name, URL etc.)
- Grab those details within the default pom that is generated

That said, if there is enough interest in creating full blown pom out of the box, there is no reason for not to do it. Just that, not all of them would happen via the Ivy XML route (Ivy XML schema doesn't have these mappings). We would have to do it via MakePom directly. In any case, there is always a pomExtra to fall back to.

**Comment by ijuma** [comment]
Fair enough.

**Comment by indrajitr** [comment]
Mark,

Indeed, homepage and licenses should go in global scope - would do. But for description, shouldn't it be in the same scope as the name?

Frankly, I was hesitant in stashing them within ModuleID (which represents Ivy module nicely) and these properties aren't strictly part of that. But still went ahead because (a) this approach had least impact (small diff) and (b) I wasn't sure about a good alternative place :-P

But I take the point. Please defer applying this patch, I'll send out an updated stuff later in the week.

**Comment by harrah** [comment]
Right, sorry, 'description' as you have it is good.

It sounds like the direction you want to go with this is good, both initially and then more detailed.  Looking forward to it!

**Comment by indrajitr** [comment]
Few additional things apart from what is mentioned in the commit log:

InlineConfiguration and EmptyConfiguration signature has changed here. This means, all the related public APIs should also go through signature change. Since plugins are quite likely to break because of this, I have avoided doing that where ever I could (e.g., transitiveScratch, updateClassifiers; in these cases, ModuleInfo has
limited significance anyway). But in other cases, there are some breakage. Any thought on this?

This doesn't have MANIEFEST.MF related changes. That can go in after things are streamlined for this one.

**Comment by harrah** [comment]
Don't worry about the signature changes.  They are minor, in the more advanced part, and there is a good chance the next release will be 0.11, allowing such minor changes.

Two comments:
1. I'd prefer the `<info .../>` stay in a separate defaultInfo method.
2. It looks like the common code between newConfiguredModuleID and configureEmpty can be factored out.  Do you see a reason not to?

GitHub says I can't automatically merge this.  Perhaps it needs to be rebased against the latest?

**Comment by indrajitr** [comment]
> 1. I'd prefer the `<info .../>` stay in a separate defaultInfo method

I had revoked changes in that region to align with origin/0.10 since direct `<info .../>` preparation doesn't happen anymore. Have added `defaultInfo` back now.

> 1. It looks like the common code between newConfiguredModuleID and configureEmpty can be factored out. Do you see a reason not to?

Indeed, refactored 'em :)

> GitHub says I can't automatically merge this. Perhaps it needs to be rebased against the latest?

Yes, rebase is in order. Done.

**Comment by harrah** [comment]
Ok, sorry, one more thing.  Can you rebase -i and squash the commits together?  It would be best not to have the intermediate commits.

**Comment by indrajitr** [comment]
Makes sense. Done

**Pull request merged**
