### PR TITLE
Sbt server could miss some messages

### PR DESCRIPTION
**Pull request by guillaumebort**
If the read buffer contains more than 2 messages, we need to consume them all before blocking on socket read again. For that we have to loop until the buffer does not contain anymore the message delimiter character.

Same problem in the client ServerConnection code.

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @guillaumebort,

Thank you for your contribution! We really value the time you've taken to put this together.

We see that you have signed the Lightbend Contributors License Agreement before, however, the CLA has changed since you last signed it.
Please review the new CLA and sign it before we proceed with reviewing this pull request:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild/?sbt=pull/3523/head&deploy_to_bintray=false&run_sbt_community=false">this link.</A>

**Comment by guillaumebort** [comment]
Are the tests flakeys or do you think there is a real problem? The reported error seems totally unrelated.

**Comment by dwijnand** [comment]
I just merged https://github.com/sbt/sbt/pull/3522, do you want to try rebasing on latest 1.0.x to see if it goes green?

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild/?sbt=pull/3523/head&deploy_to_bintray=false&run_sbt_community=false">this link.</A>

**Comment by guillaumebort** [comment]
Ok retrying now :)

**Comment by guillaumebort** [comment]
Still one failure :(

**Review by eed3si9n — APPROVED** [review]

**Comment by eed3si9n** [comment]
Thanks for this contribution.

**Pull request merged**
