### PR TITLE
(Don't merge yet) Revert 4605802

### LINKED ISSUE #2411: [0.13.10] unexpected java.lang.NoSuchFieldError when use nested case class
`project/build.properties`

```
sbt.version=0.13.10-RC1
```

`A.scala`

``` scala
package example

class A {
  case class B(x: Int)

  def c = B
}

object A {
  def main(args: Array[String]): Unit = {
    (new A).c
  }
}
```

result

```
[error] (run-main-15) java.lang.NoSuchFieldError: B$module
java.lang.NoSuchFieldError: B$module
        at example.A.B(A.scala:4)
        at example.A.c(A.scala:6)
        at example.A$.main(A.scala:11)
        at example.A.main(A.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
[trace] Stack trace suppressed: run last compile:run for the full output.
java.lang.RuntimeException: Nonzero exit code: 1
        at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last compile:run for the full output.
[error] (compile:run) Nonzero exit code: 1
```

There is same problem in playframework, scalikejdbc, skinny-framework, cats.
- https://travis-ci.org/xuwei-k/Play20/jobs/104261656#L497
- https://travis-ci.org/xuwei-k/scalikejdbc/jobs/104293183#L1193
- https://travis-ci.org/seratch/skinny-framework/jobs/104275385#L2107
- https://travis-ci.org/xuwei-k/cats/jobs/104294044#L2702

### PR DESCRIPTION
**Pull request by eed3si9n**
Revert 4605802. Fixes #2411. Ref #1171

/review @Duhemm, @dwijnand

### CODE REVIEW

**Comment by dwijnand** [comment]
Sad days. LGTM.

**Comment by smarter** [comment]
After applying https://github.com/sbt/sbt/pull/2414, the test case in  https://github.com/eed3si9n/sbt/commit/1f25cdf0cdc5f0e47464a1f8b4541da87aca0889 compiles and run successfully, however I was able to reproduce the problem by changing the testcase to involve a derived value class:

``` scala
package example

class VC(val self: Int) extends AnyVal

class A {
  case class B(x: VC)
  def c = B
}
object A {
  def main(args: Array[String]): Unit = {
    (new A).c
  }
}
```

I suggest using this as a testcase instead. I can't help with the actual bug but my guess is that it has something to do with `exitingPostErasure` and https://github.com/scala/scala/commit/6dd149505d6782d35655cfd76e573e7fbeaecb77 might help, cc @adriaanm

**Comment by Duhemm** [comment]
It looks like using the changes in https://github.com/scala/scala/commit/6dd149505d6782d35655cfd76e573e7fbeaecb77 fixes the issue for both test cases in this ticket. Do we want to revert #2261 altogether or apply the fix by @adriaanm?

I created a branch with the test cases and the fix by @adriaanm:  https://github.com/sbt/sbt/compare/0.13...Duhemm:fix-2411

**Comment by eed3si9n** [comment]
@Duhemm  If you can fix this, I am ok with keeping this feature. Could you test with the projects mentioned by the original tickets:

https://travis-ci.org/xuwei-k/Play20/jobs/104261656#L497
https://travis-ci.org/xuwei-k/scalikejdbc/jobs/104293183#L1193
https://travis-ci.org/seratch/skinny-framework/jobs/104275385#L2107
https://travis-ci.org/xuwei-k/cats/jobs/104294044#L2702

**Comment by Duhemm** [comment]
@eed3si9n Of course.

**Comment by dwijnand** [comment]
If possible please forward fix. Reverts are more work in this forward-porting, multi-repo world.

**Comment by eed3si9n** [comment]
Closing this in favor of #2418

**Pull request closed without merging**
