### PR TITLE
allow more than one level of incremental compilation for less aggressive compilation

### PR DESCRIPTION
**Pull request by kevinder**
this change helps speed up compilation for expensive cases. on my codebase of ~600 files, changing a file's API will usually cause most of the files to be recompiled, which can take ~3-4 minutes. setting maxCycles to a value 2 or greater helps cut down compile times to 20-30 seconds in most cases.

maxCycles setting can probably be moved to a Key, but i used a system property for development speed reasons. the default value of 1 maintains the current behavior.

### CODE REVIEW

**Comment by kevinder** [comment]
sorry the end of the title should be "less aggressive invalidation"

**Comment by harrah** [comment]
I will try to look at this in the next few days, hopefully.  If I remember correctly, parts of the incremental compilation assume only two stages for correctness.  As you can see, though, it was designed to make it easy to have multiple stages and this was planned to happen eventually.

The main drawback with multiple stages is that there is extra overhead when the extra stages are needed and that spurious errors that wouldn't exist in a clean build can be more common.

Regardless, I'll merge it if you can make it configurable through a standard sbt setting.  This is a bit more invasive, but I think it is more appropriate.

**Comment by harrah** [comment]
This can go in if it is configurable as a setting.  If it this is done within the next week, it can go into 0.11.1, otherwise it can go into the release after it is implemented.

**Comment by kevinder** [comment]
hi mark, i looked into moving maxCycles to a Keys setting. it appears that because /compile is a subproject, it cannot access sbt.Keys directly. i looked into threading it through, and the entry point is IncrementalCompile.apply(). none of the arguments are settings or configuration options though, so it was unclear where to add it. is there a best practice for passing a SettingKey through? thanks.

**Comment by harrah** [comment]
Right, you want to configure maxCycles in Keys.scala and Defaults.scala.  Then, in Defaults.scala, pull the value of maxCycles in the compileInputs task and pass the value through, not the key.

**Comment by gnprice** [comment]
Mark, can you elaborate on how this can lead to spurious errors that wouldn't exist in a clean build?

Unless there are dependencies sbt doesn't know about (can that happen?), we still always recompile a file if one of its dependencies' APIs changes.

On the converse side... I guess I don't see anything to guarantee that all dependencies are up to date before recompiling a file. (E.g., A -> B -> C -> D and also A -> D; D's API changes in a way that will also change B's API; we may recompile A with the new D and old B.) Is that the issue, or am I just missing that and the issue is something else?

When the codebase is large I think the overhead of more stages will be much less than the cost of compiling extra files. I'm not sure how it compares for smaller codebases.

**Comment by harrah** [comment]
sbt generally knows about all dependencies, so that isn't the problem here.  New dependencies can be introduced, although this isn't a problem with sbt's current approach.

The problem is basically as you state.  It is present in sbt now- it just is more likely to happen when you have more stages and when later stages are more aggressive in their size.

**Comment by harrah** [comment]
This will very likely be a part of future incremental recompilation enhancements, so I'm closing this.

**Pull request closed without merging**
