### PR TITLE
CrossVersion.full strips off -bin-suffix.

### PR DESCRIPTION
**Pull request by milessabin**
See discussion [here](https://gitter.im/sbt/sbt?at=57ea91d7783fe9b9459f74d2).

### CODE REVIEW

**Review by dwijnand — APPROVED** [review]

**Comment by dwijnand** [comment]
For @eed3si9n to decide if this can be included in 0.13.13, in which case it should be re-targeted for the 0.13.13 branch.

And then according to that decision, this needs notes in either `notes/0.13.13.markdown` or a file in `notes/0.13.14/`.

**Review by eed3si9n — CHANGES_REQUESTED** [review]
I think this would break the sbt 0.13 semantics, and it would hurt the existing libraries that's actually using `-bin` (Lightbend Reactive Platform).

**Review by eed3si9n — APPROVED** [review]

**Comment by eed3si9n** [comment]
LGTM pending Travis.

**Comment by milessabin** [comment]
Are you OK with this going into 0.13.13? If so I'll rebase to that and add release notes.

**Review by dwijnand — CHANGES_REQUESTED** [review]
@milessabin I've changed the target to 0.13.13.

Please could you amend the commit adding a note in notes/0.13.13.markdown?

**Comment by milessabin** [comment]
Will do :-)

**Comment by dwijnand** [comment]
Thanks. I want to get this into 0.13.13-RC2, which I'll cut tomorrow.

**Comment by dwijnand** [comment]
0.13.13-RC3*

**Comment by eed3si9n** [comment]
> Are you OK with this going into 0.13.13?

Yes.

**Comment by eed3si9n** [comment]
> dwijnand changed the base branch to sbt:0.13.13 from sbt:0.13 an hour ago

This Github feature is so cool.

**Comment by milessabin** [comment]
Notes added.

**Comment by milessabin** [comment]
There was one failing job in the last build ... any ideas?

**Review by dwijnand — APPROVED** [review]

**Comment by dwijnand** [comment]
Networking issues - #2758. I'll restart jobs until everything passes.

**Pull request merged**
