### PR TITLE
Adding `scalaOrg` setting key for scala clones.

### PR DESCRIPTION
**Pull request by vjovanov**
Adding scalaOrg key that specifies organization (artifactId) of scala used in the project. The change does not affect version checks for dependecies and LauncherConfiguration.

Modified scalaProvider cache in Launcher to use (scalaOrg, version) as a key.

Downloaded jars are stored in the folder scala-.../lig-<scalaOrg> if scalaOrg is not default.

scala-org is an advanced setting so it can not be used in build.sbt.

### CODE REVIEW

**Comment by harrah** [comment]
This is far enough along that it will make it into the beta.  Please have these changes made by Thursday and I will review it one last time and merge it for the beta.  Thanks!

**Comment by vjovanov** [comment]
I had to add another `val ScalaOrg` in the `ScalaInstance` due to the fact that `ScalaInstance` is in util. Is there a place in the code where I can add this constant so it is visible from every module?

**Comment by harrah** [comment]
I have verified tests work for the standard Scala organization.  To ensure this feature continues to work for you in the future, I suggest writing a scripted test that uses an alternate organization.

**Comment by vjovanov** [comment]
Thanks for the help. I will put a test in once we get Scala milestones deployed.

**Pull request merged**
