### PR TITLE
Add doc task to travis-ci

### LINKED ISSUE #3127: Run `doc` in CI, to catch scaladoc issues
h/t to @fommil for the idea.

This depends on #2812 ("Errors running sbtRoot/compile:doc") to be fixed first.

# Mentoring Instructions

## Links

sbt's Travis CI is split into a matrix of CI, which is found at:

https://github.com/sbt/sbt/blob/1d7b35bd67722511b9a058113e7a1070984e6758/.travis.yml#L31-L45

## Solution

The solution is to either add a new matrix entry of `doc` or add `doc` to one of the existing ones, depending on the relative impacts.

## Testing

The best way to test this is to enable Travis CI on your own fork, and experiment with it building your branch.

## Motivation

The motivation is to catch any scaladoc issues well before a release is cut.

## Background

Historically we've had bad Scaladoc, which we've had to last-minute workaround during a release.

### PR DESCRIPTION
**Pull request by regadas**
- [x] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/1.x/CONTRIBUTING.md) guidelines

Closes #3127

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @regadas,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by regadas** [comment]
I signed the CLA

**Review by eed3si9n — APPROVED** [review]

**Comment by eed3si9n** [comment]
Thanks!

**Comment by eed3si9n** [comment]
@regadas We made a survey form to collect feedback on the contribution process. Please fill it out when get you get a minute. https://goo.gl/forms/LDPlTl9Wso7YwEri2

**Pull request merged**
