### PR TITLE
0.13.10 branch changes

### PR DESCRIPTION
**Pull request by eed3si9n**
/review @dwijnand

### CODE REVIEW

**Comment by dwijnand** [comment]
Restarted a few times. Genuine build failure (pending scripted test passes)

**Comment by Duhemm** [comment]
The branch 0.13 already has a `sbt/src/sbt-test/source-dependencies/trait-members-modified/pending` and this PR creates a new `sbt/src/sbt-test/source-dependencies/trait-members-modified/test` instead of renaming the existing file... That's strange.

**Comment by eed3si9n** [comment]
- 0.13: https://github.com/sbt/sbt/commits/0.13/sbt/src/sbt-test/source-dependencies/trait-member-modified
- 0.13.10: https://github.com/sbt/sbt/commits/0.13.10/sbt/src/sbt-test/source-dependencies/trait-member-modified

**Comment by eed3si9n** [comment]
I can add another commit to change it to `test`

**Comment by Duhemm** [comment]
I messed up when porting @gkossakowski's test, sorry.

**Comment by eed3si9n** [comment]
#2471

**Pull request closed without merging**
