### PR TITLE
Follow source layout conventions supported by Eclipse

### PR DESCRIPTION
**Pull request by gkossakowski**
This pull request consists of 3 commits. The largest one is about moving source files around so they follow package structure. That enables Scala plugin for Eclipse to support code navigation as it manages to properly resolve locations of source files corresponding to Symbols.

I verified that with this change you can import xsbt's code in Eclipse, build it from there and have code navigation support that works very nicely.

### CODE REVIEW

**Comment by gkossakowski** [comment]
Oh, I forgot to mention that I run `test` before and after those changes. Not all tests pass but I get the same failures with latest `0.13` branch.

**Comment by harrah** [comment]
Merged in ef39aeb9c1ea443c17356695758a31152910c4a7.  Eclipse files belong in the per-user .gitignore, though.

**Comment by gkossakowski** [comment]
Good suggestion on putting Eclipse project files to per-user `.gitignore`. This will solve it for all of projects I work on.

**Comment by gkossakowski** [comment]
And thanks for prompt merging! I'm rebasing the rest of my changes and I'll be submitting them in separate pull requests.

**Pull request closed without merging**
