### PR TITLE
[#6696] Add shutdownall to sbt runner to shutdown all sbt-launch processes

### LINKED ISSUE #6696: Add a `shutdownall sbt`
With sbt server, we can have many idle processes running in the background. For one reason or another (low cpu, low ram, unresponding server) the user may want to kill all these sbt processes.

One of the possible solution is to run this bash command manually: `jps -v | grep sbt-launch | cut -f1 -d ' ' | xargs kill -9`.

For convenience, sbt could provide a similar command. It could be part of the existing script (`sbt -shutdownall`) or a standalone script `shutdownall-sbt`.

### PR DESCRIPTION
**Pull request by er1c**
Fixes #6696

#### OSX

```
$ ./sbt shutdownall
shutdown 1 sbt processes
$ ./sbt shutdownall
shutdown 0 sbt processes
```

#### Windows

```
PS C:\Users\Eric Peters> sbt shutdownall
SUCCESS: The process with PID 9948 has been terminated.
shutdown 1 sbt processes
PS C:\Users\Eric Peters> sbt shutdownall
shutdown 0 sbt processes
PS C:\Users\Eric Peters> sbt shutdownall
shutdown 0 sbt processes
PS C:\Users\Eric Peters> sbt shutdownall
SUCCESS: The process with PID 16512 has been terminated.
shutdown 1 sbt processes
PS C:\Users\Eric Peters>
```

### CODE REVIEW

**Comment by eed3si9n** [comment]
May I suggest a slightly gentler name like `shutdownall`?

**Comment by er1c** [comment]
> shutdownall

@eed3si9n done!

**Comment by eed3si9n** [comment]
I understand this is not a real sbt command like `shutdown`, but it might be confusing that to shutdown one you don't need `--` but to shutdown all, you need `--`. My suggestion would be to pretend this is a command and call it:

```bash
$ sbt shutdownall
```

WDYT?

Also, could there be a Windows parity for this feature?

**Comment by er1c** [comment]
> I understand this is not a real sbt command like `shutdown`, but it might be confusing that to shutdown one you don't need `--` but to shutdown all, you need `--`. My suggestion would be to pretend this is a command and call it:
> 
> ```shell
> $ sbt shutdownall
> ```
> 
> WDYT?
> 
> Also, could there be a Windows parity for this feature?

I like it, thanks for thinking outside the box and consistency in usage.  I'll also see about the windows parity.

**Comment by er1c** [comment]
@eed3si9n updated, removed the `--` and added `.bat` support

**Review by eed3si9n — APPROVED** [review]
Thanks!

**Comment by charego** [comment]
Note with environment variable `SBT_NATIVE_CLIENT=true`, you will also need to supply `--server` for this to work.

```
$ sbt --server shutdownall
shutdown 1 sbt processes
```

**Pull request merged**
