### PR TITLE
Fix bincompat from change in #2268

### PR DESCRIPTION
**Pull request by dwijnand**

### CODE REVIEW

**Comment by typesafe-tools** [comment]
Can one of the admins verify this patch?

**Comment by dwijnand** [comment]
Travis finally passed. Ready for review.

**Comment by eed3si9n** [comment]
I think you're missing the semantic difference introduced in 9fbbaab58e246bce7b21117e079206519c386b57. The old one returns directory while the new one returns the actual *.class location IIUC.

**Comment by dwijnand** [comment]
Which change(s) in particular?

I'm a bit lost. My intent here is just the restore binary compatibility. Any semantic difference introduced in that commit was accepted and is already in 0.13. Do you want to revert that and restore the previous semantics?

**Comment by eed3si9n** [comment]
See

```
-   * Returns a URL for the directory or jar containing the the class file `cl`.
+   * Returns a URL for the classfile containing the given class
```

I think we need to add both the implementation. /cc @stuhood

**Comment by eed3si9n** [comment]
Closing this in favor of #2342

**Pull request closed without merging**
