### PR TITLE
Provide more diagnostic info for undefined settings

### PR DESCRIPTION
**Pull request by DavidPerezIngeniero**
This solves this issue:
https://github.com/sbt/sbt/issues/2008

This is my previous error message:

```
sbt.Init$RuntimeUndefined: References to undefined settings at runtime.
```

which doesn't tell me what is happening.

Now, I get this additional information:

```
setting(ScopedKey(Scope(Select(ProjectRef(file:/home/d/rds/,rds)),Global,Global,Global),testApi)) at RangePosition(/home/d/rds/build.sbt,LineRange(233,234)) referenced from ScopedKey(Scope(Select(ProjectRef(file:/home/d/rds/,servision)),Select(ConfigKey(api)),Global,Global),start)

```

Now I know where the problem lies!  :-)

### CODE REVIEW

**Comment by typesafe-tools** [comment]
Can one of the admins verify this patch?

**Comment by dwijnand** [comment]
Nice turnaround :)

Perhaps it would be nicer if it were output some like (I hand-wrote this, I mean generally how sbt pretty prints settings):

```
{file:/home/d/rds/}rds/*:testApi at /home/d/rds/build.sbt:233 referenced from
{file:/home/d/rds/}servision/api:start at /home/d/rds/build.sbt:555
```

**Comment by DavidPerezIngeniero** [comment]
Is there any existing API for that?

**Comment by dwijnand** [comment]
I don't know, but somewhere `inspect` outputs that.

**Comment by jsuereth** [comment]
Yeah, some of the "API" is internal methods that should get turned into API.  This is a a really nice improvement!

**Comment by jsuereth** [comment]
LGTM, pending some "pretty printing" we may want to try.

**Comment by jsuereth** [comment]
macro arg dep nested appears to be flaky.

**Comment by jsuereth** [comment]
Would you mind rebasing this so we can get the travis tests passing? I'd like to merge it in.

Thanks!
- Josh

**Comment by DavidPerezIngeniero** [comment]
Sorry for the delay, I've been travelling and quite busy.

I've merged the latest SBT modifications on branch 0.13.

**Comment by jsuereth** [comment]
Thanks!

**Comment by dwijnand** [comment]
do we want notes for this?

**Comment by eed3si9n** [comment]
@dwijnand You can send a PR for a note or leave it. I probably left it alone when I was last checking all the commits.

**Pull request merged**
