### PR TITLE
Externalize resourceFilter configuration

### PR DESCRIPTION
**Pull request by indrajitr**
This would enable customizing the resource filter and keep using unmanagedResourcesTask.

### CODE REVIEW

**Comment by indrajitr** [comment]
Hi Mark, 
The second patch b515bb0 is more of cosmetic and wasn't part of the original pull request.

But since it is showing up, here is the rationale: 
Since `collectFiles` practically does all that `unmanagedResourcesTask` does and some more, things can be made more consistent. I doubt if anybody would be using `unmanagedResourcesTask` in it's current form and thus deleted it. And even if anybody did, it's signature would change anyway if you accept the patch 0cc0643 (which is part of the pull request).

But if you think that'd be harsh, it can be marked deprecated instead.

**Comment by harrah** [comment]
Hey Indrajit,

If I were to adjust filters, I would have a single `include` key, a single `exclude` key, scope them accordingly, and deprecate sourceFilter, defaultExcludes, and others.  This would be more consistent, what do you think?

**Comment by indrajitr** [comment]
Okay, updated per your suggestion.
I think single word keys would be too generic, thus kept the key names as `includeFilter` and `excludeFilter`.

**Comment by harrah** [comment]
Indrajit, if you have time, could you review these related changes I made?  The idea is that deprecating the keys is only helpful if they still do something.

**Comment by indrajitr** [comment]
Barring the small [comment](https://github.com/harrah/xsbt/commit/228b245d2dbe6192401a424a0dcee4e535fb793e#commitcomment-568249) things look cool!

Also trying to stay backward compatible with previous config is good idea (it should have struck me).

Although I didn't quite follow what you meant by:

> The idea is that deprecating the keys is only helpful if they still do something.

**Comment by harrah** [comment]
I meant that we might as well just remove the `sourceFilter` and `classpathFilter` keys if the `unmanaged*` commands don't use them.  Otherwise, the user sees a deprecation and would reasonably assume that the settings would still work.

**Comment by indrajitr** [comment]
Aha, cool!

**Pull request merged**
