### PR TITLE
Roll back aggressive deletion of cache. Fixes #1091.

### LINKED ISSUE #637: ZIP dependency SNAPSHOTs not being updated in 0.12.1
I'm using SBT 0.12.1 and I'm seeing ZIP artifact based SNAPSHOT dependencies not being updated, even after executing 'update'. Example:

Dependency:
    "io.escalante" % "escalante-dist" % "0.2.0-SNAPSHOT" artifacts(Artifact("escalante-dist", "zip", "zip")),

I first updated the dependency on 10th December and I've just updated it yesterday, 10th of January. Looking at my .ivy folder I see:

```
-rw-r--r--  1 g  staff  34084 Jan 10 23:53 ivy-0.2.0-SNAPSHOT.xml
-rw-r--r--  1 g  staff   6122 Jan 10 23:53 ivy-0.2.0-SNAPSHOT.xml.original
-rw-r--r--  1 g  staff   1114 Jan 11 17:16 ivydata-0.2.0-SNAPSHOT.properties
drwxr-xr-x  3 g  staff    102 Dec 18 18:41 zips
```

And zips contains the one from December :(

```
-rw-r--r--  1 g  staff  140518828 Dec 10 18:55 escalante-dist-0.2.0-SNAPSHOT.zip
```

So, the ZIP has not been updated?? :(

Metadata file info: 
- ivy-0.2.0-SNAPSHOT.xml: https://gist.github.com/4511969
- ivydata-0.2.0-SNAPSHOT.properties: https://gist.github.com/4511987
- maven-metadata.xml in https://repository.jboss.org/nexus/content/groups/public/io/escalante/escalante-dist/0.2.0-SNAPSHOT/maven-metadata.xml: https://gist.github.com/4511994

What is going on here?

### LINKED ISSUE #1091: sbt keen to re-download snapshot dependency on every update
## steps

```
$ cat project/build.properties 
sbt.version=0.13.1

$ cat build.sbt
scalaVersion := "2.11.0-SNAPSHOT"

resolvers += Opts.resolver.sonatypeSnapshots
```

Run `$ sbt clean ++2.11.0-SNAPSHOT compile` multiple times.
## problem

Each time scala-library.jar and scala-reflect.jar are downloaded.
## original report

This is making working with scala snapshots unbearable. Maybe this will turn out to be my doing, but I'm desperate enough to ask. If this is some unfortunate default, consider the claimed bug that it is the default.

```
% cat build.sbt
resolvers in Global += Opts.resolver.sonatypeSnapshots

scalaVersion in Global := "2.11.0-SNAPSHOT"

libraryDependencies += "org.scala-lang" % "scala-reflect" % scalaVersion.value

% sbt update
[info] Set current project to root-2014-01-18_scala_2 (in build file:/Users/paulp/scratch/2014-01-18_scala_2/)
[info] Updating {file:/Users/paulp/scratch/2014-01-18_scala_2/}root-2014-01-18_scala_2...
[info] Resolving jline#jline;2.11 ...
[info] downloading https://oss.sonatype.org/content/repositories/snapshots/org/scala-lang/scala-library/2.11.0-SNAPSHOT/scala-library-2.11.0-20140118.024846-520.jar ...
[info]  [SUCCESSFUL ] org.scala-lang#scala-library;2.11.0-SNAPSHOT!scala-library.jar (15297ms)
[info] downloading https://oss.sonatype.org/content/repositories/snapshots/org/scala-lang/scala-reflect/2.11.0-SNAPSHOT/scala-reflect-2.11.0-20140118.024846-519.jar ...
[info]  [SUCCESSFUL ] org.scala-lang#scala-reflect;2.11.0-SNAPSHOT!scala-reflect.jar (13974ms)
[info] Done updating.
[success] Total time: 38 s, completed Jan 18, 2014 3:28:02 PM

% sbt update
[info] Set current project to root-2014-01-18_scala_2 (in build file:/Users/paulp/scratch/2014-01-18_scala_2/)
[info] Updating {file:/Users/paulp/scratch/2014-01-18_scala_2/}root-2014-01-18_scala_2...
[info] Resolving jline#jline;2.11 ...
[info] downloading https://oss.sonatype.org/content/repositories/snapshots/org/scala-lang/scala-library/2.11.0-SNAPSHOT/scala-library-2.11.0-20140118.024846-520.jar ...
[info]  [SUCCESSFUL ] org.scala-lang#scala-library;2.11.0-SNAPSHOT!scala-library.jar (18217ms)
[info] downloading https://oss.sonatype.org/content/repositories/snapshots/org/scala-lang/scala-reflect/2.11.0-SNAPSHOT/scala-reflect-2.11.0-20140118.024846-519.jar ...
[info]  [SUCCESSFUL ] org.scala-lang#scala-reflect;2.11.0-SNAPSHOT!scala-reflect.jar (16273ms)
[info] Done updating.
[success] Total time: 40 s, completed Jan 18, 2014 3:28:56 PM
```

### PR DESCRIPTION
**Pull request by eed3si9n**
- sbt 0.12.3 introduced 482f9905235217c339934d8a7a560aae13b7f296 (aggressive deletion of cache) to fix #637 and #641.
- The underlying issue of #641 was an incorrect classifier, and it was
  fixed in 718fa9177254e6067cafdc1ee6a744ba5c325921 for #683 and shipped as sbt 0.13.0.

We should roll back 482f9905235217c339934d8a7a560aae13b7f296 to fix #1091 (re-download of SNAPSHOTs). Rolling it back should not cause regression of #641 as confirmed by the scripted test `scripted dependency-management/cache-classifiers` and its externalized version [eed3si9n/test-sbt-641](https://github.com/eed3si9n/test-sbt-641).

### CODE REVIEW

**Comment by jsuereth** [comment]
LGTM

**Comment by xeno-by** [comment]
Will this be part of 0.13.5?

**Comment by eed3si9n** [comment]
Yea. 0.13 branch eventually becomes 0.13.5.

**Comment by lauris** [comment]
I can't find any release that references this commit. Is it possible to use this fix now?

**Comment by eed3si9n** [comment]
The commit is tagged `0.13.5-RC2`, which I tagged on Friday. It'll stay RC for a week, and if no bugs are found it becomes `0.13.5`.

**Comment by lauris** [comment]
Thanks. Just upgraded to 0.13.5-RC2 and everythings works as expected.

**Pull request merged**
