### PR TITLE
Always export apiURL even if autoAPIMappings is false.

### PR DESCRIPTION
**Pull request by jkinkead**
Copy of #2230, against 1.0.x.

### CODE REVIEW

**Comment by typesafe-tools** [comment]
Can one of the admins verify this patch?

**Comment by eed3si9n** [comment]
Re-running a few Travis jobs, but generally LGTM

**Comment by dwijnand** [comment]
LGTM

**Comment by eed3si9n** [comment]
Forgot about the notes. Could you send another PR with a note entry here? - https://github.com/sbt/sbt/tree/1.0.x/notes/0.13.10

**Pull request merged**
