### PR TITLE
update to lm-coursier-shaded 2.0.0-RC6-8

### LINKED ISSUE #5170: Excluded dependency isn't excluded
## steps
After upgrading from SBT 1.1.4 to 1.3.2 I observed this misbehaviour:

```
libraryDependencies ++= Seq("commons-jelly" % "commons-jelly" % "1.0"
					exclude("xerces", "xmlParserAPIs")
					exclude("javax.servlet", "servlet-api")
					exclude("servlet-api", "servlet-api")
					exclude("dom4j", "dom4j")
					exclude("junit", "junit")
					exclude("jdom", "jdom")
                                        exclude("xalan", "xalan")
					exclude("com.ibm.icu", "icu4j"))
```

## problem

I run `dependencyTree` by using this useful [sbt-dependency-graph plugin](https://github.com/jrudolph/sbt-dependency-graph), and here is an excerpt of the output:
```
commons-jelly:commons-jelly:1.0
  +-commons-beanutils:commons-beanutils:1.6 (evicted by: 1.8.3)
  +-commons-beanutils:commons-beanutils:1.8.3
  +-commons-cli:commons-cli:1.0
  | +-commons-lang:commons-lang:1.0 (evicted by: 2.6)
  | +-commons-lang:commons-lang:2.6
  | 
  +-commons-collections:commons-collections:2.1 (evicted by: 3.2.2)
  +-commons-collections:commons-collections:3.2.2
  +-commons-discovery:commons-discovery:0.2-dev
  +-commons-discovery:commons-discovery:20030211.213356 (evicted by: 0.2-dev)
  +-commons-jexl:commons-jexl:1.0
  +-commons-lang:commons-lang:2.0 (evicted by: 2.6)
  +-commons-lang:commons-lang:2.6
  +-forehead:forehead:1.0-beta-5
  +-jaxen:jaxen:1.1-beta-4
  | +-xerces:xercesImpl:2.6.2 (evicted by: 2.9.1)
  | +-xerces:xercesImpl:2.9.1
  | | +-xml-apis:xml-apis:1.3.04
  | | 
  | +-xom:xom:1.0b3
  |   +-com.ibm.icu:icu4j:2.6.1
  |   +-org.ccil.cowan.tagsoup:tagsoup:0.9.7
  |   +-xerces:xercesImpl:2.2.1 (evicted by: 2.9.1)
  |   +-xerces:xercesImpl:2.9.1
  |     +-xml-apis:xml-apis:1.3.04
  |     
  +-xml-apis:xml-apis:1.0.b2 (evicted by: 1.3.04)
  +-xml-apis:xml-apis:1.3.04
```

## expectation

Not to include com.ibm.icu:icu4j:2.6.1 dependency.
I've excluded it explicitly.

## notes
- Scala 2.12.10
- Linux 64 bits
- Java 8

### LINKED ISSUE #5291: Test scope dependencies silently evict Compile/Runtime dependencies
## steps
sbt version: `1.3.4`

## problem

After upgrading our project from SBT 1.2.8 to 1.3.4 we were seeing an `UnsupportedOperationException` in production. Details here: https://github.com/featureflow/featureflow-java-sdk/issues/4

This was apparently caused by the okhttp 3.2.0 artifact being evicted by version 3.11.0.

But the `evicted` output gives no clue as to why:
```
[info]  * com.squareup.okhttp3:okhttp:3.11.0 is selected over 3.2.0
[info]      +- io.featureflow:featureflow-java-sdk:1.0.3          (depends on 3.2.0)
```

Looking a bit deeper, I found that there was a single library that transitively depends on okhttp 3.11.0:

```
* com.typesafe.play:play-test:2.7.3:test
  ...
  + org.fluentlenium:fluentlenium-core:3.7.1
    + org.seleniumhq.selenium:selenium-remote-driver:3.141.59
      ...
      + com.squareup.okhttp3:okhttp:3.11.0
    + org.seleniumhq.selenium:selenium-support:3.141.59
      ...
      + com.squareup.okhttp3:okhttp:3.11.0
  + org.seleniumhq.selenium:selenium-firefox-driver:3.141.59
      + com.squareup.okhttp3:okhttp:3.11.0
```

But, as you can see, this one is scoped to `Test`.

## expectation

okhttp version 3.2.0 should be used during runtime / compilation.

### PR DESCRIPTION
**Pull request by eed3si9n**
This brings in per-config resolution (https://github.com/coursier/sbt-coursier/pull/235)
Fixes https://github.com/sbt/sbt/issues/5291
Fixes https://github.com/sbt/sbt/issues/5170

https://github.com/coursier/sbt-coursier/releases/tag/v2.0.0-RC6-8

https://github.com/coursier/sbt-coursier/releases/tag/v2.0.0-RC6-7

Ref https://github.com/coursier/sbt-coursier/releases/tag/v2.0.0-RC6-6

- Fix an issue in the handling of strict in `versionReconciliation`, that was enabling strict mode for all modules as soon as it was enabled for one
- Put `<override>` elements in the published `ivy.xml`, corresponding to `dependencyOverrides`
- Don't report evictions for modules whose version was forced via `dependencyOverrides`
- Update coursier from `2.0.0-RC6-19` to `2.0.0-RC6-21`

Ref https://github.com/coursier/sbt-coursier/releases/tag/v2.0.0-RC6-5

- Update Coursier from 2.0.0-RC6-14 to 2.0.0-RC6-19
- Ignore missing artifacts in `updateSbtClassifiers`
- Run resolution for each configuration (dependencies in test can't bump versions in compile anymore)

### CODE REVIEW

**Comment by eed3si9n** [comment]
/cc @alexarchambault 

https://travis-ci.org/github/sbt/sbt/jobs/692200455 2 scripted tests failed:

```
[error] (scripted) Failed tests:
[error] 	dependency-management/override
[error] 	dependency-management/provided
```

### dependency-management/override

```
[info] Running dependency-management/override
[info] [info] Loading settings for project global-plugins from metals.sbt ...
[info] [info] Loading global plugins from /tmp/sbt_9ed16e40/global/plugins
[info] [info] Loading project definition from /tmp/sbt_9ed16e40/project
[info] [warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[info] [info] Compiling 1 Scala source to /tmp/sbt_9ed16e40/project/target/scala-2.12/sbt-1.0/classes ...
[info] [info] Done compiling.
[info] [success] Generated .bloop/sbt_9ed16e40-build.json
[info] [success] Total time: 2 s, completed May 28, 2020, 3:02:56 PM
[info] [info] Loading settings for project sbt_9ed16e40 from build.sbt ...
[info] [info] Set current project to sbt_9ed16e40 (in build file:/tmp/sbt_9ed16e40/)
[info] [info] Set current project to override (in build file:/tmp/sbt_9ed16e40/)
[info] [info] Defining libraryDependencies
[info] [info] The new value will be used by allDependencies, dependencyPositions
[info] [info] Reapplying settings...
[info] [info] Set current project to sbt_9ed16e40 (in build file:/tmp/sbt_9ed16e40/)
[info] [success] Total time: 1 s, completed May 28, 2020, 3:02:59 PM
[info] [info] Defining dependencyOverrides
[info] [info] The new value will be used by csrConfiguration, moduleSettings and 2 others.
[info] [info] 	Run `last` for details.
[info] [info] Reapplying settings...
[info] [info] Set current project to sbt_9ed16e40 (in build file:/tmp/sbt_9ed16e40/)
[info] [error] java.util.NoSuchElementException: key not found: (junit:junit,3.8.1)
[info] [error] 	at scala.collection.immutable.Map$Map1.apply(Map.scala:140)
[info] [error] 	at lmcoursier.internal.SbtUpdateReport$.$anonfun$apply$1(SbtUpdateReport.scala:328)
[info] [error] 	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:273)
[info] [error] 	at scala.collection.Iterator.foreach(Iterator.scala:943)
[info] [error] 	at scala.collection.Iterator.foreach$(Iterator.scala:943)
[info] [error] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
[info] [error] 	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
[info] [error] 	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
[info] [error] 	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
[info] [error] 	at scala.collection.TraversableLike.map(TraversableLike.scala:273)
[info] [error] 	at scala.collection.TraversableLike.map$(TraversableLike.scala:266)
[info] [error] 	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
[info] [error] 	at lmcoursier.internal.SbtUpdateReport$.apply(SbtUpdateReport.scala:307)
[info] [error] 	at lmcoursier.internal.UpdateRun$.update(UpdateRun.scala:85)
[info] [error] 	at lmcoursier.CoursierDependencyResolution.$anonfun$update$40(CoursierDependencyResolution.scala:227)
[info] [error] 	at scala.util.Either.map(Either.scala:353)
[info] [error] 	at lmcoursier.CoursierDependencyResolution.$anonfun$update$39(CoursierDependencyResolution.scala:224)
[info] [error] 	at scala.util.Either.flatMap(Either.scala:341)
[info] [error] 	at lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:222)
[info] [error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:60)
[info] [error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:53)
[info] [error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:103)
[info] [error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:73)
[info] [error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:116)
[info] [error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:228)
[info] [error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:116)
[info] [error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:97)
[info] [error] 	at sbt.util.Tracked$.$anonfun$inputChangedW$1(Tracked.scala:219)
[info] [error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:130)
[info] [error] 	at sbt.Classpaths$.$anonfun$updateTask0$5(Defaults.scala:3099)
[info] [error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[info] [error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[info] [error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[info] [error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[info] [error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[info] [error] 	at sbt.Execute.work(Execute.scala:291)
[info] [error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[info] [error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:184)
[info] [error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:41)
[info] [error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[info] [error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[info] [error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[info] [error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[info] [error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[info] [error] 	at java.base/java.lang.Thread.run(Thread.java:834)
[info] [error] (update) java.util.NoSuchElementException: key not found: (junit:junit,3.8.1)
[info] [error] Total time: 0 s, completed May 28, 2020, 3:03:00 PM
[error] x dependency-management/override
```

### dependency-management/provided

```
[info] Running dependency-management/provided
[info] [info] Loading settings for project global-plugins from metals.sbt ...
[info] [info] Loading global plugins from /tmp/sbt_9ed16e40/global/plugins
[info] [info] Loading project definition from /tmp/sbt_9ed16e40/project
[info] [warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[info] [info] Compiling 1 Scala source to /tmp/sbt_9ed16e40/project/target/scala-2.12/sbt-1.0/classes ...
[info] [info] Done compiling.
[info] [success] Generated .bloop/sbt_9ed16e40-build.json
[info] [success] Total time: 1 s, completed May 28, 2020, 3:07:03 PM
[info] [info] Loading settings for project root from build.sbt ...
[info] [info] Set current project to root (in build file:/tmp/sbt_9ed16e40/)
[info] [info] Set current project to root (in build file:/tmp/sbt_9ed16e40/)
[info] [info] Update report:
[info] [info] 	Resolve time: -1 ms, Download time: -1 ms, Download size: -1 bytes
[info] [info] 	compile:
[info] [info] 		org.scala-lang:scala-library:2.12.11:default (): (Artifact(scala-library, jar, jar, None, Vector(), None, Map(), None, false),/home/travis/.sbt/scripted/boot/fakeboot/scala-2.12.11/lib/scala-library.jar)
[info] [info] 		javax.servlet:servlet-api:2.5:default: (Artifact(servlet-api, jar, jar, None, Vector(), Some(https://repo1.maven.org/maven2/javax/servlet/servlet-api/2.5/servlet-api-2.5.jar), Map(), None, false),/home/travis/.cache/coursier/v1/https/repo1.maven.org/maven2/javax/servlet/servlet-api/2.5/servlet-api-2.5.jar)
[info] [info] 	compile-internal:
[info] [info] 		org.scala-lang:scala-library:2.12.11:default (): (Artifact(scala-library, jar, jar, None, Vector(), None, Map(), None, false),/home/travis/.sbt/scripted/boot/fakeboot/scala-2.12.11/lib/scala-library.jar)
[info] [info] 		javax.servlet:servlet-api:2.5:default: (Artifact(servlet-api, jar, jar, None, Vector(), Some(https://repo1.maven.org/maven2/javax/servlet/servlet-api/2.5/servlet-api-2.5.jar), Map(), None, false),/home/travis/.cache/coursier/v1/https/repo1.maven.org/maven2/javax/servlet/servlet-api/2.5/servlet-api-2.5.jar)
[info] [info] 	docs:
[info] [info] 	optional:
[info] [info] 	plugin:
[info] [info] 	pom:
[info] [info] 	provided:
[info] [info] 	runtime:
[info] [info] 		org.scala-lang:scala-library:2.12.11:default (): (Artifact(scala-library, jar, jar, None, Vector(), None, Map(), None, false),/home/travis/.sbt/scripted/boot/fakeboot/scala-2.12.11/lib/scala-library.jar)
[info] [info] 		javax.servlet:servlet-api:2.5:default: (Artifact(servlet-api, jar, jar, None, Vector(), Some(https://repo1.maven.org/maven2/javax/servlet/servlet-api/2.5/servlet-api-2.5.jar), Map(), None, false),/home/travis/.cache/coursier/v1/https/repo1.maven.org/maven2/javax/servlet/servlet-api/2.5/servlet-api-2.5.jar)
[info] [info] 	runtime-internal:
[info] [info] 		org.scala-lang:scala-library:2.12.11:default (): (Artifact(scala-library, jar, jar, None, Vector(), None, Map(), None, false),/home/travis/.sbt/scripted/boot/fakeboot/scala-2.12.11/lib/scala-library.jar)
[info] [info] 		javax.servlet:servlet-api:2.5:default: (Artifact(servlet-api, jar, jar, None, Vector(), Some(https://repo1.maven.org/maven2/javax/servlet/servlet-api/2.5/servlet-api-2.5.jar), Map(), None, false),/home/travis/.cache/coursier/v1/https/repo1.maven.org/maven2/javax/servlet/servlet-api/2.5/servlet-api-2.5.jar)
[info] [info] 	scala-tool:
[info] [info] 		org.scala-lang:scala-compiler:2.12.11:default: (Artifact(scala-compiler, jar, jar, None, Vector(), None, Map(), None, false),/home/travis/.sbt/scripted/boot/fakeboot/scala-2.12.11/lib/scala-compiler.jar)
[info] [info] 		org.scala-lang:scala-compiler:2.12.11:optional: (Artifact(scala-compiler, jar, jar, None, Vector(), None, Map(), None, false),/home/travis/.sbt/scripted/boot/fakeboot/scala-2.12.11/lib/scala-compiler.jar)
[info] [info] 		org.scala-lang:scala-library:2.12.11:default (): (Artifact(scala-library, jar, jar, None, Vector(), None, Map(), None, false),/home/travis/.sbt/scripted/boot/fakeboot/scala-2.12.11/lib/scala-library.jar)
[info] [info] 		org.scala-lang:scala-library:2.12.11:optional (): (Artifact(scala-library, jar, jar, None, Vector(), None, Map(), None, false),/home/travis/.sbt/scripted/boot/fakeboot/scala-2.12.11/lib/scala-library.jar)
[info] [info] 		org.scala-lang:scala-reflect:2.12.11:default (): (Artifact(scala-reflect, jar, jar, None, Vector(), None, Map(), None, false),/home/travis/.sbt/scripted/boot/fakeboot/scala-2.12.11/lib/scala-reflect.jar)
[info] [info] 		org.scala-lang.modules:scala-xml_2.12:1.0.6:default: (Artifact(scala-xml_2.12, bundle, jar, None, Vector(), Some(https://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.12/1.0.6/scala-xml_2.12-1.0.6.jar), Map(), None, false),/home/travis/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.12/1.0.6/scala-xml_2.12-1.0.6.jar)
[info] [info] 		jline:jline:2.14.6:default: (Artifact(jline, jar, jar, None, Vector(), Some(https://repo1.maven.org/maven2/jline/jline/2.14.6/jline-2.14.6.jar), Map(), None, false),/home/travis/.cache/coursier/v1/https/repo1.maven.org/maven2/jline/jline/2.14.6/jline-2.14.6.jar)
[info] [info] 		org.fusesource.jansi:jansi:1.12:default: (Artifact(jansi, jar, jar, None, Vector(), Some(https://repo1.maven.org/maven2/org/fusesource/jansi/jansi/1.12/jansi-1.12.jar), Map(), None, false),/home/travis/.cache/coursier/v1/https/repo1.maven.org/maven2/org/fusesource/jansi/jansi/1.12/jansi-1.12.jar)
[info] [info] 	sources:
[info] [info] 	test:
[info] [info] 		org.scala-lang:scala-library:2.12.11:default (): (Artifact(scala-library, jar, jar, None, Vector(), None, Map(), None, false),/home/travis/.sbt/scripted/boot/fakeboot/scala-2.12.11/lib/scala-library.jar)
[info] [info] 		javax.servlet:servlet-api:2.5:default: (Artifact(servlet-api, jar, jar, None, Vector(), Some(https://repo1.maven.org/maven2/javax/servlet/servlet-api/2.5/servlet-api-2.5.jar), Map(), None, false),/home/travis/.cache/coursier/v1/https/repo1.maven.org/maven2/javax/servlet/servlet-api/2.5/servlet-api-2.5.jar)
[info] [info] 	test-internal:
[info] [info] 		org.scala-lang:scala-library:2.12.11:default (): (Artifact(scala-library, jar, jar, None, Vector(), None, Map(), None, false),/home/travis/.sbt/scripted/boot/fakeboot/scala-2.12.11/lib/scala-library.jar)
[info] [info] 		javax.servlet:servlet-api:2.5:default: (Artifact(servlet-api, jar, jar, None, Vector(), Some(https://repo1.maven.org/maven2/javax/servlet/servlet-api/2.5/servlet-api-2.5.jar), Map(), None, false),/home/travis/.cache/coursier/v1/https/repo1.maven.org/maven2/javax/servlet/servlet-api/2.5/servlet-api-2.5.jar)
[info] [success] Total time: 0 s, completed May 28, 2020, 3:07:05 PM
[info] [success] Total time: 0 s, completed May 28, 2020, 3:07:05 PM
[info] [success] Total time: 0 s, completed May 28, 2020, 3:07:05 PM
[info] [success] Total time: 0 s, completed May 28, 2020, 3:07:05 PM
[info] [success] Total time: 0 s, completed May 28, 2020, 3:07:05 PM
[info] [info] Loading settings for project global-plugins from metals.sbt ...
[info] [info] Loading global plugins from /tmp/sbt_9ed16e40/global/plugins
[info] [info] Loading project definition from /tmp/sbt_9ed16e40/project
[info] [success] Generated .bloop/sbt_9ed16e40-build.json
[info] [success] Total time: 1 s, completed May 28, 2020, 3:07:06 PM
[info] [info] Loading settings for project root from build.sbt ...
[info] [info] Set current project to root (in build file:/tmp/sbt_9ed16e40/)
[info] [error] java.lang.RuntimeException: /home/travis/.cache/coursier/v1/https/repo1.maven.org/maven2/javax/servlet/servlet-api/2.5/servlet-api-2.5.jar incorrectly included in runtime.
[info] [error] 	at scala.sys.package$.error(package.scala:30)
[info] [error] 	at $e2395f60688763816687$.$anonfun$checkServletAPI$2(build.sbt:33)
[info] [error] 	at scala.Option.foreach(Option.scala:407)
[info] [error] 	at $e2395f60688763816687$.checkServletAPI(build.sbt:33)
[info] [error] 	at $e2395f60688763816687$.$anonfun$root$7(build.sbt:24)
[info] [error] 	at $e2395f60688763816687$.$anonfun$root$7$adapted(build.sbt:12)
[info] [error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[info] [error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[info] [error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[info] [error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[info] [error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[info] [error] 	at sbt.Execute.work(Execute.scala:291)
[info] [error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[info] [error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:184)
[info] [error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:41)
[info] [error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[info] [error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[info] [error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[info] [error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[info] [error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[info] [error] 	at java.base/java.lang.Thread.run(Thread.java:834)
[info] [error] (check) /home/travis/.cache/coursier/v1/https/repo1.maven.org/maven2/javax/servlet/servlet-api/2.5/servlet-api-2.5.jar incorrectly included in runtime.
[info] [error] Total time: 0 s, completed May 28, 2020, 3:07:07 PM
[error] x dependency-management/provided 
```

**Comment by alexarchambault** [comment]
I confirm there are things that changed in the handling of provided dependencies… They're basically resolved along things in `Compile`. I'll have a closer look at the tests that fail here, maybe I made the wrong choice in https://github.com/coursier/sbt-coursier/commit/031648a1d7a25bf6fccc306ba620da3847b5070a.

**Comment by eed3si9n** [comment]
dependency-management/override and dependency-management/provided still failed under 
lm-coursier-shaded 2.0.0-RC6-6.

**Comment by julienrf** [comment]
> I'll have a closer look at the tests that fail here, maybe I made the wrong choice in [coursier/sbt-coursier@031648a](https://github.com/coursier/sbt-coursier/commit/031648a1d7a25bf6fccc306ba620da3847b5070a).

@alexarchambault Do you know if the problem comes from sbt or coursier?

**Comment by alexarchambault** [comment]
These tests broke after things changed on the coursier side apparently. There's already some provided and `dependencyOverrides` tests in the sbt-coursier repo, so I'm not sure what goes wrong here.

**Comment by eed3si9n** [comment]
With the latest `dependency-management/override` no longer fails (because it's checking for `contains(...)`) and I have a fix for `dependency-management/provided` here - https://github.com/coursier/sbt-coursier/pull/262

**Pull request merged**
