### PR TITLE
Run unit tests from compileInterface on Travis CI.

### LINKED ISSUE #2357: Travis CI doesn't run unit tests
The relevant fragment of travis script looks like this:

```
script:
  - sbt -J-XX:ReservedCodeCacheSize=128m "$SCRIPTED_TEST"
```

I believe we should add `sbt test` in front of running scripted tests.

### PR DESCRIPTION
**Pull request by gkossakowski**
Also, make the intent of the env variable clearer in travis configuration.

Fixes #2357.

### CODE REVIEW

**Comment by typesafe-tools** [comment]
Can one of the admins verify this patch?

**Comment by eed3si9n** [comment]
This is actually going to catch a test failure that I mentioned in https://github.com/sbt/sbt/issues/2357#issuecomment-170099841 likely coming from 0f616294c4e713dc415f5dc3ae7aef257decb228 in #2343

**Comment by dwijnand** [comment]
+1

**Comment by eed3si9n** [comment]
LGTM

**Pull request merged**
