### PR TITLE
Parsing of a credentials file to add Ivy Credentials to the launcher

### PR DESCRIPTION
**Pull request by avalade**
Hi Mark -
I've patched the launcher code a bit to add support for specifying a file using the sbt.boot.credentials system property which is parsed and any credentials are added to the CredentialsStore static instance.  The location defaults to ~/.ivy2/.credentials currently.

Let me know if there's any way that we could get this into xsbt as it's pretty handy, especially with the newly added support for private repositories in Nathan's Conscript utility.

Thanks,
- Aaron

### CODE REVIEW

**Comment by harrah** [comment]
The fundamentals are correct and the patch can get merged after some details get worked out:
1. The latest branch is 0.11.
2. ResolveValues.readProperties can be reused (you'll need to widen its access).
3. Did you move addCredentials for a reason?
4. It appears to be a bit heavy on the number of classes generated.  This isn't necessarily a problem in the rest of sbt, but the launcher is supposed to be kept to a reasonable size.  I won't ask you to handle this; just be aware that things will get tweaked a bit after it gets merged.
5. I'm not sure about having a default credentials file.  Normal projects don't have a default credentials file, so I don't think the launcher should either.

**Comment by avalade** [comment]
1. I can move this pull request over to the 0.11 branch.  Should I close this pull request and open another on the 0.11 branch?
2. I've changed ResolveValues.readProperties to be private to the package
3. That was a change which shouldn't have gone through.  I've fixed that in the change.
4. I've refactored to remove the for comprehension since that was what caused the majority of the classes to be generated.
5. I've removed the default credentials file and instead allowed the file to be specified through either a system property or an environment variable.  I added the environment variable because the system property was swallowed when using Conscript.

I've also cleaned up the patch to use TABs so it fits in with the rest of the code.  Apologies for not doing that at first!
- Aaron

**Comment by harrah** [comment]
Yes, please open a new pull request if that is what is required to move it to the 0.11 branch.  Also, merge the commits into a single commit.  It looks ready otherwise, thanks.

**Comment by avalade** [comment]
Moving this pull request to the 0.11 branch.

**Pull request closed without merging**
