### PR TITLE
Fix carriage return in supershell progress state

### PR DESCRIPTION
**Pull request by sebastian-alfers**
Preserved the carriage return if followed by a line feed.

### CODE REVIEW

**Comment by sebastian-alfers** [comment]
@eed3si9n As [mentioned](https://github.com/sbt/sbt/pull/6555#issuecomment-864554539), I run the following without metals locally:

```
$ sbt
...
sbt:sbtRoot> project utilLogging
...
sbt:Util Logging> testOnly *.ProgressStateSpec
```

And I get this:

```
[info] Formatting 1 Scala sources...
[info] Formatting 1 Scala sources...
[error] scalafmt version 2.3.2 classpath is corrupted: /Users/sebalf/dev/sebastian-alfers/sbt/.scalafmt.conf
```

However when I apply the following it works:

```
-addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.3.0")
+addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.4.2")
```

I can create a separate PR if you think it makes sense but wanted to keep it out of this PR.

**Review by eed3si9n — APPROVED** [review]
Thanks!

**Comment by sebastian-alfers** [comment]
Not sure if the failing builds are related to my change.

**Comment by eed3si9n** [comment]
@sebastian-alfers I think it is tangentially related in a sense that adding additional test has uncovered some weird race condition / initialization issue that was previously not noticed. I have a fix for that, which I tested first on top of this PR to make sure it would fix both - https://github.com/sbt/sbt/pull/6557

**Pull request merged**
