### PR TITLE
Change position of Detailed-Topics

### PR DESCRIPTION
**Pull request by jaceklaskowski**

### CODE REVIEW

**Comment by eed3si9n** [comment]
We are currently working on a new website, so I want to hold off on making too much changes if it's ok. I've already converted `rst` files into markdown, and I'd need to track them manually.

**Comment by jaceklaskowski** [comment]
Fine to wait till the new website's ready for changes. Should I queue my changes here or stop them completely until the new website's ready?

**Comment by eed3si9n** [comment]
I would appreciate if you could wait, since change from `rst` to markdown would result in merge conflicts and I'd need to merge them manually.

**Comment by eed3si9n** [comment]
The new site is up. Please reopen any fixes against sbt/website project.

**Pull request closed without merging**
