### PR TITLE
Update Community-Plugins.rst

### PR DESCRIPTION
**Pull request by davidharcombe**
Add sbt-multi-publish plugin to list of community plugins

### CODE REVIEW

**Comment by harrah** [comment]
This is a good idea.  We should get the default to be this.  It is tricky because publishTo's type is wrong (as you know), but we could start by removing the need for the code duplication in the plugin.  I understand why `ConvertResolver` is duplicated and I think we can open that up to fix that.  Why isn't `IvyActions.publish` sufficient?  Is it just to avoid calling `checkFilesPresent` multiple times?

**Comment by davidharcombe** [comment]
The reason I didn't use `IvyActions.publish` was that I must have gone down a rabbit-hole looking for a way to create the ivy-style `Resolver` and by the time I'd fixed _that_, I'd forgotten about the `IvyActions.publish`!

I've refactored to use the `IvyActions` since you mention it; it's more logical than duplicating the code, and the `checkFilesPresent` is such a lightweight action, it doesn't really matter if it gets called more than once.

**Comment by harrah** [comment]
Makes sense!  Thanks for the refactoring.  I merged this to 0.12 and 0.13, but will update the docs later.

**Comment by jsuereth** [comment]
Should we close this if it's merged?

**Comment by harrah** [comment]
See the comments.  The referenced plugin allows publishing to multiple repositories.  Ignoring compatibility, this would be easy to implement right in sbt and it would make sense to do so.  We can open a separate issue for it, but this is open because of that.

**Pull request closed without merging**
