### PR TITLE
FPORT: Make JCenter opt in

### PR DESCRIPTION
**Pull request by dwijnand**
Forward-port of #2335.

Depends upon a release with sbt/librarymanagement#17.

### CODE REVIEW

**Comment by typesafe-tools** [comment]
Can one of the admins verify this patch?

**Comment by Duhemm** [comment]
@dwijnand I think that the latest release of sbt/librarymanagement (0.1.0-M6) includes sbt/librarymanagement#17.

**Comment by dwijnand** [comment]
Well this is the change that required 0.13.11, so I'll wait for that change to be pushed sbt/librarymanagement before updating this.

This forward-porting-with-split-repo business is so time consuming.

**Comment by eed3si9n** [comment]
Superseded by #2481

**Pull request closed without merging**
