### PR TITLE
Fix #1136 - Ivy's + dependency ranges not converted appropriately to maven.

### LINKED ISSUE #1136: make-pom does not translate ivy revision ranges to valid maven revision ranges
Discovered this when trying to download bijection-guava via this pom: view-source:http://search.maven.org/remotecontent?filepath=com/twitter/bijection-guava_2.9.3/0.6.0/bijection-guava_2.9.3-0.6.0.pom

``` xml
<dependency>
<groupId>com.google.code.findbugs</groupId>
<artifactId>jsr305</artifactId>
<version>1.3.+</version>
</dependency>
```

Isolated, the failure looks like so:

``` console
$ cat pom.xml 
<?xml version='1.0' encoding='UTF-8'?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0">
    <modelVersion>4.0.0</modelVersion>
    <groupId>fake</groupId>
    <artifactId>fake</artifactId>
    <packaging>jar</packaging>
    <version>0.0.1</version>
    <dependencies>
        <dependency>
            <groupId>com.twitter</groupId>
            <artifactId>bijection-guava_2.9.3</artifactId>
            <version>0.6.0</version>
        </dependency>
    </dependencies>
</project>
$ mvn -U dependency:tree
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building fake 0.0.1
[INFO] ------------------------------------------------------------------------
Downloading: http://repo.maven.apache.org/maven2/com/twitter/bijection-guava_2.9.3/0.6.0/bijection-guava_2.9.3-0.6.0.pom
Downloaded: http://repo.maven.apache.org/maven2/com/twitter/bijection-guava_2.9.3/0.6.0/bijection-guava_2.9.3-0.6.0.pom (0 B at 0.0 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/com/twitter/bijection-core_2.9.3/0.6.0/bijection-core_2.9.3-0.6.0.pom
Downloaded: http://repo.maven.apache.org/maven2/com/twitter/bijection-core_2.9.3/0.6.0/bijection-core_2.9.3-0.6.0.pom (0 B at 0.0 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/org/scala-lang/scala-library/2.9.3/scala-library-2.9.3.pom
Downloaded: http://repo.maven.apache.org/maven2/org/scala-lang/scala-library/2.9.3/scala-library-2.9.3.pom (0 B at 0.0 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/com/google/code/findbugs/jsr305/1.3.+/jsr305-1.3.+.pom
[WARNING] The POM for com.google.code.findbugs:jsr305:jar:1.3.+ is missing, no dependency information available
Downloading: http://repo.maven.apache.org/maven2/com/google/guava/guava/14.0/guava-14.0.pom
Downloaded: http://repo.maven.apache.org/maven2/com/google/guava/guava/14.0/guava-14.0.pom (0 B at 0.0 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/com/google/guava/guava-parent/14.0/guava-parent-14.0.pom
Downloaded: http://repo.maven.apache.org/maven2/com/google/guava/guava-parent/14.0/guava-parent-14.0.pom (0 B at 0.0 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/com/twitter/bijection-guava_2.9.3/0.6.0/bijection-guava_2.9.3-0.6.0.jar
Downloading: http://repo.maven.apache.org/maven2/com/twitter/bijection-core_2.9.3/0.6.0/bijection-core_2.9.3-0.6.0.jar
Downloading: http://repo.maven.apache.org/maven2/org/scala-lang/scala-library/2.9.3/scala-library-2.9.3.jar
Downloading: http://repo.maven.apache.org/maven2/com/google/guava/guava/14.0/guava-14.0.jar
Downloading: http://repo.maven.apache.org/maven2/com/google/code/findbugs/jsr305/1.3.+/jsr305-1.3.+.jar
Downloaded: http://repo.maven.apache.org/maven2/com/twitter/bijection-guava_2.9.3/0.6.0/bijection-guava_2.9.3-0.6.0.jar (0 B at 0.0 KB/sec)
Downloaded: http://repo.maven.apache.org/maven2/com/google/guava/guava/14.0/guava-14.0.jar (0 B at 0.0 KB/sec)
Downloaded: http://repo.maven.apache.org/maven2/org/scala-lang/scala-library/2.9.3/scala-library-2.9.3.jar (0 B at 0.0 KB/sec)
Downloaded: http://repo.maven.apache.org/maven2/com/twitter/bijection-core_2.9.3/0.6.0/bijection-core_2.9.3-0.6.0.jar (0 B at 0.0 KB/sec)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.645s
[INFO] Finished at: Tue Feb 25 08:10:33 MST 2014
[INFO] Final Memory: 8M/150M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project fake: Could not resolve dependencies for project fake:fake:jar:0.0.1: Could not find artifact com.google.code.findbugs:jsr305:jar:1.3.+ in central (http://repo.maven.apache.org/maven2) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

```

The corresponding sbt build snippet that leads to this pom is:

``` scala
    libraryDependencies ++= Seq(
      "com.google.code.findbugs" % "jsr305" % "1.3.+",
      "com.google.guava" % "guava" % "14.0"
    )
```

Peeking at MakePom does show a straight mapping with no treatment to ensure things like ivy's support for a trailing + get mapped to maven [,) for example which is valid in maven poms: https://github.com/sbt/sbt/blob/b7c50d42698f8309c76ed5fd0efbb3ef61ee601e/ivy/src/main/scala/sbt/MakePom.scala

See this workaround pull request in bijection-guava for reference: https://github.com/twitter/bijection/pull/164

### PR DESCRIPTION
**Pull request by jsuereth**
Fix pom creation to handle Ivy's version ranges, in semi-popular usage.

Review @eed3si9n

### CODE REVIEW

**Comment by cunei** [comment]
Hi Josh, the code fails for a version like "1.+", returning "[1, .2)".

I had a look at all the possible specifications of version ranges for both Ivy and Maven. A list of Maven examples is at: http://docs.oracle.com/middleware/1212/core/MAVEN/maven_version.htm#A1000686 and a list of Ivy ranges is at: https://ant.apache.org/ivy/history/2.1.0/settings/version-matchers.html
On that basis, I put together the following alternative code, which should take into account a wider range of cases:

```
def makeDependencyVersion(revision: String): String = {
  def plusRange(s:String, shift:Int = 0) = {
    def pow(i:Int):Int = if (i>0) 10 * pow(i-1) else 1
    val (prefixVersion, revLast) = (s+"0"*shift).reverse.split("\\.",2) match {
      case Array(revLast,revRest) =>
        ( revRest.reverse + ".", revLast )
      case Array(revLast) => ("",revLast)
     }
     val lastVersion = revLast.reverse
     val lastVersionInt = lastVersion.toInt
     s"[${prefixVersion}${lastVersion},${prefixVersion}${lastVersionInt+pow(shift)})"
  }
  val startSym=Set(']','[','(')
  val stopSym=Set(']','[',')')
  try {
    if (revision endsWith ".+") {
      plusRange(revision.substring(0,revision.length-2))
    } else if (revision endsWith "+") {
      val base = revision.take(revision.length-1)
      (0 to 5).map(plusRange(base,_)).mkString(",")
    } else if (startSym(revision(0)) && stopSym(revision(revision.length-1))) {
      val start = revision(0)
      val stop = revision(revision.length-1)
      val mid = revision.substring(1,revision.length-1)
      (if (start == ']') "(" else start) + mid + (if (stop == '[') ")" else stop)
    } else revision
  } catch {
    case e: NumberFormatException =>
    // TODO - if the version doesn't meet our expectations, maybe we just issue a hard
    //        error instead of softly ignoring the attempt to rewrite.
    //sys.error(s"Could not fix version [$revision] into maven style version")
    revision
  }
}
```

This code turns the following Ivy examples into Maven as follows:

```
1.3.4      --> 1.3.4
[1.0,2.0]  --> [1.0,2.0]
[1.0,2.0[  --> [1.0,2.0)
]1.0,2.0]  --> (1.0,2.0]
]1.0,2.0[  --> (1.0,2.0)
[1.0,)     --> [1.0,)
]1.0,)     --> (1.0,)
(,2.0]     --> (,2.0]
(,2.0[     --> (,2.0)
1.+        --> [1,2)
1.3.4.+    --> [1.3.4,1.3.5)
12.31.42.+ --> [12.31.42,12.31.43)
1+         --> [1,2),[10,20),[100,200),[1000,2000),[10000,20000),[100000,200000)
1.3.4+     --> [1.3.4,1.3.5),[1.3.40,1.3.50),[1.3.400,1.3.500),[1.3.4000,1.3.5000),[1.3.40000,1.3.50000),[1.3.400000,1.3.500000)
12.31.42+  --> [12.31.42,12.31.43),[12.31.420,12.31.430),[12.31.4200,12.31.4300),[12.31.42000,12.31.43000),[12.31.420000,12.31.430000),[12.31.4200000,12.31.4300000)
```

The expansions of '1.3.4+' and similar might benefit from a second look, but this might possibly be a more complete solution.

**Comment by eed3si9n** [comment]
Is `String` the best we can do to represent version number? If we want to do range calculation, order comparison etc. shouldn't there be a type for it?

**Comment by jsuereth** [comment]
@eed3si9n I think Maven/Aether has such a thing. I'd prefer to defer the the underlying's system (in this case Ivy).   However this issue lives _between_ Ivy and Maven, so I dunno.

For now I think hackery is ok to easy over the rough edges in a binary compatible way.   Creating a real Version type should definitely be on the horizon though....

**Comment by jsuereth** [comment]
Thanks for the suggestion @cunei.  It's now fully implemented as well as adding a unit test which helps documents the reasoning behind the pieces.

I'm still not sure abut the `1+` feature allowed by Ivy, but I'm willing to use your heuristic for now, as I can't think of any better solution besides just bombing on creating the pom.

**Comment by jsuereth** [comment]
@cunei @eed3si9n this is worth a second look now.

**Pull request merged**
