### PR TITLE
Fix for sbt/sbt#2435

### PR DESCRIPTION
**Pull request by Duhemm**
Fixes sbt/sbt#2435

Consider a configuration where we have two projects, A and B.

A has a library dependency on "a" % "b" % "1.0.0" % "compile->runtime"
and "a" % "b" % "1.0.0" % "compile->runtime2"

B depends on project A, and has a library dependency on
"a" % "b" % "1.0.1" % "compile->runtime".

Note that project B depends on a more recent version of "a" % "b" than
project A, and that it depends ONLY on it's "runtime" configuration.

However, when compiling project B, we expect to have on the classpath
project A, and "a" % "b" % "1.0.1" % "compile->runtime" AND
"a" % "b" % "1.0.1" % "compile->runtime2" because it is part of the
compile configuration of project A.

This commit changes the cached resolution engine so that it behaves like
that, by first resolving dependencies on other project and then ensuring
that the dependent project specifies dependencies on the same
configurations.

### CODE REVIEW

**Comment by Duhemm** [comment]
I still can't reproduce the failure on my machine. The failure on Travis is different from the original failure (before my fix).

Wiping the cache on Travis seems to fix the issue.

**Comment by eed3si9n** [comment]
notes and forward port plz

**Comment by eed3si9n** [comment]
LGTM

**Comment by eed3si9n** [comment]
I'm seeing Travis CI failures on dependency-management/cached-resolution-configurations from PRs that has nothing to do with library management.

**Pull request merged**
