### PR TITLE
[1.7.x] lm-coursier-shaded 2.0.12

### PR DESCRIPTION
**Pull request by eed3si9n**
https://github.com/coursier/sbt-coursier/releases/tag/v2.0.12

Fixes https://github.com/sbt/sbt/issues/7058

### CODE REVIEW

**Comment by julienrf** [comment]
I wonder if this change introduced a binary incompatibility. I had to apply the following change in sbt-version-policy to upgrade from 1.7.2 to 1.7.3: https://github.com/scalacenter/sbt-version-policy/pull/147/commits/db2f37c8a60ac89cdd9914d218b8de9858d397a5

(otherwise, I got the following error: https://github.com/scalacenter/sbt-version-policy/actions/runs/3402173263/jobs/5657742540#step:5:1665

**Comment by eed3si9n** [comment]
lm-coursier-shaded should shade Shapeless if Coursier is using it, so I am not sure how what resulted to policy change related to Shapeless. Could it also be something to do with the implementation change in Coursier itself since it got fast forwarded by a year?

**Comment by julienrf** [comment]
The error wasn’t related to Shapeless, but to the API of Coursier:

~~~ text
Error:  /tmp/sbt_57e6ea27/build.sbt:47: error: value only is not a member of object lmcoursier.definitions.ModuleMatchers
Error:          ModuleMatchers.only(Module(Organization("com.chuusai"), ModuleName("shapeless_2.12"), Map())) -> Reconciliation.Strict
Error:                         ^
Error:  sbt.compiler.EvalException: Type error in expression
~~~

There used to be a method `lmcoursier.definitions.ModuleMatchers.only` with a compatible signature, but it is not here anymore.

**Comment by eed3si9n** [comment]
Ah. That's because we switched code generation to Scalafix for Scala 3 purpose. We now need:

```scala
import lmcoursier.syntax._
```

I had to do that in https://github.com/sbt/sbt/pull/7060 as well.

**Comment by julienrf** [comment]
Yes, but my point is that it seems that lm-coursier-shaded 2.0.12 is not binary compatible with version 2.0.10. This is surprising given that it’s a patch version bump.

**Pull request merged**
