### PR TITLE
use shaded JLine

### LINKED ISSUE #4943: Shade JLine
## steps

JLine in-sources JAnsi, and JLine is used by both Coursier and Scala.
lm-shaded-coursier recently leaked JLine 3 by mistake, but the same can happen with Scala in the future (https://github.com/scala/scala/pull/8036).

## problem

In case of https://github.com/sbt/sbt/pull/4925, it manifested itself as:

```
[info] [error] java.lang.NoClassDefFoundError: Could not initialize class org.fusesource.jansi.AnsiOutputStream
[info] [error] 	at jline.internal.Ansi.stripAnsi(Ansi.java:28)
[info] [error] 	at jline.console.ConsoleReader.setPrompt(ConsoleReader.java:499)
[info] [error] 	at jline.console.ConsoleReader.readLine(ConsoleReader.java:2425)
[info] [error] 	at jline.console.ConsoleReader.readLine(ConsoleReader.java:2378)
[info] [error] 	at jline.console.ConsoleReader.readLine(ConsoleReader.java:2366)
```

## expectation

Isolate ourselves from upstream uses of JLine.

### PR DESCRIPTION
**Pull request by eed3si9n**
Fixes #4943
Ref https://github.com/sbt/util/pull/209

### CODE REVIEW

**Comment by typesafe-tools** [comment]
A validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt-validator/1730/console">is in progress...</a>

**Comment by typesafe-tools** [comment]
[//]: # (Refs: pull/4959/head-develop-develop-develop-pull/209/head)
The validator <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/1730/">has checked</A> the following projects, tested using dbuild, projects built on top of each other.

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | <A HREF="https://github.com/sbt/sbt/pull/4959">pull/4959/head      </A> | sbt/sbt@91671e2a92bfb662d1ac29033be11861debeab05
  zinc              | <A HREF="https://github.com/sbt/zinc/tree/develop">develop             </A> | sbt/zinc@4b414b66778399f044beccf749073b52e63bf5ef
  io                | <A HREF="https://github.com/sbt/io/tree/develop">develop             </A> | sbt/io@63a348cce8a84c11104dea2c511d1eee1cfa3b1e
  librarymanagement | <A HREF="https://github.com/sbt/librarymanagement/tree/develop">develop             </A> | sbt/librarymanagement@edfe9c6c6367f21095e96e0704f475b8608649ec
  util              | <A HREF="https://github.com/sbt/util/pull/209">pull/209/head       </A> | sbt/util@18a423bca2e1372c356f5a7d70a97fd6fe8a6f74

:x: The result is: ***FAILED***
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild?sbt=pull/4959/head&zinc=develop&io=develop&librarymanagement=develop&util=pull/209/head&deploy_to_bintray=false&run_sbt_community=false">(restart)</A>

**Comment by typesafe-tools** [comment]
A validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt-validator/1732/console">is in progress...</a>

**Comment by eed3si9n** [comment]
Travis CI is only failing on Mima.

Whereas AppVeyor is failing https://ci.appveyor.com/project/sbt/sbt/builds/26780791/job/j7qrxi2r5ceg191p?fullLog=true with

```
[error] Exception in thread "main" java.lang.UnsatisfiedLinkError: sbt.internal.shaded.org.fusesource.jansi.internal.CLibrary.init()V
[error] 	at sbt.internal.shaded.org.fusesource.jansi.internal.CLibrary.init(Native Method)
[error] 	at sbt.internal.shaded.org.fusesource.jansi.internal.CLibrary.<clinit>(CLibrary.java:43)
[error] 	at sbt.internal.shaded.org.fusesource.jansi.AnsiConsole.wrapOutputStream(AnsiConsole.java:48)
[error] 	at sbt.internal.shaded.org.fusesource.jansi.AnsiConsole.<clinit>(AnsiConsole.java:38)
[error] 	at sbt.internal.shaded.jline.AnsiWindowsTerminal.detectAnsiSupport(AnsiWindowsTerminal.java:57)
[error] 	at sbt.internal.shaded.jline.AnsiWindowsTerminal.<init>(AnsiWindowsTerminal.java:27)
[error] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[error] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[error] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[error] 	at java.lang.Class.newInstance(Class.java:442)
[error] 	at sbt.internal.shaded.jline.TerminalFactory.getFlavor(TerminalFactory.java:205)
[error] 	at sbt.internal.shaded.jline.TerminalFactory.create(TerminalFactory.java:96)
[error] 	at sbt.internal.shaded.jline.TerminalFactory.get(TerminalFactory.java:180)
[error] 	at sbt.internal.shaded.jline.TerminalFactory.get(TerminalFactory.java:186)
[error] 	at sbt.internal.util.JLine$.terminal(LineReader.scala:123)
[error] 	at sbt.internal.util.JLine$.withTerminal(LineReader.scala:127)
[error] 	at sbt.internal.util.JLine$.usingTerminal(LineReader.scala:136)
[error] 	at sbt.internal.util.JLine$.createReader(LineReader.scala:146)
[error] 	at sbt.internal.util.SimpleReader.<init>(LineReader.scala:227)
[error] 	at sbt.internal.util.SimpleReader$.<init>(LineReader.scala:230)
[error] 	at sbt.internal.util.SimpleReader$.<clinit>(LineReader.scala)
[error] 	at sbt.Import.$init$(Import.scala:196)
[error] 	at sbt.package$.<init>(package.scala:17)
[error] 	at sbt.package$.<clinit>(package.scala)
[error] 	at sbt.RunFromSourceMain$.main(RunFromSourceMain.scala:40)
[error] 	at sbt.RunFromSourceMain.main(RunFromSourceMain.scala)
[error] x actions/aggregate 
sbt.internal.scripted.TestException: {line -1}  Reload for scripted batch execution failed.
	at sbt.scriptedtest.ScriptedTests.$anonfun$runBatchedTests$4(ScriptedTests.scala:349)

```

JLine 2.14.6 brings in JAnsi 2.12 - https://github.com/jline/jline2/blob/jline-2.14.6/pom.xml#L122
JAnsi 2.12 brings in jansi-native 1.6 - https://github.com/fusesource/jansi/blob/jansi-project-1.12/pom.xml#L40
The problematic line https://github.com/fusesource/jansi-native/blob/jansi-native-1.6/src/main/java/org/fusesource/jansi/internal/CLibrary.java#L42, which looks like it's involving loading of a native code.

Maybe we need to try JLine 3 update instead down the line.

**Comment by typesafe-tools** [comment]
[//]: # (Refs: pull/4959/head-develop-develop-develop-pull/209/head)
The validator <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/1732/">has checked</A> the following projects, tested using dbuild, projects built on top of each other.

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | <A HREF="https://github.com/sbt/sbt/pull/4959">pull/4959/head      </A> | sbt/sbt@91671e2a92bfb662d1ac29033be11861debeab05
  zinc              | <A HREF="https://github.com/sbt/zinc/tree/develop">develop             </A> | sbt/zinc@4b414b66778399f044beccf749073b52e63bf5ef
  io                | <A HREF="https://github.com/sbt/io/tree/develop">develop             </A> | sbt/io@63a348cce8a84c11104dea2c511d1eee1cfa3b1e
  librarymanagement | <A HREF="https://github.com/sbt/librarymanagement/tree/develop">develop             </A> | sbt/librarymanagement@edfe9c6c6367f21095e96e0704f475b8608649ec
  util              | <A HREF="https://github.com/sbt/util/pull/209">pull/209/head       </A> | sbt/util@18a423bca2e1372c356f5a7d70a97fd6fe8a6f74

:white_check_mark: The result is: ***SUCCESS***
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild?sbt=pull/4959/head&zinc=develop&io=develop&librarymanagement=develop&util=pull/209/head&deploy_to_bintray=false&run_sbt_community=false">(restart)</A>

**Pull request closed without merging**
