### PR TITLE
Natural whitespace handling for SBT configuration parser AKA 'no more blankies'

### LINKED ISSUE #1606: Natural whitespace handling for SBT configuration parser AKA 'no more blankies'
Open list to implement/check:
- [x] Add tests around the new no-blank-lines files and session-save
- [ ] Possibly expand the notion of "position" we have in Setting[_] to include start/stop so we can more accurately alter a build.sbt file without changing it.
- [x] Investigate @dragos [comments about tokenizer/parser](https://github.com/sbt/sbt/pull/1574#discussion-diff-17551216).
- [ ] Current SBT parser cuts line by line. If we have:

``` scala
val a = <a/><b/>

val r = 4
```

SBT parser split it to: `val a = <a/><b/>` and `val r = 4`. Scala parser will compile one by one separate.

``` scala
scala> val a = <a/><b/>
a: scala.xml.NodeBuffer = ArrayBuffer(<a/>, <b/>)
```

But this code will not compile.

``` scala
scala> :pa
// Entering paste mode (ctrl-D to finish)

val a = <a/><b/>

val r = 4

// Exiting paste mode, now interpreting.

<console>:3: error: ';' expected but 'val' found.
val r = 4
^
```

For backward compatibility we have to find, where is xml code - and at least add ; to the end (now I will add brackets ()). The code to add bracket can be rewritten.
- [x] Write acceptance tests.
- [x] I think for all sbt part - how to split code to atomic parts - it is easier to test. 
  In #noblankies we extracted `EvaluateConfigurations.splitExpressions` and  `SessionSettingsNoBlankies.oldLinesToNew` for `session save`. Both methods can be tested by unit tests - without running whole sbt.
- [x] Scala parser should be corrected. See [Scala parser cuts last bracket](http://stackoverflow.com/q/25547149/651140)

### PR DESCRIPTION
**Pull request by eed3si9n**
This PR fixes #1606. We should get this in as is for a milestone and fix whatever that needs fixing later.

### CODE REVIEW

**Comment by jsuereth** [comment]
+1   I'm ok with this as-is for M3/master.   Kudos for all the cleanups and contributions, this is a very exciting contributed PR.

**Comment by eed3si9n** [comment]
We do need to start writing a note if we wanna release this out though. What do you think about the following?:

## whitespace handling improvements

Starting sbt 0.13.7, build.sbt will be parsed using a customized Scala parser. This eliminates the requirement to use blank line as the delimiter between each settings, and also allows blank lines to be inserted at arbitrary position within a block.

This feature was contributed by [Andrzej Jozwik @ajozwik](https://github.com/ajozwik) inspired by Typesafe's @gkossakowski organizing multiple meetups with Warszaw Scala on [how to patch sbt specifically with the focus on blank line issue](http://blog.japila.pl/2014/07/gkossakowski-on-warszawscala-about-how-to-patch-scalasbt/).

**Comment by gkossakowski** [comment]
I can't find any mention of being able to fallback to the old `.sbt` parser. Is there a way to configure sbt to do that?

**Comment by eed3si9n** [comment]
@gkossakowski +1. we did talk about that internally but haven't done it. let's get that in by RC.

**Comment by ajozwik** [comment]
For fallback to old `.sbt` parser I think we must to set property on start for example `-Dold.sbt=true`. I do not know if you can put it to sbt file - it is parsed before setting is red.

**Pull request merged**
