### PR TITLE
Have updateClassifiers use the dependencyResolution task

### PR DESCRIPTION
**Pull request by alexarchambault**
- [x] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md) guidelines

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @alexarchambault,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by alexarchambault** [comment]
CLA signed

**Comment by alexarchambault** [comment]
Checking if the CI passes with this change, I'll consider adding an non-regression test if all is green.

**Comment by eed3si9n** [comment]
It's green.

**Pull request merged**
