### PR TITLE
Wip keep project on reload

### PR DESCRIPTION
**Pull request by vigdorchik**

### CODE REVIEW

**Comment by harrah** [comment]
Looks good.  
1. I think you can just use an empty Map instead of None, right?
2. The `projectMap` method should handle the case where the current project no longer exists.

**Comment by harrah** [comment]
Also, can you add a test case for when a project is removed?  Put a new Build.scala in changes/Build.scala, then in the script, do `$ copy-file changes/Build.scala project/Build.scala` and `> reload`.

This doesn't remember if the user has switched to an external build (URI) does it?  That is, it always returns to the root build (URI), right?

**Comment by harrah** [comment]
I merged it because the remaining issues are minor:
1. I don't see how the URI actually changes in the test.
2. Did you see the comment about `BuildStructure.allProjects`?

Unfortunately, I still didn't get notified even with @harrah in the commit.

**Comment by vigdorchik** [comment]
1. I copy the file with the name alphabetically before the existing, so I hope it should be picked by default.
2. I missed that part, sorry. Is it worth a separate pull request?

**Comment by harrah** [comment]
1. The URI stays the same, though: `file:///.../reload/`.  You'd have to have an external dependency (say on a project in a subdirectory) and change to a project in that external build.
2. Yes, I think it can be bundled with #1, though.

**Pull request merged**
