### PR TITLE
Remove actions/doc-scala-instance

### LINKED ISSUE #5316: actions/doc-scala-instance failure: ClassNotFoundException: scala.tools.nsc.Main
## steps

`actions/doc-scala-instance` seems to be failing on Travis CI.

## problem

https://travis-ci.org/sbt/sbt/jobs/624452309?utm_medium=notification&utm_source=github_status

```
[info] Running actions/doc-scala-instance
[info] [info] Loading project definition from /tmp/sbt_31544f53/project
[info] [info] Compiling 1 Scala source to /tmp/sbt_31544f53/project/target/scala-2.12/sbt-1.0/classes ...
[info] [info] Done compiling.
[info] [info] Loading settings for project sbt_31544f53 from build.sbt ...
[info] [info] Set current project to sbt_31544f53 (in build file:/tmp/sbt_31544f53/)
[info] [info] Set current project to doc-scala-instance (in build file:/tmp/sbt_31544f53/)
[info] [info] Main Scala API documentation to /tmp/sbt_31544f53/a/target/scala-2.12/api...
[info] [info] Non-compiled module 'compiler-bridge_2.12' for Scala 2.12.2. Compiling...
[info] [info] Attempting to fetch org.scala-sbt:compiler-bridge_2.12:1.3.1.
[info] [error] java.lang.ClassNotFoundException: scala.tools.nsc.Main
[info] [error] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
[info] [error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[info] [error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[info] [error] 	at java.lang.Class.forName0(Native Method)
[info] [error] 	at java.lang.Class.forName(Class.java:348)
[info] [error] 	at sbt.internal.inc.RawCompiler.getReporter$1(RawCompiler.scala:54)
[info] [error] 	at sbt.internal.inc.RawCompiler.apply(RawCompiler.scala:77)
[info] [error] 	at sbt.internal.inc.AnalyzingCompiler$.$anonfun$compileSources$6(AnalyzingCompiler.scala:363)
[info] [error] 	at sbt.internal.inc.AnalyzingCompiler$.handleCompilationError$1(AnalyzingCompiler.scala:338)
[info] [error] 	at sbt.internal.inc.AnalyzingCompiler$.$anonfun$compileSources$4(AnalyzingCompiler.scala:359)
[info] [error] 	at sbt.internal.inc.AnalyzingCompiler$.$anonfun$compileSources$4$adapted(AnalyzingCompiler.scala:354)
[info] [error] 	at sbt.io.IO$.withTemporaryDirectory(IO.scala:489)
[info] [error] 	at sbt.io.IO$.withTemporaryDirectory(IO.scala:499)
[info] [error] 	at sbt.internal.inc.AnalyzingCompiler$.$anonfun$compileSources$2(AnalyzingCompiler.scala:354)
[info] [error] 	at sbt.internal.inc.AnalyzingCompiler$.$anonfun$compileSources$2$adapted(AnalyzingCompiler.scala:346)
[info] [error] 	at sbt.io.IO$.withTemporaryDirectory(IO.scala:489)
[info] [error] 	at sbt.io.IO$.withTemporaryDirectory(IO.scala:499)
[info] [error] 	at sbt.internal.inc.AnalyzingCompiler$.compileSources(AnalyzingCompiler.scala:346)
[info] [error] 	at sbt.internal.inc.ZincComponentCompiler.$anonfun$compileAndInstall$3(ZincComponentCompiler.scala:261)
[info] [error] 	at sbt.internal.inc.ZincComponentCompiler.$anonfun$compileAndInstall$3$adapted(ZincComponentCompiler.scala:250)
[info] [error] 	at sbt.io.IO$.withTemporaryDirectory(IO.scala:489)
[info] [error] 	at sbt.io.IO$.withTemporaryDirectory(IO.scala:499)
[info] [error] 	at sbt.internal.inc.ZincComponentCompiler.$anonfun$compileAndInstall$2(ZincComponentCompiler.scala:250)
[info] [error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[info] [error] 	at sbt.internal.util.BufferedLogger.bufferQuietly(BufferedLogger.scala:123)
[info] [error] 	at sbt.internal.inc.ZincComponentCompiler.$anonfun$compileAndInstall$1(ZincComponentCompiler.scala:250)
[info] [error] 	at sbt.internal.inc.ZincComponentCompiler.$anonfun$compileAndInstall$1$adapted(ZincComponentCompiler.scala:247)
[info] [error] 	at sbt.io.IO$.withTemporaryDirectory(IO.scala:489)
[info] [error] 	at sbt.io.IO$.withTemporaryDirectory(IO.scala:499)
[info] [error] 	at sbt.internal.inc.ZincComponentCompiler.compileAndInstall(ZincComponentCompiler.scala:247)
[info] [error] 	at sbt.internal.inc.ZincComponentCompiler.$anonfun$compiledBridgeJar$1(ZincComponentCompiler.scala:215)
[info] [error] 	at sbt.internal.inc.IfMissing$Define.run(IfMissing.scala:19)
[info] [error] 	at sbt.internal.inc.ZincComponentManager.createAndCache$1(ZincComponentManager.scala:49)
[info] [error] 	at sbt.internal.inc.ZincComponentManager.$anonfun$files$3(ZincComponentManager.scala:60)
[info] [error] 	at sbt.internal.inc.ZincComponentManager.getOrElse$1(ZincComponentManager.scala:42)
[info] [error] 	at sbt.internal.inc.ZincComponentManager.$anonfun$files$2(ZincComponentManager.scala:60)
[info] [error] 	at sbt.internal.inc.ZincComponentManager$$anon$1.call(ZincComponentManager.scala:89)
[info] [error] 	at sbt.RunFromSourceMain$$anon$1.apply(RunFromSourceMain.scala:67)
[info] [error] 	at sbt.internal.inc.ZincComponentManager.lock(ZincComponentManager.scala:89)
[info] [error] 	at sbt.internal.inc.ZincComponentManager.$anonfun$lockSecondaryCache$1(ZincComponentManager.scala:86)
[info] [error] 	at scala.Option.map(Option.scala:230)
[info] [error] 	at sbt.internal.inc.ZincComponentManager.lockSecondaryCache(ZincComponentManager.scala:86)
[info] [error] 	at sbt.internal.inc.ZincComponentManager.fromSecondary$1(ZincComponentManager.scala:58)
[info] [error] 	at sbt.internal.inc.ZincComponentManager.$anonfun$files$6(ZincComponentManager.scala:64)
[info] [error] 	at sbt.internal.inc.ZincComponentManager.getOrElse$1(ZincComponentManager.scala:42)
[info] [error] 	at sbt.internal.inc.ZincComponentManager.$anonfun$files$5(ZincComponentManager.scala:64)
[info] [error] 	at sbt.internal.inc.ZincComponentManager$$anon$1.call(ZincComponentManager.scala:89)
[info] [error] 	at sbt.RunFromSourceMain$$anon$1.apply(RunFromSourceMain.scala:67)
[info] [error] 	at sbt.internal.inc.ZincComponentManager.lock(ZincComponentManager.scala:89)
[info] [error] 	at sbt.internal.inc.ZincComponentManager.lockLocalCache(ZincComponentManager.scala:82)
[info] [error] 	at sbt.internal.inc.ZincComponentManager.files(ZincComponentManager.scala:64)
[info] [error] 	at sbt.internal.inc.ZincComponentManager.file(ZincComponentManager.scala:70)
[info] [error] 	at sbt.internal.inc.ZincComponentCompiler.compiledBridgeJar(ZincComponentCompiler.scala:215)
[info] [error] 	at sbt.internal.inc.ZincComponentCompiler$ZincCompilerBridgeProvider.compiledBridge(ZincComponentCompiler.scala:75)
[info] [error] 	at sbt.internal.inc.ZincComponentCompiler$ZincCompilerBridgeProvider.fetchCompiledBridge(ZincComponentCompiler.scala:81)
[info] [error] 	at sbt.internal.inc.AnalyzingCompiler.loader(AnalyzingCompiler.scala:260)
[info] [error] 	at sbt.internal.inc.AnalyzingCompiler.getInterfaceClass(AnalyzingCompiler.scala:278)
[info] [error] 	at sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:245)
[info] [error] 	at sbt.internal.inc.AnalyzingCompiler.doc(AnalyzingCompiler.scala:177)
[info] [error] 	at sbt.internal.inc.AnalyzingCompiler.doc(AnalyzingCompiler.scala:158)
[info] [error] 	at sbt.Doc$.$anonfun$scaladoc$1(Doc.scala:39)
[info] [error] 	at sbt.Doc$.$anonfun$scaladoc$1$adapted(Doc.scala:39)
[info] [error] 	at sbt.RawCompileLike$.$anonfun$prepare$1(RawCompileLike.scala:83)
[info] [error] 	at sbt.RawCompileLike$.$anonfun$prepare$1$adapted(RawCompileLike.scala:76)
[info] [error] 	at sbt.RawCompileLike$.$anonfun$cached$3(RawCompileLike.scala:67)
[info] [error] 	at sbt.RawCompileLike$.$anonfun$cached$3$adapted(RawCompileLike.scala:65)
[info] [error] 	at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:154)
[info] [error] 	at sbt.RawCompileLike$.$anonfun$cached$1(RawCompileLike.scala:72)
[info] [error] 	at sbt.RawCompileLike$.$anonfun$cached$1$adapted(RawCompileLike.scala:55)
[info] [error] 	at sbt.Defaults$.$anonfun$docTaskSettings$3(Defaults.scala:1641)
[info] [error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[info] [error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[info] [error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[info] [error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[info] [error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[info] [error] 	at sbt.Execute.work(Execute.scala:291)
[info] [error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[info] [error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:184)
[info] [error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[info] [error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info] [error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[info] [error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info] [error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[info] [error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[info] [error] 	at java.lang.Thread.run(Thread.java:748)
[info] [error] (a / Compile / doc) java.lang.ClassNotFoundException: scala.tools.nsc.Main
[info] [error] Total time: 0 s, completed Dec 13, 2019 4:23:29 AM
[error] x actions/doc-scala-instance 
```

## expectation

it should work.

### PR DESCRIPTION
**Pull request by eed3si9n**
Fixes https://github.com/sbt/sbt/issues/5316

The test doesn't look like it's testing anything.

### CODE REVIEW

**Comment by dwijnand** [comment]
See https://github.com/sbt/sbt/commit/0bb460c03ed9940c67c9048d353dfd151a5bfdd0: it's testing the behaviour of `derive` and the wiring of the default build.  The mistake was in updating `scalaVersion` in https://github.com/sbt/sbt/commit/03c9b648fb45309421a313975ea7fbe435aa7b8f#diff-7134ca2d82ae8fe2a8472267581a1b29.

**Comment by eed3si9n** [comment]
Yea I figured as much, but testing that wasn't worth the intermittent failure.
Maybe there's an actual race condition in fetching compiler bridge though - https://github.com/sbt/sbt/issues/5316

**Comment by dwijnand** [comment]
The wiring and derive I'd be worried about breaking easily.

Was the failure specific to those versions?

If you want you can use 2.12 and 2.13, with the 2.13 only `-Ymacro-annotations`.

**Comment by eed3si9n** [comment]
All I know is that actions/doc-scala-instance was failing with `ClassNotFoundException` intermittently, and it didn't look like stuff around that has changed.

**Comment by dwijnand** [comment]
Sounds like a race condition, installing the compiler bridge?

**Comment by dwijnand** [comment]
Or a race condition with thread current classloader.

**Pull request merged**
