### PR TITLE
feat: add optional framework field to the bsp

### PR DESCRIPTION
**Pull request by kpodsiad**
Supersedes https://github.com/sbt/sbt/pull/6822

### CODE REVIEW

**Comment by kpodsiad** [comment]
Do you know why one check is failing? It doesn't seem related to my changes. I wanted to ask before I'll try to investigate it myself.

**Comment by adpi2** [comment]
I just re-started the CI to see if the failure re-appears.

**Comment by adpi2** [comment]
The failure is not related to your changes. It also happened in https://github.com/sbt/sbt/pull/6824 and https://github.com/sbt/sbt/pull/6820.

I pushed a fix here to see if it's better.

**Review by adpi2 — COMMENTED** [review]
It looks good. But could you adapt the test here: https://github.com/sbt/sbt/blob/ba5f7527fef1fd947f372b9ed940052fe1ee1edc/server-test/src/test/scala/testpkg/BuildServerTest.scala#L299-L313

You should be able to run it with:
```
sbt serverTestProj/testOnly testpkg.BuildServerTest
```

**Review by adpi2 — APPROVED** [review]

**Pull request merged**
