### PR TITLE
Add in the ability to launch non xsbti.AppMain classes.

### PR DESCRIPTION
**Pull request by jsuereth**
- Deprecate old mainClass method on appProvider
- Create entryPoint method which represnets class used to launch instead.
- Create PlainApplication to wrap static `main` methods.  Can return
  either Int, Exit or Unit.
- Detect supported 'plain' classes via reflection.
- Add new unit tests appropriate to the feature.

Relatively self-contained.  Probably needs more supported 'raw' interfaces (like passing classpath), but clean enough we can just include in future sbt.

Review by @harrah, cc> @adriaanm @havocp

### CODE REVIEW

**Comment by jsuereth** [comment]
Ok, this should be ready for merge (IMHO)

**Comment by harrah** [comment]
squash and I'll merge, thanks.

**Comment by jsuereth** [comment]
squashed.

**Comment by harrah** [comment]
Merged in b0f6f9483918f7e7aeca321e0ff44f745fd5e167, thanks!

**Pull request closed without merging**
