### PR TITLE
Fixes duplicates in allJars when creating a ScalaInstance

### LINKED ISSUE #5052: do not duplicate artifacts in `allJars` when creating `ScalaInstance`
sbt 1.3.0

## problem
(I guess after migrating to Coursier)
`sbt update` output can contain duplicate artifacts with different configurations (e.g. "optional" and "default") in
```"configuration": { "name": "scala-tool" }```
sbt does not remove duplicates when creating `ScalaInstance`

## notes
relates to:
https://github.com/sbt/sbt/pull/3561
https://youtrack.jetbrains.com/issue/SCL-16208
https://youtrack.jetbrains.com/issue/SCL-16231

### PR DESCRIPTION
**Pull request by unkarjedy**
fixes #5052

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @unkarjedy,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Review by eed3si9n — DISMISSED** [review]
@unkarjedy Thanks! The change LGTM.
Let me know when you signed the CLA.

**Review by eatkins — CHANGES_REQUESTED** [review]
This looks good, but I think it might be better to add the de-duplication inside of `mkScalaInstance` in case duplicate scala library jars are produced through other code paths.

**Comment by unkarjedy** [comment]
@eed3si9n I did =)

**Comment by unkarjedy** [comment]
@eatkins 
I thought about moving it to `mkScalaInstance` but I had some doubts about that. 
This is because I do not see any reasons for duplicates to appear in other places where `mkScalaInstance` is used. For example, if `scalaProvider.jars` returns duplicates it is probably a bug in that method (`/** Returns the scala-library.jar and scala-compiler.jar for this version of Scala. */`)
But if you think that a bit of defensive programming will not hurt, I will add the change =)

**Review by eatkins — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
