### PR TITLE
Add lastGrep command

### PR DESCRIPTION
**Pull request by naferx**
Ref #4072

### CODE REVIEW

**Review by eed3si9n — APPROVED** [review]
LGTM

**Comment by eed3si9n** [comment]
Thanks for this contribution.
I opened a new issue https://github.com/sbt/sbt/issues/4081 for other commands, if you're up for it.

**Comment by naferx** [comment]
@eed3si9n Yeah, I'd like to keep contributing, Thanks! 
I was wondering how to inform to the user that the command is being deprecated  
I have in mind two alternatives: 
 * Include it in the (old) detailed message
 * When the user types the (old) command it raises a warning log

**Comment by dwijnand** [comment]
> When the user types the (old) command it raises a warning log

that would be the more important effect, to me. I don't think there's a built in way to do this in sbt's commands.

**Comment by eed3si9n** [comment]
Could we output log with warning level or something?

**Comment by naferx** [comment]
I'll give it a try over the next days

**Pull request merged**
