### PR TITLE
Update to jansi 1.11

### PR DESCRIPTION
**Pull request by pvlugter**
jline actually bundles jansi. Version used by jline 2.11 is jansi 1.11:

https://github.com/jline/jline2/blob/jline-2.11/pom.xml#L117

### CODE REVIEW

**Comment by harrah** [comment]
Should probably just remove the explicit dependency, right?

**Comment by pvlugter** [comment]
Yeah, could be possible to just remove it. I remember there were some classes that were in jansi but not bundled with jline.

**Comment by pvlugter** [comment]
Here's the diff:

```
Only in jansi/org/fusesource/hawtjni/runtime: ArgFlag.class
Only in jansi/org/fusesource/hawtjni/runtime: ClassFlag.class
Only in jansi/org/fusesource/hawtjni/runtime: FieldFlag.class
Only in jansi/org/fusesource/hawtjni/runtime: JniArg.class
Only in jansi/org/fusesource/hawtjni/runtime: JniClass.class
Only in jansi/org/fusesource/hawtjni/runtime: JniField.class
Only in jansi/org/fusesource/hawtjni/runtime: JniMethod.class
Only in jansi/org/fusesource/hawtjni/runtime: MethodFlag.class
Only in jansi/org/fusesource/hawtjni/runtime: NativeStats$NativeFunction.class
Only in jansi/org/fusesource/hawtjni/runtime: NativeStats$StatsInterface.class
Only in jansi/org/fusesource/hawtjni/runtime: NativeStats.class
Only in jansi/org/fusesource/hawtjni/runtime: T32.class
```

**Comment by harrah** [comment]
https://github.com/jline/jline2/pull/44#discussion_r898102 claims those aren't used.  Still not sure why jline bundles those classes instead of a proper dependency on jansi, though.

**Comment by pvlugter** [comment]
I also don't know why it's bundled. And whether or not those classes are still needed for ansi support.

**Comment by harrah** [comment]
Superseded by 10489768440d66a231f7eed950fc9f4b21912502.

**Pull request closed without merging**
