### PR TITLE
Bump default scala version to 2.12.9

### PR DESCRIPTION
**Pull request by eatkins**
I automatically generated with:

git grep "2.12.8" | \
  cut -d ':' -f1 | uniq | xargs perl -p -i -e "s/2.12.8/2.12.9/"

### CODE REVIEW

**Review by eed3si9n — DISMISSED** [review]
LGTM pending tests passing.

**Comment by eatkins** [comment]
Yeah, I had to make some fixups.

**Comment by eatkins** [comment]
Actually, I missed a few. More changes coming.

**Comment by eatkins** [comment]
Macro paradise isn't published for 2.12.9. I know it technically isn't maintained anymore, but it seems like there should be a new version published for 2.12.9 which I'd naively think should be easy.

https://github.com/scalamacros/paradise/issues/120

**Comment by eatkins** [comment]
Neither is semanticdb.

https://github.com/scalameta/scalameta/issues/1892

**Review by eed3si9n — APPROVED** [review]
Thanks @eatkins

**Pull request merged**
