### PR TITLE
Port fix for #1544 from Dependency to ExtractUsedNames

### PR DESCRIPTION
**Pull request by Duhemm**
The fix for sbt/sbt#1237 was unfortunately not completely correct,
and infinite loops could still occur during the extraction of used
names.

In sbt/sbt#1544, a fix that was robuster and easier to understand
was applied to `/compile/interface/src/main/scala/xsbt/Dependency.scala`
in a similar situation (cyclic chains of original trees in macro
expansions).

This commit ports this fix to `ExtractUsedNames.scala`.

Closes sbt/sbt#1640, sbt/sbt#1610.

### CODE REVIEW

**Comment by typesafe-tools** [comment]
Can one of the admins verify this patch?

**Comment by jsuereth** [comment]
review by @gkossakowski

**Comment by jsuereth** [comment]
also, having seen the discussion, the patch LGTM.  Would like to merge today/tomorrow as we want to issue a 0.13.7-M3 with the new "no blank lines" parser

**Comment by gkossakowski** [comment]
LGTM.
It would be great to have a test case covering the issue, though. @Duhemm, did you manage to figure out the shape of macro definition and application that was causing the infinite loop?

**Comment by Duhemm** [comment]
@gkossakowski I've not tried yet, I'll find some time this week to investigate.

**Pull request merged**
