### PR TITLE
Multi vm tests

### PR DESCRIPTION
**Pull request by backuitist**
You can now execute your tests in multiple forked VM. Within a VM tests are executed sequentially, simplifying and making more reliable the output capture. This works well together with `testHideSuccessfulOutput`.
To activate this feature, forking must be activated.
The number of forked VM is set by `testNumberForkedJvm`. When set to more than one,  intra-vm parallel execution is disabled.

This is being discussed in 
- https://groups.google.com/forum/#!topic/sbt-dev/E7gPr8iu9b4
- https://groups.google.com/d/msg/sbt-dev/w7uli_-gQe8/FyhFYPhLX7sJ

### CODE REVIEW

**Comment by jsuereth** [comment]
Hey @backuitist Any updates on this PR?   I'd love to see parallel forked tests sometime in the future.  Just wanted to sync up on where the discussion dropped off.

**Comment by backuitist** [comment]
Hi @jsuereth i've removed the cglib stuff in https://github.com/backuitist/sbt/commit/b6124e27cc77e23b444f5bbf85932ae67a77d0f1.
I believe the only things that prevent the merge is the Apache common WriterOutputStream and some Jumi code. 
Anyhow, after using this code for some time I came to the conclusion that this feature (capturing the tests output in a single-vm running tests in parallel) is clunky and in the end not so useful.
I'm in fact removing it, and I'll submit another PR. That way you can decide whether you want to have this feature and clean this PR further or get the other one.

**Comment by backuitist** [comment]
There you go: #1112

**Comment by jsuereth** [comment]
Ok, I think I'm going to close this in favor of the other.  The other one isn't mergeable either though.  Something must have changed in the core sbt, you may want to rebase.

**Pull request closed without merging**
