### PR TITLE
Remove deprecated commands -, --, and ---

### PR DESCRIPTION
**Pull request by eed3si9n**
https://github.com/sbt/sbt/commit/86ae3c8c59df546dadb8c62901bac50c175af78a deprecated -, --, and ---.
This removes the deprecated commands.

### CODE REVIEW

**Review by Duhemm — COMMENTED** [review]
Any reason to keep `def compatCommands` (l.155)?

**Comment by eed3si9n** [comment]
I probably could remove it.

**Review by dwijnand — APPROVED** [review]
* dropped compatCommands
* dropped the whole Compat object
* MiMa'd them
* added a reference to the issue

LGTM. Merge (or squash & merge) when ✅

**Comment by eed3si9n** [comment]
Thanks @dwijnand :)

**Pull request merged**
