### PR TITLE
increase scriptedLaunchOpts to -Xmx2048M

### PR DESCRIPTION
**Pull request by eed3si9n**
Ref sbt/sbt#3520

### CODE REVIEW

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild/?sbt=pull/3521/head&deploy_to_bintray=false&run_sbt_community=false">this link.</A>

**Comment by eed3si9n** [comment]
Three jobs (scripted actions/*, scripted java/* package/* etc, and scripted test/*) still failed on the first run.

```
[error] x actions / doc-scala-instance 
[error]  Cause of test exception: {line 1}  Command failed

....

[error] x run / error 
[error]  Cause of test exception: {line 18}  Command succeeded but failure was expected

....

[error] Picked up _JAVA_OPTIONS: -Xmx2048m -Xms512m
[error] Picked up _JAVA_OPTIONS: -Xmx2048m -Xms512m
[error] x tests / fork 
[error]  Cause of test exception: {line 1}  Command failed
```

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild/?sbt=pull/3521/head&deploy_to_bintray=false&run_sbt_community=false">this link.</A>

**Comment by eed3si9n** [comment]
With `_JAVA_OPTIONS` change both actions/* and tests/* passed on the first run, so that might be it.

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild/?sbt=pull/3521/head&deploy_to_bintray=false&run_sbt_community=false">this link.</A>

**Pull request closed without merging**
