### PR TITLE
Feature descriptor optional and check consistency

### PR DESCRIPTION
**Pull request by willb**
These commits refactor ConfigurationParser.getRepositories and add two additional repository options:  `descriptorOptional` and `skipConsistencyCheck`.  These correspond to the Ivy API calls `r.setDescriptor(BasicResolver.DESCRIPTOR_OPTIONAL)` and `r.setCheckconsistency(false)`, where `r` is the resolver in question.  The modifications pass all of the tests in the sbt test task and a couple of additional tests added to exercise the additional flexibility available in `ConfigurationParser`.

### CODE REVIEW

**Comment by harrah** [comment]
Thanks for the cleanup in ConfigurationParser, splitting the commits up appropriately, for expanding the tests, and handling launcher compatibility!  Also, I appreciate you addressing both descriptorOptional and checkConsistency in this pull request.  Further comments inline...

**Comment by harrah** [comment]
Sorry, I didn't intentionally ignore this, but unfortunately GitHub doesn't notify me when new commits are pushed.  Is this ready to be merged?

**Comment by willb** [comment]
Yes, I made all of the changes from your comments.  Thanks!

best,
wb

**Comment by harrah** [comment]
Merged, thanks!  Post-review by @eed3si9n or @jsuereth to verify binary/source compatibility.

**Comment by harrah** [comment]
Thanks for the review Eugene.

**Comment by willb** [comment]
Thanks, Mark and Eugene!

**Comment by shijinkui** [comment]
hi, @willb how to set `skipConsistencyCheck=ture`. In the `repositories` file, I don't find how to set this parameter. If you know, please tell me. Thanks.

**Pull request closed without merging**
