### PR TITLE
Fix AutoPlugins declared at top-level

### PR DESCRIPTION
**Pull request by lpiepiora**
When having `AutoPlugin` declared as top-level classes, an exception is thrown during build load. This pull request is an attempt to fix it. 

The top-level `AutoPlugin` classes are not imported any more, and `autoImport` statements of top level plugins are not prefixed with `_root_`.

The issue happens on sbt 0.13.5-RC5.

```
import _root_.sbt.plugins.IvyPlugin, _root_.sbt.plugins.JvmPlugin, _root_.sbt.plugins.CorePlugin, _root_.sbt.plugins.JUnitXmlReportPlugin, MyPlugin
                                                                                                                                                   ^
sbt.compiler.EvalException: Error parsing imports for expression.
    at sbt.compiler.Eval.checkError(Eval.scala:343)
    at sbt.compiler.Eval.sbt$compiler$Eval$$parseImport(Eval.scala:295)
    at sbt.compiler.Eval$$anonfun$parseImports$1.apply(Eval.scala:289)
    at sbt.compiler.Eval$$anonfun$parseImports$1.apply(Eval.scala:289)
    at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
    at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
```

### CODE REVIEW

**Comment by jsuereth** [comment]
Sorry for not commenting on this earlier.  THe PR was a bit late for 0.13.5.

Would you mind rebasing against 0.13.6 and adding a  test for this use case?   You can find the autoplugins tests here:

https://github.com/sbt/sbt/tree/0.13/sbt/src/sbt-test/project/auto-plugins

and 

https://github.com/sbt/sbt/tree/0.13/sbt/src/sbt-test/project/binary-plugin

Generally this looks like a nice clean fix, just want to make sure we have a test so we don't break this again in future refactorings :)

**Comment by lpiepiora** [comment]
@jsuereth sorry it took me this long, but I've added tests to the places you've recommended.

Do you still want me to rebase it against 0.13.6? I would gladly do it, but frankly speaking I cannot find a branch with that name. 

Should do a pull request to the 0.13?

**Comment by eed3si9n** [comment]
0.13.6 development is happening at `0.13` branch. Please open a pull req against `0.13` & sorry about the confusion.

**Comment by lpiepiora** [comment]
No problem I'll make a pull request against `0.13` and I'll close this one. I think it's stated in the readme to where pull requests should be made. I missed that - sorry about that.

**Pull request closed without merging**
