### PR TITLE
Mirror ivy \'force\' attribute in sbt.

### PR DESCRIPTION
**Pull request by vigdorchik**

### CODE REVIEW

**Comment by harrah** [comment]
Looks good.  In the test, however, it would be good to not use 'force()' initially and verify that 'check-forced' fails.  Then, use force() and verify that it succeeds.  I've done this in other tests by the presence/absence of a file:

```
-> check-forced
$ touch force
> reload
> check-forced
```

That way, you don't have to have two copies of the build file and instead just check whether 'force' exists.

**Comment by vigdorchik** [comment]
@harrah Right. I changed the test (though initially the forced version is used, later on the non-forced is chacked).

**Comment by harrah** [comment]
Drop the pauses and it is ready to be merged.

**Comment by vigdorchik** [comment]
@harrah Done.

**Pull request merged**
