### PR TITLE
Add: hedgehog to supported default testFrameworks

### PR DESCRIPTION
**Pull request by kevin-lee**
Add: hedgehog to supported default testFrameworks

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @Kevin-Lee,

Thank you for your contribution! We really value the time you've taken to put this together.

We see that you have signed the Lightbend Contributors License Agreement before, however, the CLA has changed since you last signed it.
Please review the new CLA and sign it before we proceed with reviewing this pull request:

[https://www.lightbend.com/contribute/cla](https://www.lightbend.com/contribute/cla)

**Comment by kevin-lee** [comment]
I've signed the CLA.

**Review by eed3si9n — APPROVED** [review]
Thanks @Kevin-Lee!

**Comment by kevin-lee** [comment]
@eed3si9n Thank you for the approval!

**Pull request merged**
