### PR TITLE
Fix version parsing

### LINKED ISSUE #3011: NumberFormatException
Create project:
```Scala
name := "long-version"
organization := "xxx"
version := "1.20170314093845.0-87654321"
scalaVersion := "2.12.1"
```

And second project:
```Scala
name := "use-long-version"
organization := "xxx"
version := "1.0"
scalaVersion := "2.12.1"
libraryDependencies := Seq("xxx" %% "long-version" % "1.20170314093845.0-87654321")
```

run `sbt publishLocal` for first one and `sbt update` for second one.

Observe exception:
```
[info] Updating {file:/Users/mareks/work/git/use-long-version/}use-long-version...
java.lang.NumberFormatException: For input string: "20170314093845"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:583)
        at java.lang.Integer.parseInt(Integer.java:615)
        at scala.collection.immutable.StringLike$class.toInt(StringLike.scala:229)
        at scala.collection.immutable.StringOps.toInt(StringOps.scala:31)
        at sbt.cross.CrossVersionUtil$.scalaApiVersion(CrossVersionUtil.scala:45)
        at sbt.cross.CrossVersionUtil$$anonfun$binaryScalaVersion$1.apply(CrossVersionUtil.scala:57)
        at sbt.cross.CrossVersionUtil$$anonfun$binaryScalaVersion$1.apply(CrossVersionUtil.scala:57)
        at sbt.cross.CrossVersionUtil$.binaryVersionWithApi(CrossVersionUtil.scala:65)
        at sbt.cross.CrossVersionUtil$.binaryScalaVersion(CrossVersionUtil.scala:57)
        at sbt.CrossVersion$.binaryScalaVersion(CrossVersion.scala:211)
        at sbt.IvyScala$.sbt$IvyScala$$binaryScalaWarning$1(IvyScala.scala:104)
        at sbt.IvyScala$$anonfun$checkDependencies$1.apply(IvyScala.scala:117)
        at sbt.IvyScala$$anonfun$checkDependencies$1.apply(IvyScala.scala:117)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:251)
        at scala.collection.AbstractTraversable.flatMap(Traversable.scala:105)
        at sbt.IvyScala$.checkDependencies(IvyScala.scala:117)
        at sbt.IvyScala$.checkModule(IvyScala.scala:54)
        at sbt.IvySbt$Module$$anonfun$3.apply(Ivy.scala:177)
        at sbt.IvySbt$Module$$anonfun$3.apply(Ivy.scala:177)
        at scala.Option.foreach(Option.scala:236)
        at sbt.IvySbt$Module.x$6$lzycompute(Ivy.scala:177)
        at sbt.IvySbt$Module.x$6(Ivy.scala:167)
        at sbt.IvySbt$Module.sbt$IvySbt$Module$$moduleDescriptor0$lzycompute(Ivy.scala:167)
        at sbt.IvySbt$Module.sbt$IvySbt$Module$$moduleDescriptor0(Ivy.scala:167)
        at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
        at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
        at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:133)
        at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:57)
        at sbt.IvySbt$$anon$4.call(Ivy.scala:65)
        at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
        at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
        at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
        at xsbt.boot.Using$.withResource(Using.scala:10)
        at xsbt.boot.Using$.apply(Using.scala:9)
        at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
        at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
        at xsbt.boot.Locks$.apply0(Locks.scala:31)
        at xsbt.boot.Locks$.apply(Locks.scala:28)
        at sbt.IvySbt.withDefaultLogger(Ivy.scala:65)
        at sbt.IvySbt.withIvy(Ivy.scala:128)
        at sbt.IvySbt.withIvy(Ivy.scala:125)
        at sbt.IvySbt$Module.withModule(Ivy.scala:156)
        at sbt.IvyActions$.updateEither(IvyActions.scala:168)
        at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1481)
        at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1477)
        at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$121.apply(Defaults.scala:1512)
        at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$121.apply(Defaults.scala:1510)
        at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:37)
        at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1515)
        at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1509)
        at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:60)
        at sbt.Classpaths$.cachedUpdate(Defaults.scala:1532)
        at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1459)
        at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1411)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[error] (*:update) java.lang.NumberFormatException: For input string: "20170314093845"
```
## expectation
Expectation is that there is no such exception

## notes
The problem is not there in case the `addSbtPlugin("io.get-coursier" % "sbt-coursier" % "1.0.0-M15-1")` is used globally. 
Also, problem goes away, if last part in `1.20170314093845.0-87654321` is not numeric, like `1.20170314093845.0-a87654321`, which indicates that there is some kind of problem with pattern matching in `sbt.cross.CrossVersionUtil#scalaApiVersion` - somehow SBT tries to extract Scala version from dependency version's string.

### PR DESCRIPTION
**Pull request by eed3si9n**
Fixes #3011

### CODE REVIEW

**Comment by dwijnand** [comment]
Restarted the tests that failed for flakiness.

Mind explaining what the root cause and fix was? I can't tell the refactoring from the bug fix.

**Review by dwijnand — APPROVED** [review]
Pending Travis CI and an explanation of what the root cause and fix was, this LGTM.

**Comment by eed3si9n** [comment]
sbt tries to parse version number to do some validation, and "1.20170314093845.0-87654321" raised exception because `"20170314093845".toInt` overflows. I changed the regular expression to check if the number is 10 or less digits. Ideally I would've preferred to switch to `Long`, but alas bincompat.

**Comment by dwijnand** [comment]
Not sure how ideal that is, given it would only be pushing the problem from 10 digits to 19.

Ok, so this is more of a workaround than a fix of the underlying issue: before we failed for any number > Int.MaxValue and now we only fail for any number between (Int.MaxValue, 10^11)

**Comment by mr-git** [comment]
To be honest, I still don't understand, why version `1.2.3-4` needs to be parsed, but version `1.2.3-four` doesn't need parsing, when used for dependency resolution...

**Pull request merged**
