### PR TITLE
adding Coursier dependency resolution

### PR DESCRIPTION
**Pull request by andreaTP**
- [X] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md) guidelines

[disclaimer]
before merging make sure we default back to Ivy.

Here is the last bit on integrating the Coursier LM implementation to sbt/sbt.
This PR will be used to trigger the community build as well, possibly before merging.

cc. @eed3si9n @alexarchambault

### CODE REVIEW

**Comment by typesafe-tools** [comment]
A validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt-validator/1127/console">is in progress...</a>

**Comment by typesafe-tools** [comment]
A validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt-validator/1129/console">is in progress...</a>

**Comment by typesafe-tools** [comment]
[//]: # (Refs: pull/4430/head-develop-pull/200/head-pull/270/head-develop)
The validator <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/1129/">has checked</A> the following projects, tested using dbuild, projects built on top of each other.

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | <A HREF="https://github.com/sbt/sbt/pull/4430">pull/4430/head      </A> | sbt/sbt@bf90f35e5e9f07ec6d5ca4318d52e6b2f1f93e37
  zinc              | <A HREF="https://github.com/sbt/zinc/tree/develop">develop             </A> | sbt/zinc@c8e1f5335552bae9a7623d92866a233598fad9fc
  io                | <A HREF="https://github.com/sbt/io/pull/200">pull/200/head       </A> | sbt/io@21742bf69841f8407ed449815be73bfa15a49f8e
  librarymanagement | <A HREF="https://github.com/sbt/librarymanagement/pull/270">pull/270/head       </A> | sbt/librarymanagement@abc6d6927156970ab858285a71e7ad269be2f5cf
  util              | <A HREF="https://github.com/sbt/util/tree/develop">develop             </A> | sbt/util@cd679591d068c9863919feea4f363070c74f2774

:x: The result is: ***FAILED***
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild?sbt=pull/4430/head&zinc=develop&io=pull/200/head&librarymanagement=pull/270/head&util=develop&deploy_to_bintray=false&run_sbt_community=false">(restart)</A>

**Comment by typesafe-tools** [comment]
A validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt-validator/1131/console">is in progress...</a>

**Comment by typesafe-tools** [comment]
[//]: # (Refs: pull/4430/head-develop-pull/200/head-pull/270/head-develop)
The validator <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/1131/">has checked</A> the following projects, tested using dbuild, projects built on top of each other.

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | <A HREF="https://github.com/sbt/sbt/pull/4430">pull/4430/head      </A> | sbt/sbt@bf90f35e5e9f07ec6d5ca4318d52e6b2f1f93e37
  zinc              | <A HREF="https://github.com/sbt/zinc/tree/develop">develop             </A> | sbt/zinc@c8e1f5335552bae9a7623d92866a233598fad9fc
  io                | <A HREF="https://github.com/sbt/io/pull/200">pull/200/head       </A> | sbt/io@21742bf69841f8407ed449815be73bfa15a49f8e
  librarymanagement | <A HREF="https://github.com/sbt/librarymanagement/pull/270">pull/270/head       </A> | sbt/librarymanagement@abc6d6927156970ab858285a71e7ad269be2f5cf
  util              | <A HREF="https://github.com/sbt/util/tree/develop">develop             </A> | sbt/util@cd679591d068c9863919feea4f363070c74f2774

:x: The result is: ***FAILED***
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild?sbt=pull/4430/head&zinc=develop&io=pull/200/head&librarymanagement=pull/270/head&util=develop&deploy_to_bintray=false&run_sbt_community=false">(restart)</A>

**Comment by typesafe-tools** [comment]
A validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt-validator/1133/console">is in progress...</a>

**Comment by typesafe-tools** [comment]
[//]: # (Refs: pull/4430/head-develop-pull/200/head-pull/270/head-develop)
The validator <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/1133/">has checked</A> the following projects, tested using dbuild, projects built on top of each other.

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | <A HREF="https://github.com/sbt/sbt/pull/4430">pull/4430/head      </A> | sbt/sbt@8a8e33ba63250fed4884e7c5dfedeb23375bdd5a
  zinc              | <A HREF="https://github.com/sbt/zinc/tree/develop">develop             </A> | sbt/zinc@c8e1f5335552bae9a7623d92866a233598fad9fc
  io                | <A HREF="https://github.com/sbt/io/pull/200">pull/200/head       </A> | sbt/io@21742bf69841f8407ed449815be73bfa15a49f8e
  librarymanagement | <A HREF="https://github.com/sbt/librarymanagement/pull/270">pull/270/head       </A> | sbt/librarymanagement@abc6d6927156970ab858285a71e7ad269be2f5cf
  util              | <A HREF="https://github.com/sbt/util/tree/develop">develop             </A> | sbt/util@cd679591d068c9863919feea4f363070c74f2774

:x: The result is: ***FAILED***
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild?sbt=pull/4430/head&zinc=develop&io=pull/200/head&librarymanagement=pull/270/head&util=develop&deploy_to_bintray=false&run_sbt_community=false">(restart)</A>

**Comment by andreaTP** [comment]
despite the failre we obtained:
```
[info] Project sbt210-io-------------------: SUCCESS (project rebuilt ok)
[info] Project sbt210-util-----------------: SUCCESS (project rebuilt ok)
[info] Project sbt210-zinc-----------------: SUCCESS (project rebuilt ok)
[info] Project sbt211-io-------------------: SUCCESS (project rebuilt ok)
[info] Project sbt211-librarymanagement----: SUCCESS (project rebuilt ok)
[info] Project sbt211-util-----------------: SUCCESS (project rebuilt ok)
[info] Project sbt211-zinc-----------------: SUCCESS (project rebuilt ok)
[info] Project sbt212----------------------: SUCCESS (project rebuilt ok)
[info] Project sbt212-io-------------------: SUCCESS (project rebuilt ok)
[info] Project sbt212-librarymanagement----: SUCCESS (project rebuilt ok)
[info] Project sbt212-util-----------------: SUCCESS (project rebuilt ok)
[info] Project sbt212-util-interface-------: SUCCESS (project rebuilt ok)
[info] Project sbt212-zinc-----------------: SUCCESS (project rebuilt ok)
```
https://jenkins.scala-sbt.org:8592/job/sbt-validator/1133/console

Should be good enough to proceed, isn't is? :smile:

**Comment by typesafe-tools** [comment]
[//]: # (Refs: pull/4430/head-develop-develop-pull/270/head-develop)
The validator <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/1134/">has checked</A> the following projects, tested using dbuild, projects built on top of each other.

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | <A HREF="https://github.com/sbt/sbt/pull/4430">pull/4430/head      </A> | sbt/sbt@8a8e33ba63250fed4884e7c5dfedeb23375bdd5a
  zinc              | <A HREF="https://github.com/sbt/zinc/tree/develop">develop             </A> | sbt/zinc@c8e1f5335552bae9a7623d92866a233598fad9fc
  io                | <A HREF="https://github.com/sbt/io/tree/develop">develop             </A> | sbt/io@e6529c010c32a93b66f96a027068b7cf160099a0
  librarymanagement | <A HREF="https://github.com/sbt/librarymanagement/pull/270">pull/270/head       </A> | sbt/librarymanagement@abc6d6927156970ab858285a71e7ad269be2f5cf
  util              | <A HREF="https://github.com/sbt/util/tree/develop">develop             </A> | sbt/util@cd679591d068c9863919feea4f363070c74f2774

:white_check_mark: The result is: ***SUCCESS***

The binaries are at https://dl.bintray.com/sbt/maven-snapshots
The new sbt version is: 1.3.0-bin-20181025T102644
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild?sbt=pull/4430/head&zinc=develop&io=develop&librarymanagement=pull/270/head&util=develop&deploy_to_bintray=false&run_sbt_community=false">(restart)</A>

**Comment by typesafe-tools** [comment]
A validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt-validator/1135/console">is in progress...</a>

**Comment by leonardehrenfried** [comment]
This is a fantastic step! Thanks @andreaTP!

**Comment by typesafe-tools** [comment]
[//]: # (Refs: pull/4430/head-develop-develop-pull/270/head-develop)
The validator <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/1135/">has checked</A> the following projects, tested using dbuild, projects built on top of each other.

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | <A HREF="https://github.com/sbt/sbt/pull/4430">pull/4430/head      </A> | sbt/sbt@8a8e33ba63250fed4884e7c5dfedeb23375bdd5a
  zinc              | <A HREF="https://github.com/sbt/zinc/tree/develop">develop             </A> | sbt/zinc@c8e1f5335552bae9a7623d92866a233598fad9fc
  io                | <A HREF="https://github.com/sbt/io/tree/develop">develop             </A> | sbt/io@e6529c010c32a93b66f96a027068b7cf160099a0
  librarymanagement | <A HREF="https://github.com/sbt/librarymanagement/pull/270">pull/270/head       </A> | sbt/librarymanagement@789a4cc09c1d357e98325eacebc22ac1e54fd495
  util              | <A HREF="https://github.com/sbt/util/tree/develop">develop             </A> | sbt/util@cd679591d068c9863919feea4f363070c74f2774

:white_check_mark: The result is: ***SUCCESS***

The binaries are at https://dl.bintray.com/sbt/maven-snapshots
The new sbt version is: 1.3.0-bin-20181025T151651
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild?sbt=pull/4430/head&zinc=develop&io=develop&librarymanagement=pull/270/head&util=develop&deploy_to_bintray=false&run_sbt_community=false">(restart)</A>

**Comment by typesafe-tools** [comment]
A validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt-validator/1138/console">is in progress...</a>

**Comment by typesafe-tools** [comment]
[//]: # (Refs: pull/4430/head-develop-develop-pull/270/head-develop)
The validator <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/1138/">has checked</A> the following projects, tested using dbuild, projects built on top of each other.

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | <A HREF="https://github.com/sbt/sbt/pull/4430">pull/4430/head      </A> | sbt/sbt@1ad89a43406c206496f38156af70dea174750171
  zinc              | <A HREF="https://github.com/sbt/zinc/tree/develop">develop             </A> | sbt/zinc@c8e1f5335552bae9a7623d92866a233598fad9fc
  io                | <A HREF="https://github.com/sbt/io/tree/develop">develop             </A> | sbt/io@e6529c010c32a93b66f96a027068b7cf160099a0
  librarymanagement | <A HREF="https://github.com/sbt/librarymanagement/pull/270">pull/270/head       </A> | sbt/librarymanagement@abc6d6927156970ab858285a71e7ad269be2f5cf
  util              | <A HREF="https://github.com/sbt/util/tree/develop">develop             </A> | sbt/util@cd679591d068c9863919feea4f363070c74f2774

:white_check_mark: The result is: ***SUCCESS***

The binaries are at https://dl.bintray.com/sbt/maven-snapshots
The new sbt version is: 1.3.0-bin-20181026T084504
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild?sbt=pull/4430/head&zinc=develop&io=develop&librarymanagement=pull/270/head&util=develop&deploy_to_bintray=false&run_sbt_community=false">(restart)</A>

**Comment by andreaTP** [comment]
to go ahead I will need a release of LM ( `M1` or something) comprehending the coursier PR.

**Comment by eed3si9n** [comment]
See https://travis-ci.org/eed3si9n/sbt/builds/448039304

Out of 78 dependency-management tests, looks like only 30% of the tests are passing - https://travis-ci.org/eed3si9n/sbt

 - [ ] dependency-management/artifact
 - [ ] dependency-management/cache-classifiers
 - [ ] dependency-management/cache-local
 - [ ] dependency-management/cache-resolver
 - [ ] dependency-management/cache-update
 - [ ] dependency-management/cached-resolution-circular
 - [ ] dependency-management/cached-resolution-classifier
 - [ ] dependency-management/cached-resolution-configurations
 - [ ] dependency-management/cached-resolution-conflicts
 - [ ] dependency-management/cached-resolution-exclude
 - [ ] dependency-management/cached-resolution-force
 - [ ] dependency-management/cached-resolution-interproj
 - [x] dependency-management/cached-resolution-overrides
 - [x] dependency-management/chainresolver
 - [ ] dependency-management/circular-dependency
 - [x] dependency-management/classifier
 - [ ] dependency-management/compiler-bridge-binary
 - [x] dependency-management/configurations
 - [ ] dependency-management/configurations-to-retrieve
 - [x] dependency-management/conflict
 - [ ] dependency-management/conflict-manager
 - [x] dependency-management/conflict-manager-with-org
 - [x] dependency-management/cross-ivy-maven
 - [ ] dependency-management/default-artifact
 - [x] dependency-management/default-resolvers
 - [ ] dependency-management/deliver-artifacts
 - [x] dependency-management/dynamic-revision
 - [x] dependency-management/exclude-bundle
 - [ ] dependency-management/exclude-dependencies
 - [ ] dependency-management/exclude-scala
 - [ ] dependency-management/exclude-transitive
 - [ ] dependency-management/ext-pom-classifier
 - [ ] dependency-management/extra
 - [x] dependency-management/force
 - [ ] dependency-management/force-update-period
 - [x] dependency-management/gh-1484-npe
 - [ ] dependency-management/info
 - [x] dependency-management/inline-dependencies-a
 - [ ] dependency-management/invalidate-internal
 - [ ] dependency-management/ivy-settings-a
 - [ ] dependency-management/ivy-settings-b
 - [ ] dependency-management/ivy-settings-c
 - [ ] dependency-management/ivy-settings-multi-a
 - [ ] dependency-management/ivy-settings-multi-b
 - [ ] dependency-management/latest-local-plugin
 - [ ] dependency-management/make-pom
 - [ ] dependency-management/make-pom-type
 - [ ] dependency-management/metadata-only-resolver
 - [x] dependency-management/module-confs
 - [x] dependency-management/module-name
 - [ ] dependency-management/multiple-classifiers
 - [ ] dependency-management/no-file-fails-publish
 - [x] dependency-management/override
 - [x] dependency-management/override2
 - [ ] dependency-management/parent-publish
 - [ ] dependency-management/pom-advanced
 - [ ] dependency-management/pom-classpaths
 - [ ] dependency-management/pom-packaging
 - [ ] dependency-management/pom-parent-pom
 - [ ] dependency-management/pom-scope
 - [ ] dependency-management/pom-type
 - [ ] dependency-management/provided
 - [ ] dependency-management/provided-multi
 - [x] dependency-management/publish-to-maven-local-file
 - [ ] dependency-management/retrieve-managed-sync
 - [x] dependency-management/scala-home
 - [ ] dependency-management/scala-organization
 - [x] dependency-management/scala-organization-version-check
 - [ ] dependency-management/scala-tests-only
 - [x] dependency-management/scala-version-check-exempt
 - [ ] dependency-management/snapshot-resolution
 - [ ] dependency-management/sources
 - [x] dependency-management/t468
 - [ ] dependency-management/test-artifact
 - [x] dependency-management/transitive-excludes
 - [x] dependency-management/transitive-version-range
 - [ ] dependency-management/update-sbt-classifiers
 - [ ] dependency-management/url

Also note that bunch of other scripted tests are failing 

```
[info] [error] (b / publish) java.lang.IllegalStateException: Ivy file not found in cache for org.example#b_2.12;0.1.0-SNAPSHOT!
```

**Comment by andreaTP** [comment]
@eed3si9n talking about:
> [info] [error] (b / publish) java.lang.IllegalStateException: Ivy file not found in cache for org.example#b_2.12;0.1.0-SNAPSHOT!

this error appear because we are still using Ivy to `publish`, looks like Ivy expect to have fetched by itself dependencies, i.e. you will overcome it by re-resolving packages with Ivy once.

**Comment by typesafe-tools** [comment]
A validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt-validator/1151/console">is in progress...</a>

**Comment by typesafe-tools** [comment]
[//]: # (Refs: pull/4430/head-develop-develop-develop-develop)
The validator <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/1151/">has checked</A> the following projects, tested using dbuild, projects built on top of each other.

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | <A HREF="https://github.com/sbt/sbt/pull/4430">pull/4430/head      </A> | sbt/sbt@f4add1bb953946a28f084cfe52644576d477fe01
  zinc              | <A HREF="https://github.com/sbt/zinc/tree/develop">develop             </A> | sbt/zinc@28c35225b81333e6005440741c680b85d21133b6
  io                | <A HREF="https://github.com/sbt/io/tree/develop">develop             </A> | sbt/io@e6529c010c32a93b66f96a027068b7cf160099a0
  librarymanagement | <A HREF="https://github.com/sbt/librarymanagement/tree/develop">develop             </A> | sbt/librarymanagement@92f8b75557f9a29edf1cc7a6c9606f0b7446c60c
  util              | <A HREF="https://github.com/sbt/util/tree/develop">develop             </A> | sbt/util@cd679591d068c9863919feea4f363070c74f2774

:white_check_mark: The result is: ***SUCCESS***

The binaries are at https://dl.bintray.com/sbt/maven-snapshots
The new sbt version is: 1.3.0-bin-20181030T091902
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild?sbt=pull/4430/head&zinc=develop&io=develop&librarymanagement=develop&util=develop&deploy_to_bintray=false&run_sbt_community=false">(restart)</A>

**Comment by eed3si9n** [comment]
I mentioned this on Gitter, but I'll repeat here.
Coursier plugin seems to generate `ivy.xml` in:
- https://github.com/coursier/sbt-coursier/blob/master/modules/sbt-coursier/src/main/scala/coursier/CoursierPlugin.scala

```scala
  def makeIvyXmlBefore[T](
    task: TaskKey[T],
    shadedConfigOpt: Option[(String, String)]
  ): Setting[Task[T]] =
    task := task.dependsOn(Def.task {
      val currentProject = {
        val proj = coursierProject.value
        val publications = coursierPublications.value
        proj.copy(publications = publications)
      }
      IvyXml.writeFiles(currentProject, shadedConfigOpt, ivySbt.value, streams.value.log)
    }).value
```

- https://github.com/coursier/sbt-coursier/blob/master/modules/sbt-coursier/src/main/scala/coursier/IvyXml.scala

**Comment by alexarchambault** [comment]
FYI, I'm currently refactoring [sbt-coursier](https://github.com/coursier/sbt-coursier) so that:
- it offers a module with implementations for sbt/librarymanagement,
- it offers an sbt plugin, `sbt-lm-coursier`, setting `dependencyResolution`, that should be compatible almost as-is with the current `sbt-coursier`, passing the scripted tests of sbt-coursier too,
- if possible, `sbt-lm-coursier` should shade coursier itself.

The first two points started fine in https://github.com/coursier/sbt-coursier/pull/5, currently splitting that in clean commits in https://github.com/coursier/sbt-coursier/pull/6 and subsequent PRs.

If all goes well, I'll probably rename the former `sbt-coursier` to `sbt-coursier-legacy`, and the new `sbt-lm-coursier` to `sbt-coursier`.

Then, I guess we can check if `sbt-lm-coursier` passes tests under [`sbt/src/sbt-test/dependency-management` in sbt](https://github.com/sbt/sbt/tree/develop/sbt/src/sbt-test/dependency-management). If it does, then I guess we could consider including it as is in sbt, so that coursier is used by default in it. (Also, its `DependencyResolution` implem could be used here-or-there in sbt instead of the Ivy one.)

**Comment by alexarchambault** [comment]
^ I think that provides a clear path towards the use of coursier by sbt. Opinions?

**Comment by alexarchambault** [comment]
This all aims at finishing the prior work of @leonardehrenfried and @andreaTP.

**Comment by andreaTP** [comment]
@alexarchambault your effort is pretty much appreciated, but currently the blocker to have a proper implementation is that the logic for generating the POM file for publishing is pretty hard to replicate ( talking about this: https://github.com/coursier/sbt-coursier/blob/22595d07affff833f42755cb157ca91322267274/modules/sbt-coursier/src/main/scala/coursier/Tasks.scala#L237 ) cc. @eed3si9n

**Comment by eed3si9n** [comment]
Closing this in favor of https://github.com/sbt/sbt/pull/4614

**Pull request closed without merging**
