### PR TITLE
ignore hidden build files from the build.

### PR DESCRIPTION
**Pull request by j-keck**
sbt processes also hidden build files, which can be problematic:

https://groups.google.com/forum/#!topic/sbt-dev/MpaSiCcAHO4

---

this patch filters hidden build files when the project are loaded (in Load.discoverProjects)

### CODE REVIEW

**Comment by typesafe-tools** [comment]
Can one of the admins verify this patch?

**Comment by eed3si9n** [comment]
Generally LGTM.

Could you add an entry in https://github.com/sbt/sbt/blob/0.13/notes/0.13.8.markdown?
Also do you think it's possible to write a test for this in a form of [scripted test](https://github.com/sbt/sbt/tree/0.13/sbt/src/sbt-test/project)? Maybe one one task generate as `.#build` file and then, issue `reload`?

**Comment by j-keck** [comment]
done,

without the patch the test fails with:

```
[error] /tmp/sbt_954fce2b/ignore-hidden-build-files/.build.sbt:0: error: not found: value invalid
[error] invalid build file content
[error] ^
[info] [error] Type error in expression
[info] Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? 
[error] x project / ignore-hidden-build-files
[error]    {line 6}  Command failed: Remote sbt initialization failed
[trace] Stack trace suppressed: run last root/*:scripted for the full output.
[error] (root/*:scripted) Failed tests:
[error]     project / ignore-hidden-build-files
```

with the patch the test succeeds

```
About to run tests: 
 * project/ignore-hidden-build-files

Running project / ignore-hidden-build-files
[success] Total time: 21 s, completed Nov 25, 2014 9:54:19 AM
```

**Comment by eed3si9n** [comment]
Thanks for the contribution!

**Pull request merged**
