### PR TITLE
Do not normalize/dealias type in api extraction phase

### LINKED ISSUE #726: Spurious incremental recompilation due to invalid value for OVERRIDE flag
The incremental spuriously (on whitespace change) recompiles dependencies of a file that refers to type alias of certain kind. The example code explains it the best:

``` scala
// Foo.scala
object Foo {
  class Inner { type Xyz }
  type TypeInner = Inner { type Xyz = Int }
}

// Bar.scala
object Bar { 
  def bar: Foo.TypeInner = null
}

// Impl.scala
class Impl {
  def bleep = Bar.bar
}
```

Now, if you compile those 3 files and make a whitespace change to `Bar.scala` it'll trigger recompilation of `Impl.scala`.

If you run this test with api-diff branch merged you can easily see what's going on:

```
[info] [debug] Detected a change in a public API:
[info] [debug] --- /private/var/folders/0k/31jh6c293n31_tjkxmk90jjh0000gn/T/sbt_14084e7/inc-abstract-type-override/src/main/scala/Bar.scala
[info] [debug] +++ /private/var/folders/0k/31jh6c293n31_tjkxmk90jjh0000gn/T/sbt_14084e7/inc-abstract-type-override/src/main/scala/Bar.scala
[info] [debug] @@ -25,8 +25,8 @@
[info] [debug]  ^inherited^ final def $isInstanceOf[ java.lang.Object.T0 >: scala.this#Nothing <: scala.this#Any](): scala.this#Boolean
[info] [debug]  ^inherited^ final def $asInstanceOf[ java.lang.Object.T0 >: scala.this#Nothing <: scala.this#Any](): <java.lang.Object.T0>
[info] [debug]  def bar: this#Outer#Inner with java.lang.this#Object with scala.this#Any
[info] [debug]  {
[info] [debug]  
[info] [debug] -type Xyz = scala.this#Int
[info] [debug] +override type Xyz = scala.this#Int
[info] [debug]  }
[info] [debug]  }
```

This modifier appears and disappears depending on whether you recompile all files together or separately. Ultimately, this is a bug in the compiler related to separate compilation. The underlaying issue is tracker here: https://issues.scala-lang.org/browse/SI-7361

### LINKED ISSUE #736: Sbt fails to detect change of structure when type aliases dealias to the same type
Consider the following code:

``` scala
// Foo.scala
object Foo {
  type S1 = String
  type S2 = String
  def foo: S1 = null
}

// Bar.scala
class Bar {
  // inferred return type is Foo.S1; this type is pickled in the bytecode of Bar
  def bar = Foo.foo
}
```

Now if you change return type of `Foo.foo` to `Foo.S2` sbt won't detect this as a change to the structure of `Foo` and won't recompile `Bar`. Therefore incorrect (stale) type will be stored in pickled information for `Bar`. This violates the invariant that incremental compilation always leads to the same end result (in terms of bytecode in this case) as full, clean compile.

The reason is that sbt eagerly normalizes (which involves dealiasing) types when it indexes structure of compilation units, see:
https://github.com/sbt/sbt/blob/bef8ce05b900e393f2437bf0a18a7e0c1a622343/compile/interface/src/main/scala/xsbt/API.scala#L317

Note: the method is wrongly called `dealias` since it performs normalization.

### PR DESCRIPTION
**Pull request by gkossakowski**
In summary, this series of commits:
- drops type normalization in api phase
- fixes #726 and adds test case covering it
- fixes #736 and adds test case covering it
- addresses problem with main method detection after
  dropping type dealiasing

As explained in #736, the api phase cannot normalize/dealias types
because it might miss changes to structure when two type aliases
that dealias to the same type are involved.

It turns out there's no test case that breaks if we remove type
normalization/dealiasing apart from main method detection.

The main method detection implemented by `xsbt.api.Discovery` has a design
flaw because it works with `xsbti.api.*` data structures that represent
structure of Scala program extracted by API phase. That phase runs before
erasure so it extracts unerased, Scala types. However, a main method is
defined in terms of JVM bytecode types so detection should be implemented
by scanning the bytecode and not Scala types. That would involve adding
support for bytecode scanning and rewriting the whole Discovery object.
Instead of doing that I decided to just add detection of
`scala.Predef.String` type in addition to `java.lang.String` type.
In order to do that I had to hack `Discovery.simpleName` method
implementation. This hack doesn't make it any worse as it was already
hacked in rather arbitrary fashion.

Dropping type normalization also fixes #726 by not running into
stale cache in Scala compiler problem described in SI-7361.

### CODE REVIEW

**Comment by jsuereth** [comment]
Greg - I'm nervous that this change is user facing, particularly for SNAP.  I'm going to issue a test case of our external-to-core-sbt use of Discovery.

Also, I'm rather concerned about the fallout of the switch to how names are sanitized to only include String.   This is the current mechanism of writing any kind of integration testing code that inspects the current state of the project for available classes (well, in fact any task that wants to grab available classes, like run-main).  You may be pushing the aliased-name madness from the compiler on all sbt users.   That's what the original method was intended to avoid.

In any case, I'll get you a test case ASAP.

**Comment by gkossakowski** [comment]
@jsuereth: thanks for review and pinging me.

Yes, I'd like to see a test case which my change breaks.

As I demonstrated with my own test case incremental compiler cannot dealias type for _correctness_. I don't know what's the exact contract of Discovery that it _tries_ to implement but to me the design of that whole file is broken. As I mentioned in commit message, main method is a jvm-level concept and we try to use Scala types to model it. This a doomed to fail or require elaborate logic (essentially: reimplementation of type erasure).

Type aliases are not madness of Scala compiler, they are types as any other.

**Comment by gkossakowski** [comment]
@jsuereth: Also could you point me to how snap uses Discovery?

**Comment by gkossakowski** [comment]
@jsuereth: ping

@harrah: what's your take on this PR?

**Comment by jsuereth** [comment]
Greg - 

Type aliases are great, but when we talk about the "Discovery" API, we're talking about finding methods/classes using scala types.  However, most users (myself included) expect aliases to be normalized.  We need to do what's best for the user.  Since Discovery is a public facing API - you'll have to provide a deprecation period for the current behavior (of normalized types) if you'd like to change it.

Is there any kind of alternative workaround that won't hit the deprecation policy?

**Comment by harrah** [comment]
Heh, ignore Josh's hyperbole (type aliases and madness).  In any case, there are two separate issues now. 
1. The Discovery API has presented a dealiased API, people depended on that, and now it is changing.
2. #736, which concerns the correct behavior for incremental compilation.

Let's keep discussions that are specific to incremental compilation correctness on #736.  Discussions on implementation and discovery should be here.  I will wait for Josh's links and tests for discovery before commenting there.  I will separately comment on this PR and #736.

**Comment by harrah** [comment]
I disagree that there is a design flaw in main method detection.  It is indeed an approximation, but it is an intentional tradeoff that works well in practice.  Dropping dealiasing may complicate the picture, but this main method detection was/is essentially free.

**Comment by gkossakowski** [comment]
@jsuereth: before we start talking about deprecation period I'd really like to understand what do I break. The discovery returns an instance of this class:

`Discovered(baseClasses: Set[String], annotations: Set[String], hasMain: Boolean, isModule: Boolean)`

With my fix to add support for `Predef.String` the `hasMain` will have the correct value. The `isModule` won't be affected. I don't know what would you use `baseClasses` and `annotations` for but if they don't involve type alises (which mostly likely they don't) then you are good.

**Comment by gkossakowski** [comment]
@harrah: I could see your argument that this class is good enough for internal sbt use. I still think it would be better if you just scanned bytecode and not depend on details of incremental compiler but I don't have strong preference.

If we are fine with approximation then tuning this approximation to deal with `String` type alias should be equally fine, right?

**Comment by jsuereth** [comment]
@gkossakowski Base-classes and annotations are the specific case I'm concerned about.

This API is used to discover classes in your project that do things.  For example, in the-project-that-was-snap, we look for anything that extends "xsbti.Main".  For convenience purposes, this may be behind a type alias to clean the API (at least at one time I had it like that before the final implementation, which uses a trait).   This API needs to return the top-level classes that are extended by a given class, so we can find those that we should attempt to run as part of integration tests.

The annotation is doubley true.  We want everyone that writes @Test on their class, regardless of if you have "type Test = foo.bar.Test" or what not.  This is included for trying to implement "byte code generators".

Now, in terms of whether its ok to make the change, it's something we should discuss.   Like I said, this guy is public, if undocumented.  Let's Document what it does, and figure out how to evolve if.  IF we want to change semanticcs, probably the best thing to do is hit the simple-build-tool list with the proposed change and see if people complain, because the fact is we _don't know_ who may be affected right now, so you can't make any assumptions.

Even so, I'm not a fan of this level of change without a deprecation period for the previous behavior (and additional documentation).

Let's follow some boy-scout rule here.  The Discovery API is something that needs to be documented, and is on my list for the 1.0 documentation spree.

**Comment by gkossakowski** [comment]
@jsuereth: is there any reason why all of what you described cannot be done with Java reflection. All what you described should be done with Java reflection.

Also, I'll ask on sbt mailing list as you advised. However, now I have to catch my plane.

**Comment by jsuereth** [comment]
@gkossakowski As mark mentioned, this was performed with java reflection at one point, but it causes a significant slowdown, hence the move to the current method.   

Like I said before:  Let's understand what the current API is exposing and how it's used and look for acceptible solutions.   While Mark may have other opinions, I'm very hesitant on this change as it stands.   Especially in sbt, we need to think of the user first.   I think just documenting what the DIscovery API is and what it's used for can help you in trying to push some patches.  I'm more than happy to clarify now that I have some free time (with the caveat that the impending release is threatening my free time every day, and luckily it didn't hit this afternoon).

And yes, let's get some discussion on the mailing list.  Like I said, i'm not sure of the impact, but I worry that not de-aliasing will cause issues with users of DIscovery.

**Comment by gkossakowski** [comment]
Where did Mark mentioned that Discovery was invented for performance
reasons? Also, there are a lot of Java libs and frameworks that rely
heavily on reflection and perform just fine. I'd like to understand that
issue.

On Thursday, April 25, 2013, Josh Suereth wrote:

> @gkossakowski https://github.com/gkossakowski As mark mentioned, this
> was performed with java reflection at one point, but it causes a
> significant slowdown, hence the move to the current method.
> 
> Like I said before: Let's understand what the current API is exposing and
> how it's used and look for acceptible solutions. While Mark may have other
> opinions, I'm very hesitant on this change as it stands. Especially in sbt,
> we need to think of the user first. I think just documenting what the
> DIscovery API is and what it's used for can help you in trying to push some
> patches. I'm more than happy to clarify now that I have some free time
> (with the caveat that the impending release is threatening my free time
> every day, and luckily it didn't hit this afternoon).
> 
> And yes, let's get some discussion on the mailing list. Like I said, i'm
> not sure of the impact, but I worry that not de-aliasing will cause issues
> with users of DIscovery.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/sbt/sbt/pull/737#issuecomment-17052120
> .

## 

Grzegorz Kossakowski
Scalac hacker at Typesafe http://www.typesafe.com/
twitter: @gkossakowski http://twitter.com/gkossakowski
github: @gkossakowski http://github.com/gkossakowski

**Comment by jsuereth** [comment]
@gkossakowski a quote from above """I disagree that there is a design flaw in main method detection. It is indeed an approximation, but it is an intentional tradeoff that works well in practice. Dropping dealiasing may complicate the picture, but this main method detection was/is essentially free."""

Discovery was added because we already were looking at the information in inceremental compiler, so it was more efficient to go after it here.  It became the canonical way in sbt to inspect for classes/annotations etc.

A lot of java libs and frameworks may use annotations, but e.g. maven still uses class naming conventions.   In SBT we tried to grab "more correct" behavior via this "Analysis" and "Discovery" api.   It was "essentially" free, and had little performance hit, whereas opening and scanning class files and directories _does_ have a non-negligible hit.

**Comment by jsuereth** [comment]
Also, let's try to be a little more pragmatic.  Are you willing to alter  semantics of discovery _and_ implement a bytecode introector _and_ show us that it has little performance impact, _and_ test that we don't break existing user builds via the new mechanism?

Is there an alternative where we do not need to invent a new subsystem for discovery?

I hope you understand why im saying you need to deprecrate and fix in a later version.

**Comment by gkossakowski** [comment]
@jsuereth: by "essentially free" I understood that it was easy to implement. @harrah did you have performance in mind when you said that?

I think we exceeded budget of discussing this PR. I'll raise more general issue of encapsulating incremental compiler implementation details because I have much more involved changes coming so we need to understand the problem a little better.

I'm closing this PR, I'll resubmit with normalization removed but dealiasing kept.

**Comment by gkossakowski** [comment]
I accidentally reopened this issue but clicking the wrong button on issue list. I'm very sorry for that. Closing again.

**Pull request closed without merging**
