### PR TITLE
Move NameHashing from incremental to api subproject.

### PR DESCRIPTION
**Pull request by gkossakowski**
It should have been there from the beginning because NameHashing is tied
to internals of the API subproject.

It was added to incremental subproject by mistake.

### CODE REVIEW

**Comment by gkossakowski** [comment]
Review by @eed3si9n

**Comment by jsuereth** [comment]
errors look legitimate

**Comment by gkossakowski** [comment]
Seems like I broke something while cherry-picking. I'll reopen once I sort it out.

**Comment by gkossakowski** [comment]
Compilation failure fixed.

**Comment by jsuereth** [comment]
Nice, LGTM

**Pull request merged**
