### PR TITLE
Bump to latest version of ivy.

### LINKED ISSUE #2118: Merge Ant parent license fix
We need to merge https://github.com/apache/ant-ivy/pull/7 into this repo's Ant fork to fix https://github.com/sbt/sbt-license-report/issues/7

### PR DESCRIPTION
**Pull request by jsuereth**
Fixes #2118 

Review by @eed3si9n

### CODE REVIEW

**Comment by eed3si9n** [comment]
LGTM pending Travis

**Comment by jsuereth** [comment]
ok, we'll have to wait for the ivy jars to propogate before we can test this.

**Comment by eed3si9n** [comment]
Merged

**Comment by dwijnand** [comment]
Should this have notes?

**Pull request merged**
