### PR TITLE
Bump to our own release of ivy 2.4.x

### PR DESCRIPTION
**Pull request by jsuereth**
- Bumps to our own branch of ivy (github.com/sbt/ivy)
- Includes a ~50% improvement in performance when dealing
  with maven resolution + dependencyManagement fun
- Tweaks to API differences between Ivy 2.3 + 2.4

Review by @eed3si9n 

cc> @Kewpie007

### CODE REVIEW

**Comment by manuelbernhardt** [comment]
+1000

**Comment by eed3si9n** [comment]
Merged

**Comment by shikhar** [comment]
@jsuereth is there an upstream IVY issue for "Includes a ~50% improvement in performance when dealing with maven resolution + dependencyManagement fun"

**Comment by jsuereth** [comment]
@shikhar yes, https://issues.apache.org/jira/browse/IVY-1465

**Pull request merged**
