### PR TITLE
Add improved classloader construction short circuit

### PR DESCRIPTION
**Pull request by eatkins**
In order for sbt to function well, it needs the test interface, jansi
and forked jline jars provided by a classloader that is parent to all
other sbt classloaders. To do this for just the test interface jar, I
just checked if the top loader in the app configuration had the correct
name. Now that there are three jars, this is more complicated so I
updated the launcher to create a top loader with the method getEarlyJars
implemented and returning the three needed jars. This is a much more
scalable design.

If sbt is entered with a configuration that does not have a top loader
with the getEarlyJars method defined, then we just fall back on
constructing the default layered classlaoder from the configuration
classpath.

The motivation for this change is that I discovered that sbt immediately
crashed when I tried to run a non-snapshot version. After this change, I
verified that both snapshot and non-snapshot versions of the latest sbt
code could load with both an obsolete and up-to-date launcher.

### CODE REVIEW

**Comment by eed3si9n** [comment]
> The motivation for this change is that I discovered that sbt immediately
crashed when I tried to run a non-snapshot version.

Could you elaborate here? Is there something wrong in the current develop branch?

**Comment by eatkins** [comment]
That’s right. I published local a build with a version like `1.4.0-jline` and then I ran `sbt -Dsbt.version=1.4.0-jline`. sbt immediately crashed on startup. For some reason that I admittedly don’t fully understand, snapshot versions didn’t crash. I didn’t test a nightly build but I suspect one would crash on startup based on this experience.

**Comment by eed3si9n** [comment]
I just took current HEAD (https://github.com/sbt/sbt/commit/6110734383d9ce719cc48abd16557d2aaa58412e) and publishLocal'ed `1.4.0-LOCAL20200712`, and as far as I can tell, it worked fine:

```
$ sbt new scala/scala-seed.g8
[info] welcome to sbt 1.3.12 (AdoptOpenJDK Java 1.8.0_232)
[info] loading settings for project global-plugins from idea.sbt,vimquit.sbt,plugins.sbt,pgp.sbt ...
[info] loading global plugins from /Users/eed3si9n/.sbt/1.0/plugins
[info] set current project to tmp (in build file:/private/tmp/)
[info] set current project to tmp (in build file:/private/tmp/)

A minimal Scala project.

name [Scala Seed Project]: helloo

Template applied in /private/tmp/./helloo

[Ga:/tmp]$ cd helloo
[Ga:/tmp/helloo]$ vim
[Ga:/tmp/helloo]$ cat project/build.properties
sbt.version=1.4.0-LOCAL20200712
[Ga:/tmp/helloo]$ sbt
[info] [launcher] getting org.scala-sbt sbt 1.4.0-LOCAL20200712  (this may take some time)...
:: loading settings :: url = jar:file:/usr/local/Cellar/sbt/1.3.12/libexec/bin/sbt-launch.jar!/org/apache/ivy/core/settings/ivysettings.xml
:: loading settings :: url = jar:file:/usr/local/Cellar/sbt/1.3.12/libexec/bin/sbt-launch.jar!/org/apache/ivy/core/settings/ivysettings.xml
:: loading settings :: url = jar:file:/usr/local/Cellar/sbt/1.3.12/libexec/bin/sbt-launch.jar!/org/apache/ivy/core/settings/ivysettings.xml
:: loading settings :: url = jar:file:/usr/local/Cellar/sbt/1.3.12/libexec/bin/sbt-launch.jar!/org/apache/ivy/core/settings/ivysettings.xml
:: loading settings :: url = jar:file:/usr/local/Cellar/sbt/1.3.12/libexec/bin/sbt-launch.jar!/org/apache/ivy/core/settings/ivysettings.xml
:: loading settings :: url = jar:file:/usr/local/Cellar/sbt/1.3.12/libexec/bin/sbt-launch.jar!/org/apache/ivy/core/settings/ivysettings.xml
:: loading settings :: url = jar:file:/usr/local/Cellar/sbt/1.3.12/libexec/bin/sbt-launch.jar!/org/apache/ivy/core/settings/ivysettings.xml
:: loading settings :: url = jar:file:/usr/local/Cellar/sbt/1.3.12/libexec/bin/sbt-launch.jar!/org/apache/ivy/core/settings/ivysettings.xml
:: retrieving :: org.scala-sbt#boot-app
        confs: [default]
        89 artifacts copied, 0 already retrieved
[info] welcome to sbt 1.4.0-LOCAL20200712 (AdoptOpenJDK Java 1.8.0_232)
[info] loading settings for project global-plugins from idea.sbt,pgp.sbt,plugins.sbt,vimquit.sbt ...
[info] loading global plugins from /Users/eed3si9n/.sbt/1.0/plugins
[info] loading project definition from /private/tmp/helloo/project
[info] Compiling 1 Scala source to /private/tmp/helloo/project/target/scala-2.12/sbt-1.0/classes ...
[info] Done compiling.
[info] loading settings for project root from build.sbt ...
[info] set current project to helloo (in build file:/private/tmp/helloo/)
sbt:helloo>
[info] sbt server started at local:///Users/eed3si9n/.sbt/1.0/server/ecfbc4587d5c01fce0e4/sock
sbt:helloo> compile
[info] Compiling 1 Scala source to /private/tmp/helloo/target/scala-2.13/classes ...
[info] Done compiling.
```

**Comment by eatkins** [comment]
Interesting. The issue was real and repeatable for me and fixed by this change. I wonder what is different between our configurations. Regardless, the old code was terrible and this is an improvement. I meant to fix it before #5620.

**Review by eed3si9n — APPROVED** [review]

**Pull request merged**
