### PR TITLE
support binary version in launcher

### PR DESCRIPTION
**Pull request by eed3si9n**
See [support for _2.10 suffix by default in launchconfig](https://groups.google.com/d/topic/simple-build-tool/Wsyjmj_ASU8/discussion).
### steps

Save the following as `/Users/foo/bar/launchconfig`.

```
[app]
  version: 1.0.1
  org: org.scalaxb
  name: scalaxb
  class: scalaxb.compiler.SbtApp
[scala]
  version: 2.10.0
[repositories]
  sonatype-public: https://oss.sonatype.org/content/repositories/public/
  maven-central
```

Then run:

```
$ java -Xmx1G -jar ~/Applications/sbt/sbt-launch-0.12.0.jar @"/Users/foo/bar/launchconfig"
```
### problem

```
Getting org.scalaxb scalaxb_2.10.0 1.0.1 ...

:: problems summary ::
:::: WARNINGS
        module not found: org.scalaxb#scalaxb_2.10.0;1.0.1
```
### what this changes
1. `cross-versioned` property is expanded to `true|false|none|binary|full`.
2. `cross-versioned` now defaults to `binary`.
3. when `cross-versioned` is `binary` it uses `LaunchCrossVersion.binaryScalaVersion(sv)` to build the _2.10 style suffix.

### CODE REVIEW

**Comment by harrah** [comment]
This looks good overall.

**Comment by eed3si9n** [comment]
Refactored to Java enum. Btw can we get rid of one of the launcher specs?

**Comment by harrah** [comment]
If you want to make sure that `launcher.specification` is completely merged into `Detailed-Topics/Launcher`, go for it.

**Comment by eed3si9n** [comment]
Added catch all clause with an error message for string parsing.
Also checked the `launcher.specification`. I found a few outdated or missing stuff, but nothing new, so deleted it.

**Comment by harrah** [comment]
New problem, unfortunately.  Because `sbt.CrossVersionUtil` gets included in the launcher, it will be loaded from the launcher for the main sbt as well.  However, it has been processed with ProGuard, so it is missing some needed methods.  You can see this by running `scripted/actions`, for example.

One option is to put it in `sbt.cross.CrossVersionUtil` and configure ProGuard to keep everything in `sbt.cross.*`.  This seems fragile, though.  The launcher will prevent an application from loading classes in `xsbt.boot` (see `BootFilteredLoader.scala`) and this could either be extended to exclude `sbt.cross` or CrossVersionUtil.scala could be processed (pre or post) to be in `xsbt.boot` for the launcher and `sbt.cross` for main sbt.

**Comment by jsuereth** [comment]
if I get a vote, I think hiding the CrossVersionUtil inside the launcher and allowing sbt to load its own version is definitely the way to go.  So I'd vote for the sbt.cross -> xsbt.boot post processing for the launcher.

**Comment by eed3si9n** [comment]
@harrah @jsuereth so if I'm understanding the issue correctly, ProGuard is chopping up `sbt/CrossVersionUtil*.class` in the launcher jar so the references from main is broken.
And both your suggestions are to duplicate the source code into different packages: `sbt.cross` and `xsbt.boot`
correct?

Is there an existing post processing that I need to follow, or can I just do code gen using sbt task that I am familiar with? I'll remove `crossSub` from `launchSub` deps and generate the code for launcher by regex substitution of `package sbt.cross`.

**Comment by harrah** [comment]
Right.  The other suggestion from me was to put it in `xsbt.boot` or change `BootFilteredLoader` to exclude `sbt.cross`.  It won't get loaded from the launcher then.

If you go the post-processing route, there is `Transform.transform`, which will do property substitution, but I think that's it.

**Comment by eed3si9n** [comment]
Implemented code gen into `sbt.cross` and `xsbt.boot`. The scripted runs, but the tests are now failing in a different way:

```
Running actions / cross
[info] Getting net.java.dev.jna jna 3.2.3 ...
[info] :: retrieving :: org.scala-sbt#boot-jna
[info]  confs: [default]
[info]  1 artifacts copied, 0 already retrieved (838kB/59ms)
[info] Getting org.scala-sbt sbt 0.13.0-SNAPSHOT ...
[info] :: retrieving :: org.scala-sbt#boot-app
[info]  confs: [default]
[info]  45 artifacts copied, 0 already retrieved (12179kB/246ms)
[info] Getting Scala 2.10.0 (for sbt)...
[info] :: retrieving :: org.scala-sbt#boot-scala
[info]  confs: [default]
[info]  5 artifacts copied, 0 already retrieved (24106kB/256ms)
[info] [info] Set current project to default-30bb88 (in build file:/private/var/folders/bc/mmccbbns3f37k9x499ydvlk40000gn/T/sbt_c3e4bf46/cross/)
[info] java.lang.RuntimeException: Internal sbt error: could not get parser result.
[info]  at scala.sys.package$.error(package.scala:27)
[info]  at scala.Predef$.error(Predef.scala:142)
[info]  at sbt.InputTask$$anonfun$sbt$InputTask$$getResult$1$$anonfun$apply$3.apply(InputTask.scala:71)
[info]  at sbt.InputTask$$anonfun$sbt$InputTask$$getResult$1$$anonfun$apply$3.apply(InputTask.scala:71)
[info]  at scala.Option.getOrElse(Option.scala:120)
[info]  at sbt.InputTask$$anonfun$sbt$InputTask$$getResult$1.apply(InputTask.scala:71)
[info]  at sbt.InputTask$$anonfun$sbt$InputTask$$getResult$1.apply(InputTask.scala:70)
[info]  at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
[info]  at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:42)
[info]  at sbt.std.Transform$$anon$4.work(System.scala:64)
[info]  at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:231)
[info]  at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:231)
[info]  at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
[info]  at sbt.Execute.work(Execute.scala:237)
[info]  at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:231)
[info]  at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:231)
[info]  at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
[info]  at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
[info]  at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
[info]  at java.util.concurrent.FutureTask.run(FutureTask.java:138)
[info]  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
[info]  at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
[info]  at java.util.concurrent.FutureTask.run(FutureTask.java:138)
[info]  at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
[info]  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
[info]  at java.lang.Thread.run(Thread.java:680)
[info] [error] (*:check) Internal sbt error: could not get parser result.
```

**Comment by harrah** [comment]
Perhaps you need to rebase to latest commit?  I applied this pull request locally and the test passes.

**Comment by eed3si9n** [comment]
Rebasing did the trick. `scripted actions/*` all passed.

**Comment by harrah** [comment]
Merged in 125727ba8369b85dc7141f266e2ca467b19514d0.  Thanks!

**Pull request closed without merging**
