### PR TITLE
Fix VM argument passing by .sbtopts file and JAVA_TOOL_OPTIONS environmental variable

### PR DESCRIPTION
**Pull request by ptrdom**
Also contains few improvements to launcher script integration test setup.

### CODE REVIEW

**Comment by ptrdom** [comment]
Fixes https://github.com/sbt/sbt/issues/7387.

**Comment by eed3si9n** [comment]
Thanks for the contribution!

**Comment by ptrdom** [comment]
Happy to contribute!

I see that test `SbtScriptTest` `sbt -D arguments` is hanging on all OS, I can replicate that locally, but only if I execute all tests - executing only `sbt -D arguments` makes it succeed. Needs more investigation, probably improvements to the test suite too.

**Comment by ptrdom** [comment]
Aha, it is the `sbt --sbt-version` that actually hangs. It seems it just boots the sbt and process does not exit. I wonder how did that test managed to pass in `1.9.x` and `1.10.x` branches on the remote.

**Comment by ptrdom** [comment]
@eed3si9n Could you approve the workflow again? I think I fixed the failing test.

**Comment by ptrdom** [comment]
Okay, so it seems like a bunch of tests in `SbtScriptTest` just hang because spawned sbt process does not exit. Will investigate further.

**Comment by ptrdom** [comment]
@eed3si9n Should be good now, managed to execute the tests locally fine. Had to restore those python scripts in `itegration-test/bin`, no idea what is so magic about them, but passing them as `JAVA_CMD` both makes tests pass and execute fast.

**Comment by ptrdom** [comment]
@eed3si9n Adding a test for `JAVA_TOOL_OPTIONS` made linux/mac runners fail, so I pushed a fix for `sbt.sh` too.

**Comment by eed3si9n** [comment]
Looks like `$HOME/.sbt/boot/` directory got corrupted?

```bash
[error] (Compile / compileIncremental) sbt.internal.inc.InvalidComponent: Expected single file for component 'org.scala-sbt-compiler-bridge_2.12-1.9.2-bin_2.12.18__61.0', found: /home/runner/.sbt/boot/scala-2.12.18/org.scala-sbt/sbt/1.9.1/org.scala-sbt-compiler-bridge_2.12-1.9.2-bin_2.12.18__61.0/org.scala-sbt-compiler-bridge_2.12-1.9.2-bin_2.12.18__61.0.jar, /home/runner/.sbt/boot/scala-2.12.18/org.scala-sbt/sbt/1.9.1/org.scala-sbt-compiler-bridge_2.12-1.9.2-bin_2.12.18__61.0/org.scala-sbt-compiler-bridge_2.12-1.9.2-bin_2.12.18__61.0-1.9.2_20230626T014432.jar
```

You might need to temporarily add

```
rm -rf $HOME/.sbt/boot/
```
 in ci.yml.

**Comment by eed3si9n** [comment]
Sending https://github.com/sbt/sbt/pull/7394 to sidestep this issue.

**Pull request merged**
