### PR TITLE
Add equals/hashCode to APIs, and deprecate groupBy.

### PR DESCRIPTION
**Pull request by benjyw**
equals/hashCode are useful for debugging/verifying/testing,
and the groupBy implementation is naive. It'll be replaced
by a groupBy implementation in Analysis that will handle
external/internal dep transitions correction.

Feel free to close the other pull request and merge this one, to keep your git history clean.

### CODE REVIEW

**Comment by harrah** [comment]
This looks good.  You can squash instead of opening a new pull request.

**Comment by benjyw** [comment]
Closed in favor of #905.

**Comment by benjyw** [comment]
That doesn't mess github up? I'm learning all sorts of new things today.

**Comment by harrah** [comment]
Well, it depends.  I think things are currently sorted out, but they've had issues and regressions here in the past.  If you are ok with new pull requests, that's fine by me.

**Comment by harrah** [comment]
Here is an example of what happens: https://github.com/scala/scala/pull/3016.  At least, I think that was because of a rebase.

EDIT: I mean the "discussed outdated diff ... Show outdated diff" part.

**Pull request closed without merging**
