### PR TITLE
sbt 1.4.0-RC2 + pack flaky-behaving tests together

### PR DESCRIPTION
**Pull request by eed3si9n**
Ref https://github.com/sbt/sbt/issues/5891

### CODE REVIEW

**Comment by eatkins** [comment]
I have made progress on debugging what is going on with serverTestProj. Are the nio tests actually flaky or are they just triggering the bug where scripted never returns after the last test completes?

**Comment by eed3si9n** [comment]
> Are the nio tests actually flaky or are they just triggering the bug where scripted never returns after the last test completes?

I don't know the cause for that is, but I know that third Travis CI job often gets stuck.

**Comment by eatkins** [comment]
Ok. I think I'm close to fixing the flakiness with serverTestProj. It's possible that these fixes will also address the scripted issues.

**Comment by eed3si9n** [comment]
Closing this in favor of https://github.com/sbt/sbt/pull/5905

**Pull request closed without merging**
