### PR TITLE
Fix -Yrangepos.

### PR DESCRIPTION
**Pull request by lexspoon**
Unlike other settings, this one requires that a mixin be added to Global.

### CODE REVIEW

**Comment by lexspoon** [comment]
The -Yrangepos is important for Semmle, as it would be for most any tool that wants to map analysis results back to original Scala source code. As things stand, -Yrangepos takes no effect for projects that are built with SBT.

For comparison, here is how the core Scala tooling creates a compiler:

https://github.com/scala/scala/blob/master/src/compiler/scala/tools/nsc/Main.scala#L69

It's annoying, but it does seem to be the way Scala wants to be invoked.

Please let me know any way I can help further with this issue.

**Comment by harrah** [comment]
I don't see a problem merging this.  It will only affect -Yrangepos users, who don't get what they want now anyway.  I seem to remember -Yrangepos itself causing other problems with sbt in the past, but perhaps they have been fixed.

**Comment by lexspoon** [comment]
Thanks for the fast review, Mark.

I have now updated the patch to remove the unnecessary line at line 76.

I should have mentioned that I have verified -Yrangepos to work with SBT once this pull goes in. However, the core feature is a little buggy, which might be what you are recollecting. I will follow up on that separately.

**Comment by harrah** [comment]
Merged in b7250bb52827b3d270e9659072dbbaa344980180.

**Pull request closed without merging**
