### PR TITLE
Revert #1163

### PR DESCRIPTION
**Pull request by gkossakowski**
The #1237 reported a critical regression against sbt 0.13.2-RC1. We have a fix on its way in #1238 but I'd like us to better understand [whether](https://github.com/sbt/sbt/issues/1237#issuecomment-39718977) there's a bug in Scala 2.11 and whether the fix in #1237 is complete.

Therefore, I propose we revert #1163 (the PR that introduced improved macro handling) in sbt 0.13.2 to unblock the release. We'll fix the macro handling for good in 0.13.5 which is around the corner.

### CODE REVIEW

**Comment by gkossakowski** [comment]
//cc @Duhemm, @xeno-by

**Comment by gkossakowski** [comment]
Review by @jsuereth.

**Comment by jsuereth** [comment]
LGTM. I think this is the right fix.  most likely 0.13.5 will be a few weeks after 0.13.2 final anyway.

**Comment by jsuereth** [comment]
After TravisCI reports success, I'll merge and release. 

Thanks for staying on top of this @gkossakowski and @duhemm

**Comment by gkossakowski** [comment]
@jsuereth: I'd like to draw your attention to 4cc5e4a. I hope I did the right thing there.

**Comment by jsuereth** [comment]
Yeah, that's the right fix.  I think with 0.13.5 we're going to use sbt-git for release versioning off of tags rather than this gunk with these files all the time.

**Comment by gkossakowski** [comment]
Ok. Great to hear that the process is being constantly improved!

**Comment by jsuereth** [comment]
GO GO Travis CI!

**Comment by retronym** [comment]
Even if we fix the bug in Scala 2.10.5 / 2.11.1, we'll still need the workaround in SBT, so I don't think we should rule out merging the other PR.

**Comment by jsuereth** [comment]
@retronym Well, the macro-support will be delayed until 0.13.5 due to this (which is only a few weeks away now anyway.

**Comment by gkossakowski** [comment]
@retronym: the behavior in 2.10.x is correct. It's regression in Scala 2.11.

**Comment by jsuereth** [comment]
Ok, this passed the incremental compiler tests in travis. In the last few tests fail, we may blame the slow resolution issue facing all travis CI builds now.

**Pull request merged**
