### PR TITLE
Add configurationsToRetrieve

### PR DESCRIPTION
**Pull request by ajsquared**
This supports configuring a subset of configurations from which to retrieve dependencies when retrieveManaged is true.

### CODE REVIEW

**Comment by typesafe-tools** [comment]
Can one of the admins verify this patch?

**Comment by eed3si9n** [comment]
LGTM

**Comment by ajsquared** [comment]
I'm not able to reproduce the failures from Travis locally.

**Comment by eed3si9n** [comment]
I restarted those Travis jobs, likely it's the tests being flaky.

**Comment by ajsquared** [comment]
Hmm the "scripted tests/*" is still failing.  The failed tests all had this error:
https://gist.github.com/ajsquared/64df60f761fa45df4292

**Pull request merged**
