### PR TITLE
Don't fork JVM when no tests are given to run. Closes a case of #512

### PR DESCRIPTION
**Pull request by vigdorchik**
It looks like Object{Input/Output}Stream don't like it when empty arrays are serialized. An optimization any way.

### CODE REVIEW

**Comment by harrah** [comment]
This looks fine.  It seems unlikely that Object*Stream has problems with an empty array, though (and this should be straightforward to verify).

**Comment by vigdorchik** [comment]
This was the most plausible conjecture given the stacktraces I repeatedly got and the fact that this CL fixes the hang demonstrated.

**Comment by harrah** [comment]
I suspect it is a symptom of a deeper problem and I think it is more likely that there is a bug in the wire protocol.  

For example, this might not be the problem here, but the logger and handler in ForkMain in testing/agent/ are not thread safe.  If a test framework makes calls from multiple threads, these will corrupt the output stream because OOS is not thread safe.

Or, in ForkTests in main/actions/, there is code like:

``` scala
os.writeInt(frameworks.size)
for ((clazz, args) <- argMap) {
  os.write...
}
```

`frameworks` is a Seq and `argMap` is a Map constructed from it.  Although I doubt this is the problem here, `frameworks.size` could be different from `argMap.size`, resulting in the agent hanging or reading corrupt data.

**Comment by harrah** [comment]
If you are sure it is a problem with ObjectOutputStream, please demonstrate it.  If we do not follow through and verify the underlying cause, then we will probably see this problem again.  Given the reliability of reproducing and the simplicity of the test case, I don't see how it could appear under circumstances any more favorable to debugging than this.

**Comment by vigdorchik** [comment]
It looks like writing primitive types to ObjectStream is not supported:

Welcome to Scala version 2.9.1.final (Java HotSpot(TM) 64-Bit Server VM, Java 1.6.0_33).
Type in expressions to have them evaluated.
Type :help for more information.

scala> import java.io._
import java.io._

scala> val fos = new FileOutputStream("t")
fos: java.io.FileOutputStream = java.io.FileOutputStream@2c4f71a3

scala> val os = new ObjectOutputStream(fos)
os: java.io.ObjectOutputStream = java.io.ObjectOutputStream@16369fdc

scala> os.writeInt(0)

scala> val fis = new FileInputStream("t")
fis: java.io.FileInputStream = java.io.FileInputStream@1c6745b9

scala> val is = new ObjectInputStream(fis)
is: java.io.ObjectInputStream = java.io.ObjectInputStream@5c8032df

scala> is.readInt()
java.io.EOFException
        at java.io.DataInputStream.readInt(DataInputStream.java:375)
        at java.io.ObjectInputStream$BlockDataInputStream.readInt(ObjectInputStream.java:2775)
        at java.io.ObjectInputStream.readInt(ObjectInputStream.java:949)
        at .<init>(<console>:13)
        at .<clinit>(<console>)
        at .<init>(<console>:11)
        at .<clinit>(<console>)
        at $print(<console>)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:704)
        at scala.tools.nsc.interpreter.IMain$Request$$anonfun$14.apply(IMain.scala:920)
        at scala.tools.nsc.interpreter.Line$$anonfun$1.apply$mcV$sp(Line.scala:43)
        at scala.tools.nsc.io.package$$anon$2.run(package.scala:25)
        at java.lang.Thread.run(Thread.java:662)

writing java.lang.Integer on the other hand doesn't pose any problems.

**Comment by harrah** [comment]
Flush the output stream before reading.  Otherwise, the data isn't guaranteed to be written to disk.  I expect the same is true for the test agent, since it communicates over a socket.

**Comment by vigdorchik** [comment]
Right, it works now. However I don't quite get the contract of
ObjectOutputStream. Should I flush after every write?

**Pull request closed without merging**
