### PR TITLE
[1.3.x] "client / clean" + scalatest layer revert + cross parallel fix

### LINKED ISSUE #5308: NoClassDefFoundError when generating test reports with ScalaTest
Ref https://github.com/sbt/sbt/pull/5273

## steps
Mac OSX Catalina
sbt binary version: (brew install sbt) : 1.3.4
Version defined in build.properties : 1.3.5

#### build.sbt

```scala
import Dependencies._

ThisBuild / scalaVersion     := "2.13.1"
ThisBuild / version          := "0.1.0-SNAPSHOT"
ThisBuild / organization     := "com.example"
ThisBuild / organizationName := "example"

lazy val root = (project in file("."))
  .settings(
    name := "sbt-5308",
    libraryDependencies += "org.scalatest" %% "scalatest" % "3.1.0" % Test,
    libraryDependencies += "com.vladsch.flexmark" % "flexmark-all" % "0.35.10" % Test,
    Test / testOptions += Tests.Argument(TestFrameworks.ScalaTest, "-h", "target/generated/test-reports"),
  )
```

Then

```
test
```

## problem
sbt test fails with the following stack trace;

```
[info] Compiling 25 Scala sources to /Users/gavinbaumanis/workspace/ecpr/pas/target/scala-2.13/test-classes ...
[error] java.lang.NoClassDefFoundError: com/vladsch/flexmark/ast/Node
[error] 	at org.scalatest.tools.ReporterFactory.createHtmlReporter(ReporterFactory.scala:194)
[error] 	at org.scalatest.tools.ReporterFactory.getReporterFromConfiguration(ReporterFactory.scala:245)
[error] 	at org.scalatest.tools.ReporterFactory.$anonfun$createReportersFromConfigurations$1(ReporterFactory.scala:254)
[error] 	at scala.collection.Iterator$$anon$9.next(Iterator.scala:573)
[error] 	at scala.collection.mutable.ListBuffer.addAll(ListBuffer.scala:120)
[error] 	at scala.collection.mutable.ListBuffer$.from(ListBuffer.scala:38)
[error] 	at scala.collection.immutable.List$.from(List.scala:617)
[error] 	at scala.collection.immutable.List$.from(List.scala:611)
[error] 	at scala.collection.SeqFactory$Delegate.from(Factory.scala:306)
[error] 	at scala.collection.immutable.Seq$.from(Seq.scala:44)
[error] 	at scala.collection.immutable.Seq$.from(Seq.scala:41)
[error] 	at scala.collection.IterableOps.map(Iterable.scala:672)
[error] 	at scala.collection.IterableOps.map$(Iterable.scala:672)
[error] 	at org.scalatest.tools.ReporterConfigurations.map(ReporterConfiguration.scala:42)
[error] 	at org.scalatest.tools.ReporterFactory.createReportersFromConfigurations(ReporterFactory.scala:253)
[error] 	at org.scalatest.tools.ReporterFactory.getDispatchReporter(ReporterFactory.scala:257)
[error] 	at org.scalatest.tools.Framework$ScalaTestRunner.<init>(Framework.scala:670)
[error] 	at org.scalatest.tools.Framework.runner(Framework.scala:1124)
[error] 	at sbt.Defaults$.$anonfun$createTestRunners$1(Defaults.scala:1096)
[error] 	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
[error] 	at scala.collection.immutable.Map$Map2.foreach(Map.scala:159)
[error] 	at scala.collection.TraversableLike.map(TraversableLike.scala:238)
[error] 	at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
[error] 	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
[error] 	at sbt.Defaults$.createTestRunners(Defaults.scala:1090)
[error] 	at sbt.Defaults$.allTestGroupsTask(Defaults.scala:1158)
[error] 	at sbt.Defaults$.$anonfun$testTasks$10(Defaults.scala:895)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.Execute.work(Execute.scala:290)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:834)
    )
[error] Caused by: java.lang.ClassNotFoundException: com.vladsch.flexmark.ast.Node
[error] 	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
[error] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
[error] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
[error] 	at org.scalatest.tools.ReporterFactory.createHtmlReporter(ReporterFactory.scala:194)
[error] 	at org.scalatest.tools.ReporterFactory.getReporterFromConfiguration(ReporterFactory.scala:245)
[error] 	at org.scalatest.tools.ReporterFactory.$anonfun$createReportersFromConfigurations$1(ReporterFactory.scala:254)
[error] 	at scala.collection.Iterator$$anon$9.next(Iterator.scala:573)
[error] 	at scala.collection.mutable.ListBuffer.addAll(ListBuffer.scala:120)
[error] 	at scala.collection.mutable.ListBuffer$.from(ListBuffer.scala:38)
[error] 	at scala.collection.immutable.List$.from(List.scala:617)
[error] 	at scala.collection.immutable.List$.from(List.scala:611)
[error] 	at scala.collection.SeqFactory$Delegate.from(Factory.scala:306)
[error] 	at scala.collection.immutable.Seq$.from(Seq.scala:44)
[error] 	at scala.collection.immutable.Seq$.from(Seq.scala:41)
[error] 	at scala.collection.IterableOps.map(Iterable.scala:672)
[error] 	at scala.collection.IterableOps.map$(Iterable.scala:672)
[error] 	at org.scalatest.tools.ReporterConfigurations.map(ReporterConfiguration.scala:42)
[error] 	at org.scalatest.tools.ReporterFactory.createReportersFromConfigurations(ReporterFactory.scala:253)
[error] 	at org.scalatest.tools.ReporterFactory.getDispatchReporter(ReporterFactory.scala:257)
[error] 	at org.scalatest.tools.Framework$ScalaTestRunner.<init>(Framework.scala:670)
[error] 	at org.scalatest.tools.Framework.runner(Framework.scala:1124)
[error] 	at sbt.Defaults$.$anonfun$createTestRunners$1(Defaults.scala:1096)
[error] 	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
[error] 	at scala.collection.immutable.Map$Map2.foreach(Map.scala:159)
[error] 	at scala.collection.TraversableLike.map(TraversableLike.scala:238)
[error] 	at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
[error] 	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
[error] 	at sbt.Defaults$.createTestRunners(Defaults.scala:1090)
[error] 	at sbt.Defaults$.allTestGroupsTask(Defaults.scala:1158)
[error] 	at sbt.Defaults$.$anonfun$testTasks$10(Defaults.scala:895)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.Execute.work(Execute.scala:290)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:834)
[error] (Test / executeTests) java.lang.NoClassDefFoundError: com/vladsch/flexmark/ast/Node
[error] Total time: 11 s, completed 14 Dec. 2019, 9:43:57 am

```

## expectation
sbt test to complete successfully

## notes
sbt binary 1.3.4 AND build.properties 1.3.4 does NOT have this issue.

### LINKED ISSUE #5316: actions/doc-scala-instance failure: ClassNotFoundException: scala.tools.nsc.Main
## steps

`actions/doc-scala-instance` seems to be failing on Travis CI.

## problem

https://travis-ci.org/sbt/sbt/jobs/624452309?utm_medium=notification&utm_source=github_status

```
[info] Running actions/doc-scala-instance
[info] [info] Loading project definition from /tmp/sbt_31544f53/project
[info] [info] Compiling 1 Scala source to /tmp/sbt_31544f53/project/target/scala-2.12/sbt-1.0/classes ...
[info] [info] Done compiling.
[info] [info] Loading settings for project sbt_31544f53 from build.sbt ...
[info] [info] Set current project to sbt_31544f53 (in build file:/tmp/sbt_31544f53/)
[info] [info] Set current project to doc-scala-instance (in build file:/tmp/sbt_31544f53/)
[info] [info] Main Scala API documentation to /tmp/sbt_31544f53/a/target/scala-2.12/api...
[info] [info] Non-compiled module 'compiler-bridge_2.12' for Scala 2.12.2. Compiling...
[info] [info] Attempting to fetch org.scala-sbt:compiler-bridge_2.12:1.3.1.
[info] [error] java.lang.ClassNotFoundException: scala.tools.nsc.Main
[info] [error] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
[info] [error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[info] [error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[info] [error] 	at java.lang.Class.forName0(Native Method)
[info] [error] 	at java.lang.Class.forName(Class.java:348)
[info] [error] 	at sbt.internal.inc.RawCompiler.getReporter$1(RawCompiler.scala:54)
[info] [error] 	at sbt.internal.inc.RawCompiler.apply(RawCompiler.scala:77)
[info] [error] 	at sbt.internal.inc.AnalyzingCompiler$.$anonfun$compileSources$6(AnalyzingCompiler.scala:363)
[info] [error] 	at sbt.internal.inc.AnalyzingCompiler$.handleCompilationError$1(AnalyzingCompiler.scala:338)
[info] [error] 	at sbt.internal.inc.AnalyzingCompiler$.$anonfun$compileSources$4(AnalyzingCompiler.scala:359)
[info] [error] 	at sbt.internal.inc.AnalyzingCompiler$.$anonfun$compileSources$4$adapted(AnalyzingCompiler.scala:354)
[info] [error] 	at sbt.io.IO$.withTemporaryDirectory(IO.scala:489)
[info] [error] 	at sbt.io.IO$.withTemporaryDirectory(IO.scala:499)
[info] [error] 	at sbt.internal.inc.AnalyzingCompiler$.$anonfun$compileSources$2(AnalyzingCompiler.scala:354)
[info] [error] 	at sbt.internal.inc.AnalyzingCompiler$.$anonfun$compileSources$2$adapted(AnalyzingCompiler.scala:346)
[info] [error] 	at sbt.io.IO$.withTemporaryDirectory(IO.scala:489)
[info] [error] 	at sbt.io.IO$.withTemporaryDirectory(IO.scala:499)
[info] [error] 	at sbt.internal.inc.AnalyzingCompiler$.compileSources(AnalyzingCompiler.scala:346)
[info] [error] 	at sbt.internal.inc.ZincComponentCompiler.$anonfun$compileAndInstall$3(ZincComponentCompiler.scala:261)
[info] [error] 	at sbt.internal.inc.ZincComponentCompiler.$anonfun$compileAndInstall$3$adapted(ZincComponentCompiler.scala:250)
[info] [error] 	at sbt.io.IO$.withTemporaryDirectory(IO.scala:489)
[info] [error] 	at sbt.io.IO$.withTemporaryDirectory(IO.scala:499)
[info] [error] 	at sbt.internal.inc.ZincComponentCompiler.$anonfun$compileAndInstall$2(ZincComponentCompiler.scala:250)
[info] [error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[info] [error] 	at sbt.internal.util.BufferedLogger.bufferQuietly(BufferedLogger.scala:123)
[info] [error] 	at sbt.internal.inc.ZincComponentCompiler.$anonfun$compileAndInstall$1(ZincComponentCompiler.scala:250)
[info] [error] 	at sbt.internal.inc.ZincComponentCompiler.$anonfun$compileAndInstall$1$adapted(ZincComponentCompiler.scala:247)
[info] [error] 	at sbt.io.IO$.withTemporaryDirectory(IO.scala:489)
[info] [error] 	at sbt.io.IO$.withTemporaryDirectory(IO.scala:499)
[info] [error] 	at sbt.internal.inc.ZincComponentCompiler.compileAndInstall(ZincComponentCompiler.scala:247)
[info] [error] 	at sbt.internal.inc.ZincComponentCompiler.$anonfun$compiledBridgeJar$1(ZincComponentCompiler.scala:215)
[info] [error] 	at sbt.internal.inc.IfMissing$Define.run(IfMissing.scala:19)
[info] [error] 	at sbt.internal.inc.ZincComponentManager.createAndCache$1(ZincComponentManager.scala:49)
[info] [error] 	at sbt.internal.inc.ZincComponentManager.$anonfun$files$3(ZincComponentManager.scala:60)
[info] [error] 	at sbt.internal.inc.ZincComponentManager.getOrElse$1(ZincComponentManager.scala:42)
[info] [error] 	at sbt.internal.inc.ZincComponentManager.$anonfun$files$2(ZincComponentManager.scala:60)
[info] [error] 	at sbt.internal.inc.ZincComponentManager$$anon$1.call(ZincComponentManager.scala:89)
[info] [error] 	at sbt.RunFromSourceMain$$anon$1.apply(RunFromSourceMain.scala:67)
[info] [error] 	at sbt.internal.inc.ZincComponentManager.lock(ZincComponentManager.scala:89)
[info] [error] 	at sbt.internal.inc.ZincComponentManager.$anonfun$lockSecondaryCache$1(ZincComponentManager.scala:86)
[info] [error] 	at scala.Option.map(Option.scala:230)
[info] [error] 	at sbt.internal.inc.ZincComponentManager.lockSecondaryCache(ZincComponentManager.scala:86)
[info] [error] 	at sbt.internal.inc.ZincComponentManager.fromSecondary$1(ZincComponentManager.scala:58)
[info] [error] 	at sbt.internal.inc.ZincComponentManager.$anonfun$files$6(ZincComponentManager.scala:64)
[info] [error] 	at sbt.internal.inc.ZincComponentManager.getOrElse$1(ZincComponentManager.scala:42)
[info] [error] 	at sbt.internal.inc.ZincComponentManager.$anonfun$files$5(ZincComponentManager.scala:64)
[info] [error] 	at sbt.internal.inc.ZincComponentManager$$anon$1.call(ZincComponentManager.scala:89)
[info] [error] 	at sbt.RunFromSourceMain$$anon$1.apply(RunFromSourceMain.scala:67)
[info] [error] 	at sbt.internal.inc.ZincComponentManager.lock(ZincComponentManager.scala:89)
[info] [error] 	at sbt.internal.inc.ZincComponentManager.lockLocalCache(ZincComponentManager.scala:82)
[info] [error] 	at sbt.internal.inc.ZincComponentManager.files(ZincComponentManager.scala:64)
[info] [error] 	at sbt.internal.inc.ZincComponentManager.file(ZincComponentManager.scala:70)
[info] [error] 	at sbt.internal.inc.ZincComponentCompiler.compiledBridgeJar(ZincComponentCompiler.scala:215)
[info] [error] 	at sbt.internal.inc.ZincComponentCompiler$ZincCompilerBridgeProvider.compiledBridge(ZincComponentCompiler.scala:75)
[info] [error] 	at sbt.internal.inc.ZincComponentCompiler$ZincCompilerBridgeProvider.fetchCompiledBridge(ZincComponentCompiler.scala:81)
[info] [error] 	at sbt.internal.inc.AnalyzingCompiler.loader(AnalyzingCompiler.scala:260)
[info] [error] 	at sbt.internal.inc.AnalyzingCompiler.getInterfaceClass(AnalyzingCompiler.scala:278)
[info] [error] 	at sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:245)
[info] [error] 	at sbt.internal.inc.AnalyzingCompiler.doc(AnalyzingCompiler.scala:177)
[info] [error] 	at sbt.internal.inc.AnalyzingCompiler.doc(AnalyzingCompiler.scala:158)
[info] [error] 	at sbt.Doc$.$anonfun$scaladoc$1(Doc.scala:39)
[info] [error] 	at sbt.Doc$.$anonfun$scaladoc$1$adapted(Doc.scala:39)
[info] [error] 	at sbt.RawCompileLike$.$anonfun$prepare$1(RawCompileLike.scala:83)
[info] [error] 	at sbt.RawCompileLike$.$anonfun$prepare$1$adapted(RawCompileLike.scala:76)
[info] [error] 	at sbt.RawCompileLike$.$anonfun$cached$3(RawCompileLike.scala:67)
[info] [error] 	at sbt.RawCompileLike$.$anonfun$cached$3$adapted(RawCompileLike.scala:65)
[info] [error] 	at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:154)
[info] [error] 	at sbt.RawCompileLike$.$anonfun$cached$1(RawCompileLike.scala:72)
[info] [error] 	at sbt.RawCompileLike$.$anonfun$cached$1$adapted(RawCompileLike.scala:55)
[info] [error] 	at sbt.Defaults$.$anonfun$docTaskSettings$3(Defaults.scala:1641)
[info] [error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[info] [error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[info] [error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[info] [error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[info] [error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[info] [error] 	at sbt.Execute.work(Execute.scala:291)
[info] [error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[info] [error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:184)
[info] [error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[info] [error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info] [error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[info] [error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info] [error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[info] [error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[info] [error] 	at java.lang.Thread.run(Thread.java:748)
[info] [error] (a / Compile / doc) java.lang.ClassNotFoundException: scala.tools.nsc.Main
[info] [error] Total time: 0 s, completed Dec 13, 2019 4:23:29 AM
[error] x actions/doc-scala-instance 
```

## expectation

it should work.

### LINKED ISSUE #5321: +clean performance regression in 1.3.5
## steps
sbt version: `1.3.5`

Execute:
```
git clone https://github.com/7mind/izumi.git
cd izumi
sbt +clean
echo 'sbt.version = 1.3.4' > project/build.properties
sbt +clean
```

## problem

With `1.3.5` `+clean` is noticeably slower, it also reports progress for each subproject instead of just once for the whole task:

```
sbt:izumi> +clean
[info] Forcing Scala version to 2.12.10 on all projects.
[info] Reapplying settings...
[info] Set current project to izumi (in build file:/Users/kai/src/izumi/)
[success] Total time: 0 s, completed 18 Dec 2019, 15:06:38
[success] Total time: 0 s, completed 18 Dec 2019, 15:06:38
[success] Total time: 0 s, completed 18 Dec 2019, 15:06:38
[success] Total time: 0 s, completed 18 Dec 2019, 15:06:38
[success] Total time: 0 s, completed 18 Dec 2019, 15:06:38
[success] Total time: 0 s, completed 18 Dec 2019, 15:06:38
[success] Total time: 0 s, completed 18 Dec 2019, 15:06:38
[success] Total time: 0 s, completed 18 Dec 2019, 15:06:39
[success] Total time: 0 s, completed 18 Dec 2019, 15:06:39
[success] Total time: 0 s, completed 18 Dec 2019, 15:06:39
[success] Total time: 0 s, completed 18 Dec 2019, 15:06:39
[success] Total time: 0 s, completed 18 Dec 2019, 15:06:39
[success] Total time: 0 s, completed 18 Dec 2019, 15:06:39
[success] Total time: 0 s, completed 18 Dec 2019, 15:06:39
[success] Total time: 0 s, completed 18 Dec 2019, 15:06:39
[success] Total time: 0 s, completed 18 Dec 2019, 15:06:39
[success] Total time: 0 s, completed 18 Dec 2019, 15:06:40
[success] Total time: 0 s, completed 18 Dec 2019, 15:06:40
[success] Total time: 0 s, completed 18 Dec 2019, 15:06:40
[success] Total time: 0 s, completed 18 Dec 2019, 15:06:40
[success] Total time: 2 s, completed 18 Dec 2019, 15:06:42
[success] Total time: 0 s, completed 18 Dec 2019, 15:06:43
[success] Total time: 0 s, completed 18 Dec 2019, 15:06:43
[success] Total time: 0 s, completed 18 Dec 2019, 15:06:43
[success] Total time: 0 s, completed 18 Dec 2019, 15:06:43
[success] Total time: 0 s, completed 18 Dec 2019, 15:06:43
[success] Total time: 0 s, completed 18 Dec 2019, 15:06:43
[success] Total time: 0 s, completed 18 Dec 2019, 15:06:43
[success] Total time: 0 s, completed 18 Dec 2019, 15:06:43
[success] Total time: 0 s, completed 18 Dec 2019, 15:06:43
[success] Total time: 0 s, completed 18 Dec 2019, 15:06:44
[success] Total time: 0 s, completed 18 Dec 2019, 15:06:44
[success] Total time: 0 s, completed 18 Dec 2019, 15:06:44
[success] Total time: 0 s, completed 18 Dec 2019, 15:06:44
[success] Total time: 0 s, completed 18 Dec 2019, 15:06:44
[success] Total time: 0 s, completed 18 Dec 2019, 15:06:44
[success] Total time: 0 s, completed 18 Dec 2019, 15:06:44
[success] Total time: 0 s, completed 18 Dec 2019, 15:06:44
[success] Total time: 1 s, completed 18 Dec 2019, 15:06:45
[success] Total time: 0 s, completed 18 Dec 2019, 15:06:45
[info] Forcing Scala version to 2.13.1 on all projects.
[info] Reapplying settings...
[info] Set current project to izumi (in build file:/Users/kai/src/izumi/)
[success] Total time: 0 s, completed 18 Dec 2019, 15:06:47
[success] Total time: 0 s, completed 18 Dec 2019, 15:06:48
[success] Total time: 0 s, completed 18 Dec 2019, 15:06:48
[success] Total time: 0 s, completed 18 Dec 2019, 15:06:48
[success] Total time: 0 s, completed 18 Dec 2019, 15:06:48
[success] Total time: 0 s, completed 18 Dec 2019, 15:06:48
[success] Total time: 0 s, completed 18 Dec 2019, 15:06:48
[success] Total time: 0 s, completed 18 Dec 2019, 15:06:48
[success] Total time: 0 s, completed 18 Dec 2019, 15:06:48
[success] Total time: 0 s, completed 18 Dec 2019, 15:06:48
[success] Total time: 0 s, completed 18 Dec 2019, 15:06:48
[success] Total time: 0 s, completed 18 Dec 2019, 15:06:48
[success] Total time: 0 s, completed 18 Dec 2019, 15:06:48
[success] Total time: 0 s, completed 18 Dec 2019, 15:06:48
[success] Total time: 0 s, completed 18 Dec 2019, 15:06:48
[success] Total time: 0 s, completed 18 Dec 2019, 15:06:48
[success] Total time: 0 s, completed 18 Dec 2019, 15:06:48
[success] Total time: 0 s, completed 18 Dec 2019, 15:06:48
[success] Total time: 0 s, completed 18 Dec 2019, 15:06:48
[success] Total time: 0 s, completed 18 Dec 2019, 15:06:48
[success] Total time: 0 s, completed 18 Dec 2019, 15:06:49
[success] Total time: 0 s, completed 18 Dec 2019, 15:06:49
[success] Total time: 0 s, completed 18 Dec 2019, 15:06:49
[success] Total time: 0 s, completed 18 Dec 2019, 15:06:49
[success] Total time: 0 s, completed 18 Dec 2019, 15:06:49
[success] Total time: 0 s, completed 18 Dec 2019, 15:06:49
[success] Total time: 0 s, completed 18 Dec 2019, 15:06:49
[success] Total time: 0 s, completed 18 Dec 2019, 15:06:49
[success] Total time: 0 s, completed 18 Dec 2019, 15:06:49
[success] Total time: 0 s, completed 18 Dec 2019, 15:06:49
[success] Total time: 0 s, completed 18 Dec 2019, 15:06:49
[success] Total time: 0 s, completed 18 Dec 2019, 15:06:49
[success] Total time: 0 s, completed 18 Dec 2019, 15:06:49
[success] Total time: 0 s, completed 18 Dec 2019, 15:06:49
[success] Total time: 0 s, completed 18 Dec 2019, 15:06:49
[success] Total time: 0 s, completed 18 Dec 2019, 15:06:49
[success] Total time: 0 s, completed 18 Dec 2019, 15:06:49
[success] Total time: 0 s, completed 18 Dec 2019, 15:06:49
[info] Reapplying settings...
[info] Set current project to izumi (in build file:/Users/kai/src/izumi/)
```

## expectation

With `1.3.4` it works as expected:

```
sbt:izumi> +clean
[info] Setting Scala version to 2.12.10 on 49 projects.
[info] Excluded 1 projects, run ++ 2.12.10 -v for more details.
[info] Reapplying settings...
[info] Set current project to izumi (in build file:/Users/kai/src/izumi/)
[success] Total time: 0 s, completed 18 Dec 2019, 15:08:09
[info] Setting Scala version to 2.13.1 on 46 projects.
[info] Excluded 4 projects, run ++ 2.13.1 -v for more details.
[info] Reapplying settings...
[info] Set current project to izumi (in build file:/Users/kai/src/izumi/)
[success] Total time: 0 s, completed 18 Dec 2019, 15:08:12
[info] Reapplying settings...
[info] Set current project to izumi (in build file:/Users/kai/src/izumi/)
```

### PR DESCRIPTION
**Pull request by eed3si9n**
Backport of
- workaround client / clean problem #5317 Ref #5314 Ref #5265
- Remove actions/doc-scala-instance #5318 
- Revert scalatest layer #5327
- Run cross commands (with `+`) in parallel when possible #5329

Fixes #5316 
Fixes #5321 
Fixes #5308

### CODE REVIEW

**Review by eatkins — APPROVED** [review]
LGTM.

**Comment by eed3si9n** [comment]
I opened https://github.com/sbt/sbt/issues/5335 for the failure, which is unrelated and caused by Sonatype OSS Public going away.

**Comment by jrudolph** [comment]
This change only seems safe when `crossPaths := true`. In akka/akka, we have been using `crossPaths := false` for mostly unknown historical reasons and so it seems using `+` in 1.3.6 now leads to classes being mixed up between Scala versions. More concretely, it seems we have included 2.12 class files in 2.13 jars (see https://github.com/akka/akka/issues/28807). Was it good luck that there wasn't more damage or maybe we just don't know?

The safest thing to do would be to disallow `+` for projects that use `crossPath := false`, a more optimistic approach might be to go back to the previous behavior in that case (serial execution).

**Comment by jrudolph** [comment]
Or maybe, I misunderstand what #5329 changed? Does it run the commands for each Scala version in parallel? Or does it still run commands per Scala version sequentially but for each versioned command makes sure that all tasks for that command are still run in parallel?

**Comment by eed3si9n** [comment]
> Does it run the commands for each Scala version in parallel? Or does it still run commands per Scala version sequentially but for each versioned command makes sure that all tasks for that command are still run in parallel?

It's the latter. Changing Scala version is treated to be a stateful command but the tasks will run parallel across the aggregated subprojects as it does in normal shell.

**Comment by jrudolph** [comment]
Thanks for the clarification, @eed3si9n, so maybe it's not necessarily the cause of the problem. Seemed somewhat likely since it happened during an update from 1.2.8 to 1.3.6.

**Pull request merged**
