### PR TITLE
Add link to sbt-sonatype plugin

### PR DESCRIPTION
**Pull request by xerial**
I created sbt-sonatype plugin https://github.com/xerial/sbt-sonatype that simplifies release processes at Sonatype Nexus repository. Please add a link to this plugin.

Thanks in advance.

### CODE REVIEW

**Comment by jsuereth** [comment]
Cool, thanks for the new plugin!

**Comment by xerial** [comment]
When will this update be reflected to the documentation?
Do I need to send pull requests for all 0.13.x branches?

**Comment by jsuereth** [comment]
Documentation against the 0.13.1 branch is automatically pushed to the 0.13.1 site.  0.13.2-RC1 should go out end of the week, which is when the docs get bumped to 0.13.2, and the automated push will be against the 0.13.2 branch.

Sorry I didn't warn you about that earlier.

**Comment by xerial** [comment]
Thanks! 
I will send another pull request to 0.13.1 and 0.13.2-RC1.

**Comment by jsuereth** [comment]
You're already in the branch for 0.13.2-RC1 :)

I'm about to merge 0.13.1 docs back, maybe I'll do a cherry pick for you instead.

**Comment by xerial** [comment]
Thanks for your help!

**Comment by xerial** [comment]
And also, please do a cherry-pick https://github.com/sbt/sbt/pull/1098, too.

Thanks.

**Pull request merged**
