### PR TITLE
Addresses #4206 - Introduces fgRun and fgRunMain

### LINKED ISSUE #4206: fgRun feature
## steps

1. `fgRun`.

## expectation

Works like `run` in sbt 0.13.

### PR DESCRIPTION
**Pull request by agaro1121**
- [x] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/1.x/CONTRIBUTING.md) guidelines

Fixes #4206 

- adds fgRun to work like the `run` command in 0.13
- adds fgRunMain to work like the `runMain` command in 0.13

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @agaro1121,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by eed3si9n** [comment]
@agaro1121 Thanks for the contribution. Please comment when you signed the CLA.

**Comment by agaro1121** [comment]
Happy to contribute @eed3si9n !
I signed the CLA

**Review by eed3si9n — APPROVED** [review]
LGTM

**Comment by eed3si9n** [comment]
@agaro1121 We made a survey form to collect feedback on the contribution process. Please fill it out when get you get a minute. https://goo.gl/forms/LDPlTl9Wso7YwEri2

**Pull request merged**
