### PR TITLE
'fork in test' initial implementation.

### PR DESCRIPTION
**Pull request by vigdorchik**

### CODE REVIEW

**Comment by harrah** [comment]
1. Dropping `forkOptions` looks like the right approach.
2. We will need a section on [the changes page](https://github.com/harrah/xsbt/wiki/ChangeSummary_0.12.0) on forking tests as well as [Testing](https://github.com/harrah/xsbt/wiki/Testing) (probably right after Filter Classes).  It should describe
   - what 'fork in test' does, including the note that forked tests are always sequential and do not support tags
   - the advanced control that 'testGrouping' gives and some examples of using it

**Comment by vigdorchik** [comment]
1. I've changed according to the first bunch of comments. More to come.
2. I think it makes sense to change the documentation once the functionality is in the codebase, I'll do that.

**Comment by harrah** [comment]
There were a couple of comments that I got a notification about (in reply to [this comment](https://github.com/vigdorchik/xsbt/commit/7afc9e77c61c222caaa2a2df1634d03290c58b48#commitcomment-1159265)), but I don't see them here.  Did you delete them?

**Comment by vigdorchik** [comment]
On Mon, Apr 2, 2012 at 5:34 PM, Mark Harrah
reply@reply.github.com
wrote:

**Comment by harrah** [comment]
Ok, no problem.  Just wanted to make sure they didn't get lost.

**Comment by harrah** [comment]
Ok, that looks good.  I these are the remaining comments to address:
1. [Expand description](https://github.com/vigdorchik/xsbt/commit/7afc9e77c61c222caaa2a2df1634d03290c58b48#commitcomment-1159260)
2. [System.err.println](https://github.com/vigdorchik/xsbt/commit/7afc9e77c61c222caaa2a2df1634d03290c58b48#commitcomment-1161870)
3. [case object InProcess](https://github.com/vigdorchik/xsbt/commit/7afc9e77c61c222caaa2a2df1634d03290c58b48#commitcomment-1159275)
4. [swallowed IOException](https://github.com/harrah/xsbt/pull/415#commitcomment-1159265)

**Pull request merged**
