### PR TITLE
Fixes #1834, `<developers>` section is not rendered correctly in the pom.xml 

### LINKED ISSUE #1834: `<developers>` section is not rendered correctly in the pom.xml
This change introduced the bug:

https://github.com/sbt/sbt/commit/183c2bcfe2a84295deea82eed2179a72c50289cc#diff-6e0d918801855e22733193038a712c35R108

The output in pom.xml looks like this:

```
<developers> moduleInfo.developers.map&lt;function1&gt; </developers>
```

### PR DESCRIPTION
**Pull request by MaxWorgan**
Fixes #1834
Inserted missing brackets so developer xml renders correctly

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @MaxWorgan,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.typesafe.com/contribute/cla](http://www.typesafe.com/contribute/cla)

**Comment by typesafe-tools** [comment]
Can one of the admins verify this patch?

**Comment by eed3si9n** [comment]
LGTM pending CI

**Comment by MaxWorgan** [comment]
CI has finished and 2 jobs failed - not sure why it's not displaying. The failures don't appear to have anything to do with this change...

**Comment by eed3si9n** [comment]
I restarted those two jobs on Travis to see what happens.

**Pull request merged**
