### PR TITLE
FPORT: Avoid CCE when scalac internally uses compileLate

### PR DESCRIPTION
**Pull request by Duhemm**
Forward port of #2453

### CODE REVIEW

**Comment by dwijnand** [comment]
LGTM

**Comment by dwijnand** [comment]
How is this passing given the forward port to sbt/incrementalcompiler isn't even merged, let alone released and updated to??

**Comment by Duhemm** [comment]
The test was not in the correct directory for sbt 1.0, good catch!

**Comment by dwijnand** [comment]
Rebased in #2487

"... and he snags the ball and runs with it..."

**Pull request closed without merging**
