### PR TITLE
Add scalaCompilerBridgeBinaryJar task

### PR DESCRIPTION
**Pull request by smarter**
The end goal is to rewrite Dotty's compiler-bridge in Java (this is easy
since the zinc-specific phases are in the compiler itself) to simplify
the bootstrapping process.

### CODE REVIEW

**Comment by smarter** [comment]
@Duhemm can you review ?

**Review by Duhemm — APPROVED** [review]
LGTM.

Is the future plan to use this new task in sbt-dotty primarily, or is it only for bootstrapping purposes?

If the plan is to use that in sbt-dotty, then we should make sure that the bridge is compiled with the oldest Java version that Dotty supports before distributing, but I don't see another problem.

**Comment by smarter** [comment]
Yes, the plan would be to make https://github.com/lampepfl/dotty/tree/master/sbt-bridge Java-only and keep it that way. Our CI should always publish using the oldest Java version we support, otherwise things would break even now since we have some Java files.

**Comment by smarter** [comment]
@eed3si9n OK to merge?

**Review by eed3si9n — APPROVED** [review]

**Comment by eed3si9n** [comment]
Yea. Let's merge this.

**Pull request merged**
