### PR TITLE
Avoid compiler crash for naked `key.value` calls.

### LINKED ISSUE #1031: Compiler crash when .value, etc... used outside of task macro
This was caused by the removal of `resetLocalAttrs`.  When `.value, etc...` are used properly, the task/setting macros remove them as part of macro expansion.  When they are not removed, they survive beyond typers.  Therefore, problems with untyped trees from the `.value`-like macros are only exposed when used in the wrong context.

### PR DESCRIPTION
**Pull request by retronym**
Untyped trees underneath typed trees makes Jack and sad boy.
And they make superaccessors a sad phase.

The recent refactoring to retain original types in the trees
representing the argument to the task macro meant that the `value`
macro also was changed to try to avoid this untyped-under-typed
problem. However, it didn't go deep enough, and left the child
trees of the placeholder tree `InputWrapper.wrap[T](key)` untyped.

This commit uses `c.typeCheck` to locally typeheck that tree fully
instead.

Fixes #1031 

Review by @harrah

### CODE REVIEW

**Comment by jsuereth** [comment]
LGTM

**Comment by jsuereth** [comment]
Thanks much for fixing this @retronym ! Really good to see someone with expertise on this.

**Comment by retronym** [comment]
Just pushed without the accidentally-added changes.

**Comment by harrah** [comment]
LGTM

**Pull request merged**
