### PR TITLE
Synchronize with changes to Zinc logger API

### PR DESCRIPTION
**Pull request by jvican**
https://github.com/sbt/zinc/pull/325

### CODE REVIEW

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild/?sbt=pull/3316/head&deploy_to_bintray=false">this link.</A>

**Comment by typesafe-tools** [comment]
A dbuild validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/92/console">is in progress...</a>

**Comment by eed3si9n** [comment]
Thanks for this!
You would probably need to pass in `pull/122/head` for lm.

**Comment by typesafe-tools** [comment]
[//]: # (Refs: pull/3316/head-pull/325/head-1.0-1.0-1.0-1.0.x)
dbuild <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/92/">has checked</A> the following projects against Scala 2.12:

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | <A HREF="https://github.com/sbt/sbt/pull/3316">pull/3316/head      </A> | sbt/sbt@0cc3cfb36444e1efda7c4b5661f8a7ef95fcd7da
  zinc              | <A HREF="https://github.com/sbt/zinc/pull/325">pull/325/head       </A> | sbt/zinc@510d64dd11f0593c592df257bb04cf7c3ee23449
  io                | <A HREF="https://github.com/sbt/io/tree/1.0">1.0                 </A> | sbt/io@f55849d988b94941309d316c43533b0af423f244
  librarymanagement | <A HREF="https://github.com/sbt/librarymanagement/tree/1.0">1.0                 </A> | sbt/librarymanagement@f8d3718d283cacdc11c6d4a9f101c675f687dc49
  util              | <A HREF="https://github.com/sbt/util/tree/1.0">1.0                 </A> | sbt/util@fe7743878fb590765582aec86d0e45df6ae0a936
  website           | <A HREF="https://github.com/sbt/website/tree/1.0.x">1.0.x               </A> | sbt/website@7e644bc8fc623589152e98bee75afd44893690e3

:x: The result is: ***FAILED***
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild?sbt=pull/3316/head&zinc=pull/325/head&io=1.0&librarymanagement=1.0&util=1.0&website=1.0.x&deploy_to_bintray=false">(restart)</A>

**Comment by typesafe-tools** [comment]
A dbuild validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/93/console">is in progress...</a>

**Comment by typesafe-tools** [comment]
[//]: # (Refs: pull/3316/head-pull/325/head-1.0-pull/122/head-1.0-1.0.x)
dbuild <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/93/">has checked</A> the following projects against Scala 2.12:

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | <A HREF="https://github.com/sbt/sbt/pull/3316">pull/3316/head      </A> | sbt/sbt@0cc3cfb36444e1efda7c4b5661f8a7ef95fcd7da
  zinc              | <A HREF="https://github.com/sbt/zinc/pull/325">pull/325/head       </A> | sbt/zinc@510d64dd11f0593c592df257bb04cf7c3ee23449
  io                | <A HREF="https://github.com/sbt/io/tree/1.0">1.0                 </A> | sbt/io@f55849d988b94941309d316c43533b0af423f244
  librarymanagement | <A HREF="https://github.com/sbt/librarymanagement/pull/122">pull/122/head       </A> | sbt/librarymanagement@e3891c8732dc248bd3ff3be9d5c796454d66bc3a
  util              | <A HREF="https://github.com/sbt/util/tree/1.0">1.0                 </A> | sbt/util@fe7743878fb590765582aec86d0e45df6ae0a936
  website           | <A HREF="https://github.com/sbt/website/tree/1.0.x">1.0.x               </A> | sbt/website@7e644bc8fc623589152e98bee75afd44893690e3

:x: The result is: ***FAILED***
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild?sbt=pull/3316/head&zinc=pull/325/head&io=1.0&librarymanagement=pull/122/head&util=1.0&website=1.0.x&deploy_to_bintray=false">(restart)</A>

**Comment by typesafe-tools** [comment]
A dbuild validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/94/console">is in progress...</a>

**Comment by eed3si9n** [comment]
The dbuild failure 

```
[error] Error during tests:
[error] 	sbt.internal.parser.SessionSettingsSpec
[error] 	sbt.internal.parser.ErrorSpec
[error] 	sbt.internal.parser.NewFormatSpec
[error] 	sbt.internal.parser.SessionSettingsQuickSpec
```

was already observed yesterday, so I think this is good to go.

**Comment by typesafe-tools** [comment]
[//]: # (Refs: pull/3316/head-pull/325/head-1.0-74d8a3835d535d3d787e9294539a0a3efc47674d-1.0-1.0.x)
dbuild <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/94/">has checked</A> the following projects against Scala 2.12:

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | <A HREF="https://github.com/sbt/sbt/pull/3316">pull/3316/head      </A> | sbt/sbt@0cc3cfb36444e1efda7c4b5661f8a7ef95fcd7da
  zinc              | <A HREF="https://github.com/sbt/zinc/pull/325">pull/325/head       </A> | sbt/zinc@510d64dd11f0593c592df257bb04cf7c3ee23449
  io                | <A HREF="https://github.com/sbt/io/tree/1.0">1.0                 </A> | sbt/io@f55849d988b94941309d316c43533b0af423f244
  librarymanagement | <A HREF="https://github.com/sbt/librarymanagement/tree/74d8a3835d535d3d787e9294539a0a3efc47674d">74d8a3835d535d3d787e9294539a0a3efc47674d</A> | sbt/librarymanagement@74d8a3835d535d3d787e9294539a0a3efc47674d
  util              | <A HREF="https://github.com/sbt/util/tree/1.0">1.0                 </A> | sbt/util@fe7743878fb590765582aec86d0e45df6ae0a936
  website           | <A HREF="https://github.com/sbt/website/tree/1.0.x">1.0.x               </A> | sbt/website@7e644bc8fc623589152e98bee75afd44893690e3

:x: The result is: ***FAILED***
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild?sbt=pull/3316/head&zinc=pull/325/head&io=1.0&librarymanagement=74d8a3835d535d3d787e9294539a0a3efc47674d&util=1.0&website=1.0.x&deploy_to_bintray=false">(restart)</A>

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild/?sbt=pull/3316/head&deploy_to_bintray=false">this link.</A>

**Comment by jvican** [comment]
This PR is already passing `test:compile` locally if I checkout https://github.com/sbt/zinc/pull/325. Ripple PR completed.

**Pull request merged**
