### PR TITLE
Change the tuple enrichment deprecation warning messages

### LINKED ISSUE #3454: Tuple enrichments are deprecated in 0.13 but not in 1.0
## steps

- 0.13: https://github.com/sbt/sbt/blob/96ddc33a3e5ecc36ee34a2f032e307501390f4d8/main/settings/src/main/scala/sbt/Structure.scala#L295 
- 1.0: https://github.com/sbt/sbt/blob/037559c8d3f1aee3db95c63650ef8cfd265b28fb/main-settings/src/main/scala/sbt/Structure.scala#L570

## problem

Code that uses tuple enrichments in 0.13 compiles with deprecation warnings while it compiles clean in 1.0.

## expectation

I expect tuple enrichments to compile without deprecation warnings in 0.13.

## notes

I'm working on sbtfix and I'd like the expected output code to compile without deprecation warnings. Users expect a migration tool to remove deprecation warnings.

sbt version: 0.13.16

### PR DESCRIPTION
**Pull request by olafurpg**
Fixes #3454

### CODE REVIEW

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild/?sbt=pull/3455/head&deploy_to_bintray=false">this link.</A>

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild/?sbt=pull/3455/head&deploy_to_bintray=false">this link.</A>

**Review by dwijnand — APPROVED** [review]
Thanks Olaf

**Comment by olafurpg** [comment]
The CI failures seem to be unrelated to this PR. https://travis-ci.org/sbt/sbt/jobs/265527456

**Comment by eed3si9n** [comment]
Restarting the Travis CI job.

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild/?sbt=pull/3455/head&deploy_to_bintray=false">this link.</A>

**Pull request merged**
