### PR TITLE
Fixes Issue #3154 - "It is not a test" in JUnit XML reports.

### LINKED ISSUE #3154: ScalaTest nested suites reported as "(It is not a test)" in JUnitXmlReportPlugin reports
[ScalaTest nested suites](http://doc.scalatest.org/2.0/index.html#org.scalatest.Suites) don't report useful test names in XML reports.  Each is reported as ["It is not a test"](https://github.com/sbt/sbt/blob/1.0.x/testing/src/main/scala/sbt/JUnitXmlTestsListener.scala#L79).

Similar to:

1. https://github.com/scalatest/scalatest/issues/780
2. https://github.com/JetBrains/sbt-tc-logger/issues/8

### PR DESCRIPTION
**Pull request by jameskoch**
Fixes #3154

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @jameskoch,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by lightbend-cla-validator** [comment]
Hi @jameskoch,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by jameskoch** [comment]
Just signed the CLA.

**Review by eed3si9n — APPROVED** [review]

**Comment by eed3si9n** [comment]
Looks good. Thanks for the contribution!

**Comment by jameskoch** [comment]
@eed3si9n let me know if you need another green build in order to merge.  I've had at least one green on the initial commit. Don't quite know how high the bar to merge is, and which tests might be inherently flaky in CI.

**Comment by eed3si9n** [comment]
Yea. There's a known concurrency issue in 0.13. I'll keep hitting restart job on Travis CI until we can get green.

**Pull request merged**
