### PR TITLE
Allow single-letter aliases

### LINKED ISSUE #1074: + fails with single-letter-named aliases
```
[sbt-0-13-1]> alias z = ; show scalaVersion ; help scalaVersion
[sbt-0-13-1]> z
[info] 2.10.4-RC1
The version of Scala used for building.
[sbt-0-13-1]> + z
[error] Expected any character
[error] + z
[error]    ^
```

Shouldn't at least `alias` command warn a user when a single-letter name is used to define an alias?

### PR DESCRIPTION
**Pull request by kzys**
Fixes #1074.

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @kzys,

Thank you for your contribution! We really value the time you've taken to put this together.

We see that you have signed the Lightbend Contributors License Agreement before, however, the CLA has changed since you last signed it.
Please review the new CLA and sign it before we proceed with reviewing this pull request:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by kzys** [comment]
Let me fix the commit comment. That is misleading.

**Comment by lightbend-cla-validator** [comment]
Hi @kzys,

Thank you for your contribution! We really value the time you've taken to put this together.

We see that you have signed the Lightbend Contributors License Agreement before, however, the CLA has changed since you last signed it.
Please review the new CLA and sign it before we proceed with reviewing this pull request:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by dwijnand** [comment]
Hi @kzys, thank you for looking into how to fix #1074.

Could you explain why this is the fix? `any.+` _looks_ correct, while `any.*` looks too loose (can't you then call simply `+` which makes no sense?)

**Comment by dwijnand** [comment]
I believe the TravisCI failure are legitimate failures too.

**Comment by kzys** [comment]
~~Sorry. Seems the issue has been fixed on 1.0.x already. I initially confirmed that the issue is still there by calling launch/target/sbt-launch.jar from sbt's source directory but that was 0.13.11 due to project/build.properties.~~

Let me take a look Travis failures tonight.

**Comment by dwijnand** [comment]
rebased

**Comment by eed3si9n** [comment]
Closing this in favor of https://github.com/sbt/sbt/pull/4355

**Pull request closed without merging**
