### PR TITLE
Evaluate test result only once

### LINKED ISSUE #5003: Test results XML malformed in legacy file name format
## Steps
sbt version: 1.2.8 (doesn't occur on 1.1.6)
scala: 2.13
play: 2.7.3
os: win, linux, osx
run tests in sbt

## Problem
Test results of file prefixed with "TEST-" are sometimes malformed. It looks like they are written 1.5x to the file, which makes the file unparsable. 

Example
```
<?xml version='1.0' encoding='UTF-8'?>
<testsuite tests="9"
           errors="0" failures="0" skipped="0" time="1">
    <properties>
    </properties>
    <testcase classname="xxx"
              name="yyy"
              time="1">
    </testcase>
    <system-out><![CDATA[]]></system-out>
    <system-err><![CDATA[]]></system-err>
</testsuite>m-out><![CDATA[]]></system-out>
<system-err><![CDATA[]]></system-err>
        </testsuite>
```
Note stuff `m-out>...`

## Expectation
All test results should be valid XML.

## Notes
I think it was introduced with #4343, which makes the test results run twice.
It occurs only on one project using sbt 1.2.8 Others have duplicated test results, as expected, and they are all valid XML.

### PR DESCRIPTION
**Pull request by mkljakubowski**
Fixes #5003

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Review by eed3si9n — APPROVED** [review]
Thanks @mkljakubowski!
The change LGTM.
Did you sign the Lightbend CLA?

**Comment by eed3si9n** [comment]
https://www.lightbend.com/contribute/cla/verify

**Comment by mkljakubowski** [comment]
@eed3si9n Yes, I did sign the CLA. This is why I repushed same change. Thought it will validate the CLA again.

**Comment by eatkins** [comment]
@mkljakubowski is the gmail address of the commit the same email address you use for github? The commit email address and the github email address need to be the same for the validator.

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by eed3si9n** [comment]
Closing this in favor of https://github.com/sbt/sbt/pull/5017.

**Comment by eed3si9n** [comment]
@mkljakubowski As Ethan wrote, I think the issue is coming from GitHub not being aware of `mkl.jakubowski` gmail that you're using for the commit. Could you add that to your GitHub profile please? You don't have to make it public, but I think GitHub somehow needs to know.

**Comment by mkljakubowski** [comment]
I have added my email to github settings.
Indeed, it wasn't there. Maybe this was the issue.

**Pull request closed without merging**
