### PR TITLE
Include instructions for backspace key under cygwin (mintty)

### PR DESCRIPTION
**Pull request by bmjsmith**
Added note about setting in mintty to force sending of ^H which is necessary for the scala console backspace to work when jline.UnixTerminal is set and stty erase is ^H.  Additional documentation for #562.

### CODE REVIEW

**Comment by harrah** [comment]
Thanks!  Does this only apply to cygwin with mintty?  Is there a good reason this isn't the default for mintty in the first place?

**Comment by bmjsmith** [comment]
I'm not sure on the why.  There is a lot of history here and I guess the usual "windows does it differently for no apparent reason" sort of thing.

This will apply to any stty configured terminal that has a backspace keypress mapped to a different character than the erase key under stty.  I don't think it will be a problem for msys (git bash) since that seems to be a windows terminal, but would guess rxvt and xterm under cygwin to be similar.

**Comment by harrah** [comment]
Ok, thanks.  Do you think should this be on the main Setup page or on the Setup Notes page?

**Comment by bmjsmith** [comment]
I didn't even know there was a Setup Notes page, so I wouldn't have noticed it there myself.

**Comment by jsuereth** [comment]
Yeah, I think we may want to streamline the setup page.  I think it makes more sense for users to click on what system they want to use to run sbt (like Cygwin, Windows, Debian, Rpm, Universal, Manual) and then pop them into a page that contains information on how to obtain files _and_ some setup notes right inline.  The current flow is a bit too engineery (i.e. fully categorized, but not efficient for user browsing).

**Comment by harrah** [comment]
Merged in https://github.com/sbt/sbt/commit/ffc58d416037db25944ea8bed4a5502ec2643f2f, thanks!

**Pull request closed without merging**
