### PR TITLE
An attempt to fix `compactify` scripted test failure.

### PR DESCRIPTION
**Pull request by gkossakowski**
My suspicion is that Travis CI stopped allowing long file names
on its file system. Let's verify that hypothesis.

### CODE REVIEW

**Comment by gkossakowski** [comment]
Once Travis verifies this PR I'll create an another one with better commit message mentioning #1553.

**Comment by typesafe-tools** [comment]
Can one of the admins verify this patch?

**Comment by jsuereth** [comment]
LGTM!  Thanks for the fix.  Should I wait for the better PR to merge?

**Comment by eed3si9n** [comment]
@gkossakowski ok. I may have misattributed the cause to name hashing. Travis setting was recently changed in #1547.

**Comment by gkossakowski** [comment]
I'll submit improved PR tomorrow.

**Comment by gkossakowski** [comment]
See #1557

**Pull request closed without merging**
