### PR TITLE
[1.x] Bump JLine 3 to `3.28.0`

### PR DESCRIPTION
**Pull request by Friendseeker**
https://github.com/jline/jline3/releases/tag/jline-3.28.0

7 feature PRs, 4 bugfix PRs, 2 maintenance PRs.

Other than https://github.com/jline/jline3/pull/1129, only `.java` files are changed. There's no change around native code & JNI layer.

1 regression (https://github.com/jline/jline3/issues/1139) with `ScriptFile` execution, but it doesn't look like `sbt` is using `ScriptFile` functionalities.

Tested locally on Windows & M1 MacBook against locally published sbt release and tab completion, history, console are working.

### CODE REVIEW

**Comment by eed3si9n** [comment]
Unless there's a change we want, I'm inclined to keep JLine as is for now.

**Comment by Friendseeker** [comment]
> Unless there's a change we want, I'm inclined to keep JLine as is for now.

This makes a lot of sense. I mainly just made the PR to ensure our JLine version is in sync with Scala Compiler's JLine version, as Scala Compiler plans to adopt JLine `3.28.0` in https://github.com/scala/scala/pull/10950.

@SethTisue What do you think? Should we keep JLine versions in sync or okay for them to diverge?

**Comment by SethTisue** [comment]
The unknowns here are unknown unknowns, so we're rolling the dice either way. I'm okay with whatever Eugene decides. I do intend to take the 3.28.0 upgrade for 2.13.17, but that's not for a while.

**Comment by SethTisue** [comment]
we've merged an upgrade to 3.29.0 for 2.13.17

**Pull request closed without merging**
