### PR TITLE
[sbt 1.0] Make publishTo & otherResolvers TaskKey's

### LINKED ISSUE #2059: Change publishTo type from setting Key to task Key
I want to use the credentials taskKey in the definition of the publishTo resolver (S3 Resolver) but I can't.
Is there another way to do this ?

### PR DESCRIPTION
**Pull request by dwijnand**
Fixes #2059

### CODE REVIEW

**Comment by dwijnand** [comment]
`dependency-management/snapshot-resolution` provides an interesting case. It currently has:

``` scala
    publishMavenStyle := (publishTo.value match {
      case Some(repo) =>
        repo match {
          case repo: PatternsBasedRepository => repo.patterns.isMavenCompatible
          case _: RawRepository => false // TODO - look deeper
          case _: MavenRepository => true
          case _: MavenCache => true
          case _ => false  // TODO - Handle chain repository?
        }
      case _ => true
    })
```

That will no longer work as `publishMavenStyle` is a setting and `publishTo` is a task with this PR.

Should I fix it for the test, or shall I make `publishMavenStyle` a task? /cc @eed3si9n

**Comment by dwijnand** [comment]
For now I (somewhat) fixed it locally to that scripted test, just so Travis would go green. But let me know.

**Comment by eed3si9n** [comment]
So we now know it's possible, why do we want this again?

**Comment by dwijnand** [comment]
The initial feature request (#2059) said because they wanted to define `publishTo` in terms of `credentials`, which is a task.

I'm not sure I see a strong use-case there, but, without intending to sound like the devil's advocate, may I invert the question to you: why don't we want to do this?

For clarity, I don't feel strongly that we do, this was just easy pickings that was originally in the 1.0.0 milestone. So I'm happy not to, but we should close the feature request too then.

**Comment by eed3si9n** [comment]
`publishTo` seems to come up occasionally, so I was wondering what your take is. Recently I've seen an issue because bintray-sbt checks for Bintray credential file, and bintray-sbt was included into an Activator template. @2m I think also brought this up.

It's a classic setting vs task debate. From a common sense point of view where you publish your artifacts should not change over the lifetime of an sbt session. Turning it into a runtime behavior seems like an incidental complexity because it might want to depend on things that are tasks. I'm leaning towards merging this, but I want to see what's going on.

**Comment by dwijnand** [comment]
Sounds like you mean https://github.com/softprops/bintray-sbt/issues/88.

There's also @2m's needs-a-rework PR https://github.com/softprops/bintray-sbt/pull/69.

The argument for setting is that we feel it should be sufficient, and settings are more performant (because they're memoized).

The argument for task is that it's more flexible.

So, if you really wonder my take, I mildly bias in this case to allow for the flexibility. (For instance this same argument applied to `version` (https://github.com/sbt/sbt/issues/2171) is much different, because version is so cornerstone to a project).

But I'm happy to hold this PR for a little while, but please let's not put in on the dead-but-no-closed PRs stack - a closed PR can always be re-opened months later.

**Comment by 2m** [comment]
That is correct, @dwijnand. This is what I needed when working on `bintray-sbt` - to be able to make `publishTo` (currenty a setting) depend on `credentials` (currently a task), `publishTo` needs to become a task.

**Comment by dwijnand** [comment]
Artifactory (see #2088) requires the publishing URL to have a `;build.timestamp=...` suffix for SNAPSHOTs, as a guide for what SNAPSHOTs artefacts belong to the same version.

By `publishTo` being a setting defined in terms of current time (eg. `... + ";build.timestamp=" + new java.util.Date().getTime`), the build user must remember to reload the build in order to have a new suffix for the next snapshot release.

Instead if `publishTo` per a task this particular issue would work correctly out the box, because `publishTo` is then read by `publishConfiguration`, which uses the same URL for all the artefacts in the same publish.

At least in terms of the sbt 0.13 codebase, the only other place `publishTo` is used is to define `otherResolvers`, which then because part of the definition of the `ivyConfiguration`.

So I think we should merge this, if TravisCI passes.

**Comment by dwijnand** [comment]
Oh actually, let me know, so I'll write some notes before we merge.

**Comment by dwijnand** [comment]
Thank you

**Pull request merged**
