### PR TITLE
Allow customization of remote cache artifacts

### PR DESCRIPTION
**Pull request by iRevive**
That's my attempt to implement #5638.

I'm new to the SBT code base, therefore some approaches can be reconsidered.  

Currently, I have one concern regarding `RemoteCacheArtifact` ADT.  `final case class` can lead to bin compact problems in the future. Should I use `sealed abstract class` instead?

### CODE REVIEW

**Comment by eed3si9n** [comment]
> Currently, I have one concern regarding RemoteCacheArtifact ADT. final case class can lead to bin compact problems in the future. Should I use sealed abstract class instead?

We created Contraband to generate pseudo case classes - https://www.scala-sbt.org/contraband/. See https://github.com/sbt/sbt/blob/develop/protocol/src/main/contraband/jsonrpc.contra and https://github.com/sbt/sbt/blob/develop/protocol/src/main/contraband/bsp.contra for some examples.

**Comment by iRevive** [comment]
I switched to contraband generated classes.

**Comment by eed3si9n** [comment]
@iRevive Could you add a [scripted test](https://www.scala-sbt.org/1.x/docs/Testing-sbt-plugins.html) under https://github.com/sbt/sbt/tree/develop/sbt/src/sbt-test/actions demonstrating the extension capability?

**Comment by iRevive** [comment]
I've added a scripted test

**Review by eed3si9n — APPROVED** [review]
Thanks!

**Pull request merged**
