### PR TITLE
Add Resolver.bintrayIvyRepo

### PR DESCRIPTION
**Pull request by dwijnand**

### CODE REVIEW

**Comment by typesafe-tools** [comment]
Can one of the admins verify this patch?

**Comment by dwijnand** [comment]
I guess `bintrayIvyRepo` is a better name. WDYT?

**Comment by eed3si9n** [comment]
+1 on `bintrayIvyRepo`

**Comment by dwijnand** [comment]
Updated.

**Comment by dwijnand** [comment]
Fixed compilation error.

**Pull request merged**
