### PR TITLE
port addSbtPluginCommand to sbt 0.13

### PR DESCRIPTION
**Pull request by jastice**
Port #4211 to sbt 0.13 so that IntelliJ Scala plugin can use plugin injection without requiring users to upgrade their sbt builds to 1.x

edit: it actually does work as expected

### CODE REVIEW

**Comment by eed3si9n** [comment]
I wonder if Travis is failing because it's on Java 6.

```
$ java -Xmx32m -version
java version "1.6.0_41"
```

Maybe we need to use `-Dsbt.repository.secure=false`

**Comment by jastice** [comment]
I've had resolve problems with JDK7 as well. In that case adding these parameters worked:
`-Djdk.tls.client.protocols=TLSv1.2 -Dhttps.protocols=TLSv1.2`

With JDK6 that probably won't work.

**Comment by jastice** [comment]
required for https://youtrack.jetbrains.com/issue/SCL-14247

**Comment by eed3si9n** [comment]
Please rebase on 0.13.

**Pull request merged**
