### PR TITLE
Fix a number of terminal io bugs

### LINKED ISSUE #5863: 1.4.0-RC1 regression: Enter in sbt terminal is not working when running code using readLine
## steps

Non-working Enter is happening under these conditions under Linux version 5.4.0-47-generic and Ubuntu 18.04.1:
```
$ cat project/build.properties 
sbt.version=1.4.0-RC1

$ cat build.sbt 
scalaVersion := "2.13.3"

$ cat Main.scala 
object Main {
  def main(args: Array[String]): Unit = {
    println("Hello, World!")
    val s = scala.io.StdIn.readLine("write something: ")
    println(s"You wrote: $s")
  }
}

$ sbt
[info] welcome to sbt 1.4.0-RC1 (Ubuntu Java 11.0.8)
```
Now run and write something including Enter, see example of user input below echoed to terminal:
```
sbt:hello-scala> run
[info] compiling 1 Scala source to /home/bjornr/tmp/hello-scala/target/scala-2.13/classes ...
[info] running Main 
Hello, World!
write something: write something: now user is typing but WHY write something ECHOED TWICE? now pressing enter
pressing enter again
now enter twice 

readLine is never ended
now pressing Ctrl+D
You wrote: now user is typing but WHY write something ECHOED TWICE? now pressing enter
[success] Total time: 45 s, completed Sep 17, 2020, 12:19:24 PM
sbt:hello-scala> 
[info] shutting down sbt server
```

## problem

Three problems probably related to jline:
* The enter key is not working when trying to complete a readLine by user
* The text message given as argument to readLine is echoed twice
* When finally exiting readLine using Ctrl+D then sbt is terminated

## expectation

* The Enter key should work with readLine as in sbt 1.3.13
* The text message given as argument to readLine should only be printed once
* Ctrl+D in readLine should not terminate sbt

## notes

This might be related to #5861 and #5856

### PR DESCRIPTION
**Pull request by eatkins**
This PR fixes #5863 #5856 #5828.

### CODE REVIEW

**Comment by eed3si9n** [comment]
Looks like AppVeyor got stuck?

```
[info] sbt server started at local:sbt-server-cdcbba2ed91f9a230908
[info] new client connected: network-1
{"jsonrpc":"2.0","id":1,"result":{"capabilities":{"textDocumentSync":{"openClose":true,"change":0,"willSave":false,"willSaveWaitUntil":false,"save":{"includeText":false}},"hoverProvider":false,"definitionProvider":true}}}
[info] new client connected: network-2
success
[info] - exit success
[info] new client connected: network-3
[info] - exit failure
[info] new client connected: network-4
success
[info] - two commands
[info] new client connected: network-5
[info] - two commands with failing second
[info] new client connected: network-6
[info] - two commands with leading failure
[info] new client connected: network-7
success
[info] - three commands
[info] new client connected: network-8
[info] - three commands with middle failure
[info] new client connected: network-9
[info] - compi completions
[info] new client connected: network-10

No cached test names found. Press '<tab>' to compile: 
```

**Comment by eatkins** [comment]
Looking

**Comment by eatkins** [comment]
Yep. There was a small oversight that the test caught by hanging. I fixed the underlying problem but also made it so that the tests shouldn't get stuck in the future.

**Comment by melezov** [comment]
Hey there! In regards to #5828, I'm afraid this branch makes things much worse :(

    [instafin-web] $ show sbtVersion
    [info] 1.4.0-SNAPSHOT
    [instafin-web] $ HOME [1;%p1%dH END [1;%p1%dF UP [1;%p1%dA DOWN [1;%p1%dB LEFT [1;%p1%dD RIGHT [1;%p1%dC

The arrow keys no longer work. BACKSPACE works, but I can't get to test DELETE since I can't "move" before another character with either HOME nor LEFT.

Pls, instruct if there's a different component to QA other than eatkins/terminal-fixes (only build SBT, no modules).
The same behavior is exhibited in powershell, windows console, cygwin treminal, ...
Using Windows 10.

The workaround `sbt -Djline.terminal=jline.UnsupportedTerminal` that worked with 1.4.0-RC1 is no longer operational and doesn't allow "typing in" any characters on this branch.

**Comment by eatkins** [comment]
Thanks for testing this. I don't think it should be too terrible to fix your issues. The difference is likely that I have been doing my windows testing on a vm over ssh. I will test directly on the vm using the powershell command.

**Comment by eatkins** [comment]
I can reproduce on my vm outside of ssh so I'm optimistic I can fix this quickly.

**Comment by eatkins** [comment]
@melezov I was able to reproduce and fix the issues you reported with the latest code.

**Review by eed3si9n — APPROVED** [review]
Thanks!

**Comment by melezov** [comment]
Great, will test immediately! (better while we're still in RC phase) :)

**Comment by melezov** [comment]
Fantastic, with 1.4.0-RC2 Home, End, Delete and Backspace all work perfectly.

I'd like to also report a collateral enhancement in that the Insert button which didn't work in 1.3.x now works in SBT 1.4.0-RC2 🥇 
(albeit, it still only shows as ~ when in SBT's console, but that's the same as in 1.3.x)

Thanks a lot!

**Comment by eatkins** [comment]
You're welcome. I did indeed have to add special handling for the insert key https://github.com/sbt/sbt/pull/5874/commits/036fef33832ae672f13c394f39a0ed1b5040d4ec. I'm a little confused though. What does "(albeit, it still only shows as ~ when in SBT's console, but that's the same as in 1.3.x)" mean? Does it work in some scenarios but not others? I did test that if I manually typed \E[2~ that it switched to insert mode but I don't actually have an insert key so I wasn't sure that it would definitely work with a keyboard that did have one.

**Comment by melezov** [comment]
Oh, it means that if you run "sbt console" in your project thus entering the Scala REPL for the project, the Insert key will not work and only emit the tilde ~ character instead. 

This is the same as how it behaved in SBT 1.3.x's "sbt console", I'm assuming it's an issue of the underlying Scala REPL.
Honestly extremely low priority, but perhaps the REPL peeps might learn something from your fix?

**Comment by eatkins** [comment]
Aah, that makes sense. Is this scala 2.13, 2.12 or dotty?

**Comment by melezov** [comment]
The `~` is in 2.12. 
But yes, now I remember I've seen the different handling for 2.13 - it works there 🎉

I haven't yet touched dotty with a 9-foot pole, so 🤷‍♀️ there

**Pull request merged**
