### PR TITLE
Sort setting key names in the inspect tree view

### PR DESCRIPTION
**Pull request by 2m**
This little add-on helps quite a lot when comparing two dependency trees, i.e. after and before a change in the build.

### CODE REVIEW

**Comment by jsuereth** [comment]
Thanks for the submission!  This LGTM once tests report back success or timeout.

**Comment by 2m** [comment]
Yea. I tried to run tests on my machine, but it seems to hang at some places.

**Comment by jsuereth** [comment]
`scripted` timed out or `test`?   We have a legitimate deadlock somewhere in the process code, but I can't actually remove the commit which introduced it due to binary compatibility restrictions and I haven't been able to fix it. (Note:  Don't use #> or <# in the process lib)

**Comment by 2m** [comment]
It would just stop running tests after a while, and would not drop back to sbt console.

```
[info] + Locks.Lock in nonexisting directory: OK, passed 100 tests.
[info] + Locks.Uncontested re-entrant lock: OK, passed 100 tests.
[info] + Locks.Uncontested double lock: OK, passed 100 tests.
[info] + Locks.Contested single lock: OK, passed 100 tests.
[info] Passed: Total 56, Failed 0, Errors 0, Passed 56
^C
```

Another try.

```
[info] Total for specification ScalaProviderTest
[info] Finished in 2 ms
[info] 9 examples, 0 failure, 0 error
[info] 
[info] Passed: Total 56, Failed 0, Errors 0, Passed 56
^C
```

**Comment by jsuereth** [comment]
Right.  It's the `scripted` test which matter, generally.  And after the lock tests is the Process test, which has the deadlock.  In any case, Travis is reporting the usual timeouts I see, so this is good to go.

**Pull request merged**
