### PR TITLE
JLine 3.27.0 (was 3.24.1) for sbt 1.10.x

### PR DESCRIPTION
**Pull request by SethTisue**
wdyt @eed3si9n might it be this simple?

at https://github.com/jline/jline3/releases/tag/jline-parent-3.25.0 it says: "Merge Jansi library into JLine" and I'm unclear on whether that's somehow problematic for us here.

fyi @hamzaremmal

if this works out I can forward-port to `develop` branch, of course.

### CODE REVIEW

**Comment by eed3si9n** [comment]
```bash
[info] /home/runner/.cache/coursier/jvm/graalvm-java11@22.2.0/bin/native-image -cp /home/runner/work/sbt/sbt/client/target/native-image-internal/manifest.jar --no-fallback --initialize-at-run-time=sbt.client -H:IncludeResourceBundles=jline.console.completer.CandidateListCompletionHandler -H:+ReportExceptionStackTraces -H:-ParseRuntimeOptions -H:Name=/home/runner/work/sbt/sbt/client/target/bin/sbtn sbt.client.Client /home/runner/work/sbt/sbt/client/target/bin/sbtn
WARNING: Unknown module: org.graalvm.nativeimage.llvm specified to --add-exports
WARNING: Unknown module: org.graalvm.nativeimage.llvm specified to --add-exports
WARNING: Unknown module: org.graalvm.nativeimage.llvm specified to --add-exports
Error: Could not find option 'UnlockExperimentalVMOptions' from 'jar:file:///home/runner/.cache/coursier/v1/https/repo1.maven.org/maven2/org/jline/jline-terminal-jna/3.25.1/jline-terminal-jna-3.25.1.jar!/META-INF/native-image/org.jline/jline-terminal-jna/native-image.properties'. Use -H:PrintFlags= to list all available options.
Could not find option 'UnlockExperimentalVMOptions' from 'jar:file:///home/runner/.cache/coursier/v1/https/repo1.maven.org/maven2/org/jline/jline-native/3.25.1/jline-native-3.25.1.jar!/META-INF/native-image/org.jline/jline-native/native-image.properties'. Use -H:PrintFlags= to list all available options.
Could not find option 'UnlockExperimentalVMOptions' from 'jar:file:///home/runner/.cache/coursier/v1/https/repo1.maven.org/maven2/org/jline/jline-terminal/3.25.1/jline-terminal-3.25.1.jar!/META-INF/native-image/org.jline/jline-terminal/native-image.properties'. Use -H:PrintFlags= to list all available options.
Could not find option 'UnlockExperimentalVMOptions' from 'jar:file:///home/runner/.cache/coursier/v1/https/repo1.maven.org/maven2/org/jline/jline-terminal-jansi/3.25.1/jline-terminal-jansi-3.25.1.jar!/META-INF/native-image/org.jline/jline-terminal-jansi/native-image.properties'. Use -H:PrintFlags= to list all available options.
Error: Image build request failed with exit status 1
[error] native-image command failed with exit code '1'
[error] (sbtClientProj / nativeImage) native-image command failed with exit code '1'
[error] Total time: 30 s, completed Feb 21, 2024 1:21:47 AM
```

**Comment by eed3si9n** [comment]
Per https://github.com/jline/jline3/pull/886/commits/2e9c4f907191068f6a3686ac11e37ced115b0638 JLine 3 use Graal Native Image 23.1.1, but because JDK 23 isn't out yet, our normal channels to get GraalVM, like Coursier or SDKMAN do not list graal 23 yet.

**Comment by SethTisue** [comment]
so I should try to use https://github.com/marketplace/actions/github-action-for-graalvm, I guess? I'm unfamiliar with Graal stuff

**Comment by SethTisue** [comment]
~note to self: Eugene's https://github.com/sbt/sbt/pull/7501 has some changes I should maybe pull in~ done

**Comment by xuwei-k** [comment]
- https://github.com/sbt/sbt/issues/7502 🤔

**Comment by hvesalai** [comment]
@eed3si9n do you think this would be back-ported to 1.9.x also?

**Comment by eed3si9n** [comment]
Not sure, but we should first get it working for 1.10.x?

**Comment by SethTisue** [comment]
sorry I haven't had time lately to push this PR forward, but I haven't forgotten, either. (I also owe the scala/scala repo a similar PR.) once it's merged, it would be good to have an sbt 1.10.0-M2 that we could test with before maybe back porting to 1.9.x — feels like it's been a while since M1

**Comment by SethTisue** [comment]
about Graal, Eugene has inquired at https://github.com/jline/jline3/issues/954

**Comment by SethTisue** [comment]
> because JDK 23 isn't out yet, our normal channels to get GraalVM, like Coursier or SDKMAN do not list graal 23 yet 

According to https://www.graalvm.org/release-calendar/ , "Note: Beginning with JDK 21, the release numbering scheme for language runtimes differs from the one used for GraalVM releases"

So I think it's not relevant that JDK 23 isn't out yet, unless I'm confused.

As for how to actually proceed, I've been trying to figure that out...

**Comment by SethTisue** [comment]
JLine 3.26.0 is out — I'll update this PR to use it instead. It's supposed to fix the Graal Native Image issue.

**Comment by mkurz** [comment]
Didn't make it into sbt 1.10.0 :cry: Hoping for a patch release...

**Comment by eed3si9n** [comment]
I tried locally before releasing sbt 1.10.0, and afaict the situation has not changed with the new JLine.

**Comment by SethTisue** [comment]
no improvement in JLine 3.26.3 either

I wish I had time to dig into this, but I know nothing about Native Image. It's possible I could try to figure it out sometime after October 1.

**Comment by SethTisue** [comment]
superseded by #7695

**Pull request closed without merging**
