### PR TITLE
Disable macro heuristic for inherited macros (sbt/sbt#1142)

### PR DESCRIPTION
**Pull request by Duhemm**
> At the moment, any change (even whitespace change) to a file containing a macro will trigger invalidation of files that depend on it. The reason is that we don't have any means to detect change to implementation of a macro that could affects clients that call it so we err on conservative side.

This pull request fixes this behavior. Classes that inherit a macro are no longer considered as having a macro.

Please see [this discussion](https://github.com/sbt/sbt/issues/1142).

### CODE REVIEW

**Comment by xeno-by** [comment]
Hi guys! What do you think about this pull request?

**Comment by jsuereth** [comment]
Up to @gkossakowski .   It looks good to me, but missed the 0.13.2-RC1 by a day.  0.13.5-M2 is coming soon though (0.13.5 probably out around April), so I'm targetting it at that.

**Comment by xeno-by** [comment]
Is there are you are going to have RC2? This is such a huge improvement to usability of SBT with macros!

**Comment by gkossakowski** [comment]
I'll have a look either tonight or tomorrow.

**Comment by jsuereth** [comment]
IF a critical issue opens in the next 2 weeks, we'll have an RC2.  We normally don't allow non-regression fixes once something is in RC and 0.13.2 has been too long delayed.  However 0.13.5 will be out like a month after 0.13.2 anyway, so you shouldn't have to wait long. 

IN fact, 0.13.5 may hit RC almost immediately after 0.13.2 is out, we'll see.

**Comment by jsuereth** [comment]
Build failure appears to be a transient issue.

**Comment by gkossakowski** [comment]
Hi guys, I'm sorry for being behind on this. I got busy with some other tasks. I'll definitively look into this on Wednesday.

**Comment by Duhemm** [comment]
Thank you, I just made the changes. It looks like your comments disappeared. They were [here for the first commit](https://github.com/Duhemm/sbt/commit/1677ac86bf2be7f7d0783550b19d6af3de951802) and [there for the second](https://github.com/Duhemm/sbt/commit/6902e712785b62c7c6ebf897ef56e533339a0b94)

**Comment by gkossakowski** [comment]
LGTM

Excellent work. Thanks!

**Comment by gkossakowski** [comment]
This will be shipped as part of sbt 0.13.5.

**Pull request merged**
