### PR TITLE
Update TypedPath apis

### PR DESCRIPTION
**Pull request by eatkins**
I renamed getPath to toPath in io so we need to update sbt to using the
correct api.

- [x] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md) guidelines

### CODE REVIEW

**Comment by eatkins** [comment]
This needs a new io version to pass ci.

**Comment by typesafe-tools** [comment]
A validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt-validator/1329/console">is in progress...</a>

**Comment by typesafe-tools** [comment]
[//]: # (Refs: pull/4515/head-develop-develop-develop-develop)
The validator <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/1329/">has checked</A> the following projects, tested using dbuild, projects built on top of each other.

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | <A HREF="https://github.com/sbt/sbt/pull/4515">pull/4515/head      </A> | sbt/sbt@0fc92b9a76791398f79ebd7b2afd24c3edcf24ba
  zinc              | <A HREF="https://github.com/sbt/zinc/tree/develop">develop             </A> | sbt/zinc@f8d1bada4d238232b9a5b45e6e9870c31f1fc5f4
  io                | <A HREF="https://github.com/sbt/io/tree/develop">develop             </A> | sbt/io@277853c6f925777982a3b4e7fb4d953e6f012bb0
  librarymanagement | <A HREF="https://github.com/sbt/librarymanagement/tree/develop">develop             </A> | sbt/librarymanagement@96a3293c7d6b4533b7ccdd4e07be27717e6172a0
  util              | <A HREF="https://github.com/sbt/util/tree/develop">develop             </A> | sbt/util@2e0d2d920a9f11c1910f0a5d48a2ff6f2c57c44d

:x: The result is: ***FAILED***
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild?sbt=pull/4515/head&zinc=develop&io=develop&librarymanagement=develop&util=develop&deploy_to_bintray=false&run_sbt_community=false">(restart)</A>

**Comment by typesafe-tools** [comment]
A validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt-validator/1331/console">is in progress...</a>

**Comment by typesafe-tools** [comment]
[//]: # (Refs: pull/4515/head-develop-develop-develop-develop)
The validator <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/1331/">has checked</A> the following projects, tested using dbuild, projects built on top of each other.

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | <A HREF="https://github.com/sbt/sbt/pull/4515">pull/4515/head      </A> | sbt/sbt@161dfd77f289e24150baf4db5904223df845134b
  zinc              | <A HREF="https://github.com/sbt/zinc/tree/develop">develop             </A> | sbt/zinc@f8d1bada4d238232b9a5b45e6e9870c31f1fc5f4
  io                | <A HREF="https://github.com/sbt/io/tree/develop">develop             </A> | sbt/io@277853c6f925777982a3b4e7fb4d953e6f012bb0
  librarymanagement | <A HREF="https://github.com/sbt/librarymanagement/tree/develop">develop             </A> | sbt/librarymanagement@96a3293c7d6b4533b7ccdd4e07be27717e6172a0
  util              | <A HREF="https://github.com/sbt/util/tree/develop">develop             </A> | sbt/util@2e0d2d920a9f11c1910f0a5d48a2ff6f2c57c44d

:white_check_mark: The result is: ***SUCCESS***
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild?sbt=pull/4515/head&zinc=develop&io=develop&librarymanagement=develop&util=develop&deploy_to_bintray=false&run_sbt_community=false">(restart)</A>

**Review by eed3si9n — APPROVED** [review]
Thanks @eatkins!

**Pull request merged**
