### PR TITLE
Fix bug in release script due to typo.

### PR DESCRIPTION
**Pull request by jsuereth**
- Fix collection typo
- Create shared command to setup 2.11 builds
- Alter snapshot detection to allow more flexible milestone versioning.
- Remove cusotm isSnapshot key for new sbt 0.13.2 isSnapshot key.

Review by @eed3si9n cc> @paulp

Also, please WAIT for travis to report success/failure before merging.

### CODE REVIEW

**Comment by eed3si9n** [comment]
- https://travis-ci.org/sbt/sbt/jobs/25521909

```
:: problems summary ::
:::: WARNINGS
        [FAILED     ] org.scala-sbt#test-agent;0.13.2!test-agent.jar: The HTTP response code for http://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/test-agent/0.13.2/jars/test-agent.jar did not indicate a success. See log for more detail. (15030ms)
```
- https://travis-ci.org/sbt/sbt/jobs/25521920

```
[info] > Exception: java.util.NoSuchElementException: null
[info] + settings.Derived setting(s) replace DerivedSetting in the Seq[Setting[_]]: OK, proved property.
[info] + settings.DerivedSetting in ThisBuild scopes derived settings under projects thus allowing safe +=: OK, passed 100 tests.
[error] Error: Total 11, Failed 0, Errors 1, Passed 10
[error] Error during tests:
[error]     sbt.SettingsTest
```
- https://travis-ci.org/sbt/sbt/jobs/25521921

```
[error] (task-system/test:test) sbt.TestsFailedException: Tests unsuccessful
[error] (classpath/test:test) sbt.TestsFailedException: Tests unsuccessful
```

**Comment by jsuereth** [comment]
Ping @eed3si9n.  I just rebased with fixed tests and travis should be kicking off soon.

**Comment by eed3si9n** [comment]
Github says I can't merge this automatically.

**Comment by jsuereth** [comment]
Ok, rebased.

**Pull request merged**
