### PR TITLE
Escape path in Proguard in order to build xsbt under windows (with spaces in path)

### PR DESCRIPTION
**Pull request by stevegury**
Hi Mark,

I've found a problem when trying to build the master branch of xsbt on Windows (especially because I use paths with spaces).
There was some paths used by proguard in InstallExtractProject that was not properly escaped.

When trying to fixed this, I've found that they was a trait ProguardProject where all the proguard stuffs was defined. I've refactored InstallExtractProject to mix this trait, I've not see any problem with that, can you confirm that this fix is correct ?

Thanks,
Steve Gury

### CODE REVIEW

**Comment by harrah** [comment]
Hi Steve,

Thanks for working on this.  Comments:
1) The changes to ProguardProject look ok except perhaps you meant log.debug instead of log.error in the second commit?
2) The diff to InstallExtractProject shows up as touching every line, although it looks like most lines aren't touched.  Can you fix this?
3) The file permissions are changed from 644 to 755 (perhaps a windows+git issue?), which isn't needed.

Thanks,
Mark

**Comment by stevegury** [comment]
Mark,

I've made the appropriate changes, as requested.
Here is some quick comments on your remarks:
1) You're right, it was some forgotten debugging trace
2) My IDE change the "tab indented" file into a "double space indented" file, my bad
3) You're right it was a cygwin + git issue

Thanks for reading my code,
Steve

**Comment by harrah** [comment]
Thanks, Steve.  It looks good now.  I assume you replaced @ with -include because @ didn't mix well with escaping?

-Mark

**Comment by stevegury** [comment]
My first guess was that @ didn't work with quoted path, but actually no, "@" and "-include " are equivalent.
I can change "-include " to "@" if you prefer ?

Steve

**Comment by harrah** [comment]
Hi Steve,

Sorry it took so long to get back to you.  Using -include is not a problem.  Can you squash the commits into one, though?

Thanks,
Mark

**Comment by stevegury** [comment]
Hi Mark,

Here is the squash commit (3da8e4fdf00c2d799f9d)

Enjoy,
Steve

**Comment by harrah** [comment]
Done, thanks.

**Pull request closed without merging**
