### PR TITLE
Serialize Event.error.

### PR DESCRIPTION
**Pull request by vigdorchik**

### CODE REVIEW

**Comment by harrah** [comment]
Looks good, just needs a test.

**Comment by vigdorchik** [comment]
@harrah please check again. Many thanks to @ewiner for the test.

**Comment by harrah** [comment]
Unfortunately the comments on previous patches get dropped, but I still think there should be a custom Exception subclass.  This would do two things.  First, `new Throwable(e.error().toString)` means that the toString of that throwable will include an unnecessary `java.lang.Throwable:` prefix.  Second, it can be used by a client to see that it is a translated exception and not the original and have access to the name of the original exception.

**Comment by vigdorchik** [comment]
@harrah though github doesn't show it, I modified the commit to incorporate your suggestions. Looks better now, thank you.

**Comment by harrah** [comment]
Looks good, thanks.

**Comment by harrah** [comment]
Merged in b8ef434ec1b611d300646e2ad7f2638a377cbad5

**Pull request closed without merging**
