### PR TITLE
Recreating output JAR on packageBin if file was deleted

### LINKED ISSUE #4118: Packaged JAR file not re-generated if deleted
## Configuration
```scala
name := "sbt-test"

version := "0.1"

scalaVersion := "2.12.5"

artifactPath in (Compile, packageBin) := unmanagedBase.value / "build.jar"
```

## Steps
1. Run `packageBin`
2. Delete the `lib/build.jar` file
3. Run `packageBin`

## Problem
The `lib/build.jar` file is not re-created.

## Workaround
Remove `target/streams/compile/packageBin/$global/streams/output`.

## Notes
sbt version: 1.1.4

### PR DESCRIPTION
**Pull request by dadarakt**
fixes #4118

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @dadarakt,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by lightbend-cla-validator** [comment]
Hi @dadarakt,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Review by dwijnand — APPROVED** [review]
LGTM! Thanks @dadarakt.

@eed3si9n how do you feel about landing this in 1.1.x?

**Review by eed3si9n — APPROVED** [review]
Thanks @dadarakt!

**Comment by eed3si9n** [comment]
@dwijnand It's a bug fix so why not?

**Comment by dwijnand** [comment]
I wanted to gauge your assessment on how safe or not of a code change it is for a patch release.

I'm guessing you're happy with it. I am too.

**Pull request merged**
