### PR TITLE
Bump io

### PR DESCRIPTION
**Pull request by eatkins**
- [x] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md) guidelines
This is a prerequisite for #4335. Once we release a new io, I'll remove the "REVERT travis..." commit and change the 'Bump io' commit to go to the latest io version rather than `1.2.2-SNAPSHOT`.

### CODE REVIEW

**Comment by typesafe-tools** [comment]
A validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt-validator/1065/console">is in progress...</a>

**Comment by eatkins** [comment]
The travis build succeeds when built against an io snapshot, so I think this should be good to go once we release a new io version and I make the changes described above.

**Comment by typesafe-tools** [comment]
[//]: # (Refs: pull/4406/head-develop-pull/192/head-develop-develop)
The validator <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/1065/">has checked</A> the following projects, tested using dbuild, projects built on top of each other.

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | <A HREF="https://github.com/sbt/sbt/pull/4406">pull/4406/head      </A> | sbt/sbt@0d9ea24c595219135a0a0bff820ab16b2f956f3e
  zinc              | <A HREF="https://github.com/sbt/zinc/tree/develop">develop             </A> | sbt/zinc@64aa612552780dd24ef6b68885e7269d73a9bfe8
  io                | <A HREF="https://github.com/sbt/io/pull/192">pull/192/head       </A> | sbt/io@7d9d90da5c82639be9c64ea241c8e742ac46ccb7
  librarymanagement | <A HREF="https://github.com/sbt/librarymanagement/tree/develop">develop             </A> | sbt/librarymanagement@b8fd1805c315dd7fca2f356d12c01bbff50456de
  util              | <A HREF="https://github.com/sbt/util/tree/develop">develop             </A> | sbt/util@f16997d3a9ab2388b98bbf39bb2a70244d1e8d7c

:white_check_mark: The result is: ***SUCCESS***
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild?sbt=pull/4406/head&zinc=develop&io=pull/192/head&librarymanagement=develop&util=develop&deploy_to_bintray=false&run_sbt_community=false">(restart)</A>

**Review by eed3si9n — DISMISSED** [review]
LGTM pending CI

**Review by muuki88 — DISMISSED** [review]

**Pull request merged**
