### PR TITLE
Add quit command, an alias of exit. Fixes #1374.

### LINKED ISSUE #1374: quit vs. exit - unify the way how to leave any session/tool
Hi, wouldn't be better to make quitting console and sbt with the same command?
## steps

Now I need
If I want to leave console session:

```
:quit
```

If I want to leave sbt:

```
exit
```
### problem

?
### expectation

I suppose 'exit' and ':exit' would save many errors ...

### PR DESCRIPTION
**Pull request by dwijnand**
Fixes #1374.
Implemented so that it matches the Scala REPL's :quit.

### CODE REVIEW

**Comment by typesafe-tools** [comment]
Can one of the admins verify this patch?

**Comment by eed3si9n** [comment]
Wouldn't it make sense for the unified command to be vim quit? (e.g. `:quit` and `:q`)

**Comment by dwijnand** [comment]
Given the typos/inversions in the original ticket I assumed `quit` was intended.

I'm happy with whatever, I use ctl-D personally.
Would you want to drop `quit` from this PR (while adding `:quit` and `:q`)?

**Comment by eed3si9n** [comment]
We can do all three:
- `quit`
- `:quit`
- `:q`

**Comment by jsuereth** [comment]
Can we also have `kthxbai` as an option?  I've always wanted that to be supported too.

/the peanut gallery will shut up now.

**Comment by dwijnand** [comment]
Of course `kthxbai` , how could I forget?

**Comment by dwijnand** [comment]
I can obviously whip up 2 more commands (and probably will if no one comments back before) but I'm wondering, should these perhaps be encoded as aliases? i.e. using [BasicCommands.newAlias](https://github.com/sbt/sbt/blob/0.13.8/main/command/src/main/scala/sbt/BasicCommands.scala#L261-L262)?

**Comment by eed3si9n** [comment]
Alias would probably be better.

**Comment by dwijnand** [comment]
Hmm thank god I checked:

```
java.lang.AssertionError: assertion failed: ':quit' is not a valid command name.
    at scala.Predef$.assert(Predef.scala:179)
    at sbt.SimpleCommand.<init>(Command.scala:17)
    at sbt.Command$.make(Command.scala:33)
    at sbt.Command$.make(Command.scala:32)
    at sbt.BasicCommands$.newAlias(BasicCommands.scala:275)
```

:-/ Thoughts?

**Comment by eed3si9n** [comment]
I don't think there's a point in having `quit` if it doesn't work on Scala REPL.

One way to "solve" this is to define a plugin that does something along the lines of:

```
initialCommands += "\nimport sys.exit"
```

For Scala versions that defines `sys.exit`. That will allow `exit` to work on both REPL and sbt shell.

**Comment by dwijnand** [comment]
I'm not sure, perhaps having `quit` available would also make sbt a little more beginner-friendly (I'm thinking of Ctrl-C in vim :D). If so I'd just need to tweak the note, and I'll still make the command an alias.

WRT the original issue, I'll update that ticket with what we've discovered here and your suggestion, as it would obviously mean work elsewhere. Maybe I'll still do it, as it could be my gateway drug into writing and maintaining an actual sbt plugin.

**Comment by dwijnand** [comment]
Let me know if a `quit` command is still of interest.

**Pull request closed without merging**
