### PR TITLE
fix CommandStrings.settingsDetailed

### PR DESCRIPTION
**Pull request by xuwei-k**

### CODE REVIEW

**Comment by harrah** [comment]
LGTM.   Please merge at your convenience.  You should have access.

**Comment by xuwei-k** [comment]
>  You should have access.

I was given "Pull Only" access. Maybe I don't have merge(or push) permission.

https://github.com/organizations/sbt/teams/104229
screen shot 2014-01-07 at 2 09 42 am

**Comment by harrah** [comment]
I'm sorry about that.  The sbt-committers team should have push access now.

**Comment by xuwei-k** [comment]
Thanks!

**Pull request merged**
