### PR TITLE
Backport #2941 to 0.13.x

### PR DESCRIPTION
**Pull request by haochi**
Backporting the asciiGraphWidth setting that was merged in 1.0.x recently

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @haochi,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Review by dwijnand — APPROVED** [review]
Thank you @haochi. I've restarted the CI jobs that failed. LGTM.

**Comment by haochi** [comment]
@dwijnand Great thanks. I signed the CLA.

**Comment by dwijnand** [comment]
Thank you @haochi! And welcome to sbt.

**Pull request merged**
