### PR TITLE
javaOptions and javacOptions would be better off as Task

### PR DESCRIPTION
**Pull request by indrajitr**
This will also make things consistent with scalacOptions

### CODE REVIEW

**Comment by harrah** [comment]
Merged, too invasive for 0.11.1 though.

**Comment by indrajitr** [comment]
Yes, that was my worry too. But then realized most users (usually plugin folks) who have to do anything with `javaOptions` and `javacOptions` would rather want to treat them like `scalacOptions`. Since nobody raised this so far it's likely that it hasn't yet been used in situation where `Setting` and `Task` actually make difference ;)

**Comment by harrah** [comment]
Yes, I agree it will be preferred, but it would still be good to have a release without requiring source changes in such a simple case.

**Comment by indrajitr** [comment]
Now that I see you have created 0.11.1 branch (release imminent?), I completely agree on your position.

This isn't really that serious a bug to warrant code change so close to a release. It's just a pre-requisite to #252 which is very invasive to go in a dot release anyway.

**Comment by harrah** [comment]
Not so imminent, but soon enough to start putting commits on a different branch.

**Comment by indrajitr** [comment]
Wonderful!

**Pull request closed without merging**
