### PR TITLE
"inspect tree <key>" command

### PR DESCRIPTION
**Pull request by eed3si9n**
## overview

This is a slightly cleaned up version of [sbt-inspectr](https://github.com/eed3si9n/sbt-inspectr).
When `inspect tree <key>` is called, `SettingGraph` case class is created recursively
along the dependencies, calling the similar code as `inspect` command's `Project.details`.
`SettingGraph` extends `Graph` trait, which is able to render itself as an ascii tree.
## sample usage

```
> inspect 
Display all 217 possibilities? (y or n) 
> inspect tree pa
package                 package-bin             package-configuration
package-doc             package-options         package-src
packaged-artifact       packaged-artifacts      parallel-execution
> inspect tree package
[info] compile:package = Task[java.io.File]
[info]   +-compile:package-bin = Task[java.io.File]
[info]     +-compile:package-configuration(for package-bin) = Task[sbt.Packag..
[info]     | +-compile:mappings(for package-bin) = Task[scala.collection.Seq[..
[info]     | | +-compile:products = Task[scala.collection.Seq[java.io.File]]
[info]     | | 
[info]     | +-compile:artifact-path(for package-bin) = target/scala-2.9.1/he..
[info]     | | +-*:cross-target = target/scala-2.9.1
[info]     | | +-compile:artifact(for package-bin) = Artifact(helloworld,jar,..
[info]     | | | +-*/*:artifact-classifier = None
[info]     | | | +-compile:configuration = compile
[info]     | | | 
[info]     | | +-*/*:scala-version = 2.9.1
[info]     | | +-*:project-id = production:helloworld:0.1-SNAPSHOT
[info]     | | +-*/*:artifact-name = <function3>
[info]     | | 
[info]     | +-compile:package-options(for package-bin) = Task[scala.collecti..
[info]     |   +-*:organization = production
[info]     |   +-*:name = helloworld
[info]     |   +-compile:main-class = Task[scala.Option[java.lang.String]]
[info]     |   +-*/*:version = 0.1-SNAPSHOT
[info]     |   +-*/*:homepage = None
[info]     |   +-*:organization-name = production
[info]     |   +-*/*:package-options = Task[scala.collection.Seq[sbt.PackageO..
[info]     |   
[info]     +-compile:cache-directory(for package-bin) = target/scala-2.9.1/ca..
[info]     +-compile:streams(for package-bin) = Task[sbt.std.TaskStreams[sbt...
[info]       +-*/*:streams-manager = Task[sbt.std.Streams[sbt.Init$ScopedKey[..
[info]       
> inspect package
[info] Task: java.io.File
[info] Description:
[info]  Produces the main artifact, such as a binary jar.  This is typically an alias for the task that actually does the packaging.
[info] Provided by:
[info]  {file:/Users/eed3si9n/work/helloworld/}default-b65acd/compile:package
[info] Dependencies:
[info]  compile:package-bin
[info] Delegates:
[info]  compile:package
[info]  *:package
[info]  {.}/compile:package
[info]  {.}/*:package
[info]  */compile:package
[info]  */*:package
[info] Related:
[info]  test:package
> inspect actual package
[info] Task: java.io.File
[info] Description:
[info]  Produces the main artifact, such as a binary jar.  This is typically an alias for the task that actually does the packaging.
[info] Provided by:
[info]  {file:/Users/eed3si9n/work/helloworld/}default-b65acd/compile:package
[info] Dependencies:
[info]  compile:package-bin
[info] Delegates:
[info]  compile:package
[info]  *:package
[info]  {.}/compile:package
[info]  {.}/*:package
[info]  */compile:package
[info]  */*:package
[info] Related:
[info]  test:package
> help inspect

inspect [tree] <key>

    For a plain setting, the value bound to the key argument is displayed using its toString method.
    Otherwise, the type of task ("Task" or "Input task") is displayed.

    "Dependencies" shows the settings that this setting depends on.
    If 'tree' is specified, the bound value as well as the settings that this setting depends on
    (and their bound values) are displayed as a tree structure.

    "Reverse dependencies" shows the settings that depend on this setting.

    When a key is resolved to a value, it may not actually be defined in the requested scope.
    In this case, there is a defined search sequence.
    "Delegates" shows the scopes that are searched for the key.
    "Provided by" shows the scope that contained the value returned for the key.

    "Related" shows all of the scopes in which the key is defined.


> 
```

### CODE REVIEW

**Comment by harrah** [comment]
For the terminal width patch, I don't know how expensive the call to getting the terminal width is.  Do you want to capture the value once at the start of printing or is it ok to call for every line?

Is there a reason Graph is a trait instead of passing the current node as an argument to toAscii?

This:

``` scala
(Space ~> token("tree")) | (Space ~> token("actual"))
```

should be:

``` scala
token(Space ~> ("tree" | "actual"))
```

There are two places where proper data structures should be used.  The first is in the parsing code above, where the choices between 'tree', 'actual', or neither should be represented by appropriate types.  ('actual' and 'tree' are not technically mutually exclusive, but you don't need to implement that here).

The second is that the manifest checking code should be factored out so that there aren't two very similar copies.  The factored out method should return the discovered task/input task/value in an appropriate data type.

**Comment by harrah** [comment]
Also, `IO.relativize` will give you `Option[String]` instead of `Option[File]` and catching every exception should be replaced with something more specific.

**Comment by eed3si9n** [comment]
> For the terminal width patch, I don't know how expensive the call to getting the terminal width is. Do you want to capture the value once at the start of printing or is it ok to call for every line?

I don't know how expensive it is either, but I could capture this once per top-level call.

> Is there a reason Graph is a trait instead of passing the current node as an argument to toAscii?

Let me see if I can make Graph an object.

> The second is that the manifest checking code should be factored out so that there aren't two very similar copies. The factored out method should return the discovered task/input task/value in an appropriate data type.

Yea. My eventual plan was to refactor the existing `inspect` to call `SettingGraph` with one level of recursion, but I wanted to test the water before making the incision.

**Comment by harrah** [comment]
This:

``` scala
token(Space ~> ("tree" | "actual")).?
```

should be:

``` scala
val actual = "actual" ^^^ Details(true)
val tree = "tree" ^^^ DependencyTree
token(Space ~> (tree | actual)) ?? Details(false)
```

Also, make Details final.  With those changes, squash it into one commit and it is ready to be merged.  The manifest checking code and the terminal width can come in a later patch.

**Comment by eed3si9n** [comment]
Are public signatures considered an API or it's ok to change them?
I am thinking about changing:

``` scala
def details(structure: BuildStructure, actual: Boolean, scope: Scope, key: AttributeKey[_])(implicit display: Show[ScopedKey[_]]): String
```

to 

``` scala
def details(extracted: Extracted, actual: Boolean, scope: Scope, key: AttributeKey[_])(implicit display: Show[ScopedKey[_]]): String
```

since `Extracted` seems like the best place to hang the key manifest extraction.

**Comment by eed3si9n** [comment]
squashed.

**Comment by harrah** [comment]
Great, thanks!

Extracted should be for commonly used methods that need State or BuildStructure.  This needs BuildStructure, but I don't think it qualifies as commonly used.  Perhaps put it in Project.

**Comment by harrah** [comment]
Also, prefer the more specific type (here, BuildStructure) when possible.  For the API question, I'm trying to keep changes to common methods either source compatible or move them to the next minor release (here, 0.12.0).

**Pull request merged**
