### PR TITLE
Merge the 1.0.0 branch into 1.x

### PR DESCRIPTION
**Pull request by dwijnand**
Alternative to #3406: just straight up merge the 1.0.0 branch.

### CODE REVIEW

**Comment by eed3si9n** [comment]
@dwijnand Did Travis CI test the state of 1.0.0, or 1.x with merged commits?

**Comment by eed3si9n** [comment]
I think https://github.com/sbt/sbt/pull/3406 was better because I branched it off of 1.x.

**Comment by dwijnand** [comment]
GitHub pull requests merge the pull request branch into the target branch, creating a merge commit. That is the commit that Travis CI tests. Here's a reference to it: https://github.com/sbt/sbt/tree/pull/3407/merge.

You can see that in Travis CI: https://travis-ci.org/sbt/sbt/jobs/262148682

```
$ git clone --depth=50 https://github.com/sbt/sbt.git sbt/sbt
Cloning into 'sbt/sbt'...
remote: Counting objects: 6684, done.
remote: Compressing objects: 100% (3162/3162), done.
remote: Total 6684 (delta 2024), reused 5910 (delta 1761), pack-reused 0
Receiving objects: 100% (6684/6684), 1.44 MiB | 0 bytes/s, done.
Resolving deltas: 100% (2024/2024), done.
Checking connectivity... done.

$ cd sbt/sbt
$ git fetch origin +refs/pull/3407/merge:
remote: Counting objects: 291, done.
remote: Compressing objects: 100% (121/121), done.
remote: Total 291 (delta 138), reused 272 (delta 123), pack-reused 0
Receiving objects: 100% (291/291), 43.31 KiB | 0 bytes/s, done.
Resolving deltas: 100% (138/138), completed with 41 local objects.
From https://github.com/sbt/sbt
 * branch            refs/pull/3407/merge -> FETCH_HEAD

$ git checkout -qf FETCH_HEAD
```

In #3406 you create a merge commit (A) from 1.0.0 and 1.x and then want to create another merge commit between A and 1.x. I removed the extra step and the extra commit.

**Comment by eed3si9n** [comment]
> That is the commit that Travis CI tests.

I don't know. When I pull the pr/3407 locally it looks like 1.0.0, missing ba37d568f8b01c98b08ca78bf53d8067854d55b5:

```
$ git log --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit
c592b2f54 - (HEAD -> pr/3407, upstream/pr/3407, upstream/1.0.0) Merge pull request #3396 from dwijnand/rc3 (7 days ago) <Dale Wijnand>
a495aa7cb - (upstream/pr/3396) Upgrade to sbt 1.0.0-RC3 (7 days ago) <Dale Wijnand>
2f9029c62 - Merge pull request #3395 from dwijnand/mima (8 days ago) <Dale Wijnand>
deae720bf - (upstream/pr/3395) Bump mimaPreviousArtifacts to 1.0.0-RC3 (8 days ago) <Dale Wijnand>
1d3d29cda - Merge pull request #3387 from eed3si9n/wip/notes (11 days ago) <eugene yokota>
dcff4dd5e - (upstream/pr/3387) notes (11 days ago) <Eugene Yokota>
07879e26e - (tag: v1.0.0-RC3) Merge pull request #3385 from eed3si9n/wip/contraband2 (11 days ago) <eugene yokota>
b38dbc361 - Merge pull request #3380 from eed3si9n/wip/skipinpublish (11 days ago) <eugene yokota>
d1a950868 - (upstream/pr/3385) Use LM API for cached update task (11 days ago) <Eugene Yokota>
4d8d5f5df - IO, Util, LM, Zinc 1.0.0-RC3 (11 days ago) <Eugene Yokota>
0850df67e - Contraband 0.3.0 (11 days ago) <Eugene Yokota>
716203fef - Merge pull request #3383 from dwijnand/2123 (11 days ago) <Dale Wijnand>
518a905d3 - Merge pull request #3382 from eed3si9n/wip/slf4j (11 days ago) <eugene yokota>
56d7d400b - (upstream/pr/3383) Upgrade to Scala 2.12.3 (11 days ago) <Dale Wijnand>
5768ad246 - (upstream/pr/3382, origin/wip/slf4j) Log4j 2 SLF4J Binding (11 days ago) <Eugene Yokota>
5e8bbf8d0 - (upstream/pr/3380) implement `skip in publish` (12 days ago) <Eugene Yokota>
2b35107a0 - Merge pull request #3376 from eed3si9n/fport/3370 (12 days ago) <Dale Wijnand>
9a26f7ba1 - (upstream/pr/3376) Fix ^^ and don't inject scalaVersion by default (13 days ago) <Eugene Yokota>
c9f9f5ca3 - Merge pull request #3349 from dwijnand/mima (13 days ago) <eugene yokota>
c103950b1 - (upstream/pr/3349) Add, configure & enable MiMa (13 days ago) <Dale Wijnand>
3a14bd809 - Merge pull request #3367 from eed3si9n/wip/keys (13 days ago) <Dale Wijnand>
996b760a9 - Merge pull request #3365 from sbt/wip/terminalwidth (2 weeks ago) <eugene yokota>
b27ff9ace - (upstream/pr/3367) Unify to camel cased setting key (2 weeks ago) <Eugene Yokota>
57b34f56d - Merge pull request #3364 from sbt/wip/newfix (2 weeks ago) <Dale Wijnand>
467617a4b - Implement withRank (2 weeks ago) <Eugene Yokota>
f96c8b966 - (upstream/pr/3365) InteractionService#terminalWidth (2 weeks ago) <Eugene Yokota>
a68372fd5 - (upstream/pr/3364) Fix new command (2 weeks ago) <Eugene Yokota>
ac7b1498a - Merge pull request #3363 from sbt/fport/3329 (2 weeks ago) <eugene yokota>
696aacb31 - (upstream/pr/3363) Make scripted support sbt 1.0.0-RC1 or later (2 weeks ago) <Dale Wijnand>
26954994e - Merge pull request #3362 from sbt/fport/3356 (2 weeks ago) <eugene yokota>
2c4e78f41 - (upstream/pr/3362) Override current project's scalaVersion on ^^ (2 weeks ago) <Eugene Yokota>
82a8ca87e - Merge pull request #3358 from sbt/wip/linereader (2 weeks ago) <eugene yokota>
d6803f064 - Merge pull request #3351 from Duhemm/wip/fix-3299 (2 weeks ago) <Dale Wijnand>
a58b1ebce - (upstream/pr/3358) Keep ConsoleChannel open (2 weeks ago) <Eugene Yokota>
7b2b7d696 - Don't wrap InputStream for Windows (2 weeks ago) <Eugene Yokota>
9dfe1a840 - (upstream/pr/3351) Allow `.value` on SettingKey inside ifs & lambdas (3 weeks ago) <Martin Duhem>
4f42e2aa5 - Merge pull request #3346 from dwijnand/imports (3 weeks ago) <eugene yokota>
1b68c909c - Merge pull request #3345 from dwijnand/rm-Seq2Vector (3 weeks ago) <eugene yokota>
f821ddb6d - (upstream/pr/3346) Add missing aliases in Imports (3 weeks ago) <Dale Wijnand>
be1b4897e - (upstream/pr/3345) Un-implicit & deprecated Seq2Vector (3 weeks ago) <Dale Wijnand>
a06873683 - Merge pull request #3342 from sbt/wip/sbt1 (3 weeks ago) <Dale Wijnand>
b2220fe9d - (upstream/pr/3342) sbt 1.0.0-RC2 (3 weeks ago) <Eugene Yokota>
```

**Comment by dwijnand** [comment]
You're looking at the head commit of pull/3407: https://github.com/sbt/sbt/tree/pull/3407/head
I'm talking about the merge commit of pull/3407: https://github.com/sbt/sbt/tree/pull/3407/merge

**Comment by dwijnand** [comment]
Found a bug in GitHub. Or maybe a limitation. https://github.com/sbt/sbt/blob/pull/3407/merge/CONTRIBUTING.md doesn't work.

But if you [get the permalink](https://help.github.com/articles/getting-permanent-links-to-files/) to https://github.com/sbt/sbt/tree/pull/3407/merge you get:

https://github.com/sbt/sbt/tree/f9cf12282401379927d41eab28bcb591c21086ba

and thus https://github.com/sbt/sbt/blob/f9cf12282401379927d41eab28bcb591c21086ba/CONTRIBUTING.md

where Typesafe references have been changed with Lightbend references.

**Comment by eed3si9n** [comment]
ok. Thanks for the clarification.

**Review by eed3si9n — APPROVED** [review]

**Pull request merged**
