### PR TITLE
bump lm-coursier-shaded 2.0.0-RC4-1

### LINKED ISSUE #5132: [1.3.x coursier] artifact type overriden in libraryDependencies ignored
## steps
sbt version: 1.3.0, 1.3.2

build.sbt
```
libraryDependencies += "io.grpc" % "protoc-gen-grpc-java" % "1.23.0" % "compile" artifacts(Artifact("protoc-gen-grpc-java", "protoc-plugin", "exe", "linux-x86_64"))
```

## problem

update report shows `exe` as artifact type
```
bjaglin@x1:/tmp/sbt$ sbt "show update" | grep -m1 protoc-gen-grpc-java
[info] 		io.grpc:protoc-gen-grpc-java:1.23.0:default: (Artifact(protoc-gen-grpc-java, exe, exe, Some(linux-x86_64), Vector(), Some(https://repo1.maven.org/maven2/io/grpc/protoc-gen-grpc-java/1.23.0/protoc-gen-grpc-java-1.23.0-linux-x86_64.exe), Map(), None, false),/home/bjaglin/.cache/coursier/v1/https/repo1.maven.org/maven2/io/grpc/protoc-gen-grpc-java/1.23.0/protoc-gen-grpc-java-1.23.0-linux-x86_64.exe)
```

## expectation

update report should show `protoc-plugin` as artifact type

https://github.com/sbt/librarymanagement/blob/3377168/core/src/main/scala/sbt/librarymanagement/ModuleIDExtra.scala#L120-L125
> If this ModuleID represents a dependency, these artifact definitions override the information in the dependency's published metadata.

## notes

disabling coursier brings back the 1.2.x / expected behavior

```
bjaglin@x1:/tmp/sbt$ sbt "show update" | grep -m1 protoc-gen-grpc-java
[info] 		io.grpc:protoc-gen-grpc-java:1.23.0: (Artifact(protoc-gen-grpc-java, protoc-plugin, exe, Some(linux-x86_64), Vector(), None, Map(), None, false),/home/bjaglin/.ivy2/cache/io.grpc/protoc-gen-grpc-java/protoc-plugins/protoc-gen-grpc-java-1.23.0-linux-x86_64.exe)
```

### PR DESCRIPTION
**Pull request by bjaglin**
Fixes #5132

### CODE REVIEW

**Comment by bjaglin** [comment]
It looks like there is a regression on `scripted compiler-project/src-dep-plugin`

https://travis-ci.org/sbt/sbt/jobs/599607627
```
Running compiler-project/src-dep-plugin
[info] [info] Loading project definition from /tmp/sbt_a1e8cc4e/project
[info] [info] Compiling 1 Scala source to /tmp/sbt_a1e8cc4e/project/target/scala-2.12/sbt-1.0/classes ...
[info] [info] Done compiling.
[info] [info] Loading settings for project sbt_a1e8cc4e from build.sbt ...
[info] [info] Loading settings for project def from build.sbt ...
[info] [info] Set current project to sbt_a1e8cc4e (in build file:/tmp/sbt_a1e8cc4e/)
[info] [info] Set current project to src-dep-plugin (in build file:/tmp/sbt_a1e8cc4e/)
[info] [warn] 
[info] [warn] 	Note: Unresolved dependencies path:
[info] [error] sbt.librarymanagement.ResolveException: Error downloading org.example:demo-compiler-plugin_2.12:0.1
[info] [error]   Not found
[info] [error]   not found: /home/travis/.ivy2/local/org.example/demo-compiler-plugin_2.12/0.1/ivys/ivy.xml
[info] [error]   not found: https://repo1.maven.org/maven2/org/example/demo-compiler-plugin_2.12/0.1/demo-compiler-plugin_2.12-0.1.pom
[info] [error] 	at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:245)
[info] [error] 	at lmcoursier.CoursierDependencyResolution.$anonfun$update$34(CoursierDependencyResolution.scala:214)
[info] [error] 	at scala.util.Either$LeftProjection.map(Either.scala:573)
[info] [error] 	at lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:214)
[info] [error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:60)
[info] [error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:52)
[info] [error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:102)
[info] [error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:69)
[info] [error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:115)
[info] [error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:228)
[info] [error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:115)
[info] [error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:96)
[info] [error] 	at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:150)
[info] [error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:129)
[info] [error] 	at sbt.Classpaths$.$anonfun$updateTask0$5(Defaults.scala:2946)
[info] [error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[info] [error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[info] [error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[info] [error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[info] [error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[info] [error] 	at sbt.Execute.work(Execute.scala:290)
[info] [error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[info] [error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[info] [error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[info] [error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[info] [error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[info] [error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[info] [error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[info] [error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[info] [error] 	at java.base/java.lang.Thread.run(Thread.java:834)
[info] [error] (use / update) sbt.librarymanagement.ResolveException: Error downloading org.example:demo-compiler-plugin_2.12:0.1
[info] [error]   Not found
[info] [error]   not found: /home/travis/.ivy2/local/org.example/demo-compiler-plugin_2.12/0.1/ivys/ivy.xml
[info] [error]   not found: https://repo1.maven.org/maven2/org/example/demo-compiler-plugin_2.12/0.1/demo-compiler-plugin_2.12-0.1.pom
[info] [error] Total time: 1 s, completed Oct 18, 2019, 12:29:20 PM
[error] x compiler-project/src-dep-plugin 
[error]  Cause of test exception: {line 2}  Command failed: use/compile failed
```

**Comment by bjaglin** [comment]
bisecting the regression:
- 2.0.0-RC4-1 is KO
- 2.0.0-RC4 is KO
- **2.0.0-RC3-6 is KO**
- 2.0.0-RC3-5 is OK
- 2.0.0-RC3-4 is OK (master)

https://github.com/coursier/sbt-coursier/compare/v2.0.0-RC3-5...v2.0.0-RC3-6 gives us a good potential candidate: https://github.com/coursier/sbt-coursier/pull/136 (which by the way was not brought-in here despite the fact that https://github.com/sbt/sbt/issues/4995#issuecomment-537222424 was closed?)

**Comment by bjaglin** [comment]
I am not familiar with what the scripted test protects, should I open an issue upstream?

**Comment by alexarchambault** [comment]
@bjaglin Yeah, https://github.com/coursier/sbt-coursier/pull/136 is the culprit. In the mean time, if you still want to benefit from the fix of https://github.com/sbt/sbt/issues/5132, you can add the `sbt-lm-coursier` plugin, like
```scala
addSbtPlugin("io.get-coursier" % "sbt-lm-coursier" % "2.0.0-RC4-1")
```

**Edit**: I'm not sure about that (sbt-lm-coursier) ^ It'll work with the [coursier-based sbt launcher](https://github.com/coursier/sbt-launcher), usable via [its custom sbt-extras script](https://raw.githubusercontent.com/coursier/sbt-extras/master/sbt), but I'm not sure it will with the default sbt launcher.

**Comment by bjaglin** [comment]
@eed3si9n @alexarchambault, since you were author/reviewer of https://github.com/coursier/sbt-coursier/pull/136, can you advise on the next step? Namely, whether the behavior that the failing scripted protects should be handled by sbt-coursier so that the discussion can continue in a new upstream ticket, or if https://github.com/coursier/sbt-coursier/pull/136 should first be reverted (and reworked later), as it prevents any coursier bump in sbt? Thanks!

**Comment by eed3si9n** [comment]
so https://github.com/sbt/sbt/blob/e17c64dfb60e56fd9070115ac6b051f7a1985a97/sbt/src/sbt-test/compiler-project/src-dep-plugin/build.sbt is:

```scala
import Configurations.{CompilerPlugin => CPlugin}

lazy val use = project.dependsOn(RootProject(file("def")) % CPlugin).settings(
  autoCompilerPlugins := true
)
```

This requires that the `CompilerPlugin` configuration of `use` to depend on the `Compile` configuration of `def` subproject, which I think is similar to the concern I raised in https://github.com/coursier/sbt-coursier/pull/136#discussion_r324250741. I'd say the next step would be to fix Coursier?

**Comment by eed3si9n** [comment]
https://github.com/coursier/sbt-coursier/pull/158

**Comment by eed3si9n** [comment]
Closing this in favor of https://github.com/sbt/sbt/pull/5240

**Pull request closed without merging**
