### PR TITLE
Ensure sequences in analysis files are read in order.

### PR DESCRIPTION
**Pull request by benjyw**
For various reasons, we serialize sequences as:

0 -> foo
1 -> bar
...

Until now we were implicitly relying on the sequences being in order.
However external code may end up (due to bugs or otherwise) messing
with the ordering:

1 -> bar
0 -> foo
...

This change ensures that we don't get confused by that. Although
it's best if external code doesn't mess up the ordering, it's still
a good idea to be defensive about this.

Note that the sequences we serialize are short, so the extra sort
is not a performance concern.

### CODE REVIEW

**Comment by jsuereth** [comment]
So, for the Travis failure, I rebooted the failing 2.11 job just to see if it was a transient "concurrency" test failure.  reviewing shortly.

**Comment by gkossakowski** [comment]
@jsuereth: I'm happy to review anything incremental compiler related.

**Comment by gkossakowski** [comment]
Actually, it's one-liner. Hence LGTM.

**Comment by jsuereth** [comment]
Hmm, looks like we have some sort of unrelated 2.11 concurrency issue here making the tests fail.   I'm ok merging this, but we shouldn't let anything big through until we figure out that issue.

**Comment by benjyw** [comment]
Thanks for the quick turnaround!

**Pull request merged**
