### PR TITLE
Default force gc to false

### PR DESCRIPTION
**Pull request by jsuereth**
Workaround for #1329 
Related #1223

Review by @eed3si9n

### CODE REVIEW

**Comment by eed3si9n** [comment]
Could you add a documentation in `src/sphinx/Community/Changes.rst` for adding the force GC, and now defaulting to `false`?

**Comment by jsuereth** [comment]
@eed3si9n done.  Also removed mention of RC1->RC2.   That kind of info isn't really needed in Changes, which is more about major release changes.

**Comment by ijuma** [comment]
Good to see this. Forcing GCs so frequently is too dangerous.

**Comment by jsuereth** [comment]
@ijuma sadly, we'll have to have some kind of an alternative to try to request one on misbehaving machines.  We're getting way to many preventable permgen errors on jenkins.

**Pull request merged**
