### PR TITLE
use Relaxed reconciliation strategy by default 

### LINKED ISSUE #4720: [1.3.0-RC1] coursier fails when with "Conflicting dependencies"
- [x] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md) guidelines

## steps
Add `"com.github.gpgekko" % "sbt-autoprefixer" % "1.2.0"` to a project

## problem
```
[error] lmcoursier.internal.shaded.coursier.error.ResolutionError$Several: Error downloading org.webjars.npm:browserslist:[2.5.1,3)
[error]   Not found
[error]   not found: https://repo1.maven.org/maven2/org/webjars/npm/browserslist/2.11.3/browserslist-2.11.3.pom
[error]   not found: C:\Users\katri\.ivy2\local\org.webjars.npm\browserslist
[error]   not found: https://repo.triplequote.com/artifactory/sbt-plugins-release/org.webjars.npm/browserslist/
[error]   not found: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.webjars.npm/browserslist/
[error]   not found: http://repo.typesafe.com/typesafe/releases/org/webjars/npm/browserslist/maven-metadata.xml
[error] Conflicting dependencies:
[error] org.webjars.npm:is-number:2.1.0:default(compile)
[error] org.webjars.npm:is-number:4.0.0:default(compile)
[error] org.webjars.npm:kind-of:3.2.2:default(compile)
[error] org.webjars.npm:kind-of:6.0.2:default(compile)
[error] org.webjars.npm:string-width:1.0.2:default(compile)
[error] org.webjars.npm:string-width:2.1.1:default(compile)
[error] org.webjars.npm:strip-ansi:3.0.1:default(compile)
[error] org.webjars.npm:strip-ansi:4.0.0:default(compile)
[error]         at lmcoursier.internal.shaded.coursier.error.ResolutionError$.from(ResolutionError.scala:70)
[error]         at lmcoursier.internal.shaded.coursier.Resolve.validate0$1(Resolve.scala:141)
[error]         at lmcoursier.internal.shaded.coursier.Resolve.$anonfun$ioWithConflicts0$4(Resolve.scala:183)
[error]         at lmcoursier.internal.shaded.coursier.util.Task$.$anonfun$flatMap$2(Task.scala:11)
[error]         at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
[error]         at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
[error]         at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] (update) lmcoursier.internal.shaded.coursier.error.ResolutionError$Several: Error downloading org.webjars.npm:browserslist:[2.5.1,3)
[error]   Not found
[error]   not found: https://repo1.maven.org/maven2/org/webjars/npm/browserslist/2.11.3/browserslist-2.11.3.pom
[error]   not found: C:\Users\katri\.ivy2\local\org.webjars.npm\browserslist
[error]   not found: https://repo.triplequote.com/artifactory/sbt-plugins-release/org.webjars.npm/browserslist/
[error]   not found: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.webjars.npm/browserslist/
[error]   not found: http://repo.typesafe.com/typesafe/releases/org/webjars/npm/browserslist/maven-metadata.xml
[error] Conflicting dependencies:
[error] org.webjars.npm:is-number:2.1.0:default(compile)
[error] org.webjars.npm:is-number:4.0.0:default(compile)
[error] org.webjars.npm:kind-of:3.2.2:default(compile)
[error] org.webjars.npm:kind-of:6.0.2:default(compile)
[error] org.webjars.npm:string-width:1.0.2:default(compile)
[error] org.webjars.npm:string-width:2.1.1:default(compile)
[error] org.webjars.npm:strip-ansi:3.0.1:default(compile)
[error] org.webjars.npm:strip-ansi:4.0.0:default(compile)
```

## expectation
Now, the POM truly is missing for some reason, but it worked just fine with 1.2.8

sbt version: 1.3.0-RC1

### PR DESCRIPTION
**Pull request by eed3si9n**
Fixes #4720
Ref coursier/coursier#1293
This is currently blocked by coursier/sbt-coursier#112

### CODE REVIEW

**Review by eatkins — DISMISSED** [review]
LGTM, though I'm not really that familiar with this area of sbt.

**Comment by eed3si9n** [comment]
I am starting to see NoClassDefFoundError in the Travis CI and AppVeyor jobs:

```
[info] [error] java.lang.NoClassDefFoundError: Could not initialize class org.fusesource.jansi.AnsiOutputStream
[info] [error] 	at jline.internal.Ansi.stripAnsi(Ansi.java:28)
[info] [error] 	at jline.console.ConsoleReader.setPrompt(ConsoleReader.java:499)
[info] [error] 	at jline.console.ConsoleReader.readLine(ConsoleReader.java:2425)
[info] [error] 	at jline.console.ConsoleReader.readLine(ConsoleReader.java:2378)
[info] [error] 	at jline.console.ConsoleReader.readLine(ConsoleReader.java:2366)
```

Could this be related to https://github.com/coursier/coursier/pull/1283, which adds JAnsi 1.18?

sbt uses JLine2, which in-sources older JAnsi 1.12 - https://github.com/jline/jline2/blob/jline-2.14.6/pom.xml#L122

@alexarchambault Is there a way to shade this?

Edit: I sent a PR - https://github.com/coursier/sbt-coursier/pull/120. It seems to work at least locally.

Edit2: Just saw https://github.com/coursier/sbt-coursier/pull/118.

**Comment by alexarchambault** [comment]
To repeat my opinion from coursier issues / PRs, I'm not sure it's a good idea to change the default version reconciliation just to accomodate some npm modules. Enable it for `org.webjars.*:*` if you want, but enabling it for all modules is just going to confuse people, and result in invalid classpaths down the line…

**Comment by eed3si9n** [comment]
The purpose of this change is more for keeping semantic compatibility with Ivy's resolution. Even though version ranges (intervals) are used more often in the context of webjars, I think it's worse to have an ah-hoc rules for a subset of artifacts.

I started digging deep into this area when I ran Lagom sample applications using sbt 1.3.0-RC3 (https://github.com/lagom/lagom-samples/pull/82) and found the following:

```
[error] lmcoursier.internal.shaded.coursier.error.ResolutionError$ConflictingDependencies: Conflicting dependencies:
[error] io.grpc:grpc-core:1.16.1:default(compile)
[error] io.grpc:grpc-core:1.20.0:default(compile)
[error] io.grpc:grpc-core:[1.16.1]:default(compile)
[error] io.grpc:grpc-core:[1.20.0]:default(compile)
[error] 	at lmcoursier.internal.shaded.coursier.Resolve$.validate(Resolve.scala:394)
[error] 	at lmcoursier.internal.shaded.coursier.Resolve.validate0$1(Resolve.scala:140)
[error] 	at lmcoursier.internal.shaded.coursier.Resolve.$anonfun$ioWithConflicts0$4(Resolve.scala:184)
[error] 	at lmcoursier.internal.shaded.coursier.util.Task$.$anonfun$flatMap$2(Task.scala:14)
[error] 	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
[error] 	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
[error] 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (hello-impl / update) lmcoursier.internal.shaded.coursier.error.ResolutionError$ConflictingDependencies: Conflicting dependencies:
[error] io.grpc:grpc-core:1.16.1:default(compile)
[error] io.grpc:grpc-core:1.20.0:default(compile)
[error] io.grpc:grpc-core:[1.16.1]:default(compile)
[error] io.grpc:grpc-core:[1.20.0]:default(compile)
```

Since we have lots of Play and Lagom users, smooth transition of is a must have. Note that this isn't a webjar conflict. I think it would be better to migrate all users first into Couriser-based sbt, and then provide them with various options to make their graph more correct, using eviction report and/or strict mode.

Also part of the issue might be that the error reporting has regressed compared to lm-ivy that reports error with tree-view (https://github.com/sbt/sbt/pull/1447):

```
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: foundrylogic.vpp#vpp;2.2.1: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn]  Note: Unresolved dependencies path:
[warn]      foundrylogic.vpp:vpp:2.2.1
[warn]        +- org.apache.cayenne:cayenne-tools:3.0.2
[warn]        +- org.apache.cayenne.plugins:maven-cayenne-plugin:3.0.2
[warn]        +- d:d_2.10:0.1-SNAPSHOT
```

Reporting errors or conflicts this way might allow the build users to reduce some (probably not all) of the unnecessary transitive conflicts.

**Comment by eed3si9n** [comment]
GitHub UI is not reflecting the force push of 4fb7a49a94041678997284429f0af97a022157b2.

**Comment by eed3si9n** [comment]
Now it's not letting me reopen the PR

**Comment by eed3si9n** [comment]
To clarify it does say "eed3si9n force-pushed the eed3si9n:wip/coursier  branch from 38659ea to 4fb7a49", but the commits are not reflected on the commits UI, and more importantly CIs weren't notified (so I attempted to close and reopen):

commits

New PR is https://github.com/sbt/sbt/pull/4950

**Pull request closed without merging**
