### PR TITLE
chore: set a default timeout for ci

### LINKED ISSUE #7747: Add a timeout for CI jobs
c.c. https://github.com/sbt/sbt/actions/runs/9440926154/job/26000938266

Some job runs forever. Should kill them early. Say a 25 minute timeout.

### PR DESCRIPTION
**Pull request by nathanlao**
### This is a

Chore update to close https://github.com/sbt/sbt/issues/7747

### Background 

Some job runs forever, set a default 25 mins to kill them

### Solution

Reference: https://stackoverflow.com/questions/59073731/set-default-timeout-on-github-action-pipeline

### CODE REVIEW

**Review by Friendseeker — APPROVED** [review]
Thanks for the contribution!

**Review by adpi2 — APPROVED** [review]
Thanks!

**Comment by adpi2** [comment]
@nathanlao Could you please sign the CLA?

Go to https://www.lightbend.com/contribute/cla/scala and then comment on the pull request to ask for a new check.

**Comment by nathanlao** [comment]
Just done signing the CLA! Thank you for taking the time to review, appreciate the chance to contribute 🙌

**Comment by Friendseeker** [comment]
@nathanlao Would you like to port the PR to `develop` branch, or would you like me to do it?

**Comment by nathanlao** [comment]
> @nathanlao Would you like to port the PR to `develop` branch, or would you like me to do it?

@Friendseeker Hey, thanks for reminding! Can I submitted another pr to develop branch?

**Comment by Friendseeker** [comment]
> > @nathanlao Would you like to port the PR to `develop` branch, or would you like me to do it?
> 
> @Friendseeker Hey, thanks for reminding! Can I submitted another pr to develop branch?

Of course! Thanks for the contribution.

**Pull request merged**
