### PR TITLE
Make ZombieClassLoader thread safe

### PR DESCRIPTION
**Pull request by eatkins**
The previous implementation of ZombieClassLoader was not thread safe.
This caused problems because it is possible for the ManagedClassLoader
in test to leak into the coursier thread pool if the test uses bouncy
castle apis. Unfortunately, these apis seem to in some cases assign
static variables using the Thread context class loader. Because the
bouncycastle apis are implemented by the jdk, they are found in the
system classloader and thus the static references leak out of the test
context.

I had a local repro of https://github.com/sbt/sbt/issues/5249 that is
fixed by this change.

### CODE REVIEW

**Review by eed3si9n — APPROVED** [review]
Thank you!  🙌

**Comment by amanjpro** [comment]
On 1.3.5 and still seeing this error. Are you sure it is fixed?

```
Uncaught error from thread [test-linear-ads-akka.actor.internal-dispatcher-2]: loader constraint violation: loader (instance of sbt/internal/ManagedClassLoader$ZombieClassLoader) previously initiated loading for a different type with name "akka/io/TcpConnection", shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[test-linear-ads]
java.lang.LinkageError: loader constraint violation: loader (instance of sbt/internal/ManagedClassLoader$ZombieClassLoader) previously initiated loading for a different type with name "akka/io/TcpConnection"
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
  | => lat java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at akka.io.TcpConnection$$anonfun$peerSentEOF$1.applyOrElse(TcpConnection.scala:111)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:242)
	at akka.actor.Actor.aroundReceive(Actor.scala:533)
	at akka.actor.Actor.aroundReceive$(Actor.scala:531)
	at akka.io.TcpConnection.aroundReceive(TcpConnection.scala:32)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:573)
	at akka.actor.ActorCell.invoke(ActorCell.scala:543)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:269)
	at akka.dispatch.Mailbox.run(Mailbox.scala:230)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:242)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by eatkins** [comment]
This is a different, though related, bug. The next version of sbt will not close classloaders by default so you will not run into this. That being said, this may be an opportunity to audit your actor systems. I'm assuming that you're seeing these errors after running test. If so, then it means that your actor system is still running after your tests have completed. Leaked actor systems cause sbt performance to degrade over times. This can be fixed by calling `ActorSystem.terminate()` once the tests complete.

**Comment by amanjpro** [comment]
I double checked, and I made sure to Termiante all the started actors-systems. But now I see this error, which confuses me a lot:

```
java.lang.IllegalStateException: Shutdown in progress
	at java.lang.ApplicationShutdownHooks.remove(ApplicationShutdownHooks.java:82)
	at java.lang.Runtime.removeShutdownHook(Runtime.java:239)
	at sbt.internal.ShutdownHooks$.close(ShutdownHooks.scala:44)
	at sbt.xMain$.run(Main.scala:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sbt.internal.XMainConfiguration.run(XMainConfiguration.scala:45)
	at sbt.xMain.run(Main.scala:39)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:111)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:130)
	at xsbt.boot.Launch$.run(Launch.scala:111)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:37)
	at xsbt.boot.Launch$.launch(Launch.scala:119)
	at xsbt.boot.Launch$.apply(Launch.scala:20)
	at xsbt.boot.Boot$.runImpl(Boot.scala:56)
	at xsbt.boot.Boot$.main(Boot.scala:18)
	at xsbt.boot.Boot.main(Boot.scala)
[error] [launcher] error during sbt launcher: java.lang.IllegalStateException: Shutdown in progress
```

It still hangs, and SBT stays unresponsive, not even listening to Ctrl+C

**Pull request merged**
