### PR TITLE
Fix problem with initialization order in ClassToAPI.scala.

### PR DESCRIPTION
**Pull request by gkossakowski**
In `ClassToAPI` both `Private` and `Protected` vals had forward
reference to `Unqualified` so they would get `null` as a result.
Fixed that by rearranging the order of vals being declared.

This fixes a problem described in 9dd5f07.

Also, reverts 9dd5f07.

### CODE REVIEW

**Comment by gkossakowski** [comment]
@harrah: the fact that those members (and now turns out) modifiers were broken for so long and nobody noticed is quite astonishing. I don't know how that was possible.

**Comment by harrah** [comment]
Merged, thanks.  I agree it is isn't clear how this wasn't noticed.  There might be something more to it, so I'll look into it.  Thanks for finding and fixing the problem.

**Comment by harrah** [comment]
Looking at `ClassToAPI.mergeMap`, the `public` parameter gets filtered to only include inherited members.  When `getDeclaredMethods` was incorrectly passed here, it would be filtered to be empty because `getDeclaredMethods` includes no inherited members.  So, there wouldn't be anything to process.

In the other case, `getMethods` only returns public methods so there are no private/protected modifiers.

**Comment by gkossakowski** [comment]
@harrah: oh I get it. Thanks for digging into it. It's interesting combination of bugs we had here.

**Pull request closed without merging**
