### PR TITLE
Watch trigger

### PR DESCRIPTION
**Pull request by eatkins**

### CODE REVIEW

**Review by eed3si9n — DISMISSED** [review]

**Comment by eed3si9n** [comment]
appveyor failed

```
[info] [error] C:\Users\appveyor\AppData\Local\Temp\1\sbt_73978247\src\main\scala\sbt\test\A.scala:3:10: '}' expected but eof found.
[info] [error] class A {
[info] [error]          ^
[info] [error] C:\Users\appveyor\AppData\Local\Temp\1\sbt_73978247\src\main\scala\sbt\test\B.scala:3:10: '}' expected but eof found.
[info] [error] class B {
[info] [error]          ^
[info] [error] two errors found
[info] [error] (Compile / compileIncremental) Compilation failed
[info] Waiting for changes...
[error] Watch caught unexpected error:
[error] java.lang.IllegalStateException: C.scala should not trigger
[error] 	at $f4ba2cf7ff00d54415a0$.$anonfun$$sbtdef$2(C:\Users\appveyor\AppData\Local\Temp\1\sbt_73978247\build.sbt:9)
[error] 	at $f4ba2cf7ff00d54415a0$.$anonfun$$sbtdef$2$adapted(C:\Users\appveyor\AppData\Local\Temp\1\sbt_73978247\build.sbt:6)
[error] 	at sbt.internal.Continuous$.$anonfun$getFileEvents$21(Continuous.scala:711)
[error] 	at sbt.internal.Continuous$.$anonfun$getFileEvents$21$adapted(Continuous.scala:706)
[error] 	at sbt.internal.Continuous$.$anonfun$getFileEvents$27(Continuous.scala:733)
[error] 	at sbt.internal.Continuous$.$anonfun$combineInputAndFileEvents$2(Continuous.scala:817)
[error] 	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:237)
[error] 	at scala.collection.immutable.List.foreach(List.scala:392)
[error] 	at scala.collection.TraversableLike.map(TraversableLike.scala:237)
[error] 	at scala.collection.TraversableLike.map$(TraversableLike.scala:230)
[error] 	at scala.collection.immutable.List.map(List.scala:298)
[error] 	at sbt.internal.Continuous$.$anonfun$combineInputAndFileEvents$1(Continuous.scala:817)
[error] 	at sbt.nio.Watch$.safeNextAction$1(Watch.scala:346)
[error] 	at sbt.nio.Watch$.next$1(Watch.scala:353)
[error] 	at sbt.nio.Watch$.impl$1(Watch.scala:362)
[error] 	at sbt.nio.Watch$.apply(Watch.scala:370)
[error] 	at sbt.internal.Continuous$.$anonfun$runToTermination$7(Continuous.scala:360)
[error] 	at sbt.std.Streams.use(Streams.scala:89)
[error] 	at sbt.std.Streams.use$(Streams.scala:85)
[error] 	at sbt.std.Streams$$anon$1.use(Streams.scala:102)
[error] 	at sbt.internal.Continuous$.$anonfun$runToTermination$6(Continuous.scala:340)
[error] 	at sbt.EvaluateTask$.withStreams(EvaluateTask.scala:373)
[error] 	at sbt.internal.Continuous$.$anonfun$runToTermination$5(Continuous.scala:340)
[error] 	at sbt.internal.Continuous$.setup(Continuous.scala:272)
[error] 	at sbt.internal.Continuous$.$anonfun$runToTermination$1(Continuous.scala:339)
[error] 	at sbt.internal.Continuous$.withCharBufferedStdIn(Continuous.scala:306)
[error] 	at sbt.internal.Continuous$.runToTermination(Continuous.scala:320)
[error] 	at sbt.internal.Continuous$.$anonfun$continuous$1(Continuous.scala:107)
[error] 	at sbt.Command$.$anonfun$applyEffect$4(Command.scala:149)
[error] 	at sbt.Command$.$anonfun$applyEffect$2(Command.scala:144)
[error] 	at sbt.Command$.process(Command.scala:187)
[error] 	at sbt.MainLoop$.process$1(MainLoop.scala:188)
[error] 	at sbt.MainLoop$.processCommand(MainLoop.scala:223)
[error] 	at sbt.MainLoop$.$anonfun$next$2(MainLoop.scala:142)
[error] 	at sbt.State$StateOpsImpl$.runCmd$1(State.scala:273)
[error] 	at sbt.State$StateOpsImpl$.process$extension(State.scala:277)
[error] 	at sbt.MainLoop$.$anonfun$next$1(MainLoop.scala:142)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.MainLoop$.next(MainLoop.scala:142)
[error] 	at sbt.MainLoop$.run(MainLoop.scala:133)
[error] 	at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:111)
[error] 	at sbt.io.Using.apply(Using.scala:27)
[error] 	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:105)
[error] 	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:60)
[error] 	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:45)
[error] 	at sbt.MainLoop$.runLogged(MainLoop.scala:36)
[error] 	at sbt.StandardMain$.runManaged(Main.scala:124)
[error] 	at sbt.xMainImpl$.run(Main.scala:67)
[error] 	at sbt.RunFromSourceMain$.launch(RunFromSourceMain.scala:59)
[error] 	at sbt.RunFromSourceMain$.runImpl(RunFromSourceMain.scala:52)
[error] 	at sbt.RunFromSourceMain$.run(RunFromSourceMain.scala:46)
[error] 	at sbt.RunFromSourceMain$.main(RunFromSourceMain.scala:40)
[error] 	at sbt.RunFromSourceMain.main(RunFromSourceMain.scala)
[error] x watch/on-change 
[error]  Cause of test exception: {line 1}  Command failed: ~compile failed
```

**Comment by eed3si9n** [comment]
Travis also got stuck there.

**Comment by eatkins** [comment]
Yeah. There is a problem with setting `watchPersistFileStamps := true`. I am going to fix later tonight but have to run some errands now.

**Comment by eatkins** [comment]
Should hopefully be fixed by https://github.com/sbt/sbt/pull/4867/commits/15969157ebabf09da3bbe658d1b15d9aa5ee96f8. The tests pass locally for me.

**Comment by eed3si9n** [comment]
```
[info] [error] scala.MatchError: (/tmp/sbt_dc0e0842/src/a,FileAttributes(isDirectory = true, isOther = false,isRegularFile = false, isSymbolicLink = false)) (of class scala.Tuple2)
[info] [error] 	at sbt.nio.Settings$.$anonfun$fileStamps$6(Settings.scala:336)
[info] [error] 	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:244)
[info] [error] 	at scala.collection.Iterator.foreach(Iterator.scala:941)
[info] [error] 	at scala.collection.Iterator.foreach$(Iterator.scala:941)
[info] [error] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
[info] [error] 	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
[info] [error] 	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
[info] [error] 	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
[info] [error] 	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:244)
[info] [error] 	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:241)
[info] [error] 	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:108)
[info] [error] 	at sbt.nio.Settings$.$anonfun$fileStamps$1(Settings.scala:336)
[info] [error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[info] [error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[info] [error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[info] [error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:280)
[info] [error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[info] [error] 	at sbt.Execute.work(Execute.scala:289)
[info] [error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:280)
[info] [error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[info] [error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[info] [error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[info] [error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[info] [error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[info] [error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[info] [error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[info] [error] 	at java.base/java.lang.Thread.run(Thread.java:834)
[info] [error] (Compile / unmanagedResources / inputFileStamps) scala.MatchError: (/tmp/sbt_dc0e0842/src/a,FileAttributes(isDirectory = true, isOther = false,isRegularFile = false, isSymbolicLink = false)) (of class scala.Tuple2)
[info] [error] (Test / unmanagedResources / inputFileStamps) scala.MatchError: (/tmp/sbt_dc0e0842/test-src/c,FileAttributes(isDirectory = true, isOther = false,isRegularFile = false, isSymbolicLink = false)) (of class scala.Tuple2)
[info] [error] Total time: 0 s, completed Jul 16, 2019, 12:48:31 AM
[error] x project/flatten 
```

**Comment by eatkins** [comment]
Third time's a charm.

**Pull request merged**
