### PR TITLE
Add support for loading Ivy settings from a URL

### PR DESCRIPTION
**Pull request by mallman**
I am in the process of migrating an Ant build to SBT. We load our ivysettings.xml from an http url. This patch adds support for that to sbt. The syntax in build.sbt looks like

```
externalIvySettings(url("your_url_here"))
```

This patch keeps compatibility with the current syntax, i.e.

```
externalIvySettings()
```

and

```
externalIvySettings(baseDirectory(_ / "whatever.xml"))
```

still work.

### CODE REVIEW

**Comment by harrah** [comment]
This looks good except for one potential issue.  The settings file is downloaded every time the build runs as well as every time an update is performed.  Is this intended?

**Comment by mallman** [comment]
You make a good point. In the case of file resources, it certainly shouldn't be reloading (identical) files as that breaks with precedent. I will fix that.

For http(s) resources, I believe an update or build should trigger a conditional get for the resource. This will ensure freshness without needlessly downloading an identical file. Ideally, sbt wouldn't even reload the settings if they haven't been modified. I will work on this. I suspect that some of these changes will have an impact on how other protocols are handled. I'll see where things lie when file and http urls are working better.

I'll try to add these changes sometime through the upcoming weekend. Cheers!

**Comment by harrah** [comment]
I don't think local file files are a problem- it was already the case that they were hashed every time.  Also, sbt just passes the settings file to a new instance of Ivy, so I expect it is reread every 'update'.  So, I would concentrate on http and a conditional get.  Unless you object, I will merge this as is because it won't affect existing users of local settings files.  Remote urls need the improvements we are discussing before advertising the feature, though.

**Comment by mallman** [comment]
With my patch I see a

```
:: loading settings :: url = <...>
```

for file urls every time I run "update", even if the file is the same. At least with 0.11.2, running "update" is silent except for the "success" message when I run it. Are you seeing something different?

I'd still like to take some time to revisit the patch. At the least I'd like to silence this message for local files.

**Comment by mallman** [comment]
Given the limitations of the JDK's URLConnection caching framework, I don't think implementing a conditional GET is viable unless we switch from using the JDK URLConnection to something more sophisticated (and elaborate) like the Apache commons http client library. For all the gory details from someone who has actually attempted to implement http caching with the basic JDK client, see http://www.suryasuravarapu.com/2009/10/javas-http-handler-and-cache-validation-issues.html. I suggest we simply stick to the current implementation and assume that anyone who actually uses a remote ivy settings file is well-aware of---and prepared for---the implications.

In sum, I withdraw my own objection to this pull request.

**Comment by mallman** [comment]
BTW, if you'd like me to contribute updated docs to the wiki let me know. I'm just not sure how...

**Comment by harrah** [comment]
Alright.  Then, I propose that the CacheIvy should:
1. for file: protocol, hash based on the contents of the file
2. for other protocols, hash based on the URI string without retrieving the contents of the URI.  The user must explicitly run 'update' when the remote ivysettings.xml has changed.  Otherwise, sbt has to download the URL every time a non-trivial task (compile, test, console) is run.

**Comment by mallman** [comment]
That ought to do it, but dang it I committed with the wrong e-mail address. You mind if I redo them with my github address?

**Comment by mallman** [comment]
I'm going to close this pull request, back out the commits I made with the wrong e-mail address, redo them with the right e-mail address and submit a new pull request.

**Pull request closed without merging**
