### PR TITLE
Error message and Syntax

### PR DESCRIPTION
**Pull request by jastice**
* change name of field error message in server serialization
* change some syntax for IntelliJ compatibility

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @jastice,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by jastice** [comment]
(I've signed the contributor license thingy)

**Review by dwijnand — APPROVED** [review]
I'm against changing code just because IntelliJ doesn't understand it.

But not to the degree to refute this error message fix.

Thanks.

**Comment by jastice** [comment]
I do agree, so I've created an issue regarding the println error: https://youtrack.jetbrains.com/issue/SCL-10982
I haven't been able to reproduce the problem with relative imports outside of this file yet, but we're looking into it.

**Comment by eed3si9n** [comment]
Manually merged https://github.com/sbt/sbt/commit/cfecf1f6b9e39a04e5c3951f57efc3b3a1368997.
The other file is no longer used.

**Pull request closed without merging**
