### PR TITLE
Add `scala-compiler` optionally along with `scala-library`

### PR DESCRIPTION
**Pull request by backuitist**
Scala-compiler and scala-library are intimately bound, they must have the same version.
We add the compiler jar optionally to avoid a situation where a dependency needs the
scala-compiler (and therefore the scala-library) for a version lower than `version`,
resulting in a version mismatch.

Note that this change has no tests attached to it. Maybe a scripted test would be nice?
See https://groups.google.com/forum/#!topic/sbt-dev/vUrqem3TfnI

### CODE REVIEW

**Comment by backuitist** [comment]
An example of such a library is scalate. Current version is 1.6.1 which depends on compiler 2.10.0.
If your project has scalaVersion set to 2.10.2 for instance you'll get runtime errors such as "no such method error".

**Comment by gkossakowski** [comment]
@backuitist: can you give specific example of "no such method error" caused by using Scala 2.10.2? Scala is supposed to be binary backward and forward compatible so you should be able to use Scala 2.10.2 with scalate just fine.

**Comment by backuitist** [comment]
So it should be possible to have scala-compiler 2.10.0 and scala-library 2.10.2?

In 2.10.0 `scala.reflect.internal.TreeInfo` had a `firstArgument` method. It's gone in 2.10.2:

```
[info] Caused by: java.lang.NoSuchMethodError: scala.reflect.internal.TreeInfo.firstArgument(Lscala/reflect/internal/Trees$Tree;)Lscala/reflect/internal/Trees$Tree;
[info]  at scala.tools.nsc.typechecker.Typers$Typer.parentTypes(Typers.scala:1550) ~[scala-compiler-2.10.0.jar:na]
[info]  at scala.tools.nsc.typechecker.Namers$Namer.templateSig(Namers.scala:861) ~[scala-compiler-2.10.0.jar:na]
[info]  at scala.tools.nsc.typechecker.Namers$Namer.getSig$1(Namers.scala:1300) ~[scala-compiler-2.10.0.jar:na]
[info]  at scala.tools.nsc.typechecker.Namers$Namer.typeSig(Namers.scala:1347) ~[scala-compiler-2.10.0.jar:na]
[info]  at scala.tools.nsc.typechecker.Namers$Namer$$anonfun$monoTypeCompleter$1$$anonfun$apply$1.apply$mcV$sp(Namers.scala:709) ~[scala-compiler-2.10.0.jar:na]
[info]  at scala.tools.nsc.typechecker.Namers$Namer$$anonfun$monoTypeCompleter$1$$anonfun$apply$1.apply(Namers.scala:708) ~[scala-compiler-2.10.0.jar:na]
[info]  at scala.tools.nsc.typechecker.Namers$Namer$$anonfun$monoTypeCompleter$1$$anonfun$apply$1.apply(Namers.scala:708) ~[scala-compiler-2.10.0.jar:na]
[info]  at scala.tools.nsc.typechecker.Namers$Namer.scala$tools$nsc$typechecker$Namers$Namer$$logAndValidate(Namers.scala:1385) ~[scala-compiler-2.10.0.jar:na]
[info]  at scala.tools.nsc.typechecker.Namers$Namer$$anonfun$monoTypeCompleter$1.apply(Namers.scala:708) ~[scala-compiler-2.10.0.jar:na]
[info]  at scala.tools.nsc.typechecker.Namers$Namer$$anonfun$monoTypeCompleter$1.apply(Namers.scala:707) ~[scala-compiler-2.10.0.jar:na]
[info]  at scala.tools.nsc.typechecker.Namers$$anon$1.completeImpl(Namers.scala:1496) ~[scala-compiler-2.10.0.jar:na]
[info]  at scala.tools.nsc.typechecker.Namers$LockingTypeCompleter$class.complete(Namers.scala:1504) ~[scala-compiler-2.10.0.jar:na]
[info]  at scala.tools.nsc.typechecker.Namers$$anon$1.complete(Namers.scala:1494) ~[scala-compiler-2.10.0.jar:na]
[info]  at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1229) ~[scala-reflect.jar:na]
[info]  at scala.reflect.internal.Symbols$Symbol.initialize(Symbols.scala:1365) ~[scala-reflect.jar:na]
[info]  at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5119) ~[scala-compiler-2.10.0.jar:na]
[info]  at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5458) ~[scala-compiler-2.10.0.jar:na]
[info]  at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedStat$1(Typers.scala:2770) ~[scala-compiler-2.10.0.jar:na]
[info]  at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$55.apply(Typers.scala:2870) ~[scala-compiler-2.10.0.jar:na]
[info]  at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$55.apply(Typers.scala:2870) ~[scala-compiler-2.10.0.jar:na]
[info]  at scala.collection.immutable.List.loop$1(List.scala:170) ~[scala-library.jar:na]
[info]  at scala.collection.immutable.List.mapConserve(List.scala:186) ~[scala-library.jar:na]
[info]  at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:2870) ~[scala-compiler-2.10.0.jar:na]
[info]  at scala.tools.nsc.typechecker.Typers$Typer.typedPackageDef$1(Typers.scala:5127) ~[scala-compiler-2.10.0.jar:na]
[info]  at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5404) ~[scala-compiler-2.10.0.jar:na]
[info]  at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5458) ~[scala-compiler-2.10.0.jar:na]
[info]  at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5509) ~[scala-compiler-2.10.0.jar:na]
[info]  at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.apply(Analyzer.scala:98) ~[scala-compiler-2.10.0.jar:na]
[info]  at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:461) ~[scala-compiler-2.10.0.jar:na]
[info]  at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3$$anonfun$run$1.apply(Analyzer.scala:90) ~[scala-compiler-2.10.0.jar:na]
[info]  at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3$$anonfun$run$1.apply(Analyzer.scala:90) ~[scala-compiler-2.10.0.jar:na]
[info]  at scala.collection.Iterator$class.foreach(Iterator.scala:727) ~[scala-library.jar:na]
[info]  at scala.collection.AbstractIterator.foreach(Iterator.scala:1157) ~[scala-library.jar:na]
[info]  at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.run(Analyzer.scala:90) ~[scala-compiler-2.10.0.jar:na]
[info]  at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1574) ~[scala-compiler-2.10.0.jar:na]
[info]  at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1548) ~[scala-compiler-2.10.0.jar:na]
[info]  at scala.tools.nsc.Global$Run.compileSources(Global.scala:1544) ~[scala-compiler-2.10.0.jar:na]
[info]  at scala.tools.nsc.Global$Run.compile(Global.scala:1654) ~[scala-compiler-2.10.0.jar:na]
[info]  at org.fusesource.scalate.support.ScalaCompiler.compile(ScalaCompiler.scala:100) ~[scalate-core_2.10-1.6.1.jar:1.6.1]
[info]  at org.fusesource.scalate.TemplateEngine.compileAndLoad(TemplateEngine.scala:757) ~[scalate-core_2.10-1.6.1.jar:1.6.1]
```

**Comment by gkossakowski** [comment]
Oh, I misunderstood you. If you call compiler at runtime then library and compiler versions need to match.

What I meant is a bit different: you can compile your own code with Scala compiler 2.10.0 and then run your compiled code with 2.10.2 library on a classpath.

**Comment by harrah** [comment]
This is wontfix.  The reason is that as of 0.13, Scala is a normal dependency, so this is in the scope of dependency managers like Maven or Ivy, not sbt.  Unfortunately, these existing dependency managers cannot constrain two libraries to have the same version.  This would be a problem for other libraries that must be released together, not just Scala.

**Comment by backuitist** [comment]
My intent here isn't to solve the lack of expressiveness of dependency managers. And I agree this is a bit hacky, but so is scala-library auto-import feature.
Do you think adding the compiler as an optional dependency could be a problem? In my opinion it is more of a problem to end-up with the kind of bug i've shown above.

**Comment by harrah** [comment]
The auto import isn't hacky.  `autoScalaLibrary` => standard dependency on `scala-library`.  All Scala users need `scala-library` and sbt is targeted at Scala users.  Non-Scala users can set `autoScalaLibrary` to false.  An optional dependency on `scala-compiler` is hacky- not every Scala user needs it and `optional` won't help downstream users or Maven users.

I agree that is a problem, but it is a dependency management problem.  You'd see the same issue with other libraries that are locked together.  You can use a strict conflict manager, but that's about the most dependency managers get you.

**Comment by backuitist** [comment]
Ok, I'll add `"scala-compiler" % scalaVersion.value` to my build.
Thanks for answering.

**Comment by harrah** [comment]
Note that the techniques in [Conflict management](http://www.scala-sbt.org/release/docs/Detailed-Topics/Library-Management.html#conflict-management) and the following sections are also applicable here.

I understand this isn't a good situation, but there were problems with automatically overriding the version as well.  So, it was better to stick with the vanilla dependency managers in the end.

**Pull request closed without merging**
