### PR TITLE
Fix #768

### LINKED ISSUE #768: Sbt lost ivy dependencies at specific condition.
Environment:
plugin development
1. publish plugin on remote git
2. import plugin from remote git with Build.scala. Plugin will be cached with resolver sbt.ProjectResolver(inter-project)
3. publish plugin with 'publish-local'
4. remove import from Build.scala
5. add import to plugins.sbt with 'addSbtPlugin'
6. resolution process broken (plugin still cached in ivy with inter-project)

sbt.ProjectResolver drop dependency silently at line 48
def download(artifacts: Array[IArtifact], options: DownloadOptions): DownloadReport - no messages, no errors

I may reproduce it from scratch.

Investigation info draft FYI https://gist.github.com/ezh/5667717

Broken and correct .ivy2/cache/scala_2.9.2/sbt_0.12/org.digimead/sbt-dependency-manager/ivydata-0.6.4.3.properties https://gist.github.com/ezh/5667774 . Please pay attention to resolver.

### PR DESCRIPTION
**Pull request by ezh**
It was a wrong branch. Corrected.

About unit tests. I could not find any unit tests related to ProjectResolver. IMHO you just write code that works (in most cases). If you have unit test for ProjectResolver please provide location and take my regret. And I'll try to add one more test for this case.

I have no interests to make SBT better that it is. You did nice thing ;-) At least the problem easily reproduced with any environment.

Thank you.

### CODE REVIEW

**Comment by harrah** [comment]
Is this the problem fixed in 0.13 in 6d5d641dd718e2cf718d130e8571792cd7a9d84e ?  If it is, I was hoping you had a test case because I couldn't reliably reproduce it to create my own test, but the fix solved the corruption I saw at the time.  In any case, it is impressive that you tracked down the problem and came up with a fix.

If this isn't the same issue as in 6d5d641dd718e2cf718d130e8571792cd7a9d84e, can you a) eliminate the repetition of the large code block at the end and b) explain why that end part is necessary? c) explain why it only needs to be fixed in 0.12 but not 0.13?

Thanks very much for taking the time to track down, fix, and report this issue.

**Comment by ezh** [comment]
I am unable to reproduce this situation under 0.13 because there is no cached .properties.

If you run the same project with plugin in Build.scala under 0.12 and 0.13
With SBT 0.12 after start file ~/.ivy2/cache/sbt_0.12/org.digimead/sbt-dependency-manager/ivydata-0.6.4.2.properties created (substitute with any plugin id)
With SBT 0.13 after start no cache file created at all. No cache -> no problem. If this expected, I am glad.

Unfortunately 0.13 is too buggy for me. It kills my console (konsole, KDE, linebreak dissapear) Also remote building with Build.scala broken. SBT thrown crazy error that project 0-000-000-00000 contains unexpected symbols in identifier or something like this :-( I must to solve my own problems, not to add a new one :-/

About fix. This is a realy _quick_ fix. I just got your code that remove cached data and paste it few time at every location where invalid request was registered. My logic is "If this is broken cache then delete it anyway and hope for the best". If we delete broken at top then there is no call with broken entry at bottom.

IMHO most proper way is to add condition to 

```
sbt.ProjectResolver line 48
def download(artifacts: Array[IArtifact], options: DownloadOptions): DownloadReport
```

This condition must check if the requested artifact has any relation to ProjectResolver. If not, SBT must throw exception with message for example "Invalid cached artifact detected, please clean your Ivy cache". But I'm to sluggish to make pull request with this solution.

I happy if SBT will work for me someway, not significant. Right now I have solution for 0.12 because it is my working horse. And this is my problem.

**Comment by ezh** [comment]
Right now I am unable reproduce it too at different location . There is must be some special condition. I'll try to calculate it.

**Comment by ezh** [comment]
Anyway the idea to throw an exception if there is inappropriate download request will save huge amount of time and avoid headache for someone. Silent drop is funny joke :-)

**Comment by ezh** [comment]
// checkout and publish-local plugin
wget https://github.com/digimead/sbt-dependency-manager/archive/e768.tar.gz
cd sbt-dependency-manager-e786
sbt-0.12 publish-local
1. Generate valid local cache
   // get simple project
   git clone git@github.com:ezh/sbt-issue-768-example.git
   start sbt-0.12
   // check broken cache
   less ~/.ivy2/cache/scala_2.9.2/sbt_0.12/org.digimead/sbt-dependency-manager/ivydata-0.6.4.3.properties
   // It must contains at least 8 lines!!! if there is only 4 lines - it is not an option. Look at my gists with examples. Compare.
2. Generate valid inter-project cache based on local
   // uncomment lazy val root = Project("plugins", file(".")) dependsOn(dm) in Build.scala
   // comment lazy val root = Project("plugins", file(".")) dependsOn()
   // comment addSbtPlugin("org.digimead" % "sbt-dependency-manager" % "0.6.4.3")
   start sbt-0.12
   // check broken cache; resolver must be replaced with inter-project; Compare with my data
   less ~/.ivy2/cache/scala_2.9.2/sbt_0.12/org.digimead/sbt-dependency-manager/ivydata-0.6.4.3.properties
3. Use invalid inter-project cache
   // comment lazy val root = Project("plugins", file(".")) dependsOn(dm) in Build.scala
   // uncomment lazy val root = Project("plugins", file(".")) dependsOn()
   // uncomment addSbtPlugin("org.digimead" % "sbt-dependency-manager" % "0.6.4.3")
   // check broken cache for more assurance
   less ~/.ivy2/cache/scala_2.9.2/sbt_0.12/org.digimead/sbt-dependency-manager/ivydata-0.6.4.3.properties
   start sbt-0.12 <-- you got it

**Comment by ezh** [comment]
IMHO this issue only affects people that debug plugin SBT cross-version builds and switch between local and remote dependency frequently.  IMHO there are only <1% SBT plugin developers :-) So it is nothing critical if you don't merge my patch. Anyway I may apply local fix withing few seconds.

Maybe you will create more reliable fix. (if needed, especially with SBT-0.13 changes)

You my close my ticket if you think that this issue is out of scope.

King regards,
Alexey

**Comment by harrah** [comment]
I backported the cache fixes that are in 0.13 to 0.12.x and published 0.12.4-RC1.  Please let me know if this fixes your problem.  If not, I will look at your example again and try to integrate your changes.  Thanks again for your help.

**Comment by ezh** [comment]
It is fixed. I am able to load project even with incorrect ivydata-0.6.4.3.properties.

The little note. After I moved to RC1 I've got
[info] Loading project definition from /home/ezh/projects/digi-lib/0.2.3/project-dev/project/project
[debug] Running task... Cancelable: false, check cycles: false
[debug] Invalidating /home/ezh/.ivy2/local/org.scala-sbt/main/0.12.4-M1/jars/main.jar: could not find class sbt.Reference$ on the classpath.
[debug] Invalidating /home/ezh/.ivy2/local/org.scala-sbt/sbt/0.12.4-M1/jars/sbt.jar: could not find class sbt.package$ on the classpath.
[debug] 
[debug] Initial source changes: 
[debug]         removed:Set()
[debug]         added: Set()
[debug]         modified: Set()
[debug] Removed products: Set(/home/ezh/projects/digi-lib/0.2.3/project-dev/project/project/target/scala-2.9.2/sbt-0.12/classes/PluginDef$$anonfun$root$7.class, /home/ezh/projects/digi-lib/0.2.3/project-dev/project/project/target/scala-2.9.2/sbt-0.12/classes/PluginDef$$anonfun$root$9.class, /home/ezh/projects/digi-lib/0.2.3/project-dev/project/project/target/scala-2.9.2/sbt-0.12/classes/PluginDef$$anonfun$root$3.class, /home/ezh/projects/digi-lib/0.2.3/project-dev/project/project/target/scala-2.9.2/sbt-0.12/classes/PluginDef$$anonfun$root$12.class, /home/ezh/projects/digi-lib/0.2.3/project-dev/project/project/target/scala-2.9.2/sbt-0.12/classes/PluginDef$$anonfun$root$5.class, /home/ezh/projects/digi-lib/0.2.3/project-dev/project/project/target/scala-2.9.2/sbt-0.12/classes/PluginDef$.class, /home/ezh/projects/digi-lib/0.2.3/project-dev/project/project/target/scala-2.9.2/sbt-0.12/classes/PluginDef$$anonfun$root$4.class, /home/ezh/projects/digi-lib/0.2.3/project-dev/project/project/target/scala-2.9.2/sbt-0.12/classes/PluginDef.class, /home/ezh/projects/digi-lib/0.2.3/project-dev/project/project/target/scala-2.9.2/sbt-0.12/classes/PluginDef$$anonfun$root$8.class, /home/ezh/projects/digi-lib/0.2.3/project-dev/project/project/target/scala-2.9.2/sbt-0.12/classes/PluginDef$$anonfun$root$6.class, /home/ezh/projects/digi-lib/0.2.3/project-dev/project/project/target/scala-2.9.2/sbt-0.12/classes/PluginDef$$anonfun$root$1.class, /home/ezh/projects/digi-lib/0.2.3/project-dev/project/project/target/scala-2.9.2/sbt-0.12/classes/PluginDef$$anonfun$root$2.class, /home/ezh/projects/digi-lib/0.2.3/project-dev/project/project/target/scala-2.9.2/sbt-0.12/classes/PluginDef$$anonfun$root$11.class, /home/ezh/projects/digi-lib/0.2.3/project-dev/project/project/target/scala-2.9.2/sbt-0.12/classes/PluginDef$$anonfun$root$10.class)
[debug] Modified external sources: Set()
[debug] Modified binary dependencies: Set(/home/ezh/.ivy2/local/org.scala-sbt/main/0.12.4-M1/jars/main.jar, /home/ezh/.ivy2/local/org.scala-sbt/sbt/0.12.4-M1/jars/sbt.jar)
[debug] Initial directly invalidated sources: Set()
[debug] 
[debug] Sources indirectly invalidated by:
[debug]         product: Set(/home/ezh/projects/digi-lib/0.2.3/project-dev/project/project/Build.scala)
[debug]         binary dep: Set(/home/ezh/projects/digi-lib/0.2.3/project-dev/project/project/Build.scala)
[debug]         external source: Set()
[debug] All initially invalidated sources: Set(/home/ezh/projects/digi-lib/0.2.3/project-dev/project/project/Build.scala)
[debug] Recompiling all 1 sources: invalidated sources (1) exceeded 50.0% of all sources
[info] Compiling 1 Scala source to /home/ezh/projects/digi-lib/0.2.3/project-dev/project/project/target/scala-2.9.2/sbt-0.12/classes...
[debug] Getting compiler-interface from component compiler for Scala 2.9.2
[debug] Getting compiler-interface from component compiler for Scala 2.9.2
[debug] Running cached compiler 6cf84b0a, interfacing (CompilerInterface) with Scala compiler version 2.9.2
[debug] Calling Scala compiler with arguments  (CompilerInterface):
[debug]         -d
[debug]         /home/ezh/projects/digi-lib/0.2.3/project-dev/project/project/target/scala-2.9.2/sbt-0.12/classes
[debug]         -bootclasspath
[debug]         /opt/sun-jdk-1.6.0.38/jre/lib/resources.jar:/opt/sun-jdk-1.6.0.38/jre/lib/rt.jar:/opt/sun-jdk-1.6.0.38/jre/lib/sunrsasign.jar:/opt/sun-jdk-1.6.0.38/jre/lib/jsse.jar:/opt/sun-jdk-1.6.0.38/jre/lib/jce.jar:/opt/sun-jdk-1.6.0.38/jre/lib/charsets.jar:/opt/sun-jdk-1.6.0.38/jre/lib/modules/jdk.boot.jar:/opt/sun-jdk-1.6.0.38/jre/classes:/home/ezh/.sbt/boot/scala-2.9.2/lib/scala-library.jar
[debug]         -classpath
[debug]         /home/ezh/projects/digi-lib/0.2.3/project-dev/project/project/target/scala-2.9.2/sbt-0.12/classes:/home/ezh/.sbt/boot/scala-2.9.2/lib/scala-compiler.jar:/home/ezh/.ivy2/cache/jline/jline/jars/jline-1.0.jar:/home/ezh/.ivy2/cache/org.scala-tools.sbinary/sbinary_2.9.0/jars/sbinary_2.9.0-0.4.0.jar:/home/ezh/.ivy2/cache/org.apache.ivy/ivy/jars/ivy-2.3.0-rc1.jar:/home/ezh/.ivy2/cache/com.jcraft/jsch/jars/jsch-0.1.46.jar:/home/ezh/.ivy2/cache/commons-httpclient/commons-httpclient/jars/commons-httpclient-3.1.jar:/home/ezh/.ivy2/cache/commons-logging/commons-logging/jars/commons-logging-1.0.4.jar:/home/ezh/.ivy2/cache/commons-codec/commons-codec/jars/commons-codec-1.2.jar:/home/ezh/.ivy2/cache/org.scala-tools.testing/test-interface/jars/test-interface-0.5.jar
[error] /home/ezh/projects/digi-lib/0.2.3/project-dev/project/project/Build.scala:1: not found: object sbt
[error] import sbt._
[error]        ^
[error] one error found
[debug] Compilation failed (CompilerInterface)
[error](compile:compile) Compilation failed
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? ezh@devbox ~/projects/digi-lib/0.2.3 $ 

Error was gone after I delete ivi cache. I hope that such situation will not affect someone.
Please close my ticket.

**Comment by harrah** [comment]
Well, this is possibly the cause for issues with the 0.13.0-Beta1 release, so I don't think it is fixed.  I'll be looking at this again to see if it can help.

**Comment by harrah** [comment]
Thanks again for your work here.  I integrated the essence of it in the commits above.  The second issue you saw should be fixed by it.  Please report back if you see it again with 0.12.4 or 0.13 or later.

**Pull request closed without merging**
