### PR TITLE
Create RunFromSourceMain & "sbtOn" command

### PR DESCRIPTION
**Pull request by dwijnand**

### CODE REVIEW

**Comment by dwijnand** [comment]
This is failing CI because the new custom "sbt" command is being used for "sbt:scalafmt::test"..

**Comment by dwijnand** [comment]
Renamed to "sbtOn".

**Comment by eed3si9n** [comment]
Is this 1.0.x worthy?

**Comment by dwijnand** [comment]
I targeted 1.0.x so that I can use it when investigating and fixing 1.0.x hotfixes (without having to do a lot of git backflips).

Outside the large test source file, it adds and configures sbt-buildinfo (and even that in test scope) which I can't see impacting the quality and integrity of future 1.0.x hotfixes, but you're in the best position to make that judgement.

**Review by eed3si9n — APPROVED** [review]

**Pull request merged**
