### PR TITLE
Switch from JLine 1.0 to 2.10.

### PR DESCRIPTION
**Pull request by alexdupre**
sbt and scala shells behave differently, since the former uses JLine 1.0, while the latter uses a customized version of JLine 2. This is particularly true on FreeBSD, whose terminal is not supported by JLine 1.0. Here is my attempt to switch sbt to use the modern JLine 2 API.

### CODE REVIEW

**Comment by harrah** [comment]
Merged, thanks.  My main concern with JLine 2.x is that it uses an InheritableThreadLocal to access the Terminal for no apparent reason.

Also, I believe this patch changes the behavior of history so that it doesn't notice when the history file is deleted, correct?

**Comment by alexdupre** [comment]
Yes, the history file is read only once, the behavior is slightly different than before, but I think it could be considered an improvement and a more "standard" behavior.

**Comment by harrah** [comment]
Can you explain what you mean by standard?  If the backing history file is deleted, why should the in-memory history not be cleared as well?

**Comment by alexdupre** [comment]
Hmmm, actually I think I was wrong when I said that the behavior changed. It should be only an improvement, since the file is read only once, but the behavior is the same.
If you currently delete the backing history file, it will be recreated immediately and with the same lines after the next command. And this behavior is coherent with every shell history.
Or I missed anything?

**Comment by harrah** [comment]
I believe the behavior before this change is that deleting the history file clears the in-memory history.  If you say it is the way shells do it, the new behavior seems best then.  Thanks.

**Comment by pfn** [comment]
This appears to have the side-effect of making it impossible for a 0.12 sbt-launcher.jar to run 0.13 and vice versa.

Cross-version compilation of sbt plugins just became that much more difficult  :-(

**Comment by harrah** [comment]
https://groups.google.com/d/msg/simple-build-tool/5EbK-Tg9iho/MgUMsSmZjjwJ

I am aware that 0.12 cannot run 0.13, but not that 0.13 cannot run 0.12.  Can you provide an example of a 0.12 build that the 0.13 launcher fails on?

**Comment by jsuereth** [comment]
I'd like to see this too.  I've been using the new jline + 0.13 launcher on all my 0.12 builds practically since the commit landed...

**Comment by pfn** [comment]
Perhaps I was mistaken, I thought running the sbt 0.13 launcher with a
build.properties set to 0.12 failed, let me try again.

**Pull request closed without merging**
