### PR TITLE
Wip/warnings

### PR DESCRIPTION
**Pull request by Blaisorblade**
Not-yet-merged patches from issue #633.

### CODE REVIEW

**Comment by harrah** [comment]
Thanks, merged.

**Comment by gkossakowski** [comment]
@Blaisorblade: out of curiosity, how did you manage to import Sbt code base into Eclipse?

**Comment by Blaisorblade** [comment]
Well, I never got a fully stable setup and I'm not sure it was worth it, but I just described what I did in an SBTEclipse issue — typesafehub/sbteclipse#145. Still, I was able to build enough of SBT (almost everything) to get the Eclipse warnings. Maybe sometimes I even got all of it to work, not sure. I just pushed my project files in case you're interested, at [Blaisorblade/xsbt@wip/eclipse-projects](https://github.com/Blaisorblade/xsbt/tree/wip/eclipse-projects).

BTW, I recommend using a separate workspace; I did all of this in the scalac workspace and I regretted it quickly. At least for me semantic highlighting only works if Eclipse builds the code by itself, and IIRC I often needed to clean SBT's projects to get this started. But you don't want to do that for Scalac, and setting up Working Sets is a pain (plus, you can use Working Sets less often than you'd like). IIRC I very gently opened projects a few at a time, starting from leaves and continuing only after the subprojects were built without errors, to get things working.

And I probably forget something.

**Comment by gkossakowski** [comment]
@Blaisorblade: are you aware of: https://groups.google.com/d/topic/simple-build-tool/tgJzXnqVt0s/discussion ?
I'll comment on typesafehub/sbteclipse#145 as well.

**Comment by Blaisorblade** [comment]
No I wasn't! But I see that it's not yet all merged. I'd love for that to be in :+1:!

**Pull request closed without merging**
