### PR TITLE
= build Upgrade scala version to 2.12.5

### PR DESCRIPTION
**Pull request by He-Pin**
(See the guidelines for contributing, linked above)

### CODE REVIEW

**Comment by hepin1989** [comment]
https://github.com/scala/scala-dev/issues/480

**Comment by dwijnand** [comment]
what the hell.. this breaks project loading??

**Comment by He-Pin** [comment]
Should wait 2.12.6 I think.

**Comment by eed3si9n** [comment]
There's been various regressions reported on 2.12.5, so I would suggest we wait it out for now too.

**Comment by eed3si9n** [comment]
Superseded by https://github.com/sbt/sbt/pull/4129

**Pull request closed without merging**
