### PR TITLE
Add support for wildcards in Scala version switch (fuzzy switch)

### PR DESCRIPTION
**Pull request by raboof**
This adds the ability to use semantic version selector expression (such as `2.13.x` and `3.x`) in `++` command as discussed in https://github.com/sbt/sbt/discussions/6893. The following description includes the patch in https://github.com/sbt/sbt/pull/6936.

## Usage

```
++ 2.13.x test
```

## Explanation

This is an extension of existing `++ <sv> <command1>` where the given `<command1>` will be executed only within the subprojects listing `<sv>` in their respective `crossScalaVersions` setting.

sbt 1.7.0 now allows the `<sv>` part to be a semantic version selector expression, implemented originally by @tanishiking in https://github.com/sbt/librarymanagement/pull/239 based on [npm-semver](https://www.npmjs.com/package/semver#Ranges). Note that the semantic version selector expression may match at most one Scala version within `crossScalaVersions` per subproject. This is because `++` remains to be a _switch_ command.

### CODE REVIEW

**Comment by eed3si9n** [comment]
@raboof I am thinking about wrapping up 1.7.0 soon.

**Comment by raboof** [comment]
> @raboof I am thinking about wrapping up 1.7.0 soon.

Thanks for the ping, added tests (and fixed behavior), now ready for review.

**Comment by raboof** [comment]
(rebased on `origin/develop` - or should that be `origin/1.7.x` at this point?)

**Comment by eed3si9n** [comment]
1.7.x branch would be better but either is ok.

**Review by eed3si9n — APPROVED** [review]
Thanks. Looks good to me.

**Comment by SethTisue** [comment]
this is awesome. I love it!

a small suggestion. the output is:

```
sbt:root> ++3.x
[info] Setting Scala version to 3.x on 3 projects.
```

but it doesn't tell me which version it actually selected; I'd prefer not to have to `show scalaVersion` to see that information.

**Comment by He-Pin** [comment]
@raboof Seems like it can't match both `3.1.3 and 3.2.0` reported at
https://github.com/sbt/sbt/issues/7018

**Pull request merged**
