### PR TITLE
Fix sbinary cache limit when caching doc inputs

### LINKED ISSUE #1614: sbt uses sbinary to cache objects on filesystem, but it has a hard limit of 64k.
We were hit by this limit recently. See the attached stacktrace. This happened on "doc" task when the checkout dir was really long, but as far as I can tell, this is used everywhere. Although most people won't be affected by this, but this is still something that many big project will hit eventually.

Here is the hard limit in sbinary:
https://github.com/DRMacIver/sbinary/blob/master/core/src/javaprotocol.scala#L164

And here is the stacktrace:

```
java.lang.RuntimeException: encoded string too long: 66201 bytes
    at scala.sys.package$.error(package.scala:27)
    at scala.Predef$.error(Predef.scala:142)
    at sbinary.JavaUTF$StringFormat$.writes(javaprotocol.scala:165)
    at sbinary.JavaUTF$StringFormat$.writes(javaprotocol.scala:100)
    at sbt.InputCache$$anon$1.write(SeparatedCache.scala:27)
    at sbt.HListCacheImplicits$$anon$14.write(Cache.scala:185)
    at sbt.HListCacheImplicits$$anon$14.write(Cache.scala:173)
    at sbt.HListCacheImplicits$$anon$14.write(Cache.scala:186)
    at sbt.HListCacheImplicits$$anon$14.write(Cache.scala:173)
    at sbt.HListCacheImplicits$$anon$14.write(Cache.scala:186)
    at sbt.HListCacheImplicits$$anon$14.write(Cache.scala:173)
    at sbt.Tracked$CacheHelp$$anonfun$save$1.apply(Tracked.scala:68)
    at sbt.Tracked$CacheHelp$$anonfun$save$1.apply(Tracked.scala:68)
    at sbt.Using.apply(Using.scala:25)
    at sbt.Tracked$CacheHelp.save(Tracked.scala:68)
    at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:48)
    at sbt.RawCompileLike$$anonfun$cached$1.apply(RawCompileLike.scala:55)
    at sbt.RawCompileLike$$anonfun$cached$1.apply(RawCompileLike.scala:40)
    at sbt.Defaults$$anonfun$docTaskSettings$3.apply(Defaults.scala:694)
    at sbt.Defaults$$anonfun$docTaskSettings$3.apply(Defaults.scala:672)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:42)
    at sbt.std.Transform$$anon$4.work(System.scala:64)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
    at sbt.Execute.work(Execute.scala:244)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    at java.lang.Thread.run(Thread.java:662)
```

### PR DESCRIPTION
**Pull request by pvlugter**
Cache the classpath as Seq[File] rather than String in RawCompileLike. Fixes #1614.

I've based this PR on 0.13.7 branch. Let me know if it should be targeted at a different branch.

Have tried it with the Play aggregated docs and it looks good there.

### CODE REVIEW

**Comment by typesafe-tools** [comment]
Can one of the admins verify this patch?

**Comment by jsuereth** [comment]
@pvlugter Just FYI - @eed3si9n and I decided to push a 0.13.8-M1 with this in it which should be acceptable for our integration needs in the interim....

**Comment by pvlugter** [comment]
Cool, sounds good. Shall I recreate this PR against 0.13?

**Comment by eed3si9n** [comment]
I manually cherrypicked the commit. sbt 0.13.8-M1 is now out with the fix.

**Comment by pvlugter** [comment]
Thanks!

**Pull request closed without merging**
