### PR TITLE
Support wildcard exclusions

### LINKED ISSUE #1431: Support wildcard exclusions in Pom parser
Maven 3.2 supports a new way of excluding everything.

See the [attached](https://github.com/hamnis/maven-wildcard-exclusion-sbt) project for more information.

This means that you may find newer published artifacts which allows exclusions on a more general level.

Sbt does not find the dependencies which have this.

### PR DESCRIPTION
**Pull request by dwijnand**
Like

``` xml
<dependency>
  <groupId>dom4j</groupId>
  <artifactId>dom4j</artifactId>
  <version>1.6.1</version>
  <scope>compile</scope>
  <exclusions>
    <exclusion>
      <artifactId>*</artifactId>
      <groupId>*</groupId>
    </exclusion>
  </exclusions>
</dependency>
```

The idea here is that if a dependency contains exclude with wildcards than it is inTransitive.

Fixes #1431

Replaces #2713

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @jtgrabowski,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by dwijnand** [comment]
This is failing because I'm failing to do whatever is necessary to publish sbt/ivy for sbt/sbt.. /cc @eed3si9n

**Comment by dwijnand** [comment]
The key was syncing the ivy package from sbt/maven-releases to Maven Central.

This is now re-building for 0.13.13.

**Comment by dwijnand** [comment]
Green

**Comment by eed3si9n** [comment]
Nice work @jtgrabowski and @dwijnand.

**Comment by eed3si9n** [comment]
Could you forward port this please?

**Comment by dwijnand** [comment]
Sure.

**Pull request merged**
