### PR TITLE
Natural whitespace handling for SBT configuration parser AKA 'no more blankies'

### PR DESCRIPTION
**Pull request by ajozwik**
Fixed #1574 , see #1574 for more details.

### CODE REVIEW

**Comment by typesafe-tools** [comment]
Can one of the admins verify this patch?

**Comment by ajozwik** [comment]
Files to review: 
- SplitExpressionsNoBlankies.scala
- SessionSettingsNoBlankies.scala
- SessionSettings.scala
- EvaluateConfigurations.scala

and tests in:
main/src/test/scala/sbt/

**Comment by ajozwik** [comment]
#1574 contains only changes related with #noblankies. This pull request contains more commits - not related to the problem. I think for code review it is better to use #1574.
What is your purpose? Keep all on this branch? Repoen #1574 - and still commit there?
I'm waiting for decision.

**Comment by jsuereth** [comment]
SO, what I'd like to do:
1. Any improvements/fixes/tests should be issues as pull requests against the wip/no-blankies branch.  If myself / @eed3si9n issue a  PR, we'll have you review it, and vice-versa.
2. Once we've identified that no-blankies passes the 'session save' tests (which I still need to write, unless you have time to), then we can issue a PR to master.

Note: we have this planned for 0.13.7, so while I'm still fixing regressions which have shown up in 0.13.6, the plan is to stabilize/merge this before 0.13.6.   The todo list I see:
- [ ] Add tests around the new no-blank-lines files and session-save
- [ ] Possibly expand the notion of "position" we have in `Setting[_]` to include start/stop so we can more accurately alter a build.sbt file without changing it.
- [ ] Investigate @dragos comments about tokenizer/parser.

In any case, thanks much for this merge commit.  I'll pull this in immediately.  

Would you like to open a ticket for "no blank-lines" feature where we can track the minor TODOs on it?

**Comment by ajozwik** [comment]
I created   #1606  Natural whitespace handling for SBT configuration parser AKA 'no more blankies'.
Thank you for your comments.

**Pull request merged**
