### PR TITLE
Consolidated resolution

### PR DESCRIPTION
**Pull request by eed3si9n**
Fixes/improves #413

This adds a new setting key called `updateOptions`, which can enable consolidated resolution for update task.
The consolidated resolution automatically generates an artificial module descriptor based on the SHA-1 of all external dependencies (all direct, and transitive via internal dependencies). This consolidates the Ivy resolution of similar Ivy dependency graph across multiple subprojects.

This is how it's enabled:

``` scala
updateOptions := updateOptions.value.withConsolidatedResolution(true)
```

/review @jsuereth

### CODE REVIEW

**Comment by jsuereth** [comment]
Failures look related: https://travis-ci.org/sbt/sbt/jobs/30140249

**Comment by jsuereth** [comment]
LGTM, once tests pass.

**Comment by eed3si9n** [comment]
After some travis job restarts, all tests are passing.

**Comment by jsuereth** [comment]
If cache is in memory why is it using a directory?

Use a temporary directory if it's truly transient

**Comment by eed3si9n** [comment]
The cache dir is used to save a marker file to indicate cache is available. Running `clean` on any of the participating subproject of the artificial graph or the on the root project cleans the marker file, and thus forces uncached `update` next time.

**Comment by jsuereth** [comment]
I may have missed the clean hook.

It's ok to merge as-is, but I feel like the cache file is "off" and we'll hit bugs round it.   However, since it's opt in, that's ok for v1 so we can discover what the issues may be.

I would like to see a test with a projectref on a separare build and make sure the cache isn't borked

**Comment by eed3si9n** [comment]
I might be able to get rid of the folder and make this 100% in-memory, if `clean` just deleted items from the mutable map. I might have to switch to using `TrieMap` then for concurrency guard?
Also I want to still work on SHA-1 calculation of the Ivy graph.

**Comment by jsuereth** [comment]
LGTM

**Pull request merged**
