### PR TITLE
Use the new Docker queue on Travis

### PR DESCRIPTION
**Pull request by joshk**
faster, better, stronger

vms boot in seconds, network is more stable

also cleaned up the .travis.yml file a little :)

### CODE REVIEW

**Comment by typesafe-tools** [comment]
Can one of the admins verify this patch?

**Comment by eed3si9n** [comment]
sounds fun! thanks for this. can't wait to see https://travis-ci.org/sbt/sbt/builds/33257634 go green.

**Comment by eed3si9n** [comment]
Thus far bunch of jobs are dying 4~5 minutes in.

**Comment by joshk** [comment]
yeah, this is an interesting one, looks like it might be ram/memory related.

will dive in deeper soon.

**Pull request merged**
