### PR TITLE
Remove ProcessExtra and the use of java.lang.ProcessBuilder

### LINKED ISSUE #2736: Remove sbt.Process (and friends), switch to scala.sys.process

### PR DESCRIPTION
**Pull request by kzys**
Fixes #2736.

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @kzys,

Thank you for your contribution! We really value the time you've taken to put this together.

We see that you have signed the Lightbend Contributors License Agreement before, however, the CLA has changed since you last signed it.
Please review the new CLA and sign it before we proceed with reviewing this pull request:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Review by eed3si9n — APPROVED** [review]

**Review by eed3si9n — DISMISSED** [review]
I think the code change looks fine, could you make a quick note in https://github.com/sbt/sbt/blob/1.0.x/MIGRATION.md plz?

**Comment by kzys** [comment]
How about

> `sbt.Process` and `sbt.ProcessExtra` are gone. Use `scala.sys.process` instead.

?

**Comment by eed3si9n** [comment]
Sounds good.

**Comment by kzys** [comment]
Hmm, could you restart the build again? I couldn't reproduce that by `sbt 'scripted tests/*2of2'` and it doesn't seem relate to my change.

**Comment by eed3si9n** [comment]
Yea some of the test testing gets flaky sometimes. I've restarted the Travis job.

**Pull request merged**
