### PR TITLE
Multi-line prompt text offset issue (ticket #625)

### PR DESCRIPTION
**Pull request by jibbers42**
Per Mark's suggestion, in a multi-line prompt, this code passes only the bottom line to readLine(...). Any lines above are printed out directly before the readLine(...) call.

The only downside I can see is that the top lines are not printed after tab suggestion, which doesn't seem like a very big deal. They will be printed again after pressing Enter.

### CODE REVIEW

**Comment by harrah** [comment]
Thanks!  Merged in f7031502e4bb31d55d514e73613f6f4761232808 with the small change of a val instead of a var.

**Comment by jibbers42** [comment]
Grrr, C# muscle memory strikes again.

Will this make it into 0.12.2?

Thanks!

--Anthony

**Comment by harrah** [comment]
It isn't likely, sorry.  0.12.2 is already at RC1 and only regressions merit another RC.  The first RC for 0.12.3 will be 2-3 months from now.

**Comment by jibbers42** [comment]
OK, thanks anyway.

--Anthony

**Pull request closed without merging**
