### PR TITLE
Warning fixes on 0.13

### PR DESCRIPTION
**Pull request by Blaisorblade**
Fix up or silence spurious Eclipse warnings to leave only relevant ones in. I'm happy to redo this pull request in a different ways, and to try sharing the Eclipse setup (even with the Eclipse plugin, it wasn't trivial to set this up).

### CODE REVIEW

**Comment by harrah** [comment]
Accept without changes:
- Prop.Exception => Exception
- unused imports
- Output import renaming
- e => e: Throwable

Accept with changes:
- Silencing feature warnings should be done via the command-line option.  The only one that is useful is the reflection related one since that is never desired.  Experimental options should be enabled per source file.

Reject:
- The jansi code intentionally traps everything.  It technically shouldn't trap the non-StackOverflowError VirtualMachineErrors and AWTError would be weird, but this is PermGen mitigation code that should not render sbt completely unusable if jansi initialization fails.

Thanks!

**Comment by Blaisorblade** [comment]
Here's a revised attempt!

**Comment by harrah** [comment]
Are you saying the javac will emit those warnings with -Xlint and will respect those SuppressWarnings annotations?  If so, that sounds good.

**Comment by Blaisorblade** [comment]
> Are you saying the javac will emit those warnings with -Xlint and will respect those SuppressWarnings annotations? If so, that sounds good.
> What I did now was to enable -Xlint and -Xlint:-serial, so that no SuppressWarnings("serial") are needed; SuppressWarnings("rawtypes"), etc. are respected, and other warnings are still given. The compile is not completely _clean_, but the warnings I see are more interesting.

Sorry for the delay. And sorry for losing the comments - changing commits loses comments for old commits (no "discussed outdated diff" from Github anymore).

About sbteclipse: I guess I shall simply open an issue for them to support creating a project for SBT, since some issues (code generation) are just hard.

**Comment by harrah** [comment]
That's a shame the outdated diffs aren't available anymore.  Was that announced?  Don't worry about it in any case.  I merged most of the commits, but the feature warnings and -Xlint warnings patches didn't apply for some reason.  Can you take a look?

**Comment by Blaisorblade** [comment]
Thanks for the merge!
I just rebased those patches without any conflicts (uh?). The new pull request is: #648.
I haven't seen any announce about outdated diffs.

**Comment by harrah** [comment]
Ok, thanks it should all be merged now.  I use `git am` to apply patches and sometimes it gets confused or I'm using it wrong.  Thanks for the cleanups.

**Pull request closed without merging**
