### PR TITLE
Remember the range for settings read from .sbt files

### PR DESCRIPTION
**Pull request by vigdorchik**

### CODE REVIEW

**Comment by harrah** [comment]
Is there still a need for LinePosition (and a separate FilePosition trait)?

**Comment by vigdorchik** [comment]
Yep, in virtualized scala only start line is remembered:
https://github.com/TiarkRompf/scala-virtualized/wiki/SourceLocation-and-SourceContext

**Comment by vigdorchik** [comment]
So in .scala files we'll have only the start line if I understand correctly.

**Comment by vigdorchik** [comment]
Sorry, forgot to mention @harrah

**Comment by harrah** [comment]
Ok, makes sense.  It would be good to have comments indicating this: settings added with 'set' or programmatically will have NoPosition, settings from Build.scala will have a LinePosition, and build.sbt settings will have RangePosition.

**Comment by adriaanm** [comment]
I'll be merging SourceContext into master for scala-2.10.0-M3 (due in a month), I'd be happy to work with you and Philipp Haller (the author of SourceContext) to make sure we cover the functionality you need for SBT

**Comment by vigdorchik** [comment]
@adriaanm Sounds cool. Thank you!

**Pull request merged**
