### PR TITLE
Fixes #1416: Plugin command doesn't work

### LINKED ISSUE #1416: The `plugin` command doesn't work
## Steps
1. Create new play framework project using activator
2. Run `sbt` in the activator project
3. Type `plugin play.Play`

```
[play-scala] $ plugin play.Play
[error] Expected plugin
[error] plugin play.Play
[error]            ^
```
## Problems

The command should work for an arbitrary plugin. 
## Expectations

Expected output in form of

```
play.Play is activated.
It may affect these keys: scriptClasspath
    requiredStartFacilities
    wixXml
    playGenerateReverseRouter
    makePrermScript
    playRunHooks
    daemonUser
    mappings
       --- CUT ---
```

Additionally, when typed in just `plugin Play`, sbt correctly suggests `play.Play`

```
[play-scala] $ plugin Play
[error] Not a valid plugin: Play (similar: play.Play)
[error] plugin Play
```
## Notes

Output from `about` command

```
[info] Updating {file:/tmp/play-scala/}root...
Waiting for lock on /home/lpiepiora/.ivy2/.sbt.ivy.lock to be available...
[info] Resolving jline#jline;2.11 ...
[info] Done updating.
[info] This is sbt 0.13.5
[info] The current project is {file:/tmp/play-scala/}root 1.0-SNAPSHOT
[info] The current project is built against Scala 2.11.1
[info] Available Plugins: sbt.plugins.IvyPlugin, sbt.plugins.JvmPlugin, sbt.plugins.CorePlugin, sbt.plugins.JUnitXmlReportPlugin, play.Play, play.PlayJava, play.PlayScala, play.twirl.sbt.SbtTwirl, com.typesafe.sbt.jse.SbtJsEngine, com.typesafe.sbt.jse.SbtJsTask, com.typesafe.sbt.web.SbtWeb, com.typesafe.sbt.webdriver.SbtWebDriver, com.typesafe.sbt.coffeescript.SbtCoffeeScript, com.typesafe.sbt.less.SbtLess, com.typesafe.sbt.jshint.SbtJSHint, com.typesafe.sbt.rjs.SbtRjs, com.typesafe.sbt.digest.SbtDigest, com.typesafe.sbt.mocha.SbtMocha, com.typesafe.sbteclipse.plugin.EclipsePlugin, org.sbtidea.SbtIdeaPlugin, com.typesafe.sbt.SbtNativePackager
[info] sbt, sbt plugins, and build definitions are using Scala 2.10.4
```

### PR DESCRIPTION
**Pull request by lpiepiora**
This is an attempt to fix an issue with `plugin` command not working. The issue is described in #1416.

I would love to add some tests, but I need an advise on where to put them.

### CODE REVIEW

**Comment by eed3si9n** [comment]
I've written unit tests on [auto plugins](https://github.com/sbt/sbt/blob/0.13/main/src/test/scala/PluginsTest.scala) and others have written tests on [parsers](https://github.com/sbt/sbt/blob/0.13/util/complete/src/test/scala/ParserTest.scala), so you could mimic something like that if you could manage to build up a fake `State`.

**Comment by lpiepiora** [comment]
@eed3si9n thanks for the suggestion. I've built a fake `State` to test my fix. The test works (and tests the change), I'm not very confident about the way I built the `State`. I'd appreciate any suggestions.

**Comment by eed3si9n** [comment]
If it's testing your change, I'd say it's good enough for the fake `State`.

**Comment by lpiepiora** [comment]
@eed3si9n thanks for a prompt reply. 

Do you see anything else I could do on my side to get this pull request merged?

**Comment by jsuereth** [comment]
nope, this LGTM.  Thanks for the patch!

**Pull request merged**
