### PR TITLE
Remove work-arounds for Scala 2.11 problematic dependencies

### PR DESCRIPTION
**Pull request by gkossakowski**
The ff0fd6eec658502f276f89c46f4aba0e0e268ddc introduced some exclusions
that were necessary for getting sbt to resolve dependencies properly
against Scala 2.11.0-M7.

Scala 2.11.0-M8 fixed its dependency structure so we can get rid of those
exclusions now.

### CODE REVIEW

**Comment by gkossakowski** [comment]
Review by @retronym

**Comment by jsuereth** [comment]
LGTM - was this tested with the dbuild scripts?

**Comment by gkossakowski** [comment]
I tested it by building the whole sbt myself. See #1113.

I'm happy to run a dbuild job as well. Can you give me a pointer which one specifically I should run?

**Comment by jsuereth** [comment]
This one: https://github.com/typesafehub/sbt-builds-for-ide/blob/wip/cleanup-build-mechanism/sbt-on-2.11.x

**Comment by retronym** [comment]
That build doesn't compile all of SBT:

```
          projects: ["compiler-interface",
                     "classpath","logging","io","control","classfile",
                     "process","relation","interface","persist","api",
                     "compiler-integration","incremental-compiler","compile","launcher-interface"
```

Can we crank up the coverage?

**Comment by retronym** [comment]
LGTM. I used this patch locally earlier today.

**Comment by jsuereth** [comment]
Ah, right.  We used to not build all of it because of 2.11 incompatibilities with macros.  We can crank up the coverage once we figure out why it's not working inside the pr-validation automation.

**Comment by gkossakowski** [comment]
@jsuereth: as noted in #1113 I've built entire sbt on top of Scala 2.11.0-M8 locally so I think it should work now.

**Comment by jsuereth** [comment]
Just because it builds locally doesn't mean it won't break all the crazy integration scripts we have between projects.  particularly anything that alters dependencies _may_ cause issues in the dbuild script.  I'd prefer if we don't merge these types of changes until we can validate that the IDE integration still works, thanks.

**Comment by retronym** [comment]
Sorry. That stuff is only a problem if you're using M7 or earlier.

Incidentally, I'm working on dbuild at the moment, resurrecting the Community 2.11 build.

**Comment by jsuereth** [comment]
Cool.  I just want to make sure it doesn't break our existing dbuild scripts though.  Our version.properties is still on M7 for our nightlies, and my PR is still hanging in the air to update that.

**Pull request merged**
