### PR TITLE
Remove javac options from doc tool.

### PR DESCRIPTION
**Pull request by jedesah**
The java documentation tool does not take all the options that the javac tool accepts so I believe it makes sense to have two separate keys for them in sbt

### CODE REVIEW

**Comment by typesafe-tools** [comment]
Can one of the admins verify this patch?

**Comment by jsuereth** [comment]
Just a note, this doesn't actually create javadoc options that are fed into the build, hence the failures.

Additionally, right now `javacArgs in (Compile, doc)` is how you reference javadoc only arguments.

I agree with you that not all are the same, and only some are the same.   sbt's _attempt_ here is that those which are shared go in "javacAgs", those which are note get relegated to "javacArgs in (Compile,compile)" or "javacArgs in (Compile,doc)".

I'd be ok having a different key, but we'd have to tease out the areas in the build where we expect settings to be shared and they would no longer be.  If you need help working this through sbt, I can give you pointers/guidance.

thanks for opening the PR!

**Comment by jedesah** [comment]
@jsuereth Just to be clear, when you say `javacArgs`, do you mean `javacOptions` or do you mean something else I am not finding?

**Comment by jedesah** [comment]
You know, `javacOptions in (Compile, compile)` sort of solves my problem at hand for now and even though it's a little bit weird to me that javacOptions applies to the javadoc tool, if this is a complicated change, I am not sure I have time to figure this stuff out right now.

I think I will go ahead and close this PR for now. Thx for the help diagnosing my problem!

**Comment by jsuereth** [comment]
@jedesah No problem. Can you opena ticket abouta less complicated mechanism for controlling arguments between javac/javadoc? (or at least one with less confusion).

**Comment by jedesah** [comment]
Done!

**Pull request closed without merging**
