### PR TITLE
Moves JCenter and Bintray repo into object Resolver. #1405

### PR DESCRIPTION
**Pull request by eed3si9n**
This is a belated amendment to #1405.

This is more consistent with other hardcoded repos like Sonatype.
Also I'm hardcoding everything to https. Especially for convenience methods like these, we should be encouraging people to use https out of the box.

build.sbt:

``` scala
resolvers += Resolver.bintrayRepo("foo", "bar")
```

/review @jsuereth, @evgeny-goldin

### CODE REVIEW

**Comment by eed3si9n** [comment]
@evgeny-goldin Nice catch!

Given recent buzz around HTTPS, it would be nice to figure out what's going on, and fix it instead of reverting back to HTTP. curl seem to indicate that they are transferring HTTPS request to insecure HTTP:

```
$ curl -v https://jcenter.bintray.com/org/jenkins-ci/main/maven-plugin/1.534/maven-plugin-1.534.hpi                                                                                                                                                                                                           
* Adding handle: conn: 0x7fc501004000
* Adding handle: send: 0
* Adding handle: recv: 0
* Curl_addHandleToPipeline: length: 1
* - Conn 0 (0x7fc501004000) send_pipe: 1, recv_pipe: 0
* About to connect() to jcenter.bintray.com port 443 (#0)
*   Trying 108.168.194.91...
* Connected to jcenter.bintray.com (108.168.194.91) port 443 (#0)
* TLS 1.2 connection using TLS_RSA_WITH_RC4_128_SHA
* Server certificate: *.bintray.com
* Server certificate: GeoTrust SSL CA
* Server certificate: GeoTrust Global CA
> GET /org/jenkins-ci/main/maven-plugin/1.534/maven-plugin-1.534.hpi HTTP/1.1
> User-Agent: curl/7.30.0
> Host: jcenter.bintray.com
> Accept: */*
> 
< HTTP/1.1 302 
* Server nginx is not blacklisted
< Server: nginx
< Date: Sat, 09 Aug 2014 22:11:13 GMT
< Content-Length: 0
< Connection: keep-alive
< Location: http://d29vzk4ow07wi7.cloudfront.net/3f1ce1146f9ab111ae4918aa9acf0d4f7dc148c4?response-content-disposition=attachment%3Bfilename%3D%22maven-plugin-1.534.hpi%22&Policy=eyJTdGF0ZW1lbnQiOiBbeyJSZXNvdXJjZSI6Imh0dHAqOi8vZDI5dnprNG93MDd3aTcuY2xvdWRmcm9udC5uZXQvM2YxY2UxMTQ2ZjlhYjExMWFlNDkxOGFhOWFjZjBkNGY3ZGMxNDhjND9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPWF0dGFjaG1lbnQlM0JmaWxlbmFtZSUzRCUyMm1hdmVuLXBsdWdpbi0xLjUzNC5ocGklMjIiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE0MDc2MjIzMzN9LCJJcEFkZHJlc3MiOnsiQVdTOlNvdXJjZUlwIjoiMC4wLjAuMC8wIn19fV19&Signature=EYJvBFWXspJVOwIBTrNs-u5xp52Q~c0evRwJpjkmE9qkOto8O9eLjfwakdcGi0uWE3xOPh~I0TPZhgP0spb7lsgqyUrIvTqTZztRRPUtXs9~9IsnAsoWuh-2EGl28mfXoHNiN~6-Ops01ZQp-5BfzYPHNFyvrUQPfu97Nb0yix1lbrz-BisE3SsmZ4CbsEq~zLKEN6nxeP1V~bnkldwuQK19~G1uycQEtrXBKXtlTMgOFSpLXNf6WIiPwzQB3C4FHqqO79uFL2phi~9oEbYND~ee-A0MFXYahLCAehKyCIsw44E2t7-7MQFz1E8MnFgKpErasmVzU2hAcE9HdSJOQA__&Key-Pair-Id=APKAIQIOJCQ5764M5VTQ
< 
* Connection #0 to host jcenter.bintray.com left intact
```

**Comment by evgeny-goldin** [comment]
Oh sure, I didn't mean to go back to http. I agree it should be https and we need to find what causes the problem. I'll ask JFrog team to check this.

**Comment by eed3si9n** [comment]
I tried your repro project with a minor modification:

``` scala
ivyPaths := new IvyPaths(baseDirectory.value, Some(baseDirectory.value / "ivy-cache"))

name := "jcenter-test"

organization := "com.example"

version := "0.1.0-SNAPSHOT"

resolvers += Resolver.jcenterRepo

resolvers += Resolver.bintrayRepo( "evgenyg", "test" )

libraryDependencies += "org.springframework" % "spring-web" % "4.0.5.RELEASE"

libraryDependencies += "org.jenkins-ci.main" % "maven-plugin" % "1.534"

libraryDependencies += "biz.cgta" % "otest-jvm_2.10" % "0.1.0" exclude("org.scala-lang.modules.scalajs", "scalajs-sbt-plugin")

libraryDependencies += "org.test1" % "test2" % "1.0"
```

And it seems to grab majority of the files, so maybe HTTP redirection is just some red herring.

**Comment by evgeny-goldin** [comment]
Hi, @eed3si9n. The team at JFrog has addressed the issues with JCenter and my sample project is passing now so all looks good. Now, I wonder if I can start the work on making JCenter a default Maven repo for sbt instead of a Central one? We discussed it with @jsuereth in the past so I thought I'd just make sure the team is still interested. Or should I move this discussion to the dev mailing list?

**Comment by jsuereth** [comment]
I think we should talk about on the mailing list, also I'd like to see some perf numbers between jcenter/maven-central.

However, first, it I think we should also add jcenter support to the sbt launcher, so users COULD use jcenter as a default in their build.properties.   That can happen without actually switching.

**Pull request merged**
