### PR TITLE
[1.x] Bump JLine 2 to `9a88bc4`

### PR DESCRIPTION
**Pull request by Friendseeker**
Contains https://github.com/sbt/jline2/commit/9a88bc413e2b34a4580c001c654d1a7f4f65bf18

### CODE REVIEW

**Comment by SethTisue** [comment]
hmm, are we sure that removing jansi is a good idea in the JLine 2 context?

just asking; I don't remember why JLine 2 is even still present in this repo

**Comment by SethTisue** [comment]
I see that JLine 2 is still present even on the `develop` branch, is that something we could or should clean up?

**Comment by Friendseeker** [comment]
> hmm, are we sure this is a good idea in a JLine 2 context?
> 
> just asking; I'm only dimly aware of why JLine 2 is even still present in this repo

I honestly have no clue too... At this point only Eugene and perhaps Lukas / som-snytt knows. Only thing I know is that some legacy Scala 2.12 `sbt console` support relies on JLine 2...

**Comment by Friendseeker** [comment]
> I see that JLine 2 is still present even on the `develop` branch, is that something we could or should clean up?

I mean thinking positively we all get to practice working with legacy code + unmaintained legacy dep!

**Comment by SethTisue** [comment]
oh, Scala 2.12, sigh, that's plausible. still, I wonder if we should try ripping it out to verify if it's still needed

**Comment by eed3si9n** [comment]
My guess is we'd need to support layered ClassLoader unless we drop the support of some Scala versions, which I don't think is worth it.

**Review by eed3si9n — APPROVED** [review]
Thanks!

**Comment by SethTisue** [comment]
> unless we drop the support of some Scala versions, which I don't think is worth it.

it did cross my mind to try to convince you to drop support for building 2.12 projects 😈  but I'm not sure I could even convince myself, much as I would like to see 2.12 die

**Pull request merged**
