### PR TITLE
[sbt 1.0] Silent startup for scalas

### LINKED ISSUE #840: completely silent startup, for use when scripting
sbt always prints these lines when it starts:

```
[info] Loading global plugins from /Users/tisue/.sbt/plugins
[info] Loading project definition from /Users/tisue/nl.headless/project
```

Is there a way to make it not? It messes up trying to pipe the output of commands around in the Unix shell.

this was requested on the mailing list https://groups.google.com/d/msg/simple-build-tool/VZFLPc-TWPw/2B6jx5Y_JF0J and at the time @harrah suggested opening a ticket, but I couldn't find one

related: #316, which was about overall levels of noisiness. this ticket is about being able to reduce noise all the way to zero when desired.

### PR DESCRIPTION
**Pull request by eed3si9n**
This PR is on top of #2741

Fixes #840

/review @dwijnand, @Duhemm

### CODE REVIEW

**Review by dwijnand — APPROVED** [review]
Awesome!

**Comment by SethTisue** [comment]
always nice to see scripting support getting attention 👍

**Comment by eed3si9n** [comment]
@SethTisue I was in the neighborhood yesterday, and realized it was a one-liner fix `runEarly(Level.Error.toString)`.

**Comment by dwijnand** [comment]
@eed3si9n any reason this can't be in 0.13.13? I can't see any.

**Comment by eed3si9n** [comment]
@dwijnand oh I let it slip, didn't I? I was going to use this as an incentive to entice Seth into upgrading to sbt 1.0 :) You're welcome to backport.

**Pull request merged**
