### PR TITLE
Fix race condition

### PR DESCRIPTION
**Pull request by benmccann**
This was exposed by Play's scripted tests in https://github.com/playframework/playframework/pull/7133

### CODE REVIEW

**Comment by He-Pin** [comment]
Could we make use of NIO2 once we move to java8?

**Comment by benmccann** [comment]
Does NIO2 have this functionality?

NIO does in jdk7, but it doesn't work on Mac. In Play we use NIO on Windows and Linux and jnotify/polling on Mac. See https://github.com/playframework/play-file-watch/blob/master/src/main/scala/play/dev/filewatch/FileWatchService.scala#L67

**Comment by He-Pin** [comment]
Does monix's nio address this?
https://github.com/monix/monix-nio

@radusw ping?

**Comment by radusw** [comment]
@hepin1989 It will pretty soon. Currently we have this PR: https://github.com/monix/monix-nio/pull/16 by @hmemcpy ( an example: https://twitter.com/hmemcpy/status/844521638431526918 )

**Comment by benmccann** [comment]
I'm temporarily closing this pending further investigation. I think there might be a better fix

**Pull request closed without merging**
