### PR TITLE
[1.3.x] sbt-giter8-resolver 0.12.0

### PR DESCRIPTION
**Pull request by apple-corps**

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @colin-williams,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Review by eed3si9n — APPROVED** [review]

**Comment by apple-corps** [comment]
I signed the CLA and got the message `Thank you! Your submission was processed.`

**Comment by mkows** [comment]
@drocsid looks like the commit https://github.com/sbt/sbt/pull/5537/commits/788bc5e0a6b93aa348bb95f3229f89c5e60fa5ad comes from a different GitHub account, and therefore `typesafe-cla-validator` is complaining.

**Comment by colin-williams** [comment]
@mknows. I have two github accounts but pushed with my drocsid account, but commits via email linked to my other account? I just accepted the CLA via `colin-williams` account. Is there a refresh option?

**Comment by colin-williams** [comment]
I signed the CLA again and again got the message Thank you! Your submission was processed.

**Comment by mkows** [comment]
FYI this fix seems to resolve the issue with file conditional for http4s.g8 https://github.com/http4s/http4s.g8/issues/144.
I tested it on local sbt build from this PR (to be precise with one minor change of https://github.com/sbt/sbt/blob/develop/project/build.properties#L1 `sbt.version=1.3.10` – not saying it was necessary, just that it was in place).

**Pull request merged**
