### PR TITLE
Ensure that if artifact is published, we overwrite default checksums.

### LINKED ISSUE #1233: sbt 0.13.5-M2 can't publish to artifactory
When it tries to publish, you get a "XYZ exists and overwrite=false" error.  This is because it's trying to push a checksum (md5/sha1) _after_ ivy has autogenerated it, and the logic hits  files before publishing.

cc> @huntc.

### PR DESCRIPTION
**Pull request by jsuereth**
Fixes #1233
- Add a new "shim" for RepositoryResolvers that modifies the "put"
  method so that it will ignore the overwrite flag for checksums.

Review by @eed3si9n cc> @dansanduleac

### CODE REVIEW

**Comment by eed3si9n** [comment]
Travis didn't compile:

```
[error] /home/travis/build/sbt/sbt/ivy/src/main/scala/sbt/ConvertResolver.scala:36: type ReflectiveOperationException is not a member of package java.lang
[error]           case e: java.lang.ReflectiveOperationException => None
[error]                             ^
```

**Comment by jsuereth** [comment]
Yeah, looks like I was using JDK7 specific APIs by accident... yay...

**Comment by jsuereth** [comment]
@eed3si9n all good now.

**Comment by jsuereth** [comment]
@eed3si9n Also debating putting something like this in sbt: https://github.com/jsuereth/evil_monkey

**Comment by eed3si9n** [comment]
Might as well go all the way.

**Comment by jsuereth** [comment]
@eed3si9n Is that a "go all the way in this PR" or "wait until evil monkey is stable and then merge it in".  It'll take me a bit to get memoizing in the evil monkey done that I'd use it in this PR.

This PR is good to go as-is, we can clean it up in Ivy directly _OR_ via our own monkey-patching hackery later.

**Comment by eed3si9n** [comment]
Merged. but +1 on evil monkey eventually.

**Comment by huntc** [comment]
Nice one chaps!

**Comment by indykish** [comment]
This is one of the reason I moved back from 0.13.5-M2 to 0.13.1.

Is this fix available in 0.13.2 ?  I just hit the same problem. 

> last *:publish
> java.io.IOException: destination file exists and overwrite == false
>     at org.apache.ivy.plugins.repository.url.URLRepository.put(URLRepository.java:75)

**Comment by jsuereth** [comment]
0.13.5-M3 is out with the fix.

**Comment by indykish** [comment]
@jsuereth  Tried 0.13.5-M3 by cleaning up ./ivy2/cache. It takes longer to compile and is hung when I attempt to compile the second time by doing `clean` and `compile`.
I think 0.13.2 and 0.13.5-M3 doesn't solve our need, and sonatype publish needs to work for us. We are moving back to 0.13.1.

`incOptions := incOptions.value.withNameHashing(true)` prompted us to try 0.1.3.5-M3. 

I wonder why 0.13.2 was shipped with the publish bug still there.

**Comment by jsuereth** [comment]
@indykish The overwrite flag wasn't supposed to be in 0.13.2, so that's a bug.  0.13.5 will be released shortly with the fix.

However, _what_ is going on with hung compiles here.  Can I get more information, perhaps a jstack dump when it hangs?  That sounds like you need to open another ticket so we can resolve that before the 0.13.5 final.

**Comment by indykish** [comment]
@jsuereth Wonderful. I cleanly wiped out the `./ivy2/cache, ./sbt/boot, staging, target` and tweaked a few JVM settings as I am on custom built openjdk8, and included  `incOptions := incOptions.value.withNameHashing(true)`  in all our projects. I am good now. Enjoying 0.13.5-M3. If I hit that problem again, i will report it with jstack dump. Thanks again.

**Comment by jsuereth** [comment]
@indykish Well, glad to hear it's working!  Still hope this isn't a common thing others experience.

**Comment by jroper** [comment]
So, is this supposed to not be an issue in 0.13.2?  Because I'm definitely seeing it (or something related) 0.13.2.  It doesn't happen for snapshot versions, but it's happening for non snapshot versions.

What also really isn't helping here is that the error message doesn't say what it failed to publish - that needs to be fixed with priority, because there seem to be many related issues here, and not knowing which file it's failing on makes it impossible to do any further debug.

**Comment by jroper** [comment]
I have a project that reproduces the issue for me 100%.  If it's unrelated to this issue, let me know and I'll create a new issue.

https://github.com/typesafehub/activator-tutorial-generator

That's the project.  It's configured to run with SBT 0.13.1, and works fine.  But, change it to 0.13.2, and change the version to a non snapshot version, and you get the overwrite error.

**Comment by jsuereth** [comment]
@jroper I'm unable to reproduce in 0.13.6-SNAPSHOT with dbeugging enabled:

```
[info]  published activator-tutorial-generator_2.10 to http://private-repo.typesafe.com/typesafe/maven-releases/com/typesafe/activator/activator-tutorial-generator_2.10/0.0.0-suck-josh-2/activator-tutorial-generator_2.10-0.0.0-suck-josh-2.pom
[info]  published activator-tutorial-generator_2.10 to http://private-repo.typesafe.com/typesafe/maven-releases/com/typesafe/activator/activator-tutorial-generator_2.10/0.0.0-suck-josh-2/activator-tutorial-generator_2.10-0.0.0-suck-josh-2.jar
[info]  published activator-tutorial-generator_2.10 to http://private-repo.typesafe.com/typesafe/maven-releases/com/typesafe/activator/activator-tutorial-generator_2.10/0.0.0-suck-josh-2/activator-tutorial-generator_2.10-0.0.0-suck-josh-2-sources.jar
[info]  published activator-tutorial-generator_2.10 to http://private-repo.typesafe.com/typesafe/maven-releases/com/typesafe/activator/activator-tutorial-generator_2.10/0.0.0-suck-josh-2/activator-tutorial-generator_2.10-0.0.0-suck-josh-2-javadoc.jar
[info] :: delivering :: com.typesafe.sbt#sbt-activator-tutorial-generator;0.0.0-suck-josh-2 :: 0.0.0-suck-josh-2 :: release :: Wed May 28 09:26:01 EDT 2014
[info]  delivering ivy file to /home/jsuereth/projects/sbt/diagnose/activator-tutorial-generator/plugin/target/scala-2.10/sbt-0.13/ivy-0.0.0-suck-josh-2.xml
[info]  published sbt-activator-tutorial-generator to http://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-activator-tutorial-generator/scala_2.10/sbt_0.13/0.0.0-suck-josh-2/jars/sbt-activator-tutorial-generator.jar
[info]  published sbt-activator-tutorial-generator to http://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-activator-tutorial-generator/scala_2.10/sbt_0.13/0.0.0-suck-josh-2/srcs/sbt-activator-tutorial-generator-sources.jar
[info]  published sbt-activator-tutorial-generator to http://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-activator-tutorial-generator/scala_2.10/sbt_0.13/0.0.0-suck-josh-2/docs/sbt-activator-tutorial-generator-javadoc.jar
[info]  published ivy to http://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-activator-tutorial-generator/scala_2.10/sbt_0.13/0.0.0-suck-josh-2/ivys/ivy.xml
```

**Pull request merged**
